### ISSUE TITLE
Caused by OutOfMemoryError: GC ove rhead limit exceeded 

### ISSUE THREAD

**Issue by androidhuoniao** [facebook/buck#1041]
run buck in windows
```
fatal: Not a git repository (or any of the parent directories): .git
Not using buckd because watchman isn't installed.
fatal: Not a git repository (or any of the parent directories): .git
[-] PARSING BUCK FILES...FINISHED 0.0s [100%]
[2016-12-09 10:14:15.569][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //main:src_aop_Normal_Debug#dex failed. Caused by OutOfMemoryError: GC ove
rhead limit exceeded
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:375)
        at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:706)
        at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:654)
        at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:399)
        at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:344)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:207)
        at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:92)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1270)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:696)
        at com.facebook.buck.cli.Main.main(Main.java:1858)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //main:src_aop_Normal_Debug#dex failed. Caused by OutOfMemoryError: GC overhead limit excee
ded
        at com.facebook.buck.command.Build.executeBuild(Build.java:287)
        at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:334)
        ... 14 more
Caused by: java.lang.RuntimeException: Building //main:src_aop_Normal_Debug#dex failed. Caused by OutOfMemoryError: GC overhead limit exceeded
        at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1053)
        at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:1035)
        at com.facebook.buck.rules.CachingBuildEngine$4.onFailure(CachingBuildEngine.java:1022)
        at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:140)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1405)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:105)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.android.dx.cf.code.RopperMachine.run(RopperMachine.java:630)
        at com.android.dx.cf.code.Simulator$SimVisitor.visitLocal(Simulator.java:612)
        at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:409)
        at com.android.dx.cf.code.Simulator.simulate(Simulator.java:94)
        at com.android.dx.cf.code.Ropper.processBlock(Ropper.java:787)
        at com.android.dx.cf.code.Ropper.doit(Ropper.java:742)
        at com.android.dx.cf.code.Ropper.convert(Ropper.java:349)
        at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:282)
        at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:139)
        at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:94)
        at com.android.dx.command.dexer.Main.processClass(Main.java:760)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:703)
        at com.android.dx.command.dexer.Main.access$300(Main.java:88)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:632)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:662)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:540)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:309)
        at com.android.dx.command.dexer.Main.run(Main.java:268)
        at com.android.dx.command.dexer.Main.run(Main.java:238)
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:183)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:163)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1399)
        at com.facebook.buck.rules.CachingBuildEngine.lambda$11(CachingBuildEngine.java:340)
        at com.facebook.buck.rules.CachingBuildEngine$$Lambda$233/1724882443.call(Unknown Source)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$102/1187903677.apply(Unknown Source)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)



```

**Comment by androidhuoniao** [comment]
I find a solution, set Xmx3g, everything will be ok
