### ISSUE TITLE
`buck test --all` not recognizing `[repositories]`

### ISSUE THREAD

**Issue by aary** [facebook/buck#1076]
There seems to be an inconsistency with the `buck test --all` and the `[repositories]` "cell" features.  `buck test --all` and possibly other features that cause a traversal of the file structure to read and parse `BUCK` files do not appear take into account the `[repositories]` section. 

This folder contains a project that illustrates this issue [buck-bug.tar.gz](https://github.com/facebook/buck/files/682328/buck-bug.tar.gz)

The file structure of the attached folder looks like this 
```
.
├── .buckconfig
├── external
└── repo-one
    ├── BUCK
    └── repo-one
        ├── .buckconfig
        ├── external
        └── one
            ├── BUCK
            └── test
                └── BUCK

6 directories, 5 files
```

And running `buck test --all`  in the root `buck-bug` folder gives the following error
```
$ buck test --all
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.3s [100%] 🐳  New buck daemon
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...1.0s
[2017-01-03 19:29:40.109][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: Raw data claims to come from [repo-one/repo-one/one], but we tried rooting it at [one].
        at com.facebook.buck.parser.RawNodeParsePipeline.parseBuildTargetFromRawRule(RawNodeParsePipeline.java:71)
        at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:136)
        at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:57)
        at com.facebook.buck.parser.TargetNodeParsePipeline.computeNode(TargetNodeParsePipeline.java:115)
        at com.facebook.buck.parser.TargetNodeParsePipeline.computeNode(TargetNodeParsePipeline.java:53)
        at com.facebook.buck.parser.ConvertingPipeline.dispatchComputeNode(ConvertingPipeline.java:147)
        at com.facebook.buck.parser.ConvertingPipeline.lambda$null$6(ConvertingPipeline.java:99)
        at com.facebook.buck.parser.ConvertingPipeline$$Lambda$174/792855998.apply(Unknown Source)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:595)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:96)
        at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:1108)
        at com.facebook.buck.parser.ConvertingPipeline.lambda$getNodeJob$7(ConvertingPipeline.java:97)
        at com.facebook.buck.parser.ConvertingPipeline$$Lambda$170/1741702730.get(Unknown Source)
        at com.facebook.buck.parser.PipelineNodeCache.getJobWithCacheLookup(PipelineNodeCache.java:72)
        at com.facebook.buck.parser.ConvertingPipeline.getNodeJob(ConvertingPipeline.java:94)
        at com.facebook.buck.parser.ParsePipeline.getNode(ParsePipeline.java:94)
        at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:157)
        at com.facebook.buck.parser.Parser.lambda$buildTargetGraph$13(Parser.java:305)
        at com.facebook.buck.parser.Parser$$Lambda$171/1493158871.findChildren(Unknown Source)
        at com.facebook.buck.graph.AcyclicDepthFirstPostOrderTraversal$Explorable.<init>(AcyclicDepthFirstPostOrderTraversal.java:114)
        at com.facebook.buck.graph.AcyclicDepthFirstPostOrderTraversal.traverse(AcyclicDepthFirstPostOrderTraversal.java:82)
        at com.facebook.buck.parser.Parser.buildTargetGraph(Parser.java:335)
        at com.facebook.buck.parser.Parser.buildTargetGraphForTargetNodeSpecs(Parser.java:446)
        at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:420)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:205)
        at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:92)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1283)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:705)
        at com.facebook.buck.cli.Main.main(Main.java:1872)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
```

The exception originates from [this line](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/parser/RawNodeParsePipeline.java#L71).  Manually running tests via `buck test <test target>`, adding dependencies to the submodule and then building does not seem to cause any issues.

**Comment by marcinkosiba** [comment]
Thanks for the report. The 'cell' feature is still a work in progress.

It looks like the parser doesn't "stop" at cell boundaries when doing recursive traversals (I think the issue isn't specific to buck test, probably `buck targets //...` would fail in a similar way).

Just to set expectations: we don't nest cells like this internally, so fixing this is not high priority for us.

**Comment by aary** [comment]
I could try and fix it, but I have no idea where the relevant part of that code starts... Could you point me in the right direction and I can give it a shot?

**Comment by marcinkosiba** [comment]
Take a look at Parser.resolveTargetSpecs. In the first loop we try and get all of the BUCK files by calling AbstractBuildFileSpec.forEachBuildFile, but that method doesn't have any code to stop at cell boundaries, so it might recurse into any cells that may be nested in the current cell.
Then, in the second for loop, that iterates over the build files, we have this line:
```
      Cell cell = rootCell.getCell(firstSpec.getBuildFileSpec().getCellPath());
```
That just 'trusts' the BuildFileSpec to always be constrained to a single cell, but, like I mentioned, there doesn't seem to be any code that would ensure that is the case.

Ideally we'd change the code in the second loop to get the 'right' cell, instead of trusting the spec. We could also make the forEachBuildFile not recurse into child cells, however that would make `//...` less useful as it would mean "everything in the current cell" instead of "everything"
