### ISSUE TITLE
Invalid BSER header

### ISSUE THREAD

**Issue by joewalnes** [facebook/buck#1078]
Every once in a while this exception occurs when running buck. Not easily reproducible. Running again fixes the issue.

```bash
$ buck build //src/...
```

```java
[2017-01-05 18:46:16.653][error][command:6e1b9607-4a83-4764-a316-13986a01ebde][tid:1712][com.facebook.buck.cli.Main] Uncaught exception at top level
com.facebook.buck.bser.BserDeserializer$BserEofException: Invalid BSER header (expected 3 bytes, got 0 bytes)
        at com.facebook.buck.bser.BserDeserializer.readBserBuffer(BserDeserializer.java:126)
        at com.facebook.buck.bser.BserDeserializer.deserializeBserValue(BserDeserializer.java:113)
        at com.facebook.buck.io.WatchmanSocketClient.sendWatchmanQuery(WatchmanSocketClient.java:149)
        at com.facebook.buck.io.WatchmanSocketClient.access$000(WatchmanSocketClient.java:41)
        at com.facebook.buck.io.WatchmanSocketClient$1.call(WatchmanSocketClient.java:84)
        at com.facebook.buck.io.WatchmanSocketClient$1.call(WatchmanSocketClient.java:81)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Versions:

```
$ buck --version
buck version v2016.03.28.01
$ watchman --version
3.0.0
```

**Comment by shs96c** [comment]
Hi Joe,

When I've seen this before, it's because the build files aren't valid
Python. In particular, "autodeps" generated BUCK files with merge conflicts
will cause buck to shit the bed in a particularly non-obvious way.

Dunno if that's what you're seeing as the cause? Does anything change
before you get the BSER warning? Also, are you using watchman (and
therefore the buck daemon) or just separate Buck invocations. If you're
unsure, the start of the build output will tell you what buck thinks it's
doing.

Simon

**Comment by marcinkosiba** [comment]
I remember fixing a bug that would cause similar symptoms. Sometimes the bser codec becomes unusable for some reason after an exception happens and re-using a Python parser process would cause these kinds of errors. The fix was to implement python process 'retiring' in the parser pipeline.

@joewalnes could you check your buck-out/log/buck-0.log for any useful details when this happens?

**Comment by joewalnes** [comment]
@marcinkosiba Next time this happens, I'll look at the log file.

@shs96c Answering your questions...

> it's because the build files aren't valid Python

I don't think that's the cause as I've seen it happen when the BUCK files haven't been changed recently.

> "In particular, "autodeps" generated BUCK files

I'm not using autodeps first. (Side note: I'm not using it because of the scary EXPERIMENTAL warning - do you think I should be? Is it relatively stable?)

> Does anything change before you get the BSER warning?

General code changes. Nothing out of the ordinary. Also re-running immediately after the failure seems to fix it.

> Also, are you using watchman

Yep. "Using watchman."

---

I realize my version is pretty old so I'm going to upgrade and assume it's fixed. I'll close the issue. If it re-occurs with latest, I'll re-open.
