### ISSUE TITLE
Sporadic failures while running android tests

### ISSUE THREAD

**Issue by ZacSweers** [facebook/buck#1107]
Periodically when I run all unit tests on android, a bunch all fail due to this:

```
FAILURE //library/ui-core:test_release main: //library/ui-core:test_release failed on step junit with an exception:
process creation blocked due to pending nailgun exit
java.io.IOException: process creation blocked due to pending nailgun exit
	at com.facebook.buck.util.BgProcessKiller.checkArmedStatus(BgProcessKiller.java:88)
	at com.facebook.buck.util.BgProcessKiller.startProcess(BgProcessKiller.java:97)
	at com.facebook.buck.util.DefaultProcessExecutor.launchProcess(DefaultProcessExecutor.java:169)
	at com.facebook.buck.util.DefaultProcessExecutor.launchAndExecute(DefaultProcessExecutor.java:129)
	at com.facebook.buck.util.DefaultProcessExecutor.launchAndExecute(DefaultProcessExecutor.java:117)
	at com.facebook.buck.shell.ShellStep.launchAndInteractWithProcess(ShellStep.java:161)
	at com.facebook.buck.shell.ShellStep.execute(ShellStep.java:107)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.cli.TestRunning.lambda$2(TestRunning.java:898)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Not sure where to start on it for more info. Using okbuck. CC @kageiit

**Comment by marcinkosiba** [comment]
It looks like the BgProcessKiller thought the buckd process was going down. Were there any prior build/test failures?
