### ISSUE TITLE
Quick Start doesn't build

### ISSUE THREAD

**Issue by Macarse** [facebook/buck#112]
```
$ buck build app
[-] PARSING BUILD FILES...FINISHED 0.2s
[+] BUILDING...0.6s
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //apps/myapp:app#uber_r_dot_java...  0.6s (running dx[0.1s])
 |=> IDLE
Log:

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing com/example/R$attr.class
...while processing com/example/R$attr.class

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing com/example/R$string.class
...while processing com/example/R$string.class

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing com/example/R.class
...while processing com/example/R.class
3 warnings
no classfiles specified
BUILD FAILED: //apps/myapp:app#uber_r_dot_java failed with exit code 1:
dx

```

**Comment by fabriziobertoglio1987** [comment]
I was trying to run and add e2e junit tests to my react-native pr https://github.com/facebook/react-native/pull/31252 and I run in this issue

```
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:419)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:322)
        at com.facebook.buck.step.StepRunner.runStep(StepRunner.java:58)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1408)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1385)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:856)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
        ...more logs...
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
```


**<details><summary>CLICK TO OPEN FULL LOG</summary>**
<p>

```
➜  react-native git:(fix/image-accessibility) buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests

Invalidating internal cached state: Buck configuration options changed between invocations. This may cause slower builds.
  Removed value download.in_build='true'

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
        at com.android.dx.command.dexer.Main.processClass(Main.java:780)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:746)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:91)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1688)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:700)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:597)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:324)
        at com.android.dx.command.dexer.Main.run(Main.java:295)
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:419)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:322)
        at com.facebook.buck.step.StepRunner.runStep(StepRunner.java:58)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1408)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1385)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:856)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:792)
        at com.android.dx.command.dexer.Main.access$1600(Main.java:91)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1727)
        at com.android.dx.command.dexer.Main.processClass(Main.java:778)
        ... 29 more
1 error; aborting


UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
        at com.android.dx.command.dexer.Main.processClass(Main.java:780)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:746)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:91)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1688)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:700)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:597)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:324)
        at com.android.dx.command.dexer.Main.run(Main.java:295)
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:419)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:322)
        at com.facebook.buck.step.StepRunner.runStep(StepRunner.java:58)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1408)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1385)
        at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:856)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:792)
        at com.android.dx.command.dexer.Main.access$1600(Main.java:91)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1727)
        at com.android.dx.command.dexer.Main.processClass(Main.java:778)
        ... 29 more
1 error; aborting

Parsing buck files: finished in 1.5 sec
Building: finished in 0.6 sec (100%) 367/558 jobs, 2 updated
  Total time: 1.9 sec
Command failed with exit code 1.
    When running <dx>.
    When building rule //ReactAndroid/src/main/third-party/java/okhttp:okhttp3-urlconnection#dex.
```

</p>
</details>

I'm using Java 1.8

```
➜  react-native git:(fix/image-accessibility) ls $ANDROID_SDK/build-tools
20.0.0  23.0.1  24.0.0  26.0.3  28.0.3  29.0.0  29.0.1  29.0.2  29.0.3  30.0.3  31.0.0-rc1
```
any idea on how to solve this? Is this a buck issue or connected to [okhttp](https://github.com/square/okhttp/issues)? 
I ended up cloning the buck repo and giving a look at the code, but maybe the issue is connected to okhttp and I would appreciated some guidance in finding a solution.

I'm experiencing this running react-native androidTest suite following the instructions https://github.com/facebook/react-native/blob/79090c48026a932a688ad80a715cdc9c0fe00a78/ReactAndroid/src/androidTest/buck-runner/BUCK#L3-L9

```
# We are running instrumentation tests in simple mode: app code and instrumentation are in the same APK
# Currently you need to run these commands to execute tests:
#
# node cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/js/TestBundle.js --bundle-output ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
# gradle :ReactAndroid:packageReactNdkLibsForBuck
# buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests
# ./scripts/run-android-instrumentation-tests.sh com.facebook.react.tests
```

Thanks a lot :peace_symbol:  :pray:
