### ISSUE TITLE
Multiple entries with same key

### ISSUE THREAD

**Issue by MCA-FSF** [facebook/buck#1132]
When I built this [demo](https://github.com/MCA-FSF/MultipleEntries) with bulid target `//Reachability:Reachability`, I met some questions.  If using cxx_library, you can build it correctly. Or if you comment the field `exported_headers` although using apple_library, you also can build it correctly. 

The detail of the error as follows：
[error][command:null][tid:176][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalArgumentException: **Multiple entries with same key:** Reachability.h=/Users/FSF/Desktop/undefine/MultipleEntries/Reachability/Reachability.h and Reachability.h=/Users/FSF/Desktop/undefine/MultipleEntries/Reachability/Reachability.h
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.ImmutableSortedMap.fromEntries(ImmutableSortedMap.java:348)
	at com.google.common.collect.ImmutableSortedMap.access$100(ImmutableSortedMap.java:57)
	at com.google.common.collect.ImmutableSortedMap$Builder.build(ImmutableSortedMap.java:500)
	at com.facebook.buck.apple.AppleDescriptions.convertAppleHeadersToPrivateCxxHeaders(AppleDescriptions.java:145)
	at com.facebook.buck.apple.AppleDescriptions.populateCxxConstructorArg(AppleDescriptions.java:237)
	at com.facebook.buck.apple.AppleDescriptions.populateCxxLibraryDescriptionArg(AppleDescriptions.java:292)
	at com.facebook.buck.apple.AppleLibraryDescription.requireSingleArchUnstrippedBuildRule(AppleLibraryDescription.java:360)
	at com.facebook.buck.apple.AppleLibraryDescription.requireUnstrippedBuildRule(AppleLibraryDescription.java:338)
	at com.facebook.buck.apple.AppleLibraryDescription.createLibraryBuildRule(AppleLibraryDescription.java:260)
	at com.facebook.buck.apple.AppleLibraryDescription.createBuildRule(AppleLibraryDescription.java:167)
	at com.facebook.buck.apple.AppleLibraryDescription.createBuildRule(AppleLibraryDescription.java:68)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:46)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:136)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:152)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:147)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:161)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)

**Comment by Coneko** [comment]
That's because you're adding the same headers both to `headers` and `exported_headers`. Each header can only be in one of the two at the time.
