### ISSUE TITLE
NullPointerException: Unknown platform type ARMV7

### ISSUE THREAD

**Issue by cesarferreira** [facebook/buck#1144]
Do you guys have any idea of why this is happening?

```bash
$ ./buckw build appDebug                                                        
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.0s
[2017-01-19 17:36:07.176][error][command:null][tid:59][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException: Unknown platform type ARMV7
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at com.facebook.buck.android.AndroidNativeLibsPackageableGraphEnhancer.enhance(AndroidNativeLibsPackageableGraphEnhancer.java:194)
	at com.facebook.buck.android.AndroidBinaryGraphEnhancer.createAdditionalBuildables(AndroidBinaryGraphEnhancer.java:223)
	at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:254)
	at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:1)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:46)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:136)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:152)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:62)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:161)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:90)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:607)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:383)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:339)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:198)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1257)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:700)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1937)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

**Comment by Coneko** [comment]
Is you android NDK installed and configured correctly? Is the `$ANDROID_NDK` environment variable pointing to it? Is the version of the ndk specified in `.buckconfig` the correct one?

**Comment by cesarferreira** [comment]
You are right, thanks!
