### ISSUE TITLE
App crashes on startup if built with buck and not with gradle

### ISSUE THREAD

**Issue by cesarferreira** [facebook/buck#1151]
So I build my app with `gradle` and it runs normally, when I build it with buck it crashes with this log, 
it's weird because it's precisely the same code, do any of you know why is it?

```
Process com.mycompany.awesomeapp created for activity com.mycompany.awesomeapp/com.mycompany.uma.app.bootstrap.BootstrapActivity
                            PID: 9839   UID:    GIDs:

         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: com.mycompany.awesomeapp, PID: 9839
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.awesomeapp/com.mycompany.uma.app.bootstrap.BootstrapActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descend
                            ant) with this activity.
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                         E      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6119)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                         E  Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                         E      at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                         E      at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                         E      at android.support.v7.app.AppCompatDelegateImplV7.onPostCreate(AppCompatDelegateImplV7.java:167)
                         E      at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:98)
                         E      at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
                         E      ... 9 more

                            Process com.mycompany.awesomeapp (PID: 9839) ended


                            Process com.mycompany.awesomeapp created for activity com.mycompany.awesomeapp/com.mycompany.app.bootstrap.BootstrapActivity
                            PID: 13427   UID:    GIDs:
```

**Comment by Coneko** [comment]
Did you write the BUCK files yourself or did you use OkBuck?

**Comment by Coneko** [comment]
If you wrote them yourself can you upload a small repro project?

If you used OkBuck can you open an issue ok OkBuck and figure out if it's an issue with the generation of the build files?

**Comment by cesarferreira** [comment]
Yup, it was with `OkBuck` thanks anyway
