### ISSUE TITLE
Android build fails with OOM

### ISSUE THREAD

**Issue by Macarse** [facebook/buck#1169]
I am using buck with okBuck. Issue first reported here: https://github.com/uber/okbuck/issues/384

The logs show the following:
```
[2017-02-08 22:33:30.147][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepFinished(javac)
[2017-02-08 22:33:30.147][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepStarted(jar)
[2017-02-08 22:33:31.784][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepFinished(jar)
[2017-02-08 22:33:31.785][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepStarted(mkdir)
[2017-02-08 22:33:31.785][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepFinished(mkdir)
[2017-02-08 22:33:31.785][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepStarted(get_class_names)
[2017-02-08 22:33:32.044][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.step.DefaultStepRunner] StepFinished(get_class_names)
[2017-02-08 22:33:32.044][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:79][com.facebook.buck.rules.CachingBuildEngine] Build completed: android_library //MyApp:src_normalDebug (25349326354ns)
[2017-02-08 22:33:32.370][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.artifact_cache.DirArtifactCache] Artifact fetch(e7ae3fbe0c8221766f79fbe297e7bb245c743c5e, Lazy path uninitialized) cache miss
[2017-02-08 22:33:32.370][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.rules.CachingBuildEngine] Cache miss for '//MyApp:src_normalDebug#dex' with rulekey 'e7ae3fbe0c8221766f79fbe297e7bb245c743c5e'
[2017-02-08 22:33:32.370][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.rules.CachingBuildEngine] Building locally: //MyApp:src_normalDebug#dex
[2017-02-08 22:33:32.370][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepStarted(rm)
[2017-02-08 22:33:32.370][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepFinished(rm)
[2017-02-08 22:33:32.370][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepStarted(mkdir)
[2017-02-08 22:33:32.371][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepFinished(mkdir)
[2017-02-08 22:33:32.371][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepStarted(estimate_dex_weight)
[2017-02-08 22:33:32.379][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepFinished(estimate_dex_weight)
[2017-02-08 22:33:32.379][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.shell.ShellStep] Command: /Users/myUser/.gradle/caches/okbuck/buck/third-party/java/dx/etc/dx --dex --no-optimize --force-jumbo --output /Users/myUser/Documents/MyApp/buck-out/gen/MyApp/src_normalDebug#dex.dex.jar /Users/myUser/Documents/MyApp/buck-out/gen/MyApp/lib__src_normalDebug__output/src_normalDebug.jar
[2017-02-08 22:33:32.380][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepStarted(dx)
[2017-02-08 22:37:57.816][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:66][com.facebook.buck.util.perf.ProcessTracker] shutDown
[2017-02-08 22:38:00.728][error][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:65][com.google.common.util.concurrent.ServiceManager] Service PerfStatsTracking [FAILED] has failed in the RUNNING state.
java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:37:57.816][error][command:null][tid:58][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[NGSession 5: com.facebook.buck.cli.Main read stream thread (NGInputStream pool),5,main]
java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:38:00.728][error][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:66][com.google.common.util.concurrent.ServiceManager] Service ProcessTracker [FAILED] has failed in the RUNNING state.
java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:37:57.816][error][command:null][tid:63][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[SuperConsoleEventBusListener-0,5,main]
java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:38:03.973][info ][command:null][tid:57][com.martiansoftware.nailgun.NGSession] NGSession shutting down
[2017-02-08 22:38:03.973][error][command:null][tid:13][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[NonReentrantSystemExit,5,main]
com.martiansoftware.nailgun.NGExitException: ExitException: status 1
	at com.martiansoftware.nailgun.NGSecurityManager.checkExit(NGSecurityManager.java:56)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at com.facebook.buck.util.shutdown.NonReentrantSystemExit$1.run(NonReentrantSystemExit.java:53)

[2017-02-08 22:38:40.996][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:83][com.facebook.buck.step.DefaultStepRunner] StepFinished(dx)
[2017-02-08 22:38:40.997][error][command:null][tid:62][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[NetworkStatsKeeper-0,5,main]
java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:41:26.499][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:54][com.facebook.buck.command.Build] Got an exception during the build.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.command.Build.executeBuild(Build.java:292)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:344)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:803)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:750)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:465)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:394)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:360)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:212)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1292)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:712)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2078)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1053)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:1035)
	at com.facebook.buck.rules.CachingBuildEngine$4.onFailure(CachingBuildEngine.java:1022)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:140)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1405)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:42:23.100][debug][command:27dec2ae-5da7-4513-aa45-c1011dc431f9][tid:54][com.facebook.buck.event.listener.SuperConsoleEventBusListener] Stopping render scheduler
[2017-02-08 22:42:31.316][debug][command:null][tid:54][com.facebook.buck.cli.Main] Failing build on exception.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:388)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:803)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:750)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:465)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:394)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:360)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:212)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1292)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:712)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2078)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.command.Build.executeBuild(Build.java:292)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:344)
	... 15 more
Caused by: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1053)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:1035)
	at com.facebook.buck.rules.CachingBuildEngine$4.onFailure(CachingBuildEngine.java:1022)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:140)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1405)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:42:31.316][info ][command:null][tid:54][com.facebook.buck.cli.Main] Awaiting termination of HTTP Write executor service. Waiting for all jobs to complete, or up to maximum of 1800 seconds...
[2017-02-08 22:42:31.316][info ][command:null][tid:54][com.facebook.buck.cli.Main] Awaiting termination of Disk IO executor service. Waiting for all jobs to complete, or up to maximum of 10 seconds...
[2017-02-08 22:42:31.318][debug][command:null][tid:54][com.facebook.buck.event.listener.ChromeTraceBuildListener] Writing Chrome trace to buck-out/log/2017-02-09_06h32m01s_buildcommand_27dec2ae-5da7-4513-aa45-c1011dc431f9/build.2017-02-08.22-32-02.27dec2ae-5da7-4513-aa45-c1011dc431f9.trace
[2017-02-08 22:42:31.324][info ][command:null][tid:54][com.facebook.buck.cli.Main] Awaiting termination of NETWORK executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2017-02-08 22:42:31.324][info ][command:null][tid:54][com.facebook.buck.cli.Main] Awaiting termination of CPU executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2017-02-08 22:42:31.324][info ][command:null][tid:54][com.facebook.buck.cli.Main] Awaiting termination of PROJECT executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2017-02-08 22:42:31.324][debug][command:null][tid:339][com.facebook.buck.io.AsynchronousDirectoryContentsCleaner] Starting to clean buck-out/.trash
[2017-02-08 22:42:31.324][debug][command:null][tid:54][com.facebook.buck.io.WatchmanSocketClient] Closing Watchman socket.
[2017-02-08 22:42:31.324][error][command:null][tid:54][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:388)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:803)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:750)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:465)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:394)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:360)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:212)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1292)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:712)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2078)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.command.Build.executeBuild(Build.java:292)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:344)
	... 15 more
Caused by: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1053)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:1035)
	at com.facebook.buck.rules.CachingBuildEngine$4.onFailure(CachingBuildEngine.java:1022)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:140)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1405)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space

[2017-02-08 22:42:31.325][debug][command:null][tid:339][com.facebook.buck.io.AsynchronousDirectoryContentsCleaner] Done cleaning buck-out/.trash
[2017-02-08 22:42:32.520][debug][command:null][tid:54][com.facebook.buck.cli.Main] Done.
```

**Comment by aiked** [comment]
This is a tricky issue. From the okBuck I can only see one dex job running, is that correct? If that's the case the only way to address is to increase the heap size, but you tried that already.

You could also check https://buckbuild.com/concept/buckconfig.html#resources to tweak what resources go where, that could remove some parallelism that would free up the system to succeed.

**Comment by Macarse** [comment]
@aiked I will try increasing the heap memory. What I don't understand is why gradle doesn't need it.

**Comment by sdwilsh** [comment]
I don't believe gradle runs `dx` in-process like Buck does.

**Comment by Macarse** [comment]
I fixed the problem by adding `-Xmx4g` to my `.buckjavaargs`. I guess somehow buck uses more ram than gradle. Would it be worth documenting?

**Comment by aiked** [comment]
@Macarse glad it got addressed.
