### ISSUE TITLE
Too many files open error when calculating ABI

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1171]
We have been seeing this issue popup when updating to the latest HEAD of buck.

```
Failed to calculate ABI for buck-out/bin/app/__src_debug#dummy_r_dot_java_rdotjava_bin__.
java.nio.file.FileSystemException: /Users/kage/src/android/buck-out/bin/app/__src_debug#dummy_r_dot_java_rdotjava_bin__/com/example/circleimageview/R$layout.class: Too many open files
java.nio.file.FileSystemException: /Users/kage/src/android/buck-out/bin/app/__src_debug#dummy_r_dot_java_rdotjava_bin__/com/example/circleimageview/R$layout.class: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.facebook.buck.jvm.java.abi.DirectoryReader.openInputStream(DirectoryReader.java:67)
	at com.facebook.buck.jvm.java.abi.DirectoryReader.openClass(DirectoryReader.java:58)
	at com.facebook.buck.jvm.java.abi.DirectoryReader.openClass(DirectoryReader.java:1)
	at com.facebook.buck.jvm.java.abi.StubbingLibraryReader.lambda$0(StubbingLibraryReader.java:40)
	at com.facebook.buck.jvm.java.abi.StubbingLibraryReader.openClass(StubbingLibraryReader.java:60)
	at com.facebook.buck.jvm.java.abi.StubbingLibraryReader.openClass(StubbingLibraryReader.java:1)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:74)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:59)
	at com.facebook.buck.jvm.java.CalculateAbiStep.execute(CalculateAbiStep.java:51)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1375)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$13(CachingBuildEngine.java:330)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //app:src_debug#dummy_r_dot_java failed with exit code 1:
calculate_abi
```

To help with git bisect, we can confirm this is not an issue on fe18898f1

**Comment by jkeljo** [comment]
I've been working in the ABI code a bunch recently, so I'll take a look. Do you happen to have a repro with something that I can clone and build?

**Comment by kageiit** [comment]
Yes, I have a repro case for you fortunately :)

Clone https://github.com/kageiit/android-studio-gradle-test/tree/buck_issue

and run these commands

```
./gradlew addSources
./buildWithBuck
```

and you will see the exception.

What I observed is that the problem only occurs if `resource_union` is set to true for android_library rules

**Comment by jkeljo** [comment]
Thanks for the repro case! I've root-caused this and I'm working up a fix now.

**Comment by jkeljo** [comment]
Fixed!

**Comment by kageiit** [comment]
Thanks!
