### ISSUE TITLE
Buck project fails with aars

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1178]
Repro case:
Clone https://github.com/kageiit/android-studio-gradle-test/tree/buck_issue
Run `./buckw project` to see the exception

Stacktrace:
```
[2017-02-12 13:26:55.076][debug][command:null][tid:15][com.facebook.buck.cli.Main] Failing build on exception.
com.facebook.buck.util.HumanReadableException: Target //.okbuck/cache:com.android.support.support-core-ui-25.1.0.aar (type android_prebuilt_aar) does not currently support flavors (tried [aar_prebuilt_jar])
	at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:127)
	at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:1)
	at com.facebook.buck.parser.TargetNodeParsePipeline.computeNode(TargetNodeParsePipeline.java:115)
	at com.facebook.buck.parser.TargetNodeParsePipeline.computeNode(TargetNodeParsePipeline.java:1)
	at com.facebook.buck.parser.ConvertingPipeline.dispatchComputeNode(ConvertingPipeline.java:147)
	at com.facebook.buck.parser.ConvertingPipeline.lambda$3(ConvertingPipeline.java:99)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.completeWithFuture(AbstractFuture.java:730)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:666)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1445)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kageiit** [comment]
cc @styurin @dreiss

**Comment by kageiit** [comment]
cc @marcinkosiba @sdwilsh this is blocking us from updating to a newer version of buck. Can someone please comment or let us know where we can help?

**Comment by Coneko** [comment]
You mean it's a regression? Can you bisect to find out where it was introduced?

**Comment by kageiit** [comment]
Sure. I can run a bisect and report back

**Comment by kageiit** [comment]
Ok, I ran a git bisect and it pointed out to 4da74e2747c730fd9269709d8be4df6333503faa as the problematic commit

**Comment by kageiit** [comment]
cc @illicitonion

**Comment by kageiit** [comment]
This is still broken with a new error message

```
java.lang.IllegalStateException://.okbuck/cache:com.android.support.support-core-ui-25.1.0.aar#aar_prebuilt_jar is flavored.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at com.facebook.buck.model.AbstractBuildTarget.checkUnflavored(AbstractBuildTarget.java:131)
	at com.facebook.buck.model.BuildTarget.checkUnflavored(BuildTarget.java:1)
	at com.facebook.buck.android.AndroidPrebuiltAarDescription.createPrebuiltJar(AndroidPrebuiltAarDescription.java:170)
	at com.facebook.buck.android.AndroidPrebuiltAarDescription.createBuildRule(AndroidPrebuiltAarDescription.java:136)
	at com.facebook.buck.android.AndroidPrebuiltAarDescription.createBuildRule(AndroidPrebuiltAarDescription.java:1)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:50)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:136)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:166)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:172)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:107)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:723)
	at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:432)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:384)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:353)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:210)
	at com.facebook.buck.cli.ProjectCommand.runBuild(ProjectCommand.java:703)
	at com.facebook.buck.cli.ProjectCommand.runBuild(ProjectCommand.java:690)
	at com.facebook.buck.cli.ProjectCommand.runIntellijProjectGenerator(ProjectCommand.java:620)
	at com.facebook.buck.cli.ProjectCommand.runIntellijProjectGenerator(ProjectCommand.java:789)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:508)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:210)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1319)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:729)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

**Comment by kageiit** [comment]
cc @illicitonion

**Comment by illicitonion** [comment]
Ugh. I've got a fix in review internally which actually makes your `buck project` call work :) Apologies for the half-fix!
