### ISSUE TITLE
Did not receive full-length key

### ISSUE THREAD

**Issue by mattoo88** [facebook/buck#1223]
On running "./buckw install -r app:bin_betaDebug" command i get this error. Using exopackage in project.

com.facebook.buck.android.agent.AgentMain main
SEVERE: Command failed
Throwable occurred: java.lang.IllegalStateException: Did not receive full-length key.
        at com.facebook.buck.android.agent.AgentMain.receiveAndValidateSessionKey(AgentMain.java:188)
        at com.facebook.buck.android.agent.AgentMain.doReceiveFile(AgentMain.java:147)
        at com.facebook.buck.android.agent.AgentMain.main(AgentMain.java:70)

        at com.facebook.buck.android.AdbHelper.checkReceiverOutput(AdbHelper.java:547)
        at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.installFile(ExopackageInstaller.java:645)
        at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.installFiles(ExopackageInstaller.java:568)
        at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.installSecondaryDexFiles(ExopackageInstaller.java:280)
        at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.doInstall(ExopackageInstaller.java:241)
        at com.facebook.buck.android.ExopackageInstaller$1.call(ExopackageInstaller.java:163)

**Comment by Coneko** [comment]
cc @cjhopman

**Comment by dreiss** [comment]
I think this has been resolved.  Please re-open if you have trouble.
