### ISSUE TITLE
Multiple entries with same key

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1250]
Hi, I'm building my android project with buck in release mode, but it failed ( debug mode works fine ), and the error message are download ( thanks for any help ):

BUILD FAILED: //:release_apk failed on step collect_smart_dex_inputs_hash with an exception:
Multiple entries with same key: com/xxx/xxx/ui/KButton=37bc61e48d6ca78899437eb8b3f6eebe05486ded and com/xxx/xxx/ui/KButton=37bc61e48d6ca78899437eb8b3f6eebe05486ded
java.lang.IllegalArgumentException: Multiple entries with same key: com/xxx/xxx/ui/KButton=37bc61e48d6ca78899437eb8b3f6eebe05486ded and com/xxx/xxx/ui/KButton=37bc61e48d6ca78899437eb8b3f6eebe05486ded
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131)
	at com.facebook.buck.android.HashInputJarsToDexStep.execute(HashInputJarsToDexStep.java:82)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1351)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$10(CachingBuildEngine.java:340)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ldjhust** [comment]
found the reason.
