### ISSUE TITLE
NoSuchMethodError when compiling buck

### ISSUE THREAD

**Issue by runningcode** [facebook/buck#1261]
Repro steps:
Checkout sha `badea1926e28e77836223fa2524f96b5b1adfec2`
`ant`
`./bin/buck build buck`

I get the following stack trace
```
[2017-03-24 12:01:08.431][error][command:null][tid:235][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //src/com/facebook/buck/event/api:api failed. Caused by NoSuchMethodError: com.facebook.buck.io.ProjectFilesystem.isFile(Ljava/nio/file/Path;)Z
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:392)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:834)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:767)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:469)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:391)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:357)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:227)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:69)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1337)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:746)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //src/com/facebook/buck/event/api:api failed. Caused by NoSuchMethodError: com.facebook.buck.io.ProjectFilesystem.isFile(Ljava/nio/file/Path;)Z
	at com.facebook.buck.command.Build.executeBuild(Build.java:290)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:342)
	... 16 more
Caused by: java.lang.RuntimeException: Building //src/com/facebook/buck/event/api:api failed. Caused by NoSuchMethodError: com.facebook.buck.io.ProjectFilesystem.isFile(Ljava/nio/file/Path;)Z
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1158)
	at com.facebook.buck.rules.CachingBuildEngine.access$10(CachingBuildEngine.java:1140)
	at com.facebook.buck.rules.CachingBuildEngine$2.onFailure(CachingBuildEngine.java:1127)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:140)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.facebook.buck.io.ProjectFilesystem.isFile(Ljava/nio/file/Path;)Z
	at com.facebook.buck.jvm.java.classes.ClasspathTraversal.createTraversalAdapter(ClasspathTraversal.java:79)
	at com.facebook.buck.jvm.java.classes.ClasspathTraversal.traverse(ClasspathTraversal.java:70)
	at com.facebook.buck.jvm.java.classes.DefaultClasspathTraverser.traverse(DefaultClasspathTraverser.java:30)
	at com.facebook.buck.jvm.java.AccumulateClassNamesStep.calculateClassHashes(AccumulateClassNamesStep.java:161)
	at com.facebook.buck.jvm.java.AccumulateClassNamesStep.execute(AccumulateClassNamesStep.java:84)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1495)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$15(CachingBuildEngine.java:342)
	... 8 more
```

Other tasks also fail with the same exception.

I also tried 
`./bin/buck clean` and then `./bin/buck build buck` and it still failed.

**Comment by aiked** [comment]
@runningcode I'm on it.

**Comment by aiked** [comment]
Yeap, I didn't find any issues. Glad it got resolved.
