### ISSUE TITLE
Buck fails to build sometimes due to ClassNotFoundException exceptions

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1272]
We sometimes see buck fail during the build with stack traces like this

```
[2017-03-31 14:56:44.743][error][command:null][tid:24][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NoClassDefFoundError: com/facebook/buck/io/PathListing
    at com.facebook.buck.event.listener.ChromeTraceBuildListener.deleteOldTraces(ChromeTraceBuildListener.java:199)
    at com.facebook.buck.event.listener.ChromeTraceBuildListener.outputTrace(ChromeTraceBuildListener.java:253)
    at com.facebook.buck.cli.Main.flushEventListeners(Main.java:1448)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1403)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:751)
    at com.facebook.buck.cli.Main.nailMain(Main.java:2135)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.lang.ClassNotFoundException: com.facebook.buck.io.PathListing
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more
```

We are on buck head. Any idea what the issue could be? It happens with and without buckd

**Comment by runningcode** [comment]
I've seen this a couple times as well, but its not reproducible. This seems to be a safe SHA `216919bbcc59403eeacfa9ce20a07fa37002da50`

**Comment by Coneko** [comment]
This usually means you need to run `ant clean` and rebuild Buck from scratch.

Does this happen if you use Buck built with Buck?

**Comment by kageiit** [comment]
This happens even after `git clean -fdx; ant` inside the buck codebase.

Running `killall java; watchman watch-del-all` seem to make it work sometimes (i.e killing off any old buck daemons)

**Comment by jkeljo** [comment]
I've seen this with `buckd`, but never without. Are you sure you get it even with `NO_BUCKD=1`?

**Comment by kageiit** [comment]
We do not get this with `NO_BUCKD=1`. We got around this issue by killing all active buck daemons whenever buck version has been changed

**Comment by kageiit** [comment]
Upstreamed to okbuck in https://github.com/uber/okbuck/commit/c2fa74ce38c9ddaa8d91eebde9b3d849c8e92b0e
