### ISSUE TITLE
BuckJavacTask breaks custom compilers

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1285]
This commit introduced a regression in being able to consume custom compilers like error prone in buck

https://github.com/facebook/buck/commit/590b4a96c098f9b90a6f3ec42b761fc749a9a861

Specifically this line: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/java/plugin/api/BuckJavacTaskProxy.java#L42

Causes the build to insta fail with this message

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.facebook.buck.jvm.java.plugin.api.BuckJavacTaskProxy.newInstance(BuckJavacTaskProxy.java:44)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:262)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:160)
	at com.facebook.buck.jvm.java.JavacStep.performBuild(JavacStep.java:154)
	at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:144)
	at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:106)
	at com.facebook.buck.jvm.java.JavacDirectToJarStep.execute(JavacDirectToJarStep.java:90)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1538)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$17(CachingBuildEngine.java:354)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.facebook.buck.jvm.java.plugin.api.BuckJavacTaskProxy.newInstance(BuckJavacTaskProxy.java:42)
	... 17 more
Caused by: java.lang.ClassCastException: com.google.errorprone.BaseErrorProneJavaCompiler$1 cannot be cast to com.sun.source.util.JavacTask
	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskProxyImpl.<init>(BuckJavacTaskProxyImpl.java:43)
	... 22 more
```

buckconfig is as below
```
[tools]
    javac_jar = error_prone_ant-2.0.19.jar
    compiler_class_name = com.google.errorprone.ErrorProneJavaCompiler
```

**Comment by kageiit** [comment]
cc @jkeljo @illicitonion @dreiss

**Comment by kageiit** [comment]
cc @cushon @msridhar want to get your thoughts on this. Seems like buck requires the `getTask` method of the custom compiler to return a `JavacTask` instead of a `CompilerTask`.

@cushon would you be ok if we changed https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/BaseErrorProneJavaCompiler.java#L85 to return a `JavacTask` with the methods delegating to the internal task instance?

**Comment by kageiit** [comment]
@cushon seems like The Javac Plugin for error prone does not do a refactoring/patching as well even if we were to pursue that approach instead of the one I suggested above. https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/ErrorProneJavacPlugin.java#L38

Is that accurate?

**Comment by jkeljo** [comment]
@kageiit yeah that commit does make Buck want a compiler that looks a little more like `javac` than previously, though still it's not expecting specific `javac` internals so it felt like fair game at the time.

I could probably make `BuckJavacTask` be more forgiving of differences, but there are going to be features that stop working if the custom compiler doesn't support all of `javac`'s public APIs, such as the coming source ABI generation which depends on a full implementation of the Compiler Tree API.

**Comment by kageiit** [comment]
I opened https://github.com/google/error-prone/pull/598 to address this as a possible fix in error prone

**Comment by kageiit** [comment]
After the above change, I see a new exception in buck

```
java.lang.IllegalArgumentException: No enum constant com.facebook.buck.jvm.java.plugin.api.TaskEventMirror.Kind.COMPILATION
java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant com.facebook.buck.jvm.java.plugin.api.TaskEventMirror.Kind.COMPILATION
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:144)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
	at com.google.errorprone.BaseErrorProneJavaCompiler$1.call(BaseErrorProneJavaCompiler.java:154)
	at com.facebook.buck.jvm.java.plugin.adapter.JavacTaskWrapper.call(JavacTaskWrapper.java:102)
	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTask.call(BuckJavacTask.java:1)
	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskProxyImpl.call(BuckJavacTaskProxyImpl.java:126)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:303)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:160)
	at com.facebook.buck.jvm.java.JavacStep.performBuild(JavacStep.java:154)
	at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:144)
	at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:106)
	at com.facebook.buck.jvm.java.JavacDirectToJarStep.execute(JavacDirectToJarStep.java:90)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1538)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$17(CachingBuildEngine.java:354)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No enum constant com.facebook.buck.jvm.java.plugin.api.TaskEventMirror.Kind.COMPILATION
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.facebook.buck.jvm.java.plugin.api.TaskEventMirror$Kind.valueOf(TaskEventMirror.java:1)
	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskListenerProxy.mirrorKind(BuckJavacTaskListenerProxy.java:62)
	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskListenerProxy.mirrorTaskEvent(BuckJavacTaskListenerProxy.java:55)
	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskListenerProxy.started(BuckJavacTaskListenerProxy.java:44)
	at com.facebook.buck.jvm.java.plugin.adapter.MultiplexingTaskListener.started(MultiplexingTaskListener.java:42)
	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.started(ClientCodeWrapper.java:695)
	at com.sun.tools.javac.api.MultiTaskListener.started(MultiTaskListener.java:112)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:792)
	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
	... 23 more
```

**Comment by kageiit** [comment]
Seems like this is related to an enum only present in jdk 9 and since error prone relies on jdk 9, `TaskEventMirror` needs to add this as well to its list of enums being mirrored

https://github.com/google/error-prone-javac/blob/upstream/src/jdk.compiler/share/classes/com/sun/source/util/TaskEvent.java#L77

**Comment by kageiit** [comment]
I opened https://github.com/facebook/buck/pull/1286 to address the above issue
