### ISSUE TITLE
Too many open files during build

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1288]
We are seeing sporadic issues with this stacktrace in buck on ci

```
Too many open files
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
    at java.nio.file.Files.newInputStream(Files.java:152)
    at com.facebook.buck.io.DefaultProjectFilesystemDelegate$1.openStream(DefaultProjectFilesystemDelegate.java:61)
    at com.google.common.io.ByteSource.copyTo(ByteSource.java:245)
    at com.google.common.io.ByteSource.hash(ByteSource.java:326)
    at com.facebook.buck.io.DefaultProjectFilesystemDelegate.computeSha1(DefaultProjectFilesystemDelegate.java:64)
    at com.facebook.buck.io.ProjectFilesystem.computeSha1(ProjectFilesystem.java:896)
    at com.facebook.buck.util.cache.DefaultFileHashCache.getFileHashCode(DefaultFileHashCache.java:143)
    at com.facebook.buck.util.cache.DefaultFileHashCache.getHashCodeAndFileType(DefaultFileHashCache.java:139)
    at com.facebook.buck.util.cache.DefaultFileHashCache.access$0(DefaultFileHashCache.java:129)
    at com.facebook.buck.util.cache.DefaultFileHashCache$1.load(DefaultFileHashCache.java:74)
    at com.facebook.buck.util.cache.DefaultFileHashCache$1.load(DefaultFileHashCache.java:1)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
    at com.facebook.buck.util.cache.DefaultFileHashCache.get(DefaultFileHashCache.java:216)
    at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:182)
    at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:373)
    at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:315)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:181)
    at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:232)
```

We are on buck version f6b6388c3dfd6f8323879fb3a61ec02291498bfa

**Comment by kageiit** [comment]
Tagging @andrewjcg and @dreiss as this change recently seems related https://github.com/facebook/buck/commit/5445cc26c0507e736f5e758e6ff446e2eb134106

**Comment by dreiss** [comment]
I don't think it's related.  File hash cache and rule key cache are independent.  Are you able to get the list of open files?

**Comment by kageiit** [comment]
We are actually seeing multiple stack traces

```
[2017-04-11 20:43:47.313][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.nio.file.FileSystemException: okbuck/release/AndroidManifest.xml: Too many open files
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:389)
	at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:585)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:235)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:69)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1339)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:741)
	at com.facebook.buck.cli.Main.main(Main.java:1938)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
	Suppressed: java.lang.NoClassDefFoundError: com/facebook/buck/rules/keys/RuleKeyCacheStatsEvent
		at com.facebook.buck.rules.keys.EventPostingRuleKeyCacheScope.close(EventPostingRuleKeyCacheScope.java:75)
		at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:623)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: com.facebook.buck.rules.keys.RuleKeyCacheStatsEvent
		at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 13 more
	Caused by: java.io.FileNotFoundException: /var/lib/jenkins/.gradle/caches/okbuck/buck1/build/classes/com/facebook/buck/rules/keys/RuleKeyCacheStatsEvent.class (Too many open files)
		at java.io.FileInputStream.open0(Native Method)
		at java.io.FileInputStream.open(FileInputStream.java:195)
		at java.io.FileInputStream.<init>(FileInputStream.java:138)
		at sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1288)
		at sun.misc.Resource.cachedInputStream(Resource.java:77)
		at sun.misc.Resource.getByteBuffer(Resource.java:160)
		at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
		at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
		... 18 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.nio.file.FileSystemException: build/okbuck/release/AndroidManifest.xml: Too many open files
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
	at com.facebook.buck.command.Build.executeBuild(Build.java:282)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:339)
	... 12 more
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: build/okbuck/release/AndroidManifest.xml: Too many open files
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:234)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:163)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:139)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:1)
	at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:34)
	at com.facebook.buck.rules.keys.RuleKeyFieldLoader.setFields(RuleKeyFieldLoader.java:62)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.newPopulatedBuilder(DefaultRuleKeyFactory.java:85)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.lambda$0(DefaultRuleKeyFactory.java:107)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.calculateNode(DefaultRuleKeyCache.java:120)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.lambda$6(DefaultRuleKeyCache.java:145)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.getNode(DefaultRuleKeyCache.java:146)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.get(DefaultRuleKeyCache.java:151)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:105)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:1)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$13(CachingBuildEngine.java:1361)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.RuntimeException: java.nio.file.FileSystemException: build/okbuck/release/AndroidManifest.xml: Too many open files
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:234)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:163)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:139)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:1)
		at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:34)
		at com.facebook.buck.rules.keys.RuleKeyFieldLoader.setFields(RuleKeyFieldLoader.java:62)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.newPopulatedBuilder(DefaultRuleKeyFactory.java:85)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.lambda$0(DefaultRuleKeyFactory.java:107)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.calculateNode(DefaultRuleKeyCache.java:120)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.lambda$6(DefaultRuleKeyCache.java:145)
		at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.getNode(DefaultRuleKeyCache.java:146)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.get(DefaultRuleKeyCache.java:151)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:105)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:1)
		at com.facebook.buck.rules.BuildRuleEvent$Suspended.<init>(BuildRuleEvent.java:327)
		at com.facebook.buck.rules.BuildRuleEvent$Suspended.<init>(BuildRuleEvent.java:323)
		at com.facebook.buck.rules.BuildRuleEvent$FinishedRuleKeyCalc.<init>(BuildRuleEvent.java:393)
		at com.facebook.buck.rules.BuildRuleEvent$FinishedRuleKeyCalc.<init>(BuildRuleEvent.java:390)
		at com.facebook.buck.rules.BuildRuleEvent.ruleKeyCalculationFinished(BuildRuleEvent.java:115)
		at com.facebook.buck.rules.BuildRuleEvent.lambda$0(BuildRuleEvent.java:433)
		at com.facebook.buck.rules.CachingBuildEngine.lambda$13(CachingBuildEngine.java:1362)
		... 13 more
	Caused by: java.nio.file.FileSystemException: build/okbuck/release/AndroidManifest.xml: Too many open files
		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
		at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
		at java.nio.file.Files.newByteChannel(Files.java:361)
		at java.nio.file.Files.newByteChannel(Files.java:407)
		at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
		at java.nio.file.Files.newInputStream(Files.java:152)
		at com.facebook.buck.io.DefaultProjectFilesystemDelegate$1.openStream(DefaultProjectFilesystemDelegate.java:61)
		at com.google.common.io.ByteSource.copyTo(ByteSource.java:245)
		at com.google.common.io.ByteSource.hash(ByteSource.java:326)
		at com.facebook.buck.io.DefaultProjectFilesystemDelegate.computeSha1(DefaultProjectFilesystemDelegate.java:64)
		at com.facebook.buck.io.ProjectFilesystem.computeSha1(ProjectFilesystem.java:896)
		at com.facebook.buck.util.cache.DefaultFileHashCache.getFileHashCode(DefaultFileHashCache.java:143)
		at com.facebook.buck.util.cache.DefaultFileHashCache.getHashCodeAndFileType(DefaultFileHashCache.java:139)
		at com.facebook.buck.util.cache.DefaultFileHashCache.access$0(DefaultFileHashCache.java:129)
		at com.facebook.buck.util.cache.DefaultFileHashCache$1.load(DefaultFileHashCache.java:74)
		at com.facebook.buck.util.cache.DefaultFileHashCache$1.load(DefaultFileHashCache.java:1)
		at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
		at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
		at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
		at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
		at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
		at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
		at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
		at com.facebook.buck.util.cache.DefaultFileHashCache.get(DefaultFileHashCache.java:216)
		at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:182)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:373)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:315)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:181)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:232)
		... 34 more
Caused by: java.nio.file.FileSystemException: build/okbuck/release/AndroidManifest.xml: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.facebook.buck.io.DefaultProjectFilesystemDelegate$1.openStream(DefaultProjectFilesystemDelegate.java:61)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:245)
	at com.google.common.io.ByteSource.hash(ByteSource.java:326)
	at com.facebook.buck.io.DefaultProjectFilesystemDelegate.computeSha1(DefaultProjectFilesystemDelegate.java:64)
	at com.facebook.buck.io.ProjectFilesystem.computeSha1(ProjectFilesystem.java:896)
	at com.facebook.buck.util.cache.DefaultFileHashCache.getFileHashCode(DefaultFileHashCache.java:143)
	at com.facebook.buck.util.cache.DefaultFileHashCache.getHashCodeAndFileType(DefaultFileHashCache.java:139)
	at com.facebook.buck.util.cache.DefaultFileHashCache.access$0(DefaultFileHashCache.java:129)
	at com.facebook.buck.util.cache.DefaultFileHashCache$1.load(DefaultFileHashCache.java:74)
	at com.facebook.buck.util.cache.DefaultFileHashCache$1.load(DefaultFileHashCache.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.facebook.buck.util.cache.DefaultFileHashCache.get(DefaultFileHashCache.java:216)
	at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:182)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:373)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:315)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:181)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:232)
	... 28 more
```

**Comment by Coneko** [comment]
Have you increased the open file limit on your machines? I assume this is on macOS machines, which has an extremely low value as the default.

**Comment by kageiit** [comment]
These are actually on linux. We increased the limit to more than the default i.e 8192 to a much higher value. We are able to get by, but have not had time to look into whats causing the issue yet. We are planning to profile this soon and will respond back with info. cc @msridhar

**Comment by v-jizhang** [comment]
Is this still happening? @kageiit

**Comment by kageiit** [comment]
> Is this still happening? @kageiit

nope. all good now
