### ISSUE TITLE
Buck builds fail with Assertion error

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1289]
Seeing this stacktrace on specific targets. reproducible 100% of the time

```
Caused by: java.lang.AssertionError
    at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:66)
    at com.facebook.buck.jvm.java.JavacEventSinkToBuckEventBusBridge.reportJavacPhaseStarted(JavacEventSinkToBuckEventBusBridge.java:106)
    at com.facebook.buck.jvm.java.tracing.JavacPhaseEventLogger.postStartedEvent(JavacPhaseEventLogger.java:106)
    at com.facebook.buck.jvm.java.tracing.JavacPhaseEventLogger.beginAnalyze(JavacPhaseEventLogger.java:90)
    at com.facebook.buck.jvm.java.tracing.TranslatingJavacPhaseTracer.beginAnalyze(TranslatingJavacPhaseTracer.java:112)
    at com.facebook.buck.jvm.java.tracing.TracingTaskListener$TraceCleaner.startAnalyze(TracingTaskListener.java:167)
    at com.facebook.buck.jvm.java.tracing.TracingTaskListener.started(TracingTaskListener.java:64)
    at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskListenerProxy.started(BuckJavacTaskListenerProxy.java:44)
    at com.facebook.buck.jvm.java.plugin.adapter.MultiplexingTaskListener.started(MultiplexingTaskListener.java:42)
    at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.started(ClientCodeWrapper.java:695)
    at com.sun.tools.javac.api.MultiTaskListener.started(MultiTaskListener.java:112)
    at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1194)
    at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1175)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
    at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
    at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
    at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
```

cc @jkeljo @illicitonion

**Comment by kageiit** [comment]
`.buckversion` is at 78a14a1a70a196ea67f4b04d03afade0eb3b9e16

Let me know if you want the rule definition and I can provide it

**Comment by kageiit** [comment]
@jkeljo any update on this? We are getting around this by removing the assertion and only logging non null events.

**Comment by v-jizhang** [comment]
@kageiit Please close this one if it is not happening. Thanks.

**Comment by kageiit** [comment]
Its still happening, but we patched our fork so its not affecting us right now. Let me know if you would like me to still close this

**Comment by v-jizhang** [comment]
Thank you. I'll take a look. Do you have a repro sample project?

**Comment by kageiit** [comment]
Actually nvm, seems like we removed our hack sometime in 2018. There were changes to the classes in the stacktrace circa 2017 end, so it may have been addressed then.

Thanks for checking!
