### ISSUE TITLE
Does NdkCxxPlatforms need to statically define versions?

### ISSUE THREAD

**Issue by hzsweers** [facebook/buck#1292]
This is a recurring issue for us, as [we have to manually update every time there's a new major NDK release](https://github.com/facebook/buck/pulls?q=is%3Apr+author%3Akageiit+ndk+is%3Aclosed) and it blocks local development until we update buck or go through the tedium of downgrading the NDK version on the system. Can we make the number matching accept any upper bound with the caveat of being unsupported/YMMV?

CC @kageiit 

https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/NdkCxxPlatforms.java#L102-L111

**Comment by Coneko** [comment]
I believe this is related to the fact google has changed how the NDK and SDK identify versions several times: both in how to find the version string, and how the version string is to be interpreted.

Ideally we'd have the users specify what version is installed where in the config, rather than doing the whole find installed versions ourselves voodoo, but that is probably not happening anytime soon.

cc @aiked, @marcinkosiba

**Comment by hzsweers** [comment]
This broke again on NDK 16

```
Generating project: finished in 26.6 sec
[2017-09-06 17:43:59.012][error][command:null][tid:15][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.AssertionError: Unknown ndk version: 16.0.4293906-beta1
	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
	at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.<init>(NdkCxxPlatforms.java:1128)
	at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.<init>(NdkCxxPlatforms.java:1106)
	at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:572)
	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:279)
	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:244)
	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:221)
	at com.facebook.buck.android.toolchain.NdkCxxPlatformsProvider.create(NdkCxxPlatformsProvider.java:58)
	at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:280)
	at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:238)
	at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:46)
	at com.facebook.buck.rules.Cell.lambda$0(Cell.java:91)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
	at com.facebook.buck.rules.Cell.getKnownBuildRuleTypes(Cell.java:120)
	at com.facebook.buck.rules.Cell.getAllDescriptions(Cell.java:220)
	at com.facebook.buck.rules.Cell.createBuildFileParser(Cell.java:299)
	at com.facebook.buck.parser.PerBuildState.createBuildFileParser(PerBuildState.java:180)
	at com.facebook.buck.parser.PerBuildState.lambda$0(PerBuildState.java:118)
	at com.facebook.buck.parser.ProjectBuildFileParserPool.lambda$1(ProjectBuildFileParserPool.java:102)
	at com.facebook.buck.util.concurrent.ResourcePool.createIfAllowed(ResourcePool.java:239)
	at com.facebook.buck.util.concurrent.ResourcePool.obtainResource(ResourcePool.java:200)
	at com.facebook.buck.util.concurrent.ResourcePool.requestResource(ResourcePool.java:176)
	at com.facebook.buck.util.concurrent.ResourcePool.access$0(ResourcePool.java:175)
	at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:129)
	at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:1)
```
