### ISSUE TITLE
Cannot build Go on Windows

### ISSUE THREAD

**Issue by Dimagog** [facebook/buck#1314]
Trying use `go_binary` rule on Windows fails. Repro steps:
```
rem Start from Buck root dir
cd test\com\facebook\buck\go\testdata\simple_binary
ren BUCK.fixture BUCK
buck build //test/com/facebook/buck/go/testdata/simple_binary:xyzzy
```
Results in exception:
```
[-] BUILDING...FINISHED 1.1s
[2017-04-30 15:23:23.038][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.facebook.buck.go.GoPlatformFlavorDomain.getValue(GoPlatformFlavorDomain.java:141)
        at com.facebook.buck.go.GoBuckConfig.lambda$3(GoBuckConfig.java:102)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
        at com.facebook.buck.go.GoBuckConfig.getDefaultPlatform(GoBuckConfig.java:119)
        at com.facebook.buck.go.GoBinaryDescription.findDepsForTargetFromConstructorArgs(GoBinaryDescription.java:100)
        at com.facebook.buck.go.GoBinaryDescription.findDepsForTargetFromConstructorArgs(GoBinaryDescription.java:1)
        at com.facebook.buck.rules.TargetNodeFactory.create(TargetNodeFactory.java:104)
        at com.facebook.buck.rules.TargetNodeFactory.createFromObject(TargetNodeFactory.java:60)
        at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:168)
        at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:1)
        at com.facebook.buck.parser.TargetNodeParsePipeline.computeNode(TargetNodeParsePipeline.java:118)
        at com.facebook.buck.parser.TargetNodeParsePipeline.computeNode(TargetNodeParsePipeline.java:1)
        at com.facebook.buck.parser.ConvertingPipeline.dispatchComputeNode(ConvertingPipeline.java:139)
        at com.facebook.buck.parser.ConvertingPipeline.lambda$3(ConvertingPipeline.java:100)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
        at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:104)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by aiked** [comment]
Hello @Dimagog, Go is not fully supported at Buck but maybe @mikekap can help with this one.

**Comment by mkaczanowski** [comment]
@Dimagog it's been a while, do you still run into this issue?

**Comment by mkaczanowski** [comment]
Closing issue. The issue was reported a year ago and I know people who have been building successfully on  windows.
Feel free to reopen if you still happen to have issue. Also our integration tests are passing
