### ISSUE TITLE
Ant Fails to Compile Source files

### ISSUE THREAD

**Issue by amanrajdce** [facebook/buck#1344]
I am trying to build buck using ant:
``$ java -version``
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
``$ ant -version``
Apache Ant(TM) version 1.9.6 compiled on July 8 2015
``$ python --version``
Python 2.7.12

While compiling source files it fails. I can't figure out what wrong I am doing 

```
ubuntu@ip-172-31-14-248:~/buck$ ant
Buildfile: /home/ubuntu/buck/build.xml

clear-successful-build:

checkversion:

compile-testrunner:
    [mkdir] Created dir: /home/ubuntu/buck/build/testrunner/classes
    [javac] Compiling 17 source files to /home/ubuntu/buck/build/testrunner/classes

compile-aosp:
    [mkdir] Created dir: /home/ubuntu/buck/build/aosp/classes
    [javac] Compiling 67 source files to /home/ubuntu/buck/build/aosp/classes
    [javac] [compiled 17912 lines in 3453 ms: 5187.3 lines/s]
    [javac] [146 .class files generated]

compile-manual-gen-src:
    [mkdir] Created dir: /home/ubuntu/buck/build/src-gen/classes
    [javac] Compiling 104 source files to /home/ubuntu/buck/build/src-gen/classes

tracing-api:
    [mkdir] Created dir: /home/ubuntu/buck/build/tracing-api/classes
    [javac] Compiling 2 source files to /home/ubuntu/buck/build/tracing-api/classes
    [javac] [compiled 182 lines in 974 ms: 186.8 lines/s]
    [javac] [3 .class files generated]
      [jar] Building jar: /home/ubuntu/buck/build/tracing-api/tracing-api.jar

bootstrapper:
    [mkdir] Created dir: /home/ubuntu/buck/build/bootstrapper/classes
    [javac] Compiling 18 source files to /home/ubuntu/buck/build/bootstrapper/classes
    [javac] [compiled 783 lines in 1315 ms: 595.4 lines/s]
    [javac] [19 .class files generated]
      [jar] Building jar: /home/ubuntu/buck/build/bootstrapper/bootstrapper.jar

package-resources:
    [mkdir] Created dir: /home/ubuntu/buck/build/classes/com/facebook/buck/android
     [copy] Copying 1 file to /home/ubuntu/buck/build/classes/com/facebook/buck/android
     [copy] Copying 1 file to /home/ubuntu/buck/build/classes/com/facebook/buck/android
     [copy] Copying 1 file to /home/ubuntu/buck/build/classes/com/facebook/buck/android
     [copy] Copying 1 file to /home/ubuntu/buck/build/classes/com/facebook/buck/android
     [copy] Copying 9 files to /home/ubuntu/buck/build/classes/buck_parser

dx-check-build:

dx:
    [mkdir] Created dir: /home/ubuntu/buck/build/dx_classes
    [javac] Compiling 391 source files to /home/ubuntu/buck/build/dx_classes
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Creating empty /home/ubuntu/buck/build/dx_classes/com/android/dx/rop/package-info.class
    [javac] Creating empty /home/ubuntu/buck/build/dx_classes/com/android/dx/ssa/package-info.class
      [jar] Building jar: /home/ubuntu/buck/build/dx.jar

compile:
    [javac] Compiling 2038 source files to /home/ubuntu/buck/build/classes
    [javac] ----------
    [javac] 1. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 0)
    [javac] 	package com.facebook.buck.apple;
    [javac] 	^
    [javac] Internal compiler error: java.lang.OutOfMemoryError: Java heap space at org.eclipse.jdt.internal.compiler.lookup.BoundSet.copy(BoundSet.java:454)
    [javac] ----------
    [javac] 2. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 402)
    [javac] 	private boolean runTestSeparately;
    [javac] 	                ^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.runTestSeparately is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 3. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 419)
    [javac] 	private boolean isUiTest;
    [javac] 	                ^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.isUiTest is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 4. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 436)
    [javac] 	private SourceList exportedHeaders;
    [javac] 	                   ^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.exportedHeaders is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 5. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 453)
    [javac] 	private PatternMatchedCollection<SourceList> exportedPlatformHeaders;
    [javac] 	                                             ^^^^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.exportedPlatformHeaders is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 6. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 470)
    [javac] 	private PatternMatchedCollection<ImmutableList<String>> exportedPlatformPreprocessorFlags;
    [javac] 	                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.exportedPlatformPreprocessorFlags is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 7. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 487)
    [javac] 	private PatternMatchedCollection<ImmutableList<StringWithMacros>> exportedPlatformLinkerFlags;
    [javac] 	                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.exportedPlatformLinkerFlags is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 8. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 504)
    [javac] 	private PatternMatchedCollection<ImmutableSortedSet<BuildTarget>> exportedPlatformDeps;
    [javac] 	                                                                  ^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.exportedPlatformDeps is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 9. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 521)
    [javac] 	private boolean reexportAllHeaderDependencies;
    [javac] 	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.reexportAllHeaderDependencies is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 10. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 538)
    [javac] 	private CxxDeps exportedCxxDeps;
    [javac] 	                ^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.exportedCxxDeps is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 11. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 550)
    [javac] 	private CxxDeps cxxDeps;
    [javac] 	                ^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.cxxDeps is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 12. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 562)
    [javac] 	private boolean thinLto;
    [javac] 	                ^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.thinLto is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 13. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 579)
    [javac] 	private PatternMatchedCollection<ImmutableSortedSet<SourceWithFlags>> platformSrcs;
    [javac] 	                                                                      ^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.platformSrcs is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 14. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 596)
    [javac] 	private SourceList headers;
    [javac] 	                   ^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.headers is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 15. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 613)
    [javac] 	private PatternMatchedCollection<SourceList> platformHeaders;
    [javac] 	                                             ^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.platformHeaders is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 16. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 630)
    [javac] 	private PatternMatchedCollection<ImmutableList<String>> platformCompilerFlags;
    [javac] 	                                                        ^^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.platformCompilerFlags is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 17. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 647)
    [javac] 	private PatternMatchedCollection<ImmutableList<String>> platformPreprocessorFlags;
    [javac] 	                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.platformPreprocessorFlags is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 18. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 664)
    [javac] 	private PatternMatchedCollection<ImmutableList<StringWithMacros>> platformLinkerFlags;
    [javac] 	                                                                  ^^^^^^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.platformLinkerFlags is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 19. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 681)
    [javac] 	private PatternMatchedCollection<ImmutableSortedSet<BuildTarget>> platformDeps;
    [javac] 	                                                                  ^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.platformDeps is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 20. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 698)
    [javac] 	private ImmutableSortedSet<Flavor> defaultFlavors;
    [javac] 	                                   ^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.defaultFlavors is hiding a field from type AppleTestDescriptionArg
    [javac] ----------
    [javac] 21. ERROR in /home/ubuntu/buck/build/gen/com/facebook/buck/apple/AppleTestDescriptionArg.java (at line 710)
    [javac] 	private CxxDeps privateCxxDeps;
    [javac] 	                ^^^^^^^^^^^^^^
    [javac] The field AppleTestDescriptionArg.InitShim.privateCxxDeps is hiding a field from type AppleTestDescriptionArg
    [javac] ----------

BUILD FAILED
/home/ubuntu/buck/build.xml:436: The following error occurred while executing this line:
/home/ubuntu/buck/build.xml:379: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.core.JDTCompilerAdapter.execute(JDTCompilerAdapter.java:80)
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1160)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:936)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jdt.internal.compiler.lookup.BoundSet.copy(BoundSet.java:454)
	at org.eclipse.jdt.internal.compiler.lookup.InferenceContext18.inferInvocationType(InferenceContext18.java:412)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedGenericMethodBinding.computeCompatibleMethod18(ParameterizedGenericMethodBinding.java:260)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedGenericMethodBinding.computeCompatibleMethod(ParameterizedGenericMethodBinding.java:84)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.computeCompatibleMethod(Scope.java:743)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.computeCompatibleMethod(Scope.java:700)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod0(Scope.java:1656)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod(Scope.java:1557)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getMethod(Scope.java:2840)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.findMethodBinding(MessageSend.java:915)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:729)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:252)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:634)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:306)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:544)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1195)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1308)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:593)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:867)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:141)
	at java.lang.Thread.run(Thread.java:748)

Total time: 1 minute 39 seconds
```

Running the ant with ``ant -v`` shows ant is pointing to correct java version
```
ubuntu@ip-172-31-14-248:~/buck$ ant -v
Apache Ant(TM) version 1.9.6 compiled on July 8 2015
Trying the default build file: build.xml
Buildfile: /home/ubuntu/buck/build.xml
Detected Java version: 1.8 in: /usr/lib/jvm/java-8-oracle/jre
Detected OS: Linux
parsing buildfile /home/ubuntu/buck/build.xml with URI = file:/home/ubuntu/buck/build.xml
Project base dir set to: /home/ubuntu/buck 
```
How do I fix this issue? Let me know if I am doing anything wrong

**Comment by styurin** [comment]
You should use ANT_OPTS like this:

```
ANT_OPTS=-Xmx512m ant
```
