### ISSUE TITLE
Exopackage fails to install on Pixel running Android O

### ISSUE THREAD

**Issue by phoenixuprising** [facebook/buck#1353]
I attempted to install an exopackage application on my Pixel XL on Android O and it failed with the following stacktrace. I also tested a Pixel C running Android O with the same build number and it installed and ran successfully.

Device: Pixel XL
AOS: Android O
Build: OPP2.170420.019 

```App not installed.  Installing now.
Installing apk on HT73A0203370 (Pixel XL).
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🏖  (Watchman reported no changes)
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.1s [100%] (2/2 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
    Details: http://localhost:64272/trace/9d9e6517-4ef4-43ac-9bb8-21b0255541f7
[+] INSTALLING...11.2s
BUILD FAILED: Failed: install exopackage apk
java.util.concurrent.ExecutionException: com.facebook.buck.android.AdbHelper$CommandFailedException: Command 'umask 022 && dalvikvm -classpath /data/app/com.facebook.buck.android.agent-1.apk:/data/app/com.facebook.buck.android.agent-2.apk:/data/app/com.facebook.buck.android.agent-1/base.apk:/data/app/com.facebook.buck.android.agent-2/base.apk com.facebook.buck.android.agent.AgentMain receive-file 2828 844816 /data/local/tmp/exopackage/com.squareup.exo/secondary-dex/secondary-310277bd35db1c4d13f99c92127c16656ab938a8.dex.jar ; echo -n :$?' failed with code 1.  Output:
Unable to locate class 'com/facebook/buck/android/agent/AgentMain'
java.lang.ClassNotFoundException: Didn't find class "com.facebook.buck.android.agent.AgentMain" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Exception in thread "main" java.lang.ClassNotFoundException: Didn't find class "com.facebook.buck.android.agent.AgentMain" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479)
    at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
    at com.facebook.buck.android.AdbHelper.adbCall(AdbHelper.java:380)
    at com.facebook.buck.android.ExopackageInstaller$AdbInterface.adbCall(ExopackageInstaller.java:141)
    at com.facebook.buck.android.ExopackageInstaller.install(ExopackageInstaller.java:228)
    at com.facebook.buck.android.AdbHelper.installApk(AdbHelper.java:578)
    at com.facebook.buck.cli.InstallCommand.installApk(InstallCommand.java:363)
    at com.facebook.buck.cli.InstallCommand.install(InstallCommand.java:248)
    at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:217)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
    at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:67)
    at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:83)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:940)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:343)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1731)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: com.facebook.buck.android.AdbHelper$CommandFailedException: Command 'umask 022 && dalvikvm -classpath /data/app/com.facebook.buck.android.agent-1.apk:/data/app/com.facebook.buck.android.agent-2.apk:/data/app/com.facebook.buck.android.agent-1/base.apk:/data/app/com.facebook.buck.android.agent-2/base.apk com.facebook.buck.android.agent.AgentMain receive-file 2828 844816 /data/local/tmp/exopackage/com.squareup.exo/secondary-dex/secondary-310277bd35db1c4d13f99c92127c16656ab938a8.dex.jar ; echo -n :$?' failed with code 1.  Output:
Unable to locate class 'com/facebook/buck/android/agent/AgentMain'
java.lang.ClassNotFoundException: Didn't find class "com.facebook.buck.android.agent.AgentMain" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Exception in thread "main" java.lang.ClassNotFoundException: Didn't find class "com.facebook.buck.android.agent.AgentMain" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.facebook.buck.android.AdbHelper.checkReceiverOutput(AdbHelper.java:548)
    at com.facebook.buck.android.RealExopackageDevice.installFile(RealExopackageDevice.java:242)
    at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.installFiles(ExopackageInstaller.java:627)
    at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.installSecondaryDexFiles(ExopackageInstaller.java:346)
    at com.facebook.buck.android.ExopackageInstaller$SingleDeviceInstaller.doInstall(ExopackageInstaller.java:303)
    at com.facebook.buck.android.ExopackageInstaller.lambda$0(ExopackageInstaller.java:232)
    at com.facebook.buck.android.ExopackageInstaller$AdbInterface$1.call(ExopackageInstaller.java:145)
    at com.facebook.buck.android.AdbHelper$AdbCallable$1.call(AdbHelper.java:446)
    at com.facebook.buck.android.AdbHelper$AdbCallable$1.call(AdbHelper.java:1)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)```

**Comment by Coneko** [comment]
cc @dreiss @cjhopman

**Comment by dreiss** [comment]
I fixed the installer.  We're still having some trouble with our internal version of the runtime, but I think the open-source version is working.  Please re-open if you have trouble.

**Comment by phoenixuprising** [comment]
Sorry for the bit of delay. I was just able to test this and it looks like it is now working properly. Thanks for the fix.
