### ISSUE TITLE
Project generation is broken on buck master

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1397]
When generating projects, this exception is thrown

```
[-] GENERATING PROJECT...FINISHED 3.2s
[2017-06-25 19:52:52.927][error][command:null][tid:15][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException
	at com.facebook.buck.ide.intellij.WorkspaceUpdater.updateIgnoredFolders(WorkspaceUpdater.java:134)
	at com.facebook.buck.ide.intellij.WorkspaceUpdater.updateExistingWorkspace(WorkspaceUpdater.java:106)
	at com.facebook.buck.ide.intellij.WorkspaceUpdater.updateOrCreateWorkspace(WorkspaceUpdater.java:73)
	at com.facebook.buck.ide.intellij.IjProjectWriter.writeWorkspace(IjProjectWriter.java:217)
	at com.facebook.buck.ide.intellij.IjProjectWriter.write(IjProjectWriter.java:72)
	at com.facebook.buck.ide.intellij.IjProject.write(IjProject.java:113)
	at com.facebook.buck.ide.intellij.IjProjectCommandHelper.writeProjectAndGetRequiredBuildTargets(IjProjectCommandHelper.java:268)
	at com.facebook.buck.ide.intellij.IjProjectCommandHelper.runIntellijProjectGenerator(IjProjectCommandHelper.java:232)
	at com.facebook.buck.ide.intellij.IjProjectCommandHelper.parseTargetsAndRunProjectGenerator(IjProjectCommandHelper.java:195)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:291)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:66)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:917)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:334)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1697)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

To repro, Checkout https://github.com/uber/okbuck , update buckversion to head and run `./buckw project`

**Comment by kageiit** [comment]
cc @styurin

**Comment by clonetwin26** [comment]
https://github.com/facebook/buck/commit/5443fc29ac6e5db81aaa3ed3dce9fb4853cd025c

**Comment by styurin** [comment]
Fixed in 40fb511f5b3e27027175497940f3fda687fb30b4

**Comment by kageiit** [comment]
Thanks for the fast fix @styurin !

**Comment by clonetwin26** [comment]
wooooo \o/
