### ISSUE TITLE
#aar_unzip] failed. Caused by [NoSuchElementException]: No value present

### ISSUE THREAD

**Issue by guhan121** [facebook/buck#1407]
in a right  *.aar file

/AndroidManifest.xml (mandatory)
/classes.jar (mandatory)
/res/ (mandatory)
/R.txt (mandatory)
/assets/ (optional)
/libs/*.jar (optional)
/jni//*.so (optional)
/proguard.txt (optional)
/lint.jar (optional)

--------------------------------------------------------------------------------
but our aar file may be like this
```
a
├── AndroidManifest.xml
└── META-INF
    └── MANIFEST.MF

1 directory, 2 files
cat a/AndroidManifest.xml 
<?xml version="1.0" encoding="utf-8"?> 
 <manifest /> 

or like this 

|-- AndroidManifest.xml
|-- META-INF
|   `-- MANIFEST.MF
`-- small-artifacts
    |-- build_version.txt
    |-- D.txt
    |-- mapping.txt
    |-- plugin.json
    |-- public_mapping.txt
    `-- R.txt

2 directories, 8 files
```

so when i run "./buckw build appRelease"

I got

```
[2017-06-29 05:22:34.462][error][command:null][tid:15][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building rule [//.okbuck/cache:com.aa.aaaa-1.0.0-SNAPSHOT.aar#aar_unzip] failed. Caused by [NoSuchElementException]:
No value present
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:382)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:952)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:882)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:516)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:418)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:384)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:66)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:930)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:335)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1669)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building rule [//.okbuck/cache:com.aa.bb-1.1.0-SNAPSHOT.aar#aar_unzip] failed. Caused by [NoSuchElementException]:
No value present
	at com.facebook.buck.command.Build.executeBuild(Build.java:278)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:331)
	... 16 more
Caused by: java.lang.RuntimeException: Building rule [//.okbuck/cache:com.aa.bb-1.1.0-SNAPSHOT.aar#aar_unzip] failed. Caused by [NoSuchElementException]:
No value present
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1214)
	at com.facebook.buck.rules.CachingBuildEngine.access$18(CachingBuildEngine.java:1205)
	at com.facebook.buck.rules.CachingBuildEngine$2.onFailure(CachingBuildEngine.java:1164)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:138)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:137)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.buck.android.UnzipAar.initializeFromDisk(UnzipAar.java:192)
	at com.facebook.buck.android.UnzipAar.initializeFromDisk(UnzipAar.java:1)
	at com.facebook.buck.rules.BuildOutputInitializer.initializeFromDisk(BuildOutputInitializer.java:41)
	at com.facebook.buck.rules.CachingBuildEngine.doInitializeFromDisk(CachingBuildEngine.java:1585)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$11(CachingBuildEngine.java:934)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$22(CachingBuildEngine.java:2001)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	... 10 more
```

how can i fix it.

**Comment by yiding** [comment]
You can fix it by constructing your aar file with the correct layout.
