### ISSUE TITLE
how to fix "duplicate entry"

### ISSUE THREAD

**Issue by guhan121** [facebook/buck#1409]
while our project contain some sub modules if sub module use `com.nucleon.heap-5.2.3_dev-SNAPSHOT.aar`
and master use `com.nucleon.android.nucleonvideolib.nucleonvideolib-2.3.41.5-dev-SNAPSHOT.aar`
because assets/bf1.dat both of them

so we got the  exception "duplicate entry"
i cmp them ，and them are same file.

```
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.heap-5.2.3_dev-SNAPSHOT.aar#aar_unzip__/assets/bf1.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.heap-5.2.3_dev-SNAPSHOT.aar#aar_unzip__/assets/bf3.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.heap-5.2.3_dev-SNAPSHOT.aar#aar_unzip__/assets/ek.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.heap-5.2.3_dev-SNAPSHOT.aar#aar_unzip__/assets/bf2.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.android.nucleonvideolib.nucleonvideolib-2.3.41.5-dev-SNAPSHOT.aar#aar_unzip__/assets/bf1.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.android.nucleonvideolib.nucleonvideolib-2.3.41.5-dev-SNAPSHOT.aar#aar_unzip__/assets/bf3.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.android.nucleonvideolib.nucleonvideolib-2.3.41.5-dev-SNAPSHOT.aar#aar_unzip__/assets/ek.dat
./buck-out/bin/.okbuck/cache/__unpack_com.nucleon.android.nucleonvideolib.nucleonvideolib-2.3.41.5-dev-SNAPSHOT.aar#aar_unzip__/assets/bf2.dat
```

i modify.
`com.facebook.buck.zip.AppendingZipOutputStreamImpl#actuallyPutNextEntry`

```
  @Override
  public void actuallyPutNextEntry(ZipEntry entry) throws IOException {
    if(!seenNames.add(entry.getName()) && entry.getName().contains(".dat"))
    {
      LOG.error("duplicate entry: " + entry.getName());
      return;
    }
    if (throwExceptionsOnDuplicate && !seenNames.add(entry.getName())) {
      // Same exception as ZipOutputStream.
      throw new ZipException("duplicate entry: " + entry.getName());
    }

    currentEntry = new EntryAccounting(clock, entry, currentOffset);
    entries.add(currentEntry);

    currentOffset += currentEntry.writeLocalFileHeader(delegate);
  }
```
when i avoid this problem (but I'm not sure I did right);

i got ::

```
[2017-07-02 23:12:26.121][debug][command:0ecc1345-b8ae-4d7d-8d04-089b69381337][tid:01][com.facebook.buck.command.Build] Got an exception during the build.
com.facebook.buck.step.StepFailedException: //client:bin_release#merge_assets failed on step merging_assets with an exception:
duplicate entry: AndroidManifest.xml
java.util.zip.ZipException: duplicate entry: AndroidManifest.xml
	at com.facebook.buck.zip.AppendingZipOutputStreamImpl.actuallyPutNextEntry(AppendingZipOutputStreamImpl.java:74)
	at com.facebook.buck.zip.CustomZipOutputStream.putNextEntry(CustomZipOutputStream.java:76)
	at com.facebook.buck.zip.DeterministicZipBuilder.addEntry(DeterministicZipBuilder.java:53)
	at com.facebook.buck.android.resources.ResourcesZipBuilder.addEntry(ResourcesZipBuilder.java:60)
	at com.facebook.buck.android.MergeAssets$MergeAssetsStep.execute(MergeAssets.java:182)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.step.StepRunner.lambda$0(StepRunner.java:39)
	at com.facebook.buck.rules.CachingBuildEngine$BuildLocally$1.lambda$0(CachingBuildEngine.java:2115)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:80)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.util.zip.ZipException: duplicate entry: AndroidManifest.xml
		at com.facebook.buck.zip.AppendingZipOutputStreamImpl.actuallyPutNextEntry(AppendingZipOutputStreamImpl.java:74)
		at com.facebook.buck.zip.CustomZipOutputStream.putNextEntry(CustomZipOutputStream.java:76)
		at com.facebook.buck.zip.DeterministicZipBuilder.addEntry(DeterministicZipBuilder.java:53)
		at com.facebook.buck.android.resources.ResourcesZipBuilder.addEntry(ResourcesZipBuilder.java:60)
		at com.facebook.buck.android.resources.ResourcesZipBuilder.close(ResourcesZipBuilder.java:72)
		at com.facebook.buck.android.MergeAssets$MergeAssetsStep.execute(MergeAssets.java:215)
		... 11 more

	at com.facebook.buck.step.StepFailedException.createForFailingStepWithException(StepFailedException.java:92)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.step.StepRunner.lambda$0(StepRunner.java:39)
	at com.facebook.buck.rules.CachingBuildEngine$BuildLocally$1.lambda$0(CachingBuildEngine.java:2115)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:80)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

crying.......   /(ㄒoㄒ)/~~

**Comment by kageiit** [comment]
@guhan121 Another solution would be to use the same aar for both places as well

**Comment by guhan121** [comment]
i use md5 fix this issue,thanks
