### ISSUE TITLE
Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by marcinkwiatkowski** [facebook/buck#1418]
We started seeing following build failures in one of the very recent versions of buck (`62b00c0a0e20a8224dd0315612f6ffa346636f40`)

```
BUILD FAILED: //instant-frameworks/deeplinks:lint_release failed with exit code 1:
genrule
stderr: Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:284)
    at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:238)
    at java.util.jar.JarVerifier.processEntry(JarVerifier.java:273)
    at java.util.jar.JarVerifier.update(JarVerifier.java:228)
    at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
    at java.util.jar.JarFile.getInputStream(JarFile.java:450)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
    at sun.misc.Resource.cachedInputStream(Resource.java:77)
    at sun.misc.Resource.getByteBuffer(Resource.java:160)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

Genrules that started failing:

```
genrule(
	name = 'lint_release',
	srcs = [
		'src/main/java',
	],
	out = 'lint_release_out',
	bash = '' \
	'mkdir -p $OUT; ' \
	'RUN_IN=`dirname $(location //.okbuck/gen/instant-frameworks/deeplinks/release:AndroidManifest.xml)`; ' \
	'exec java ' \
	'-Djava.awt.headless=true ' \
	'-Xmx1024m ' \
	'-classpath $(location //.okbuck/cache/lint:okbuck_lint) ' \
	'com.android.tools.lint.Main ' \
	'--classpath $(location :src_release) ' \
	'--exitcode ' \
	'--fullpath ' \
	'--config $(location //.okbuck/cache/lint:gradle-scripts_lint.xml) ' \
	'--xml "$OUT/lint-results.xml" ' \
	'--html "$OUT/lint-results.html" ' \
	'--sources src/main/java ' \
	'$RUN_IN ' \
	'',
)
```

**Comment by mzlee** [comment]
I believe this was resolved by reverting https://github.com/facebook/buck/commit/78311f8e1a5196dc6d4079ecd8adbff4acff238e

Does this still fail on more recent version?

**Comment by marcinkwiatkowski** [comment]
correct, thanks @mzlee
