### ISSUE TITLE
UncheckedExecutionException caused by NoSuchFileException

### ISSUE THREAD

**Issue by samuela** [facebook/buck#1433]
Ran across an uncheck exception today:

```
$ buck build //device:main
[-] PROCESSING BUCK FILES...FINISHED 0.6s [100%]
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 2.2s [100%] (6/7 JOBS, 3 UPDATED, 2 [28.6%] CACHE MISS)
[2017-07-20 22:01:44.362][error][command:null][tid:265][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //device:main#binary failed. Caused by UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:382)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:921)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:853)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:509)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:415)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:381)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:66)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:900)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:329)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1674)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //device:main#binary failed. Caused by UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.facebook.buck.command.Build.executeBuild(Build.java:278)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:331)
	... 16 more
Caused by: java.lang.RuntimeException: Building //device:main#binary failed. Caused by UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1175)
	at com.facebook.buck.rules.CachingBuildEngine.access$1200(CachingBuildEngine.java:115)
	at com.facebook.buck.rules.CachingBuildEngine$2.onFailure(CachingBuildEngine.java:1118)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:138)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4899)
	at com.facebook.buck.rules.keys.SingleBuildRuleKeyCache.getInternal(SingleBuildRuleKeyCache.java:41)
	at com.facebook.buck.rules.keys.SingleBuildRuleKeyCache.get(SingleBuildRuleKeyCache.java:48)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory.build(InputBasedRuleKeyFactory.java:94)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory.build(InputBasedRuleKeyFactory.java:46)
	at com.facebook.buck.rules.CachingBuildEngine.calculateInputBasedRuleKey(CachingBuildEngine.java:1863)
	at com.facebook.buck.rules.CachingBuildEngine.checkInputBasedCaches(CachingBuildEngine.java:407)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$buildOrFetchFromCache$5(CachingBuildEngine.java:491)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$null$25(CachingBuildEngine.java:2009)
	... 8 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4899)
	at com.facebook.buck.rules.keys.SingleBuildRuleKeyCache.getInternal(SingleBuildRuleKeyCache.java:41)
	at com.facebook.buck.rules.keys.SingleBuildRuleKeyCache.get(SingleBuildRuleKeyCache.java:52)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory.buildAppendableKey(InputBasedRuleKeyFactory.java:102)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory.access$400(InputBasedRuleKeyFactory.java:46)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setAppendableRuleKey(InputBasedRuleKeyFactory.java:161)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setAppendableRuleKey(InputBasedRuleKeyFactory.java:150)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:137)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:177)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:130)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:86)
	at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:31)
	at com.facebook.buck.rules.keys.RuleKeyFieldLoader.setFields(RuleKeyFieldLoader.java:62)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory.calculateBuildRuleKey(InputBasedRuleKeyFactory.java:81)
	at com.facebook.buck.rules.keys.SingleBuildRuleKeyCache.lambda$getInternal$0(SingleBuildRuleKeyCache.java:41)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 18 more
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:225)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:130)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:86)
	at com.facebook.buck.rules.args.AbstractSourcePathArg.appendToRuleKey(AbstractSourcePathArg.java:68)
	at com.facebook.buck.rules.args.SourcePathArg.appendToRuleKey(SourcePathArg.java:15)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory.calculateRuleKeyAppendableKey(InputBasedRuleKeyFactory.java:87)
	at com.facebook.buck.rules.keys.SingleBuildRuleKeyCache.lambda$getInternal$0(SingleBuildRuleKeyCache.java:41)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 39 more
Caused by: java.nio.file.NoSuchFileException: /Users/samuelainsworth/Development/parking/buck-out/gen/vendor/opencv/opencv-build/lib/libopencv.dylib
	at com.facebook.buck.util.cache.StackedFileHashCache.lambda$get$0(StackedFileHashCache.java:175)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:175)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:354)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setPath(InputBasedRuleKeyFactory.java:186)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setPath(InputBasedRuleKeyFactory.java:150)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:296)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setSourcePath(InputBasedRuleKeyFactory.java:205)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setSourcePath(InputBasedRuleKeyFactory.java:150)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:223)
	... 50 more
```

`//vendor/opencv/BUCK`:

```python
remote_file(
  name = 'opencv-src',
  url = 'https://github.com/opencv/opencv/archive/3.2.0.zip',
  sha1 = '7a7d2eb8cf617f58d610d856e531f3d92b89bc42',
  type = 'exploded_zip'
)

genrule(
  name = 'opencv-build',
  cmd = 'cp -r $(location :opencv-src)/opencv-3.2.0 $SRCDIR && \
         cd $SRCDIR/opencv-3.2.0 && \
         mkdir build && \
         cd build && \
         cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=$OUT .. && \
         make -j 2 && \
         make install',
  out = '.'
)

prebuilt_cxx_library(
  name = 'opencv',
  visibility = ['PUBLIC'],
  lib_dir = '$(location :opencv-build)/lib',
  include_dirs = ['$(location :opencv-build)/include']
)
```

`device/BUCK`:

```python
cxx_binary(
  name = 'main',
  srcs = ['main.cpp'],
  deps = ['//vendor/opencv:opencv']
)
```

and finally `device/main.cpp`:

```c++
#include <stdio.h>
#include <opencv2/opencv.hpp>

int main(int argc, char** argv)
{
  if ( argc != 2 )
  {
    printf("usage: DisplayImage.out <Image_Path>\n");
    return -1;
  }
  cv::Mat image;
  image = cv::imread( argv[1], 1 );
  if ( !image.data )
  {
    printf("No image data \n");
    return -1;
  }
  cv::namedWindow("Display Image", cv::WINDOW_AUTOSIZE );
  cv::imshow("Display Image", image);
  cv::waitKey(0);
  return 0;
}
```

I presume that the ultimate cause of this is an issue with the way OpenCV is being built and packaged, but I figure that unchecked exceptions are likely worthy of a bug report regardless.

**Comment by samuela** [comment]
cc @drshrey

**Comment by kolen** [comment]
I get the same error when trying to cross compile with mingw. It looks for `.dylib` despite `linker_platform` is set to `WINDOWS`.

**Comment by styurin** [comment]
@ilya-klyuchnikov can you take a look?

**Comment by ilya-klyuchnikov** [comment]
`prebuilt_cxx_library` is not supported on windows, but `prebuilt_cxx_library_group` is supported. Could you switch to `prebuilt_cxx_library_group`?

**Comment by samuela** [comment]
@ilya-klyuchnikov I'm not on Windows.

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has not been updated for more than 3 years. Thanks
