### ISSUE TITLE
BUG: Buck failed on NDK 15.1.4119039 and windows

### ISSUE THREAD

**Issue by lyrachord** [facebook/buck#1447]
git buck,
project fbsamples/bucksamples, build with with NDK 15.1.4119039
ERROR java.lang.AssertionError: D:\android\SDK\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-gcc doesn't exist.

solution
checked out the source:  
1, executableFinder not used. so ignore. Host same.
2, there is no windows exe suffix.
3, there are tree paths to find the order not took care, seems chaos

solution: 
result.toFile().exists() || new File(result.toFile().toString()+".exe").exists()

aha, path operations fly out of my mind, just File class :)

exception details:
java.lang.AssertionError: D:\android\SDK\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-gcc doesn't exist.
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
        at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.processPathPattern(NdkCxxPlatforms.java:1162)
        at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.getToolPath(NdkCxxPlatforms.java:1259)
        at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:718)
        at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:745)
        at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:599)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:278)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:243)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:220)
        at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:301)
        at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:237)
        at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:56)
        at com.facebook.buck.rules.Cell.lambda$0(Cell.java:90)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
        at com.facebook.buck.rules.Cell.getKnownBuildRuleTypes(Cell.java:119)
        at com.facebook.buck.rules.Cell.getAllDescriptions(Cell.java:219)
        at com.facebook.buck.rules.Cell.createBuildFileParser(Cell.java:283)
        at com.facebook.buck.parser.PerBuildState.createBuildFileParser(PerBuildState.java:181)
        at com.facebook.buck.parser.PerBuildState.lambda$0(PerBuildState.java:118)
        at com.facebook.buck.parser.ProjectBuildFileParserPool.lambda$1(ProjectBuildFileParserPool.java:102)
        at com.facebook.buck.util.concurrent.ResourcePool.createIfAllowed(ResourcePool.java:239)
        at com.facebook.buck.util.concurrent.ResourcePool.obtainResource(ResourcePool.java:200)
        at com.facebook.buck.util.concurrent.ResourcePool.requestResource(ResourcePool.java:176)
        at com.facebook.buck.util.concurrent.ResourcePool.access$0(ResourcePool.java:175)
        at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:129)
        at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:1)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:104)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by styurin** [comment]
I don't think we support Android on Windows right now
