### ISSUE TITLE
Kotlin only robolectric_test targets fail to compile

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1487]
The following error appears when trying to compile a `robolectric_test` target that contains only kotlin code:
```
2017-08-28 17:07:31.143][error][command:null][tid:217][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building rule [//features/check-balance:test_debug#testsjar] failed. Caused by [NoSuchFileException]:
/Users/cwoodward/Development/project/buck-out/gen/features/check-balance/lib__test_debug#testsjar__output/used-classes.json
    at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:332)
    at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:548)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:227)
    at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:67)
    at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:81)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:984)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:371)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1729)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
```

My guess is because there is no java, it is missing the `used-classes.json` file. Test targets that contain mixed java + kotlin do not have this issue.

**Comment by 0legg** [comment]
I faced the same issue recently, as a workaround I provided dummy empty java class, so source set is effectively mixed. It can lead to unnecessary compilation expenses though.

**Comment by ttsugriy** [comment]
cc @runningcode, who added support for mixed Kotlin/Java sources in https://github.com/facebook/buck/pull/1358 in case he has some ideas.

**Comment by jkeljo** [comment]
I think @cwoodwar6's guess is right on. `RobolectricTestDescription` is setting `setTrackClassUsage` based on what the `JavacOptions` say, without considering that pure Kotlin doesn't actually support it yet. https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/RobolectricTestDescription.java#L184

**Comment by jkeljo** [comment]
Mixed Kotlin+Java doesn't really support it either, so really if there's any non-Java code in there at all it should probably be turned off to prevent weirdly incorrect cache behaviors.

**Comment by jkeljo** [comment]
I'm working in this area right now, might as well fix this while I'm at it.

**Comment by kageiit** [comment]
@jkeljo scala/groovy rules might need the same treatment

**Comment by jkeljo** [comment]
@kageiit I expect so.
