### ISSUE TITLE
Error running Buck on Appveyor

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1488]
I am trying to build Buck on Appveyor in order to test a project that builds with Buck. 

I can build Buck using `ant`, but when I run `buck --version` I get this error: 

```
Command executed with exception: java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:148)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.PointerType.<init>(PointerType.java:25)
	at com.sun.jna.ptr.ByReference.<init>(ByReference.java:30)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:22)
	at com.facebook.buck.util.network.hostname.HostnameFetching.getHostnameWin32(HostnameFetching.java:53)
	at com.facebook.buck.util.network.hostname.HostnameFetching.getHostname(HostnameFetching.java:34)
	at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getHostname(DefaultExecutionEnvironment.java:51)
	at com.facebook.buck.util.environment.AbstractBuildEnvironmentDescription.of(AbstractBuildEnvironmentDescription.java:63)
	at com.facebook.buck.cli.Main.getBuildEnvironmentDescription(Main.java:1745)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1106)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:698)
	at com.facebook.buck.cli.Main.main(Main.java:1824)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
```

Any ideas?

**Comment by njlr** [comment]
Some environment information: 

```
Python 2.7.13
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
Apache Ant(TM) version 1.10.1 compiled on February 2 2017
```

**Comment by njlr** [comment]
I was able to fix this by in Appveyor:

```
environment:
  BUCK_EXTRA_JAVA_ARGS: "-Djna.nosys=true"
```
