### ISSUE TITLE
Failed to calculate ABI for log4j-api-2.9.0.jar

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#1496]
Using latest (i.e. current HEAD), after upgrading a third-party library (log4j) I am now getting this error...
```
Failed to calculate ABI for ./ThirdParty/deps/maven/log4j-api-2.9.0.jar.
java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at com.facebook.buck.jvm.java.abi.DirectoryReader.visitClass(DirectoryReader.java:60)
	at com.facebook.buck.jvm.java.abi.JarReader.visitClass(JarReader.java:53)
	at com.facebook.buck.jvm.java.abi.StubJarClassEntry.of(StubJarClassEntry.java:55)
	at com.facebook.buck.jvm.java.abi.StubJarEntry.of(StubJarEntry.java:30)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:89)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:69)
	at com.facebook.buck.jvm.java.CalculateAbiFromClassesStep.execute(CalculateAbiFromClassesStep.java:47)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1682)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1638)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

BUILD FAILED: //ThirdParty/deps:log4j-api#class-abi failed with exit code 1:
calculate_abi_from_classes
```

**Comment by ttsugriy** [comment]
@jkeljo, could you please take a look.

**Comment by brettwooldridge** [comment]
@ttsugriy @jkeljo Found it.  Java 9 issue.  Pull request coming...
