### ISSUE TITLE
Aapt2Link does not handle `@Deprecated` annotation in R.java

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1559]
Consider a resource

```
<!-- @deprecated Use {@link R.dimen#bar instead-->
<dimen name="foo">0dp</dimen>
```

This produces the following `R.java` content

```
/**
* @deprecated Use {@link R.dimen#bar instead.
*/
@Deprecated
public static final int foo=0x7f0700e3;
```

Which causes Aapt2Link to fail with

```
Buck encountered an internal error
java.lang.IllegalArgumentException: Got unexpected line: @Deprecated
	at com.facebook.buck.android.Aapt2Link$MakeRDotTxtStep.convertLines(Aapt2Link.java:357)
	at com.facebook.buck.android.Aapt2Link$MakeRDotTxtStep.execute(Aapt2Link.java:285)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1694)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1647)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

cc @dreiss

**Comment by dreiss** [comment]
I'll get to this at some point.  Now that aapt2 supports generating R.txt, we can probably restructure Buck to use that instead of trying to parse R.java.  The quick fix would be to just `MakeRDotTxtStep` to tolerate this.

**Comment by kageiit** [comment]
aapt2 in build tools 26.0.2 seems to work well out of the box now

**Comment by kageiit** [comment]
552c0b0b98ff9bf2d7c8753dc91ec3ec8eb48910 fixes this and made it possible to use stock aapt2 from the sdk build tools folder seamlessly.
