### ISSUE TITLE
NPE in buck after build finished

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1569]
Seeing this exception on latest master

```
Not using buckd because NO_BUCKD is set.
PARSING BUCK FILES... 0.3s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.3s
DOWNLOADED 867.65 KBYTES/SEC AVG, 35762 ARTIFACTS, 558.78 MBYTES
BUILDING: FINISHED IN 41m 26.0s (100%) ... 98.0% CACHE MISS
BUILD SUCCEEDED

[2017-10-07 13:51:36.557][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.facebook.buck.jvm.java.DefaultJavaLibraryRules.getAbiGenerationMode(DefaultJavaLibraryRules.java:214)
	at com.facebook.buck.jvm.java.ImmutableDefaultJavaLibraryRules.getAbiGenerationMode(ImmutableDefaultJavaLibraryRules.java:1479)
	at com.facebook.buck.jvm.java.DefaultJavaLibraryRules.willProduceSourceAbi(DefaultJavaLibraryRules.java:228)
	at com.facebook.buck.jvm.java.DefaultJavaLibraryRules.getSourceAbiRule(DefaultJavaLibraryRules.java:299)
	at com.facebook.buck.jvm.java.DefaultJavaLibraryRules.lambda$1(DefaultJavaLibraryRules.java:258)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.computeIfAbsent(SingleThreadedBuildRuleResolver.java:84)
	at com.facebook.buck.jvm.java.DefaultJavaLibraryRules.getLibraryRule(DefaultJavaLibraryRules.java:251)
	at com.facebook.buck.jvm.java.DefaultJavaLibraryRules.buildLibrary(DefaultJavaLibraryRules.java:150)
	at com.facebook.buck.jvm.groovy.GroovyLibraryDescription.createBuildRule(GroovyLibraryDescription.java:72)
	at com.facebook.buck.jvm.groovy.GroovyLibraryDescription.createBuildRule(GroovyLibraryDescription.java:1)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:88)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.lambda$0(SingleThreadedBuildRuleResolver.java:111)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.computeIfAbsent(SingleThreadedBuildRuleResolver.java:84)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.requireRule(SingleThreadedBuildRuleResolver.java:107)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:315)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraphSerially(ActionGraphCache.java:317)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:250)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:151)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:74)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:920)
	at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:453)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:521)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:412)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:379)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:80)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:79)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1065)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:386)
	at com.facebook.buck.cli.Main.main(Main.java:1626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)
```

This shows up after the build finishes and then proceeds to throw a non zero exit code

**Comment by kageiit** [comment]
cc @jkeljo

**Comment by kageiit** [comment]
@jkeljo have you had a chance to look at this?

**Comment by styurin** [comment]
Here's the reason: https://github.com/facebook/buck/blob/07baa0198425c75af5b76ef841704dad9ed517c3/src/com/facebook/buck/jvm/groovy/DefaultGroovyLibraryBuilder.java#L43

You can try to fix it yourself with adding some tests :)

**Comment by kageiit** [comment]
We have integration tests already for groovy rules. Fix is up in https://github.com/facebook/buck/pull/1571

Not sure what the test was missing exactly
