### ISSUE TITLE
IllegalStateException during action graph creation

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1572]
Seeing this on latest buck master

```
java.lang.IllegalStateException: Multiple rules created for target '//foo:test_main':
new rule '//foo:test_main' does not match existing rule '//foo:test_main'.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.computeIfAbsent(SingleThreadedBuildRuleResolver.java:92)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.requireRule(SingleThreadedBuildRuleResolver.java:107)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:315)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraphSerially(ActionGraphCache.java:317)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:250)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:151)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:74)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:920)
	at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:453)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:521)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:412)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:379)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:80)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:79)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1065)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:386)
	at com.facebook.buck.cli.Main.main(Main.java:1626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)
```

cc @yiding 

Action graph parallelization is turned off

**Comment by yiding** [comment]
Repro?

**Comment by kageiit** [comment]
Ill try to repro on the okbuck codebase. I have a feeling it could a flaky issue though. Ill update soon. Does the stack trace help in any way in the meantime?

**Comment by kageiit** [comment]
Got a repro

Clone
https://github.com/uber/okbuck

Run
```
./gradlew :okbuck -Dokbuck.wrapper=true; buck build //libraries/groovylibrary:test_main
```

See the error
```
[2017-10-10 11:37:23.306][error][command:null][tid:16][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: Multiple rules created for target '//libraries/groovylibrary:test_main':
new rule '//libraries/groovylibrary:test_main' does not match existing rule '//libraries/groovylibrary:test_main'.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.computeIfAbsent(SingleThreadedBuildRuleResolver.java:92)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.requireRule(SingleThreadedBuildRuleResolver.java:107)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:291)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraphSerially(ActionGraphCache.java:293)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:226)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:129)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:66)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:920)
	at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:453)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:521)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:412)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:379)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:79)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1065)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:386)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1825)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
```
