### ISSUE TITLE
Buck crash - Uncaught exception

### ISSUE THREAD

**Issue by techyvish** [facebook/buck#1594]
Trying to run app in iOS simulator but Buck crashes with uncaught exception.
Pleases see below for exception.
```
buck version v2017.10.01.01
```

```
buck install --run :App
Building: finished in 0.0 sec (100%) 1/1 jobs, 0 updated, 0.0% cache miss
  Total time: 0.0 sec
Installing... 0.1 sec
[2017-10-19 17:17:23.093][error][command:null][tid:1352][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.lang.ClassNotFoundException: com/sun/security/auth/module/UnixSystem
	at com.facebook.buck.util.UnixUserIdFetcher.getUserId(UnixUserIdFetcher.java:31)
	at com.facebook.buck.apple.simulator.AppleCoreSimulatorServiceController.getCoreSimulatorServicePath(AppleCoreSimulatorServiceController.java:81)
	at com.facebook.buck.cli.InstallCommand.installAppleBundleForSimulator(InstallCommand.java:690)
	at com.facebook.buck.cli.InstallCommand.installAppleBundle(InstallCommand.java:480)
	at com.facebook.buck.cli.InstallCommand.install(InstallCommand.java:294)
	at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:236)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:231)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:71)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:81)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1047)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:384)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1806)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
Caused by: java.lang.ClassNotFoundException: com/sun/security/auth/module/UnixSystem
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.facebook.buck.util.UnixUserIdFetcher.getUserId(UnixUserIdFetcher.java:26)
	... 16 more
```

**Comment by ttsugriy** [comment]
what java version are you using? The error looks like it's caused by usage of some incompatible JRE version

**Comment by jkeljo** [comment]
With the module notation in those callstacks it looks like Java 9. I imagine `com.sun.security` got locked down with Jigsaw.

**Comment by techyvish** [comment]
@ttsugriy @jkeljo I'm using `java 9.0.1`

**Comment by ttsugriy** [comment]
@techyvish currently Buck does not officially support Java 9 - we've fixed some obvious incompatibilities but there are still more to fix. Hopefully this will be addressed as part of https://github.com/facebook/buck/issues/1548 resolution, since at the moment it's not possible to compile buck with Java 9 at all.

**Comment by techyvish** [comment]
Thanks @ttsugriy, will use older version for now.

**Comment by ttsugriy** [comment]
sorry for the inconveniences @techyvish and thanks for using Buck!
