### ISSUE TITLE
buck install command is broken after recent changes around rapid install

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1638]
Seeing this stack trace when trying to install exopackage apks

```
java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.facebook.buck.android.AdbHelper.adbCall(AdbHelper.java:186)
	at com.facebook.buck.android.AdbHelper.installApkExopackage(AdbHelper.java:606)
	at com.facebook.buck.android.AdbHelper.installApk(AdbHelper.java:277)
	at com.facebook.buck.cli.InstallCommand.installApk(InstallCommand.java:434)
	at com.facebook.buck.cli.InstallCommand.install(InstallCommand.java:287)
	at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:238)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:82)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1048)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:393)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1882)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.facebook.buck.android.exopackage.RealAndroidDevice.checkReceiverOutput(RealAndroidDevice.java:245)
	at com.facebook.buck.android.exopackage.RealAndroidDevice.doMultiInstall(RealAndroidDevice.java:698)
	at com.facebook.buck.android.exopackage.RealAndroidDevice.installFiles(RealAndroidDevice.java:656)
	at com.facebook.buck.android.exopackage.ExopackageInstaller.installFiles(ExopackageInstaller.java:321)
	at com.facebook.buck.android.exopackage.ExopackageInstaller.installMissingFiles(ExopackageInstaller.java:262)
	at com.facebook.buck.android.exopackage.ExopackageInstaller.installMissingExopackageFiles(ExopackageInstaller.java:171)
	at com.facebook.buck.android.exopackage.ExopackageInstaller.doInstall(ExopackageInstaller.java:92)
	at com.facebook.buck.android.AdbHelper.lambda$4(AdbHelper.java:616)
	at com.facebook.buck.android.AdbHelper.lambda$0(AdbHelper.java:178)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.NullPointerException
		at com.facebook.buck.android.exopackage.RealAndroidDevice$BuckInitiatedInstallReceiver.addOutput(RealAndroidDevice.java:941)
		at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
		at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
		at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
		at com.android.ddmlib.Device.executeShellCommand(Device.java:599)
		at com.facebook.buck.android.exopackage.RealAndroidDevice.doMultiInstall(RealAndroidDevice.java:681)
		... 13 more
BUILD FAILED: Install failed.
```

**Comment by kageiit** [comment]
cc @styurin @dreiss

**Comment by kageiit** [comment]
As a quick update, the issue seems to be caused by old apks of `com.facebook.buck.android.agent` that do not seem to be cleaned up after buck upgrades.

Once I did `adb uninstall com.facebook.buck.android.agent` and retried the exo package install command, everything seemed to work correctly again

**Comment by kageiit** [comment]
@cjhopman may have fixed this in https://github.com/facebook/buck/commit/e0dbb6d8b27d6f540eeb376c65b1015d4606afc3

**Comment by dreiss** [comment]
Yeah, this should be fixed.  We have no idea why this bug wasn't being triggered before now.
