### ISSUE TITLE
Hard to get buckd out of a wedged state

### ISSUE THREAD

**Issue by dborowitz** [facebook/buck#166]
This morning after not using buck on my Linux machine for a few days, I get:
```
$ buck build :chrome
Using buckd.
connect: Connection refused
```

It might be nice if the tool helped me a bit here, but this seems to have completely wedged it:
```
$ buck --help
Using buckd.
connect: Connection refused
```

Indeed, there was no buckd process running. I did `rm -rf .buckd` and tried again:
```
$ buck build :chrome                                                                                                                                                                                                     
Using watchman.
Using buckd.
[-] PARSING BUILD FILES...FINISHED 2.2s
[+] BUILDING...36.7s
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //:chrome...  4.3s (running genrule[4.2s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
Log:
Client disconnected.
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:285)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.facebook.buck.cli.BuildCommand.executeBuildAndPrintAnyFailuresToConsole(BuildCommand.java:162)
        at com.facebook.buck.cli.BuildCommand.runCommandWithOptionsInternal(BuildCommand.java:132)
        at com.facebook.buck.cli.BuildCommand.runCommandWithOptionsInternal(BuildCommand.java:50)
        at com.facebook.buck.cli.AbstractCommandRunner.runCommandWithOptions(AbstractCommandRunner.java:133)
        at com.facebook.buck.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:106)
        at com.facebook.buck.cli.Command.execute(Command.java:103)
        at com.facebook.buck.cli.Main.executeCommand(Main.java:596)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:434)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:861)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:880)
        at com.facebook.buck.cli.Main.nailMain(Main.java:902)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
BUILD FAILED: Unexpected internal error (if you are using buckd, you should restart it).
```

Ok, I need to restart buckd. How? `buck shutdown` would be nice. Fortunately I was able to find the process and kill it and it seems to have worked. (Why can't buck do this for me?)

```
$ uname -a && buck --version
Linux <hostname> 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Using buckd.
buck version 0fe4569e871fd6588f7cbfb4b1d4a14baa791a9f
```

**Comment by sdwilsh** [comment]
`buck kill` is the way to do this in the future.
