### ISSUE TITLE
aapt2 causes runtime crash on Android < 5 Resources$NotFoundException

### ISSUE THREAD

**Issue by artem-zinnatullin** [facebook/buck#1667]
Switching `aapt_mode` to `aapt2` causes following crash on Android < 5:

```java
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example, PID: 2833
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f080058
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
 at android.app.ActivityThread.access$800(ActivityThread.java:135)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:136)
 at android.app.ActivityThread.main(ActivityThread.java:5017)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
 at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f080058
 at android.content.res.Resources.loadDrawable(Resources.java:2101)
 at android.content.res.Resources.getDrawable(Resources.java:700)
 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
 at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
 at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
 at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
 at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151)
 at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
 at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
 at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
 at com.example.MainActivity.onCreate(MainActivity.java:140)
 at android.app.Activity.performCreate(Activity.java:5231)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
 at android.app.ActivityThread.access$800(ActivityThread.java:135) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:136) 
 at android.app.ActivityThread.main(ActivityThread.java:5017) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:515) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
 at dalvik.system.NativeStart.main(Native Method) 
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
 at android.content.res.Resources.loadDrawable(Resources.java:2097)
 at android.content.res.Resources.getDrawable(Resources.java:700) 
 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202) 
 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190) 
 at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711) 
 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195) 
 at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
 at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131) 
 at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151) 
 at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31) 
 at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55) 
 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205) 
 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
 at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519) 
 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
 at com.example.MainActivity.onCreate(MainActivity.java:140) 
 at android.app.Activity.performCreate(Activity.java:5231) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
 at android.app.ActivityThread.access$800(ActivityThread.java:135) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:136) 
 at android.app.ActivityThread.main(ActivityThread.java:5017) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:515) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
 at dalvik.system.NativeStart.main(Native Method) 
```

Env:

- Build tools 27.0.2
- Support Libraries 25.2.0 (tried 27.0.2 as well)

Looks like Android Gradle Plugin had this problem as well, but it was fixed https://issuetracker.google.com/issues/63623801

**Comment by ttsugriy** [comment]
cc @dreiss

**Comment by dreiss** [comment]
Let's wait to hear back on that Google task to see where the fix was.

**Comment by v-jizhang** [comment]
No updates for almost 3 years, closing it now.
