### ISSUE TITLE
[Runtime crash] LC_SEGMENT or LC_SEGMENT_64 command for string table not found

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#1717]
On Mac, Buck crashed when building [this go package](https://github.com/linzhp/buck_go_examples/tree/master/cpuUsage), which refers to `github.com/shirou/gopsutil/cpu`. The error is:

```
Error scrubbing non-deterministic metadata from /Users/zplin/gocode/src/buck_go_examples/buck-out/gen/vendor/github.com/shirou/gopsutil/cpu/cgo_lib#cgo-second-step
com.facebook.buck.io.file.FileScrubber.ScrubException: LC_SEGMENT or LC_SEGMENT_64 command for string table not found
com.facebook.buck.io.file.FileScrubber$ScrubException: LC_SEGMENT or LC_SEGMENT_64 command for string table not found
	at com.facebook.buck.cxx.toolchain.objectfile.OsoSymbolsContentsScrubber.scrubFile(OsoSymbolsContentsScrubber.java:41)
	at com.facebook.buck.step.fs.FileScrubberStep.execute(FileScrubberStep.java:59)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1809)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1762)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This issue may be related to #1714, although the error is different.

**Comment by ttsugriy** [comment]
I also noticed this when trying to run integration tests on MacOS - https://travis-ci.org/facebook/buck/jobs/340362617#L4642 Internally we don't seem to be running integration tests for Go on Mac hence this issue went unnoticed. I'm not sure who would be the best person to update the scrubber to understand Go binaries.

**Comment by monty-uber** [comment]
This pull request should fix this by making the FileScrubberStep a non-critical failure: https://github.com/facebook/buck/pull/1787.

**Comment by mkaczanowski** [comment]
@linzhp you update your example and try again? (cgo_deps = [] now is cgo = ":target")

In the https://github.com/facebook/buck/commit/2ad4e1f67ff66b7f1f91d39a0e9c207eb74baf12 I fixed large chunk of the second step.

To what I understand from:
http://osxbook.com/book/bonus/chapter7/binaryprotection/

The LC_SEGMENT should be included in the macosx binaries.

Let's give it another go, I would rather check out why this is missing rather than making it non-critical.

Does the OSS go build add the LC_SEGMENT?

**Comment by linzhp** [comment]
Updated the example, and rerun the buck build using latest Buck. It succeeded. Thanks for the fix. Closing this issue.

**Comment by mkaczanowski** [comment]
great. Thanks for checking!
