### ISSUE TITLE
Exopackage without split_dex = true leads to confusing error message.

### ISSUE THREAD

**Issue by runningcode** [facebook/buck#1726]
If I have an Android binary rule with 
```
    exopackage_modes = ['secondary_dex'],
```
but I forget to add
```
    use_split_dex = True,
```

I get a confusing stack trace like so:
```
[2018-01-25 11:54:09.359][error][command:null][tid:189][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:485)
	at com.facebook.buck.android.PreDexMerge.getMetadataTxtPath(PreDexMerge.java:438)
	at com.facebook.buck.android.PreDexMerge.getMetadataTxtSourcePath(PreDexMerge.java:458)
	at com.facebook.buck.android.AndroidBinaryFilesInfo.getExopackageInfo(AndroidBinaryFilesInfo.java:111)
	at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:400)
	at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:1)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:88)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.lambda$0(SingleThreadedBuildRuleResolver.java:111)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.computeIfAbsent(SingleThreadedBuildRuleResolver.java:84)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.requireRule(SingleThreadedBuildRuleResolver.java:107)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:363)
	at com.facebook.buck.rules.ActionGraphCache$2.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraphSerially(ActionGraphCache.java:366)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:281)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:178)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:91)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:990)
	at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:444)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:517)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:401)
	at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:230)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:82)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1048)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:393)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1882)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
```

Can we make this error message better? For example 
> IllegalStateException Exopackage requires `use_split_dex = True`

**Comment by runningcode** [comment]
Just need a yes/no and I'll create a PR to do this :)
