### ISSUE TITLE
Getting `NoClassDefFoundError` even though the class is present in main dex

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#1727]
Building with `d8` with predex disabled.
Android Version: 4.4.2
Device Model: Hol-U19

Works on android version 5.x or higher

```
android_binary(
    name = 'bin_release',
    dex_tool = 'd8',
    use_split_dex = True,
    linear_alloc_hard_limit = 16777216,
    primary_dex_patterns = [
        '^android/support/multidex/MultiDex',
        '^android/support/multidex/MultiDexExtractor',
        '^android/support/multidex/ZipUtil^',
        '^io/github/inflationx/calligraphy3/CalligraphyInterceptor^',
        ...
    ],
    cpu_filters = [
        'ARMV7',
    ],
    android_sdk_proguard_config = 'none',
    proguard_config = '//.okbuck/gen/apps/tictactoe/tictactoe/release:proguard.pro',
    package_type = 'release',
    includes_vector_drawables = True,
    disable_pre_dex = True,
    deps = [
        '//.okbuck/gen/apps/tictactoe/tictactoe/release:proguard.map',
        ':res_release',
        ':src_release',
    ],
    visibility = [
        'PUBLIC',
    ],
)
```

stacktrace
```
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: com.example.tictactoe, PID: 17041
                         E  java.lang.NoClassDefFoundError: io.github.inflationx.calligraphy3.CalligraphyInterceptor
                         E      at com.example.tictactoe.core.app.TicTacToeAppDelegate.initUiFont(TicTacToeAppDelegate.java:1004)
                         E      at com.example.tictactoe.core.app.TicTacToeAppDelegate.create(TicTacToeAppDelegate.java:478)
                         E      at com.example.tictactoe.core.app.TicTacToeAppDelegate.onCreate(TicTacToeAppDelegate.java:428)
                         E      at com.example.tictactoe.core.app.TicTacToeApplication.onCreate(TicTacToeApplication.java:56)
                         E      at com.example.tictactoe.core.app.DebugTicTacToeApplication.onCreate(DebugTicTacToeApplication.java:21)
                         E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                         E      at android.app.ActivityThread.access$1600(ActivityThread.java:151)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                         E      at android.os.Handler.dispatchMessage(Handler.java:110)
                         E      at android.os.Looper.loop(Looper.java:193)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5304)
                         E      at java.lang.reflect.Method.invokeNative(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:515)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                         E      at dalvik.system.NativeStart.main(Native Method)
               dalvikvm  D  threadid=9: interp stack at 0x602bb000
```

**Comment by raviagarwal7** [comment]
note: the class actually ends up in the main dex, but the error still happens
in `primary.jar.txt`
`172 13 1 io/github/inflationx/calligraphy3/CalligraphyInterceptor.class`

in `classes.dex`
<img width="1240" alt="screen shot 2018-01-25 at 4 42 17 pm" src="https://user-images.githubusercontent.com/1913956/35419787-e07ff066-01ee-11e8-97f1-abc9f14324c7.png">
