### ISSUE TITLE
Rendering exception when running tests on CircleCI

### ISSUE THREAD

**Issue by Nickersoft** [facebook/buck#1728]
Hey guys, recently I noticed some odd behavior running my Buck tests on CircleCI. While all my tests execute perfectly locally, running them on CircleCI throws the following exception:

```
[2018-01-26 02:47:16.039][error][command:null][tid:50][com.facebook.buck.event.listener.SuperConsoleEventBusListener] Rendering exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -14
	at java.lang.String.substring(String.java:1967)
	at com.facebook.buck.event.listener.CommonThreadStateRenderer.renderLine(CommonThreadStateRenderer.java:115)
	at com.facebook.buck.event.listener.BuildThreadStateRenderer.renderStatusLine(BuildThreadStateRenderer.java:111)
	at com.facebook.buck.event.listener.SuperConsoleEventBusListener.renderLines(SuperConsoleEventBusListener.java:709)
	at com.facebook.buck.event.listener.SuperConsoleEventBusListener.createRenderLinesAtTime(SuperConsoleEventBusListener.java:540)
	at com.facebook.buck.event.listener.SuperConsoleEventBusListener.render(SuperConsoleEventBusListener.java:311)
	at com.facebook.buck.event.listener.SuperConsoleEventBusListener.lambda$startRenderScheduler$0(SuperConsoleEventBusListener.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It would seem Buck is having trouble [rendering to the console](https://github.com/facebook/buck/blob/v2017.11.16.01/src/com/facebook/buck/event/listener/CommonThreadStateRenderer.java#L115). Unfortunately, this exception is causing my tests to fail on CircleCI, and it only seems to be thrown for one specific test. The test in question is a simple ScalaTest:

```scala
this.romanizer.run("你好", true) should be("ni3hao3")
```

and yet the reason for failure seems to be an extra space (?):

```
FAILURE com.linguistic.core.lang.tests.romanizer.ChinesePRCRomanizerTests romanize() should correctly romanize Chinese words: "ni3[ ]hao3" was not equal to "ni3[]hao3"
```

I'd try to fix this test, but like I said, it runs fine locally, which makes me believe the problem is some Buck-CircleCI incompatibility. Can anyone provide any insight as to what might be causing this?

**Comment by ttsugriy** [comment]
@Nickersoft, the crash happens in a super console, which is only used for interactive sessions, but on CIs a non-interactive (simple) console is used, which which is why you cannot reproduce the issue locally. I think the only way you can reproduce the issue on a CI is by coming up with a repro in SuperConsoleEventBusListenerTest
