### ISSUE TITLE
Xcode project generation issue after nailgun update

### ISSUE THREAD

**Issue by robbertvanginkel** [facebook/buck#1738]
I just upgraded a buck and am experiencing an issue where buck crashes when prompting the user to close Xcode.

I am branched off a1053eb54d68fc516114792c63f3894619692c0d, have Xcode currently open so buck will prompt me to close it. W when doing `buck project target -v 10` I get
```

[2018-02-01 17:22:28.851][debug][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.facebook.buck.apple.project_generator.XCodeProjectCommandHelper] Displaying prompt Xcode is currently running. Buck will modify files Xcode currently has open, which can cause it to become unstable.

Kill Xcode and continue?..

Xcode is currently running. Buck will modify files Xcode currently has open, which can cause it to become unstable.

Kill Xcode and continue? [Y/n] y
[2018-02-01 17:22:31.409][debug][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.martiansoftware.nailgun.NGInputStream] Shutting down read ExecutorService

[2018-02-01 17:22:31.913][debug][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.martiansoftware.nailgun.NGInputStream] Shutting down orchestrator ExecutorService

[2018-02-01 17:22:31.914][warn ][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.martiansoftware.nailgun.NGInputStream] Interruption is signaled in close(), terminating a thread forcefully

[2018-02-01 17:22:31.914][debug][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.facebook.buck.apple.project_generator.XCodeProjectCommandHelper] Result of prompt: [Optional[y]]

[2018-02-01 17:22:31.915][debug][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.facebook.buck.util.PkillProcessManager] Killing process Xcode...

[2018-02-01 17:22:31.916][info ][command:7fe8361a-6502-4aea-818d-b861090a321b][tid:69][com.facebook.buck.util.BgProcessKiller] BuckIsDyingException: process creation blocked due to pending nailgun exit at:com.facebook.buck.util.BuckIsDyingException: process creation blocked due to pending nailgun exit
    at com.facebook.buck.util.BgProcessKiller.checkArmedStatus(BgProcessKiller.java:96)
    at com.facebook.buck.util.BgProcessKiller.startProcess(BgProcessKiller.java:110)
    at com.facebook.buck.util.DefaultProcessExecutor.launchProcess(DefaultProcessExecutor.java:172)
    at com.facebook.buck.util.DefaultProcessExecutor.launchAndExecute(DefaultProcessExecutor.java:132)
    at com.facebook.buck.util.DefaultProcessExecutor.launchAndExecute(DefaultProcessExecutor.java:103)
    at com.facebook.buck.util.DefaultProcessExecutor.launchAndExecute(DefaultProcessExecutor.java:97)
    at com.facebook.buck.util.PkillProcessManager.runProcess(PkillProcessManager.java:85)
    at com.facebook.buck.util.PkillProcessManager.killProcess(PkillProcessManager.java:64)
    at com.facebook.buck.apple.project_generator.XCodeProjectCommandHelper.checkForAndKillXcodeIfRunning(XCodeProjectCommandHelper.java:587)
    at com.facebook.buck.apple.project_generator.XCodeProjectCommandHelper.parseTargetsAndRunXCodeGenerator(XCodeProjectCommandHelper.java:207)
    at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:366)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:233)
    at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1076)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:400)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1923)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:339)
```

I verified that previously (when I was branched off 0a244cbc2aae60269751f32448f3328266106db5) this issue does not occur.

Nailgun seems to have been updated in 0a5a2354c66249441beca5565a79027aba040dbf, seems likely it is related?

**Comment by sbalabanov** [comment]
Apparently if Nailgun's input stream is explicitly closed (that's what happening in project generation after it prompts) it also terminates client connection followed by termination of Buck itself.
I'll have it fixed in a couple days.

**Comment by robbertvanginkel** [comment]
Thank you for looking into this!

**Comment by robbertvanginkel** [comment]
Any update?

**Comment by robbertvanginkel** [comment]
This was fixed.
