### ISSUE TITLE
iOS "Getting Started" instructions fail to install on simulator

### ISSUE THREAD

**Issue by dlo** [facebook/buck#1792]
https://buckbuild.com/setup/getting_started.html

> In order to build the app, you use the buck build command, specifying your app as the target. The target may be defined in the [alias] section in the .buckconfig file or it would be the name of your iOS project prepended by //[the directory where your project is located]: (e.g., //ios:BuckDempApp).

This part works great.

```
$ buck build demo_app_ios
Building: finished in 1.7 sec (100%) 19/19 jobs, 19 updated, 63.2% cache miss
  Total time: 2.0 sec
```

But, the app fails to run in the simulator, and I get a Java traceback.

> Now that you know your app has built successfully, you can install and run the app with buck install. This command both compiles and installs the application on the iOS simulator. Using the --run flag will launch the simulator as well.

```
$ buck install --run demo_app_ios
Building: finished in 0.0 sec (100%) 1/1 jobs, 0 updated, 0.0% cache miss
  Total time: 0.0 sec
Installing... 0.1 sec
[2018-03-03 12:02:28.628][error][command:null][tid:346][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.lang.ClassNotFoundException: com/sun/security/auth/module/UnixSystem
	at com.facebook.buck.util.UnixUserIdFetcher.getUserId(UnixUserIdFetcher.java:31)
	at com.facebook.buck.apple.simulator.AppleCoreSimulatorServiceController.getCoreSimulatorServicePath(AppleCoreSimulatorServiceController.java:81)
	at com.facebook.buck.cli.InstallCommand.installAppleBundleForSimulator(InstallCommand.java:694)
	at com.facebook.buck.cli.InstallCommand.installAppleBundle(InstallCommand.java:484)
	at com.facebook.buck.cli.InstallCommand.install(InstallCommand.java:296)
	at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:238)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:82)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1101)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:395)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1855)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
Caused by: java.lang.ClassNotFoundException: com/sun/security/auth/module/UnixSystem
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.facebook.buck.util.UnixUserIdFetcher.getUserId(UnixUserIdFetcher.java:26)
	... 16 more
```

I'm running Java 8:

```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/
```

**Comment by ttsugriy** [comment]
According to https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/module/UnixSystem.html this should exist in Java 8, but does not seem to exist in Java 9, so I bet that you're using Java 9. Please paste the output of `java -version`

**Comment by dlo** [comment]
You are correct, thanks for the heads up! Cheers.
