### ISSUE TITLE
run buck install and debug throws null pointer exception

### ISSUE THREAD

**Issue by kafji** [facebook/buck#1820]
Run buck install and debug on ideabuck throws a NullPointerException.

Is there a way to view a more verbose error message from ideabuck?

**Comment by styurin** [comment]
You probably can find it in the Intellij log file. On MacOS you can open it by clicking on "Help -> Show log in Finder"

**Comment by kafji** [comment]
@styurin thanks.


The error is actually because ideabuck is unable to locate adb.

Log:
```
2018-03-27 12:14:39,208 [ thread 12]  ERROR - ck.config.BuckSettingsProvider - java.lang.RuntimeException: Unable to locate adb based on environment variables, or it's not marked as being executable. You can specify the adb path from Preferences/Settings > Tools > Buck > Adb Executable Path 
java.lang.RuntimeException: Unable to locate adb based on environment variables, or it's not marked as being executable
	at com.facebook.buck.intellij.ideabuck.util.ExecutableFinder.getExecutable(ExecutableFinder.java:63)
	at com.facebook.buck.intellij.ideabuck.config.BuckExecutableDetector.getAdbExecutable(BuckExecutableDetector.java:50)
	at com.facebook.buck.intellij.ideabuck.config.BuckSettingsProvider.resolveAdbExecutable(BuckSettingsProvider.java:153)
	at com.facebook.buck.intellij.ideabuck.debugger.AndroidDebugger.init(AndroidDebugger.java:49)
	at com.facebook.buck.intellij.ideabuck.ui.BuckEventsConsumer$14.run(BuckEventsConsumer.java:640)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

But in Buck console it just shows: 
![screenshot from 2018-03-27 12-21-38](https://user-images.githubusercontent.com/1842143/37948260-86041fcc-31b9-11e8-9e1d-bd432800f2e9.png)

I've solved my issue but I think it would be better if ideabuck can show a more meaningful error directly in the buck console.
