### ISSUE TITLE
watchman doesn't like buck-out

### ISSUE THREAD

**Issue by spearce** [facebook/buck#183]
I'm turning off watchman for now. Watchman doesn't like my buck-out directory and now tells me it will refuse to work until I go read a webpage.

buck and watchman should figure out how to use buck-out together without me reading about a poison inotify add watch.

Log:
Watchman threw an exception while parsing file changes.
A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1408571228: inotify-add-watch(/home/sop/git/gerrit/buck-out/bin/gerrit-acceptance-tests/src/test/jad
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/troubleshooting.html#poison-inotify-add-watch

[2014-08-20 14:51:44.277][error][command:0030deb7-d702-48f4-eb31-5a7e1f73bb29][tid:57][com.facebook.buck.util.WatchmanWatcher] Error in Watchman output
com.facebook.buck.util.WatchmanWatcherException: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1408571228: inotify-add-watch(/home/sop/git/gerrit/buck-out/bin/gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/project/__java_test_GarbageCollectionIT_tmp__/gerrit_test_1205646360960983060/tmp) -> Permission denied
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/troubleshooting.html#poison-inotify-add-watch

        at com.facebook.buck.util.WatchmanWatcher.postEvents(WatchmanWatcher.java:290)
        at com.facebook.buck.cli.Main$Daemon.watchFileSystem(Main.java:265)
        at com.facebook.buck.cli.Main$Daemon.access$1000(Main.java:146)
        at com.facebook.buck.cli.Main.getParserFromDaemon(Main.java:668)
        at com.facebook.buck.cli.Main.executeCommand(Main.java:563)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:429)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:834)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:858)
        at com.facebook.buck.cli.Main.nailMain(Main.java:881)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)

**Comment by Coneko** [comment]
Closing, the commits @sdwilsh mentions should have fixed this.

Let us know if it happens again.

**Comment by sdwilsh** [comment]
To be clear, we don't need to verify that `.watchmanconfig` is correct, because Buck now tells `watchman` what it can safely ignore.  You don't need a `.watchmanconfig` file unless you have other tools (like `hg`) that also use `watchman`.
