### ISSUE TITLE
Unable to pass current directory to the genrule

### ISSUE THREAD

**Issue by VitalyArbuzov** [facebook/buck#1847]
I need to run a tool on the directory tree which corresponds to the logical project root.
I've tried to wrap script invocation into genrule and pass current directory to the list of srcs:
```
  native.genrule(
    name=name,
    srcs='.',
    out='.',
    cmd='...'
  )
```
However that resulted in exception that duplicates inner location for some reason:
```
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/vit/go/src/projectpath/list-projects/src/projectpath/list-projects
	at com.facebook.buck.util.cache.impl.DefaultFileHashCache.lambda$new$0(DefaultFileHashCache.java:70)
	at com.facebook.buck.util.cache.impl.FileSystemMapFileHashCache.lambda$new$0(FileSystemMapFileHashCache.java:42)
	at com.facebook.buck.util.FileSystemMap$Entry.load(FileSystemMap.java:109)
	at com.facebook.buck.util.FileSystemMap$Entry.access$400(FileSystemMap.java:68)
	at com.facebook.buck.util.FileSystemMap.get(FileSystemMap.java:295)
	at com.facebook.buck.util.FileSystemMap.get(FileSystemMap.java:272)
	at com.facebook.buck.util.cache.impl.FileSystemMapFileHashCache.get(FileSystemMapFileHashCache.java:76)
```

Got same error when trying to use export_file and pass it as a dependency to the genrule.
Also tried using glob(["**/*"]), but it fails because there are nested BUCK files:
```
BUILD FAILED: The target '//src/projectpath/list-projects:foo' tried to reference 'src/projectpath/list-projects/http/BUCK'.
This is not allowed because 'src/projectpath/list-projects/http/BUCK' can only be referenced from 'src/projectpath/list-projects/http/BUCK'
which is it's closest parent 'BUCK' file.
```

I envision that something similar to resources property in the go_test rule is needed.

**Comment by ttsugriy** [comment]
it's always a bad idea to include an entire source tree into any rule. At the very least you should have a glob with specific extensions, since otherwise, you'll end up including all sorts of temporary files that OS or editors create - this will be causing slow and non-hermetic builds. Use a glob with multiple patterns to match all files relevant for your tool instead.
