### ISSUE TITLE
Precompiled headers are not supported on Windows

### ISSUE THREAD

**Issue by shybovycha** [facebook/buck#1850]
I was trying to compile Newton Game Dynamics with my hand-crafted `BUCK` file and faced a strange exception from Buck:

```
java.lang.UnsupportedOperationException: prefix header not supported by class com.facebook.buck.cxx.toolchain.WindowsPreprocessor
        at com.facebook.buck.cxx.toolchain.WindowsPreprocessor.prefixHeaderArgs(WindowsPreprocessor.java:64)
        at com.facebook.buck.cxx.toolchain.Preprocessor.prefixOrPCHArgs(Preprocessor.java:46)
        at com.facebook.buck.cxx.AbstractPreprocessorFlags.getNonIncludePathFlags(AbstractPreprocessorFlags.java:128)
        at com.facebook.buck.cxx.PreprocessorFlags.getNonIncludePathFlags(PreprocessorFlags.java:1)
        at com.facebook.buck.cxx.AbstractPreprocessorFlags.toToolFlags(AbstractPreprocessorFlags.java:140)
        at com.facebook.buck.cxx.PreprocessorFlags.toToolFlags(PreprocessorFlags.java:1)
        at com.facebook.buck.cxx.PreprocessorDelegate.getFlagsWithSearchPaths(PreprocessorDelegate.java:185)
        at com.facebook.buck.cxx.CxxPreprocessAndCompile.lambda$3(CxxPreprocessAndCompile.java:204)
        at java.util.Optional.map(Optional.java:215)
        at com.facebook.buck.cxx.CxxPreprocessAndCompile.makeMainStep(CxxPreprocessAndCompile.java:204)
        at com.facebook.buck.cxx.CxxPreprocessAndCompile.getBuildSteps(CxxPreprocessAndCompile.java:283)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1308)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1288)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.runWithExecutor(CachingBuildRuleBuilder.java:1247)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1236)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$2.runWithDefaultExecutor(CachingBuildRuleBuilder.java:750)
        ... 9 more

    When building rule //vendor/newton-dynamics:dMath#compile-dStdAfxMath.cpp.obj818be5fd,default.
```

After random guessing and just commenting out the `precompiled_header` param of a `cxx_library` rule the thing worked:

```
cxx_precompiled_header(
    name = "dStdAfxMath",
    src = "packages/dMath/dStdAfxMath.h",
)

cxx_library(
    name = "dMath",
    # precompiled_header = ":dStdAfxMath", # <---- this one is causing the problem
    headers = glob([ "packages/dMath/*.h" ]),
    exported_headers = subdir_glob([ ("packages/dMath", "*.h") ]),
    header_namespace = "",
    srcs = glob([ "packages/dMath/*.cpp" ]),
    visibility = [ "PUBLIC" ],
)
```

But that makes me think: VisualStudio supports precompiled headers out-of-the-box, and each C++ Windows project you create contains `#include "stdafx.h"` as the first line.

But why can't Buck handle that???

Or, is there a way (except of yet undocumented flavors) to provide platform-dependant rules, e.g. to include precompiled header on *nix platforms, for now?

**Comment by ilya-klyuchnikov** [comment]
We consider precompiled headers as an anti-pattern (they are not hermetic - see https://github.com/bazelbuild/bazel/issues/1215). We do have precompiled headers only for historical reasons - and the implementation is rather non-trivial - we do not cache them (because of non-determinism).
