### ISSUE TITLE
Tests failing on GoToolchainSupplier in intellij 

### ISSUE THREAD

**Issue by robbertvanginkel** [facebook/buck#1862]
I recently took in a new set of changes in buck and tried to run some tests from intellij. Previously this was fine but whenever I try to run `com.facebook.buck.apple.project_generator.ProjectGeneratorTest` all tests immediately fail with the following stacktrace:
```
java.util.ServiceConfigurationError: com.facebook.buck.toolchain.ToolchainSupplier: Provider com.facebook.buck.go.GoToolchainSupplier not found

	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at com.facebook.buck.plugin.impl.BuckExtensionFinder.find(BuckExtensionFinder.java:53)
	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:530)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.loadToolchainDescriptorsFromPlugins(DefaultToolchainProvider.java:102)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.<init>(DefaultToolchainProvider.java:88)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProviderFactory.create(DefaultToolchainProviderFactory.java:52)
	at com.facebook.buck.rules.RootCellFactory.create(RootCellFactory.java:95)
	at com.facebook.buck.rules.LocalCellProviderFactory.lambda$create$1(LocalCellProviderFactory.java:158)
	at com.facebook.buck.rules.CellProvider.<init>(CellProvider.java:47)
	at com.facebook.buck.rules.LocalCellProviderFactory.create(LocalCellProviderFactory.java:65)
	at com.facebook.buck.rules.TestCellBuilder.build(TestCellBuilder.java:108)
	at com.facebook.buck.apple.project_generator.ProjectGeneratorTest.setUp(ProjectGeneratorTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Tests seem to run fine with `buck test`.

**Comment by styurin** [comment]
Try to rebuild the project in IntelliJ.

**Comment by robbertvanginkel** [comment]
I've tried rebuilding, invalidating IntelliJ caches, doing a fresh checkout and I still get this error every time.

**Comment by styurin** [comment]
Did you try Build -> Rebuild Project?

**Comment by robbertvanginkel** [comment]
Fixed it by recloning. I did rebuild and tried all other ways of clearing caches, but I must have missed one. Closing for now.
