### ISSUE TITLE
BUCK breaks with Kotlin 1.2.50

### ISSUE THREAD

**Issue by hzsweers** [facebook/buck#1919]
I get the following with a kotlin build on buck after trying to update to Kotlin 1.2.50

Changelog: https://github.com/JetBrains/kotlin/releases/tag/v1.2.50

```
Buck encountered an internal error
java.lang.RuntimeException: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.lambda$build$2(CachingBuildRuleBuilder.java:365)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:176)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:163)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:107)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1025)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:93)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1025)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithExecutor(CachingBuildRuleBuilder.java:1292)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1274)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultExecutor(CachingBuildRuleBuilder.java:804)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.<init>(K2JVMCompiler.kt:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.loadCompilerShim(JarBackedReflectedKotlinc.java:200)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.lambda$buildWithClasspath$3(JarBackedReflectedKotlinc.java:163)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:161)
	at com.facebook.buck.jvm.kotlin.KotlincStep.execute(KotlincStep.java:93)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1358)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1326)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithExecutor(CachingBuildRuleBuilder.java:1285)
	... 11 more
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
```

**Comment by hzsweers** [comment]
CC @kageiit @thalescm

**Comment by thalescm** [comment]
I'll try to check it out, but not finding a class makes me think it maybe is passing wrong jars to the compiler. Can you be sure it's using all 1.2.50 jars and not pointing maybe to a java home with different ones?

**Comment by hzsweers** [comment]
Not sure, this is all configured by okbuck. Will wait for @kageiit to chime in

**Comment by kageiit** [comment]
This is a problem in okbuck. Fixed by https://github.com/uber/okbuck/pull/684 . Feel free to close this
