### ISSUE TITLE
buck fails when encountering bad symlinks

### ISSUE THREAD

**Issue by wjmelements** [facebook/buck#1924]
```
Buck encountered an internal error
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/will/projects/my-app/MyApp/submodules/ios-secp256k1/framework/secp256k1.framework/Versions/A/Documentation/Documentation
	at com.facebook.buck.util.cache.impl.DefaultFileHashCache.lambda$0(DefaultFileHashCache.java:69)
	at com.facebook.buck.util.cache.impl.FileSystemMapFileHashCache.lambda$0(FileSystemMapFileHashCache.java:44)
	at com.facebook.buck.util.filesystem.FileSystemMap$Entry.load(FileSystemMap.java:99)
	at com.facebook.buck.util.filesystem.FileSystemMap$Entry.access$3(FileSystemMap.java:95)
	at com.facebook.buck.util.filesystem.FileSystemMap.get(FileSystemMap.java:279)
	at com.facebook.buck.util.cache.impl.FileSystemMapFileHashCache.get(FileSystemMapFileHashCache.java:79)
	at com.facebook.buck.util.cache.DelegatingFileHashCacheEngine.get(DelegatingFileHashCacheEngine.java:57)
	at com.facebook.buck.util.cache.impl.StatsTrackingFileHashCacheEngine.get(StatsTrackingFileHashCacheEngine.java:62)
	at com.facebook.buck.util.cache.impl.DefaultFileHashCache.get(DefaultFileHashCache.java:260)
	at com.facebook.buck.util.hashing.PathHashing.hashPath(PathHashing.java:49)
	at com.facebook.buck.util.cache.impl.DefaultFileHashCache.getDirHashCode(DefaultFileHashCache.java:221)
	at com.facebook.buck.util.cache.impl.DefaultFileHashCache.getHashCodeAndFileType(DefaultFileHashCache.java:198)
	at com.facebook.buck.util.cache.impl.DefaultFileHashCache.lambda$0(DefaultFileHashCache.java:67)
	at com.facebook.buck.util.cache.impl.FileSystemMapFileHashCache.lambda$0(FileSystemMapFileHashCache.java:44)
	at com.facebook.buck.util.filesystem.FileSystemMap$Entry.load(FileSystemMap.java:99)
	at com.facebook.buck.util.filesystem.FileSystemMap$Entry.access$3(FileSystemMap.java:95)
	at com.facebook.buck.util.filesystem.FileSystemMap.get(FileSystemMap.java:279)
```
The NoSuchFileException refers to a symlink that exists but points to a file that does not exist.
I can work around by removing the file, but better to handle the issue gracefully than to crash buck.

**Comment by sbalabanov** [comment]
How would you suggest to process it gracefully? If a symlink is an input and does not point to a valid file, build should fail anyways. Do you have in mind better error message?
Also please post the full trace and steps to repro.

**Comment by sbalabanov** [comment]
What is this link for, is it served as an input to the rule? In this case I do not believe that we want to ignore that file does not exist, even with a warning. That might create some absurd non-determinism issues.

**Comment by wjmelements** [comment]
The link was reached because of a recursive glob (ex. `src/**/*.m`) path specified in the `BUCK`.

**Comment by sbalabanov** [comment]
I believe Buck does not want to ignore anything that matches as it may be a source of non-determinism. Please delete broken link.

**Comment by wjmelements** [comment]
Even you think it should fail, at least stop it from crashing.
