### ISSUE TITLE
resource not found Exception 

### ISSUE THREAD

**Issue by Saitejakolan9** [facebook/buck#1972]
07-22 14:06:58.304 13154-13154/? I/zygote: Not late-enabling -Xcheck:jni (already on)
07-22 14:06:58.335 13154-13154/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
07-22 14:06:59.693 13154-13165/com.example.caluclator_2 I/zygote: Background concurrent copying GC freed 7892(2MB) AllocSpace objects, 0(0B) LOS objects, 62% free, 917KB/2MB, paused 129.582ms total 293.600ms
07-22 14:06:59.841 13154-13154/com.example.caluclator_2 I/InstantRun: starting instant run server: is main process
07-22 14:07:01.531 13154-13154/com.example.caluclator_2 I/zygote: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2201)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:635)
07-22 14:07:01.547 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:516)
        at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:464)
07-22 14:07:01.548 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
07-22 14:07:01.550 13154-13154/com.example.caluclator_2 I/zygote:     at void com.example.caluclator_2.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:56)
        at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
07-22 14:07:01.551 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
07-22 14:07:01.552 13154-13154/com.example.caluclator_2 I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/base.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_resources_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_5_apk.apk", zip file "/data/ap
07-22 14:07:01.553 13154-13154/com.example.caluclator_2 I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2201)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:635)
        at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:516)
        at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:464)
07-22 14:07:01.554 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.caluclator_2.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:56)
        at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
07-22 14:07:01.555 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-22 14:07:01.556 13154-13154/com.example.caluclator_2 I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
    Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
07-22 14:07:01.557 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2201)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:635)
        at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:516)
07-22 14:07:01.561 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:464)
        at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.caluclator_2.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:56)
07-22 14:07:01.562 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
07-22 14:07:01.563 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-22 14:07:01.564 13154-13154/com.example.caluclator_2 I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/base.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_resources_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_5_apk.apk", zip file "/data/ap
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
07-22 14:07:01.571 13154-13154/com.example.caluclator_2 I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2201)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:635)
        at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:516)
07-22 14:07:01.574 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:464)
        at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.caluclator_2.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:56)
        at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
07-22 14:07:01.576 13154-13154/com.example.caluclator_2 I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
07-22 14:07:01.577 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
07-22 14:07:01.581 13154-13154/com.example.caluclator_2 I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
07-22 14:07:01.594 13154-13154/com.example.caluclator_2 I/zygote: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2201)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:635)
07-22 14:07:01.596 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:516)
        at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:464)
07-22 14:07:01.597 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.caluclator_2.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:56)
        at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
07-22 14:07:01.598 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
07-22 14:07:01.604 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
07-22 14:07:01.605 13154-13154/com.example.caluclator_2 I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-22 14:07:01.606 13154-13154/com.example.caluclator_2 I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/base.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_resources_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.caluclator_2-QImaS8pb7FbQDH0Ib5W6QA==/split_lib_slice_5_apk.apk", zip file "/data/ap
07-22 14:07:01.607 13154-13154/com.example.caluclator_2 I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
07-22 14:07:01.608 13154-13154/com.example.caluclator_2 I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2201)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:635)
07-22 14:07:01.609 13154-13154/com.example.caluclator_2 I/zygote:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:516)
        at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:464)
        at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.caluclator_2.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:56)
07-22 14:07:01.610 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
07-22 14:07:01.614 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
07-22 14:07:01.615 13154-13154/com.example.caluclator_2 I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
07-22 14:07:01.616 13154-13154/com.example.caluclator_2 I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-22 14:07:01.617 13154-13154/com.example.caluclator_2 I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
07-22 14:07:01.623 13154-13154/com.example.caluclator_2 W/zygote: Verification of void android.support.v4.view.ViewCompat.addOnUnhandledKeyEventListener(android.view.View, android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerCompat) took 105.456ms
07-22 14:07:01.955 13154-13154/com.example.caluclator_2 D/AndroidRuntime: Shutting down VM
07-22 14:07:01.958 13154-13154/com.example.caluclator_2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.caluclator_2, PID: 13154
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.caluclator_2/com.example.caluclator_2.MainActivity}: android.view.InflateException: Binary XML file line #169: Binary XML file line #169: Error inflating class TextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #169: Binary XML file line #169: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #169: Error inflating class TextView
     Caused by: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x7f060055
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1013)
        at android.content.res.Resources.loadColorStateList(Resources.java:1030)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:541)
        at android.widget.TextView.<init>(TextView.java:1218)
        at android.widget.TextView.<init>(TextView.java:820)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
        at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1263)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1313)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.example.caluclator_2.MainActivity.onCreate(MainActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-22 14:07:02.100 13154-13159/com.example.caluclator_2 I/zygote: Do partial code cache collection, code=3KB, data=31KB
07-22 14:07:02.101 13154-13159/com.example.caluclator_2 I/zygote: After code cache collection, code=3KB, data=31KB
    Increasing code cache capacity to 128KB

This the issue unbale to find ColorStateList from drawable resource ID #0x7f060055
can anyone help me plz?

**Comment by timmych** [comment]
Can you please add more context to help us understand the issue? (e.g. what were you trying to accomplish, and what project is this, what command you ran)
