### ISSUE TITLE
Buck breaks on NDK updates again, this time on version 18

### ISSUE THREAD

**Issue by hzsweers** [facebook/buck#1993]
I get the following error on the latest NDK

BUCK appears to break every time there's an NDK update, and as a user I'm wondering if this pipeline could be improved. The android SDK autoupdates these aggressively. CC @kageiit 

```
java.lang.RuntimeException: Cannot create a toolchain: cxx-platforms. Cause: Cannot create a toolchain: ndk-cxx-platforms. Cause: Cannot create a toolchain: android-ndk-location. Cause: Invalid version string: 18.0.4912477-beta1
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:177)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:109)
	at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)
	at com.facebook.buck.jvm.java.JavaBinaryDescription.getCxxPlatform(JavaBinaryDescription.java:79)
	at com.facebook.buck.jvm.java.JavaBinaryDescription.findDepsForTargetFromConstructorArgs(JavaBinaryDescription.java:174)
	at com.facebook.buck.jvm.java.JavaBinaryDescription.findDepsForTargetFromConstructorArgs(JavaBinaryDescription.java:55)
	at com.facebook.buck.core.model.targetgraph.impl.TargetNodeFactory.create(TargetNodeFactory.java:124)
	at com.facebook.buck.core.model.targetgraph.impl.TargetNodeFactory.createFromObject(TargetNodeFactory.java:73)
	at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNodeFromObject(DefaultParserTargetNodeFactory.java:200)
	at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:166)
	at com.facebook.buck.parser.DefaultParserTargetNodeFactory.createTargetNode(DefaultParserTargetNodeFactory.java:57)
	at com.facebook.buck.parser.TargetNodeParsePipeline.computeNodeInScope(TargetNodeParsePipeline.java:106)
	at com.facebook.buck.parser.TargetNodeParsePipeline.computeNodeInScope(TargetNodeParsePipeline.java:52)
	at com.facebook.buck.parser.ConvertingPipelineWithPerfEventScope.computeNode(ConvertingPipelineWithPerfEventScope.java:68)
	at com.facebook.buck.parser.ConvertingPipeline.dispatchComputeNode(ConvertingPipeline.java:143)
	at com.facebook.buck.parser.ConvertingPipeline.lambda$null$0(ConvertingPipeline.java:81)
	at com.facebook.buck.parser.PipelineNodeCache.getJobWithCacheLookup(PipelineNodeCache.java:73)
	at com.facebook.buck.parser.ConvertingPipeline.lambda$getAllNodesJob$1(ConvertingPipeline.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Cannot create a toolchain: ndk-cxx-platforms. Cause: Cannot create a toolchain: android-ndk-location. Cause: Invalid version string: 18.0.4912477-beta1
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:166)
	... 24 more
Caused by: java.lang.RuntimeException: Cannot create a toolchain: ndk-cxx-platforms. Cause: Cannot create a toolchain: android-ndk-location. Cause: Invalid version string: 18.0.4912477-beta1
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:177)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.isToolchainPresent(DefaultToolchainProvider.java:125)
	at com.facebook.buck.cxx.toolchain.CxxPlatformsProviderFactory.createToolchain(CxxPlatformsProviderFactory.java:48)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:191)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.access$100(DefaultToolchainProvider.java:46)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:64)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:58)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 28 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Cannot create a toolchain: android-ndk-location. Cause: Invalid version string: 18.0.4912477-beta1
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:166)
	... 38 more
Caused by: java.lang.RuntimeException: Cannot create a toolchain: android-ndk-location. Cause: Invalid version string: 18.0.4912477-beta1
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:177)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:109)
	at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)
	at com.facebook.buck.android.toolchain.ndk.impl.NdkCxxPlatformsProviderFactory.getNdkCxxPlatforms(NdkCxxPlatformsProviderFactory.java:59)
	at com.facebook.buck.android.toolchain.ndk.impl.NdkCxxPlatformsProviderFactory.createToolchain(NdkCxxPlatformsProviderFactory.java:42)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:191)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.access$100(DefaultToolchainProvider.java:46)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:64)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:58)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 42 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Invalid version string: 18.0.4912477-beta1
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:166)
	... 54 more
Caused by: java.lang.RuntimeException: Invalid version string: 18.0.4912477-beta1
	at com.facebook.buck.util.VersionStringComparator.compare(VersionStringComparator.java:47)
	at com.facebook.buck.android.toolchain.ndk.impl.AndroidNdkFactory.createToolchain(AndroidNdkFactory.java:59)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:191)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.access$100(DefaultToolchainProvider.java:46)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:64)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:58)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 58 more
```

**Comment by styurin** [comment]
How did you configure Android NDK? Using `NDK_HOME` or `ANDROID_NDK`? Could you use `ANDROID_NDK_REPOSITORY` instead? Buck would then skip unsupported versions of NDK.

**Comment by styurin** [comment]
Because NDK evolves over time and we cannot provide updates at the same time.

**Comment by hzsweers** [comment]
Why not allow users to hit those issues though? Worst case it's incompatible and you can say it's not supported yet. Best case it works out of the box (as has been the cast in _most_ updates), and middle-ground is you get early bug reports

**Comment by styurin** [comment]
Well, you hit that issue. If you use `ANDROID_NDK` or `NDK_HOME` Buck will try to use NDK no matter which version it has. If you use `ANDROID_NDK_REPOSITORY` it will use the latest supported unless version provided by configuration. This behavior looks similar to what you described.

**Comment by njlr** [comment]
I am using versions from https://developer.android.com/ndk/downloads/older_releases rather than the one provided by Android Studio. Be sure to set the `ANDROID_NDK` variable.
