### ISSUE TITLE
Buck fails to run samples from Buck Samples.

### ISSUE THREAD

**Issue by HarikaReddyRamidi** [facebook/buck#1998]
I installed buck on windows and attempted running the samples located at  https://github.com/fbsamples/bucksamples.git and
ran into the following issue:

D:\Buck\bucksamples\hello-buck-java>buck run hello_buck_java
PARSING BUCK FILES: FINISHED IN 0.0s
CREATING ACTION GRAPH: FINISHED IN 0.0s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 0.0s (100%) 1/1 JOBS, 0 UPDATED
BUILD SUCCEEDED
Traceback (most recent call last):
  File "C:\buck\bin\..\programs\buck.py", line 261, in <module>
    fn_exec()
  File "C:\buck\programs\buck_tool.py", line 116, in execve
    self._argv, executable=self._path, env=self._envp, cwd=self._cwd
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified.

**Comment by tayloryork** [comment]
I see the same error - but @timmych note your suggestion is for 'build' not run.
`buck version 2018.08.27.01`

```
C:\source\OTHER\bucksamples\hello-buck-java>buck build --show-output hello_buck_java
Not using buckd because watchman isn't installed.
PARSING BUCK FILES... 0.0s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.3s
//com/facebook/buck/demo:hello-buck-java buck-out\gen\com\facebook\buck\demo\hello-buck-java.jar
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 2.2s (100%) 1/1 JOBS, 0 UPDATED
BUILD SUCCEEDED
```
```
C:\source\OTHER\bucksamples\hello-buck-java>buck run hello_buck_java
Not using buckd because watchman isn't installed.
PARSING BUCK FILES... 0.0s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.2s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 2.2s (100%) 1/1 JOBS, 0 UPDATED
BUILD SUCCEEDED
Traceback (most recent call last):
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 328, in execute
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 261, in _wrap_coverage
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 293, in _wrap_profiling
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 371, in _execute
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 429, in execute_entry
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 434, in execute_module
  File "C:\Python27\lib\runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\programs\buck.py", line 261, in <module>
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\programs\buck_tool.py", line 116, in execve
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by tayloryork** [comment]
I found a fix, but i'm no python expert, so I don't know if it's acceptable.
I logged everything on that line.  For brevity, I simplified by environment variables and only used a shorter simplified PATH to my jdk.  It stills fails in the same way.
```
subprocess.Popen(
['java', '-jar', 'C:\\source\\OTHER\\bucksamples\\hello-buck-java\\buck-out\\gen\\com\\facebook\\buck\\demo\\hello-buck-java.jar'],
executable=java,
env={'PATH': 'C:\\PROGRA~1\\Java\\jdk1.8.0_144\\bin'},
cwd=C:\source\OTHER\bucksamples\hello-buck-java
)
```

I found it odd that the 'arguments' lists 'java', and so does the executable.
So i took out the exectuable, so the new code is:
```
child = subprocess.Popen(
self._argv, env=self._envp, cwd=self._cwd
)
```
And voila, I see:
`Hello Buck`

**Comment by tayloryork** [comment]
@HarikaReddyRamidi Can you pull and see if that fixed your problem?

**Comment by tayloryork** [comment]
The cpp sample fail to run for a different problem. It looks like it needs some "lib" but I have no idea what lib.

```
C:\source\OTHER\bucksamples\hello-buck-cxx>C:\source\OTHER\buck\bin\buck run :main
Not using buckd because watchman isn't installed.
Parsing buck files: finished in 0.6 sec (100%)
Building: finished in 1.1 sec
  Total time: 2.2 sec
File not found: lib
    When amending path.
    When amending tool.
```
