### ISSUE TITLE
buck fails to calculate class abi for prebuilt jar

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#2005]
```
Buck encountered an internal error
java.lang.ArrayIndexOutOfBoundsException: 32800
	at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2591)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:728)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.facebook.buck.jvm.java.abi.DirectoryReader.visitClass(DirectoryReader.java:61)
	at com.facebook.buck.jvm.java.abi.JarReader.visitClass(JarReader.java:53)
	at com.facebook.buck.jvm.java.abi.StubJarClassEntry.of(StubJarClassEntry.java:56)
	at com.facebook.buck.jvm.java.abi.StubJarEntry.of(StubJarEntry.java:30)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:104)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:84)
	at com.facebook.buck.jvm.java.CalculateClassAbiStep.execute(CalculateClassAbiStep.java:52)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	... 14 more

    When running <class_abi>.
    When building rule //.okbuck/cache:org.glassfish.hk2.external--asm-all-repackaged--2.5.0-b32.jar#class-abi.
```

jar is here: https://mvnrepository.com/artifact/org.glassfish.hk2.external/asm-all-repackaged/2.5.0-b32

**Comment by zmanji** [comment]
I think to fix this we should just upgrade our asm dependency from 6.0 to 6.2.1 (latest).

**Comment by kageiit** [comment]
upgrade asm in buck @zmanji ?

**Comment by zmanji** [comment]
Yes, I think the dependencies [here](https://github.com/facebook/buck/tree/a8609ff85c7d9a50ff799513961e920fe5093090/third-party/java/asm) are outdated.

**Comment by jtorkkola** [comment]
I'm currently working on upgrading ASM to 6.2.1. Unfortunately, there are some breaking behavioral changes, so it isn't totally trivial.

**Comment by kageiit** [comment]
Seems like the upgrade merged - https://github.com/facebook/buck/commit/aad4ab401838290cea29b123eb237ef144ef0c4e

Thanks @jtorkkola !
