### ISSUE TITLE
Chocolatey package doesn't use bundled Python

### ISSUE THREAD

**Issue by Exide** [facebook/buck#2011]
I'm on Windows 10 and I already have Python 3.7.0 installed via the [installer from python.org][1]. My goal is to install [Buckaroo][3], a C++ dependency manager, which uses Buck as it's build tool. To install Buck I opted to try [Chocolatey][2].

So first I downloaded and installed Chocolatey:

```
PS E:\> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).Downloa
dString('https://chocolatey.org/install.ps1'))
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.11.
Extracting C:\Users\exide\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\exide\AppData\Local\Temp\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\exide\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
```

Then I used it to install Buck:

```
PS E:\> choco install buck
Chocolatey v0.10.11
Installing the following packages:
buck
By installing you accept licenses for the packages.
Progress: Downloading python2 2.7.15... 100%
Progress: Downloading buck 2018.08.20.01... 100%
Progress: Downloading jdk8 8.0.181... 100%

python2 v2.7.15 [Approved]
python2 package files install completed. Performing other installation steps.
The package python2 wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading python2 64 bit
  from 'https://www.python.org/ftp/python/2.7.15/python-2.7.15.amd64.msi'
Progress: 100% - Completed download of C:\Users\exide\AppData\Local\Temp\chocolatey\python2\2.7.15\python-2.7.15.amd64.msi (19.31 MB).
Download of python-2.7.15.amd64.msi (19.31 MB) completed.
Hashes match.
Installing python2...
python2 has been installed.
Installed to 'C:\Python27'
Adding C:\Python27 to PATH if needed
  python2 may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of python2 was successful.
  Software installed as 'msi', install location is likely default.

jdk8 v8.0.181 [Approved]
jdk8 package files install completed. Performing other installation steps.
The package jdk8 wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-windows-x64.exe
Installing jdk8...
jdk8 has been installed.
PATH environment variable does not have C:\Program Files\Java\jdk1.8.0_181\bin in it. Adding...
  jdk8 may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of jdk8 was successful.
  Software installed to 'C:\Program Files\Java\jdk1.8.0_181\'

buck v2018.08.20.01 [Approved]
buck package files install completed. Performing other installation steps.
The package buck wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Added C:\ProgramData\chocolatey\bin\buck.exe shim pointed to '..\lib\buck\tools\buck.bat'.
 The install of buck was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 3/3 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Finally, I tried using Buck to install Buckaroo but ran into an error:

```
PS E:\> git clone https://github.com/LoopPerfect/buckaroo.git
Cloning into 'buckaroo'...
remote: Counting objects: 6555, done.
remote: Total 6555 (delta 0), reused 0 (delta 0), pack-reused 6555R
Receiving objects: 100% (6555/6555), 877.04 KiB | 4.08 MiB/s, done.
Resolving deltas: 100% (3100/3100), done.
PS E:\> cd buckaroo
PS E:\buckaroo>buck build :buckaroo-cli
Traceback (most recent call last):
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 328, in execute
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 261, in _wrap_coverage
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 293, in _wrap_profiling
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 371, in _execute
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 429, in execute_entry
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\.bootstrap\_pex\pex.py", line 434, in execute_module
  File "C:\Program Files (x86)\Python\3.6.3\lib\runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Program Files (x86)\Python\3.6.3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\chocolatey\lib\buck\tools\buck.pex\programs\buck.py", line 19, in <module>
ModuleNotFoundError: No module named 'buck_logging'
```

I know Buck doesn't support Python 3, but Python 2 was installed by Chocolatey as part of the `choco install buck` process. I looked at the [Buck package on Chocolatey][4] and saw that `tools/buck.bat` relies on environmental variables to pick the Python interpreter for use:

```
@echo off
REM Invoke buck.pex in the same directory as this script with python
python %~dp0\buck.pex %*
```

Shouldn't it explicitly use the one that is bundled with it?

[1]: https://www.python.org/downloads/release/python-370/
[2]: https://chocolatey.org/
[3]: http://buckaroo.pm/
[4]: https://chocolatey.org/packages/buck

**Comment by philipjameson** [comment]
Hmmm.... I was not aware that python.org's installer installed python3 as 'python', as for all unix envs, python is python2, and python3 is python 3.x. We can probably change this up a bit.

**Comment by philipjameson** [comment]
Sorry for the delay on this. We now have a preference for the version installed with chocolatey, and we're pushing a version this afternoon that should have the fix. Thanks for bringing this up!

**Comment by Exide** [comment]
Cool, thanks!

I will keep an eye on the Chocolatey gallery for an updated version of Buck and try again.

**Comment by Exide** [comment]
What kind of time frame should I expect to see this new release on Chocolatey? I looked at the dates on the previous versions and it appears they went up within 24 hours after release (with the first being an exception).

This is the link I've been checking: https://chocolatey.org/packages/buck
