### ISSUE TITLE
gen-buck-info fails when git is configured differently

### ISSUE THREAD

**Issue by kkaefer** [facebook/buck#2012]
I have this in my `~/.gitconfig`:

```
[core]
	safecrlf = true
	crlf = input
	autocrlf = input
```

When building buck, I get a failure in the `gen-buck-info` step:

```
gen-buck-info:
     [exec] fatal: LF would be replaced by CRLF in test/com/facebook/buck/cli/testdata/build_report/expected_successful_build_report.win.json
     [exec] Traceback (most recent call last):
     [exec]   File "programs/gen_buck_info.py", line 69, in <module>
     [exec]     sys.exit(main(sys.argv))
     [exec]   File "programs/gen_buck_info.py", line 41, in main
     [exec]     version = buck_version.get_dirty_buck_version(path)
     [exec]   File "/Users/kkaefer/Code/buck/programs/buck_version.py", line 101, in get_dirty_buck_version
     [exec]     subprocess.check_call(["git", "add", "-A"], cwd=dirpath, env=new_environ)
     [exec]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
     [exec]     raise CalledProcessError(retcode, cmd)
     [exec] subprocess.CalledProcessError: Command '['git', 'add', '-A']' returned non-zero exit status 128
```

**Comment by vitarb** [comment]
There might be something wrong with your python installation.
I've seen similar error and it went away after I've changed back to Python 2.7.15 (from 3), though I see that you are already using 2.7. I would try installing fresh installation of python via brew and try with that.

**Comment by kkaefer** [comment]
I can try that, but removing the line ending-related directives from the config makes the `gen-buck-info` step function as intended.

**Comment by kkaefer** [comment]
(fwiw, I'm using the stock python that ships with macOS 10.12)
