### ISSUE TITLE
error parsing buck test:Boost Library unit test results

### ISSUE THREAD

**Issue by HsuanTingLu** [facebook/buck#2024]
the cxx_test runs fine when using buck run, but seems to fail to correctly parse Boost Lib unit test XML results

full output after command `buck test //test:main`,
(which for the same cxx_test rule, `buck run //test:main` works fine,
suggesting Boost library linking is fine)

```
Building: finished in 0.0 sec (100%) 3/3 jobs, 0 updated
FAILURE //test:main main: Premature end of file.
Building: finished in 0.0 sec (100%) 3/3 jobs, 0 updated
  Total time: 0.0 sec
Testing: finished in 0.0 sec (0 PASS/1 FAIL)
RESULTS FOR //test:main
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   //test:main
FAILURE //test:main main: Premature end of file.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at com.facebook.buck.util.xml.XmlDomParser.parse(XmlDomParser.java:64)
	at com.facebook.buck.util.xml.XmlDomParser.parse(XmlDomParser.java:48)
	at com.facebook.buck.util.xml.XmlDomParser.parse(XmlDomParser.java:39)
	at com.facebook.buck.cxx.CxxBoostTest.parseResults(CxxBoostTest.java:224)
	at com.facebook.buck.cxx.CxxTest.lambda$interpretTestResults$0(CxxTest.java:226)
	at com.facebook.buck.cli.TestRunning$4.call(TestRunning.java:535)
	at com.facebook.buck.cli.TestRunning$4.call(TestRunning.java:528)
	at com.facebook.buck.cli.TestRunning.lambda$runStepsAndYieldResult$1(TestRunning.java:812)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

TESTS FAILED: 1 FAILURE
Failed target: //test:main
FAIL //test:main
```

**Comment by bobyangyf** [comment]
Hi @HsuanTingLu,

Is this a custom target that you are running tests on?
Do you have a repro test that you can possibly send to us?

**Comment by HsuanTingLu** [comment]
I need some time to dig out the project, but here's the summary:
from what I recall,
it's a tiny class that I built the test for, to set the unit test environment ready,
project built and ran on macOS,
including the prebuilt BOOST lib and my c++ class code

one interesting thing is that, 
`buck test //test:main` did the job, with the primitive output from BOOST
while `buck test //test:main` seems to have failed to parse the output

I'll leave a link in the comments if I find the project repo afterwards

**Comment by bobyangyf** [comment]
Thanks. Please send us the xml or the project to repro.
