### ISSUE TITLE
Regression in buck project causes it to crash

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#2025]
This commit broke buck project badly: https://github.com/facebook/buck/commit/d4cd98d01241b7d5d5ab859fcfaef8b727fce7ec

Stacktrace:
```
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:485)
	at com.facebook.buck.features.project.intellij.ModuleBuildContext.addGeneratedSourceCodeFolder(ModuleBuildContext.java:127)
	at com.facebook.buck.features.project.intellij.BaseIjModuleRule.addAnnotationOutputIfNeeded(BaseIjModuleRule.java:289)
	at com.facebook.buck.features.project.intellij.BaseIjModuleRule.addDepsAndFolder(BaseIjModuleRule.java:152)
	at com.facebook.buck.features.project.intellij.BaseIjModuleRule.addDepsAndFolder(BaseIjModuleRule.java:162)
	at com.facebook.buck.features.project.intellij.BaseIjModuleRule.addDepsAndSources(BaseIjModuleRule.java:182)
	at com.facebook.buck.features.project.intellij.lang.android.AndroidLibraryModuleRule.apply(AndroidLibraryModuleRule.java:54)
	at com.facebook.buck.features.project.intellij.DefaultIjModuleFactory.createModuleUsingSortedTargetNodes(DefaultIjModuleFactory.java:73)
	at com.facebook.buck.features.project.intellij.DefaultIjModuleFactory.createModule(DefaultIjModuleFactory.java:53)
	at com.facebook.buck.features.project.intellij.IjModuleGraphFactory.lambda$createModules$8(IjModuleGraphFactory.java:112)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.facebook.buck.features.project.intellij.IjModuleGraphFactory.createModules(IjModuleGraphFactory.java:109)
	at com.facebook.buck.features.project.intellij.IjModuleGraphFactory.from(IjModuleGraphFactory.java:216)
	at com.facebook.buck.features.project.intellij.IjProject.performWriteOrUpdate(IjProject.java:122)
	at com.facebook.buck.features.project.intellij.IjProject.write(IjProject.java:79)
	at com.facebook.buck.features.project.intellij.IjProjectCommandHelper.writeProjectAndGetRequiredBuildTargets(IjProjectCommandHelper.java:282)
	at com.facebook.buck.features.project.intellij.IjProjectCommandHelper.runIntellijProjectGenerator(IjProjectCommandHelper.java:231)
	at com.facebook.buck.features.project.intellij.IjProjectCommandHelper.parseTargetsAndRunProjectGenerator(IjProjectCommandHelper.java:200)
	at com.facebook.buck.features.project.intellij.IjProjectSubCommand.run(IjProjectSubCommand.java:185)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:136)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:236)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1202)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:435)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:199)
```

cc @mkillianey

**Comment by kageiit** [comment]
This is still happening as of https://github.com/facebook/buck/commit/ea8add2016df57ff22cfc4c79647e63a6d7806a9

cc @mkillianey

**Comment by v-jizhang** [comment]
@kageiit  Is this still happening? Thanks

**Comment by kageiit** [comment]
cc @naveenOnarayanan can you please confirm ^

**Comment by naveenOnarayanan** [comment]
We haven't seen this issue lately. We can close this out for now, and re-visit this if we notice a regression from our side.

**Comment by v-jizhang** [comment]
Thank you.
