### ISSUE TITLE
error parsing xml output util unit test

### ISSUE THREAD

**Issue by AlessandroPatti** [facebook/buck#2034]
Parsing xml result of `//test/com/facebook/buck/util:util` unit test randomly fails. 
Full output after error

```
PARSING BUCK FILES: FINISHED IN 0.0s
CREATING ACTION GRAPH: FINISHED IN 0.0s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 0.3s (100%) 444/445 JOBS, 0 UPDATED
BUILD SUCCEEDED
TESTING //test/com/facebook/buck/util:util
[Fatal Error] :4:92: Character reference "&#
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   //test/com/facebook/buck/util:util
FAILURE //test/com/facebook/buck/util:util main: Error parsing test result data in /Users/alessandro/buck/buck-out/gen/test/com/facebook/buck/util/__java_test_util_output__/com.facebook.buck.util.SimpleProcessListenerTest.xml.
File contents:
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<testcase name="com.facebook.buck.util.SimpleProcessListenerTest" runner_capabilities="simple_test_selector">
  <test name="echoTextReceivedOnStdout" success="true" suite="com.facebook.buck.util.SimpleProcessListenerTest" time="51" type="SUCCESS"/>
  <test message="&#10;Expected: &quot;Meow\n&quot;&#10;     but: was &quot;Meow\nMeow\n&#0;&#0;&#0;&#12;e&quot;" name="catTextSentToStdinReceivedOnStdout" stacktrace="java.lang.AssertionError: &#10;Expected: &quot;Meow\n&quot;&#10;     but: was &quot;Meow\nMeow\n&#0;&#0;&#0;&#12;e&quot;&#10;&#9;at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)&#10;&#9;at org.junit.Assert.assertThat(Assert.java:956)&#10;&#9;at org.junit.Assert.assertThat(Assert.java:923)&#10;&#9;at com.facebook.buck.util.SimpleProcessListenerTest.catTextSentToStdinReceivedOnStdout(SimpleProcessListenerTest.java:66)&#10;&#9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#10;&#9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#10;&#9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#10;&#9;at java.lang.reflect.Method.invoke(Method.java:498)&#10;&#9;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#10;&#9;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#10;&#9;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#10;&#9;at org.junit  1 PARSING BUCK FILES: FINISHED IN 0.0s
.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#10;&#9;at com.facebook.buck.testrunner.SameThreadFailOnTimeout.lambda$new$0(SameThreadFailOnTimeout.java:41)&#10;&#9;at java.util.concurrent.FutureTask.run(FutureTask.java:266)&#10;&#9;at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)&#10;&#9;at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)&#10;&#9;at java.lang.Thread.run(Thread.java:748)&#10;" success="false" suite="com.facebook.buck.util.SimpleProcessListenerTest" time="7" type="FAILURE"/>
  <test name="supplierBasedInput" success="true" suite="com.facebook.buck.util.SimpleProcessListenerTest" time="12" type="SUCCESS"/>
</testcase>

java.lang.RuntimeException: Error parsing test result data in /Users/alessandro/buck/buck-out/gen/test/com/facebook/buck/util/__java_test_util_output__/com.facebook.buck.util.SimpleProcessListenerTest.xml.
File contents:
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<testcase name="com.facebook.buck.util.SimpleProcessListenerTest" runner_capabilities="simple_test_selector">
  <test name="echoTextReceivedOnStdout" success="true" suite="com.facebook.buck.util.SimpleProcessListenerTest" time="51" type="SUCCESS"/>
  <test message="&#10;Expected: &quot;Meow\n&quot;&#10;     but: was &quot;Meow\nMeow\n&#0;&#0;&#0;&#12;e&quot;" name="catTextSentToStdinReceivedOnStdout" stacktrace="java.lang.AssertionError: &#10;Expected: &quot;Meow\n&quot;&#10;     but: was &quot;Meow\nMeow\n&#0;&#0;&#0;&#12;e&quot;&#10;&#9;at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)&#10;&#9;at org.junit.Assert.assertThat(Assert.java:956)&#10;&#9;at org.junit.Assert.assertThat(Assert.java:923)&#10;&#9;at com.facebook.buck.util.SimpleProcessListenerTest.catTextSentToStdinReceivedOnStdout(SimpleProcessListenerTest.java:66)&#10;&#9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#10;&#9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#10;&#9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#10;&#9;at java.lang.reflect.Method.invoke(Method.java:498)&#10;&#9;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#10;&#9;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#10;&#9;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#10;&#9;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#10;&#9;at com.facebook.buck.testrunner.SameThreadFailOnTimeout.lambda$new$0(SameThreadFailOnTimeout.java:41)&#10;&#9;at java.util.concurrent.FutureTask.run(FutureTask.java:266)&#10;&#9;at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)&#10;&#9;at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)&#10;&#9;at java.lang.Thread.run(Thread.java:748)&#10;" success="false" suite="com.facebook.buck.util.SimpleProcessListenerTest" time="7" type="FAILURE"/>
  <test name="supplierBasedInput" success="true" suite="com.facebook.buck.util.SimpleProcessListenerTest" time="12" type="SUCCESS"/>
</testcase>

	at com.facebook.buck.test.XmlTestResultParser.parse(XmlTestResultParser.java:132)
	at com.facebook.buck.jvm.java.JavaTest.lambda$1(JavaTest.java:447)
	at com.facebook.buck.cli.TestRunning$4.call(TestRunning.java:546)
	at com.facebook.buck.cli.TestRunning$4.call(TestRunning.java:1)
	at com.facebook.buck.cli.TestRunning.lambda$3(TestRunning.java:823)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 92; Character reference "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at com.facebook.buck.util.xml.XmlDomParser.parse(XmlDomParser.java:64)
	at com.facebook.buck.test.XmlTestResultParser.doParse(XmlTestResultParser.java:138)
	at com.facebook.buck.test.XmlTestResultParser.parse(XmlTestResultParser.java:128)
	... 12 more

TESTS FAILED: 1 FAILURE
Failed target: //test/com/facebook/buck/util:util
FAIL //test/com/facebook/buck/util:util
```

**Comment by timmych** [comment]
> <test message="&#10;Expected: &quot;Meow\n&quot;&#10;     but: was &quot;Meow\nMeow\n&#0;&#0;&#0;&#12;e&quot;"

As the Buck error message mentioned, it appears the 2nd test result message contains an invalid char `&#0;`
