### ISSUE TITLE
Support Android Navigation Architecture Component

### ISSUE THREAD

**Issue by omegasoft7** [facebook/buck#2040]
When using Navigation component after running the APP as son as I want to redirect to another fragment I receive the following error:

``` Process: com.xing.beacons.android, PID: 21755
    java.lang.RuntimeException: Unable to start activity ComponentInfo{...android.feature.home.HomeActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class fragment
     Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment androidx.navigation.fragment.NavHostFragment: make sure class name exists, is public, and has an empty constructor that is public```

I presume the support has to be added to "ExoHelper.java". 
https://github.com/facebook/buck/blob/a6c7d7391a7a8e575c6372cac6690a240b5907ea/android/com/facebook/buck/android/support/exopackage/ExoHelper.java#L78

**Comment by asp2insp** [comment]
`ExoHelper` is a work-in-progress for supporting some forms of code-hot-loading in Buck, and is not involved in the normal exopackage/incremental installation flow, so I believe the issue lies elsewhere.

Can you provide some more information to help us debug this issue? 
* Are you writing your BUCK files by hand or are you using OkBuck? 
* Does the app start up successfully prior to this navigation or is this an insta-crash? 
* What is your `exopackage_modes` set to in your `android_binary` definition? 
* Do you have a dependency on the `navigation-fragment`/`navigation-ui` jars in your app? If so, is it a normal or `provided_dep`?

**Comment by asp2insp** [comment]
Closing this out due to lack of response, but please feel free to re-open if this is still an issue
