### ISSUE TITLE
Error when switching to python3 - AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by utkudiril** [facebook/buck#2059]
I have a buck project that I have been running with python2 so far. When I switched to python3 by adding the following to my .buckconfig file

[python]
    interpreter = /usr/local/bin/python3

I get the following error (removed some paths):

Build failed: Command failed with exit code 1.
stderr: Traceback (most recent call last):
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/.bootstrap/_pex/pex.py", line 328, in execute
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/.bootstrap/_pex/pex.py", line 261, in _wrap_coverage
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/.bootstrap/_pex/pex.py", line 293, in _wrap_profiling
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/.bootstrap/_pex/pex.py", line 371, in _execute
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/.bootstrap/_pex/pex.py", line 429, in execute_entry
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/.bootstrap/_pex/pex.py", line 434, in execute_module
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/src/com/facebook/buck/python/make_pex.py", line 181, in <module>
  File "buckd/resources/94f51dbd7177e9e6867bd54f047de048914d7a7c/path_to_pex/src/com/facebook/buck/python/make_pex.py", line 147, in main
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by njlr** [comment]
I think the future is Skylark, not Python 3: https://buckbuild.com/concept/skylark.html

**Comment by utkudiril** [comment]
I am not trying to use python 3 as the buck language but use it as my project interpreter. Is there a different setting for this?

**Comment by njlr** [comment]
My mistage, I was thinking of this option: 

```ini=
[parser]
  default_build_file_syntax = SKYLARK
```

**Comment by scottrice** [comment]
Hijacking this old issue with a workaround + more details.

## The Issue

As mentioned in the original post, the issue is the use of `iteritems()` in `make_pex.py`, which doesn't exist in python3 (`items` now does what `iteritems` does). This is a problem because we execute `make_pex.py` with whatever the configured python interpreter is - https://github.com/facebook/buck/blob/71e515269fc54693a18f8d13c68f65a939644d48/src/com/facebook/buck/features/python/toolchain/impl/DefaultPexToolProvider.java#L87-L88

This means setting your interpreter to python3 is a trap, since Buck-internal code doesn't work in that environment.

The fix is to either make `make_pex.py` work with all Python versions, or somehow use a different interpreter for it (since Buck itself relies on Python2 it means an interpreter for it must exist somewhere on the system, so maybe hijack that? Not sure how difficult it is to make a file work on every possible Python version)

## The Immediate Workaround

If you want to use Python3 for a project and this issue hasn't been solved yet, there is an easy workaround.

Rather than doing

```
[python]
interpreter = python3
```

You change it to the following

```
[python#py3]
interpreter = python3
```

and then change your BUCK file accordingly

```
python_binary(
  name = "TooCoolForSchool",
  platform = "py3",  # <<< THIS IS THE CRUCIAL LINE
  # ...
)
```

This tells Buck to use the py3 interpreter for your binary, but still lets it run `make_pex.py` with the old one.

**Comment by v-jizhang** [comment]
Buck is now Python3 compatible.
