### ISSUE TITLE
Output directory of go_binary becomes a symlink

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#2141]
When a `go_binary` rule uses a `genrule` as its `resources`, and the `genrule`'s `out` parameter is ".", the output directory of a `go_binary` rule becomes a symlink to the output directory of the `genrule`.

Steps to reproduce:

```shell
git clone git@github.com:linzhp/buck_go_examples.git
cd buck_go_examples
buck build genrule:bin
tree buck-out/gen/genrule
buck-out/gen/genrule
├── bin -> /Users/zplin/gocode/src/buck_go_examples/buck-out/gen/genrule/data
├── bin#compile,default
│   └── bin.a
├── data
│   ├── bin
│   └── data.txt
├── data__srcs
│   └── data.txt -> /Users/zplin/gocode/src/buck_go_examples/genrule/data.txt
└── data__tmp
```
As we can see, `bin` is pointing to the output folder of `data`, and the compiled binary is in the data folder too.

Now if one adds a few blank line to genrule/main.go, Buck build will crash with the following error:

```shell
buck build genrule:bin
Building: finished in 0.2 sec (100%) 5/5 jobs, 2 updated
  Total time: 0.2 sec
Buck encountered an internal error
java.nio.file.FileAlreadyExistsException: /Users/zplin/gocode/src/buck_go_examples/buck-out/gen/genrule/bin
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider.createDirectory(BuckFileSystemProvider.java:173)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at com.facebook.buck.step.fs.AbstractMkdirStep.execute(AbstractMkdirStep.java:40)
	at com.facebook.buck.step.fs.MkdirStep.execute(MkdirStep.java:16)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	... 16 more

    When running <mkdir>.
    When building rule //genrule:bin.
```

**Comment by linzhp** [comment]
Thanks!

**Comment by mkaczanowski** [comment]
I had to revert the fix, this needs more investigation

**Comment by mkaczanowski** [comment]
the symlink was causing caching troubles. @chantra fixed the issue in:
https://github.com/facebook/buck/commit/bea44f266c62edde5f626a0004e0a1f901e7c47c

```
├── bin
│   ├── bin
│   └── data.txt
├── bin#compile,platform007-clang
│   └── bin.a
├── bin-go-build-info
│   └── bin-go-build-info.go
├── bin-go-build-info__srcs
├── bin-go-build-info__tmp
├── data
│   └── data.txt
├── data__srcs
│   └── data.txt -> /data/users/mkaczanowski/fbsource/fbcode/tutorials/go/echo/client/data.txt
└── data__tmp
```
