### ISSUE TITLE
Buck doesn't work with WorkManger alpha08 and above

### ISSUE THREAD

**Issue by CeciliaGuo47** [facebook/buck#2149]
In WorkManager alpha08 and above, it uses tools:targetApi="n" in the AndroidManifest.xml instead of tools:targetAPI="n". The manifest merger buck uses is not case insensitive. So buck can't merge the AndroidManifest.xml in WorkManager. More info [here](https://issuetracker.google.com/u/1/issues/114358542). Is it possible to fix it in the new release of buck?

The error I got is as blow:

Buck encountered an internal error
java.lang.RuntimeException: /path/to/project/buck-out/bin/3rdparty/jvm/android/arch/work/__unpack_work-runtime.aar#aar_unzip__/AndroidManifest.xml:28:9-34:35: Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT
at com.android.manifmerger.XmlElement.<init>(XmlElement.java:142)
at com.android.manifmerger.XmlElement.initMergeableChildren(XmlElement.java:870)
at com.android.manifmerger.XmlElement.<init>(XmlElement.java:170)
at com.android.manifmerger.XmlElement.initMergeableChildren(XmlElement.java:870)
at com.android.manifmerger.XmlElement.<init>(XmlElement.java:170)
at com.android.manifmerger.XmlDocument.getRootNode(XmlDocument.java:229)
at com.android.manifmerger.ManifestMerger2.loadLibraries(ManifestMerger2.java:591)
at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:122)
at com.android.manifmerger.ManifestMerger2.access$600(ManifestMerger2.java:53)
at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:1003)
at com.facebook.buck.android.GenerateManifestStep.mergeManifests(GenerateManifestStep.java:121)
at com.facebook.buck.android.GenerateManifestStep.execute(GenerateManifestStep.java:90)
at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
... 16 more
Caused by: /path/to/project/buck-out/bin/3rdparty/jvm/android/arch/work/__unpack_work-runtime.aar#aar_unzip__/AndroidManifest.xml:28:9-34:35: Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT
at com.android.common.ide.common.res2.MergingException$Builder.build(MergingException.java:134)
... 29 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.android.manifmerger.AttributeOperationType.TARGETAPI
at java.lang.Enum.valueOf(Enum.java:238)
at com.android.manifmerger.AttributeOperationType.valueOf(AttributeOperationType.java:54)
at com.android.manifmerger.XmlElement.<init>(XmlElement.java:124)
... 28 more

When running <generate_manifest>.

**Comment by CeciliaGuo47** [comment]
This bug is fixed in this PR https://github.com/facebook/buck/pull/2153

**Comment by styurin** [comment]
Fixed in 04000d48656d4c498813942b454b9d13fb570665
