### ISSUE TITLE
Got errors trying to compile buck

### ISSUE THREAD

**Issue by launchpadtt** [facebook/buck#2171]
I followed the instructions at https://buckbuild.com/setup/getting_started.html in the Build From Source section to try and build Buck from the git checkout and got the following errors. The prerequisites were installed correctly. Any assistance getting it up and running would be appreciated. I assuming I am missing some prerequisite or my python installation is missing something?

```
    chrisym-mbp:buck chrisym$ ./bin/buck build --show-output buck
    Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    Building: finished in 1.4 sec (100%) 76/1536 jobs, 19 updated
      Total time: 1.6 sec
    Command failed with exit code 1.
    stderr: Traceback (most recent call last):
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 184, in <module>
        sys.exit(main())
      File "/Users/chrisym/Library/MobileTools/buck/ant-out/buck-modules-resources/python/make_pex.py", line 157, in main
        for dst, src in manifest["modules"].iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
        When running <pex>.
        When building rule //py/hash:hash_files.
    chrisym-mbp:buck chrisym$ 
```

I tried it with Python 2 and Python 3. Same behavior in both cases.

**Comment by scottrice** [comment]
This error is due to make_pex.py not supporting Python3. When you do `which python` and `python -v` on the command line, what do you get?
