### ISSUE TITLE
``buck project`` fails if ``android_prebuilt_aar`` is used

### ISSUE THREAD

**Issue by ncalexan** [facebook/buck#219]
I have a ``BUCK`` file with a snippet like:
```
android_prebuilt_aar(
  name = 'support-v4',
  aar = '$(ANDROID_HOME)/extras/android/m2repository/com/android/support/support-v4/21.0.0/support-v4-21.0.0.aar',
  visibility = [ 'PUBLIC' ],
)
```

``buck build`` is fine; ``buck project`` fails with:

```
BUILD FAILED: Rule for target '//java/thirdparty:play-services#aar_classes_jar' could not be resolved.
```

An extract from the log:

```
[2014-11-15 21:43:12.605][debug][command:43a0c5c9-6a90-4f32-9672-cb93b1e6d6a2][tid:01][com.facebook.buck.cli.Main] Failing build on exception.
com.facebook.buck.util.HumanReadableException: Rule for target '//java/thirdparty:play-services#aar_classes_jar' could not be resolved.
	at com.facebook.buck.rules.BuildRuleResolver.getRule(BuildRuleResolver.java:69)
	at com.facebook.buck.rules.SourcePathResolver.getPath(SourcePathResolver.java:58)
	at com.facebook.buck.command.Project.writeJsonConfig(Project.java:992)
	at com.facebook.buck.command.Project.createIntellijProject(Project.java:211)
	at com.facebook.buck.cli.ProjectCommand.runIntellijProjectGenerator(ProjectCommand.java:199)
	at com.facebook.buck.cli.ProjectCommand.runCommandWithOptionsInternal(ProjectCommand.java:137)
	at com.facebook.buck.cli.ProjectCommand.runCommandWithOptionsInternal(ProjectCommand.java:1)
	at com.facebook.buck.cli.AbstractCommandRunner.runCommandWithOptions(AbstractCommandRunner.java:140)
	at com.facebook.buck.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:112)
	at com.facebook.buck.cli.Command.execute(Command.java:122)
	at com.facebook.buck.cli.Main.executeCommand(Main.java:639)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:456)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:912)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:965)
	at com.facebook.buck.cli.Main.main(Main.java:983)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:44)
```

**Comment by sdwilsh** [comment]
Thanks for the report.  It'd be great if you can confirm this fixes the issue for you.
