### ISSUE TITLE
Inconsistency between watchman and native globbing 

### ISSUE THREAD

**Issue by naveenOnarayanan** [facebook/buck#2201]
Seems like there is a discrepancy between the watchman globbing and native globbing with regards to handling wild characters. The native globber explicitly requires individual segmented wild characters whereas watchman does not seem to have that requirement. This is causing inconsistencies in building / running targets on environments with/without watchman.

**Example target setup**
## Directory Structure
```
tests/
  | --> test.py 
  | --> foo/bar/data/
       |----> a.txt
       |----> b.txt
       |----> c.txt
```

## Target definition
```
python_test(
    name = "test_main",
    srcs = glob([
        'tests/*.py',
    ]),
    resources = glob([
        'tests/**data/**'
    ])
)
```

## Watchman globbing
* Passes and is able to add `tests/foo/bar/data/*` as resources

## Native globbing
* Fails with the following error:
```
ERROR:..scripts/BUCK:50:17: Traceback (most recent call last):
	File "scripts/BUCK", line 42
		python_test(name = "test_main", srcs = glob(["..."]), <2 more arguments>)
	File "scripts/BUCK", line 50, in python_test
		glob(["tests/**data/**"])
recursive wildcard must be its own segment (in glob pattern 'tests/**data/**')
```

**Comment by naveenOnarayanan** [comment]
Resolved with latest changes
