### ISSUE TITLE
ClassCastException for generating Intellij project

### ISSUE THREAD

**Issue by VisheshVadhera** [facebook/buck#2226]
Running into the following exception when trying to index buck project for Intellij:

```
Buck encountered an internal error
java.lang.ClassCastException: com.facebook.buck.core.rules.configsetting.ConfigSettingDescription cannot be cast to com.facebook.buck.core.model.targetgraph.DescriptionWithTargetGraph
        at com.facebook.buck.features.project.intellij.ShallowTargetNodeToBuildRuleTransformer.transform(ShallowTargetNodeToBuildRuleTransformer.java:65)
        at com.facebook.buck.core.rules.resolver.impl.SingleThreadedActionGraphBuilder.lambda$1(SingleThreadedActionGraphBuilder.java:115)
        at com.facebook.buck.core.rules.resolver.impl.SingleThreadedActionGraphBuilder.computeIfAbsent(SingleThreadedActionGraphBuilder.java:88)
        ... 26 more
```

The steps which I followed were:

1. 
```
git clone --depth 1 https://github.com/facebook/buck.git
cd buck
ant
```

2.
```
./bin/buck build --show-output buck
buck-out/gen/programs/buck.pex --help
```

3.
```
./bin/buck project --ide intellij
```

**Comment by styurin** [comment]
We don't use `buck project` to create IntelliJ project in Buck repository. We have checked-in IntelliJ project that you can open from IntelliJ.

The error is because it doesn't support `config_setting` rule.

**Comment by VisheshVadhera** [comment]
Alright. Also when I open the project in Intellij, I still see some classes as unidentifiable by Intellij.

**Comment by styurin** [comment]
This problem was fixed some time ago. `buck project` now skips all configuration targets including `config_setting`.
