### ISSUE TITLE
Premature removal of --java11-test-mode

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#2232]
@jtorkkola When I was using the January 10 buck build, version 2019.01.10.01, and using the ``--java11-test-mode`` option, my build was working fine.

On the latest master HEAD version of buck:

``` buck version e1fec3196532dc58cf06461ac0f3020f63f570bc ```

I get the build failure message:

```You're using Java 11, but Buck requires Java 8.```

I am on MacOS X 10.14.3, and my environment is as such:
```
> java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```
```
> buck --version
buck version e1fec3196532dc58cf06461ac0f3020f63f570bc
```

Build output:
```
Unable to connect to Buck daemon, restarting it...
Not using buckd because daemon failed to start.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.Error: java.lang.ClassNotFoundException: com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:141)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:111)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:109)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:109)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:103)
	at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:190)
	at java.base/java.io.File.toPath(File.java:2290)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:813)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:758)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:751)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:750)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:725)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:493)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:476)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:475)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:444)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:313)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:697)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
Caused by: java.lang.ClassNotFoundException: com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:131)
	... 34 more
You're using Java 11, but Buck requires Java 8.
Please follow https://buckbuild.com/setup/getting_started.html to properly setup your local environment and avoid build issues.
```
When I built buck on the commit *immediately prior* to the removal commit (fadef0fe2051e3533e111638a2f68989431154ba), I do not see the failure above.  When I built buck on the commit *immediately after* the removal commit (99641972d9b9da9226cabdb9eb76db58524ce97a), then the error returns.

**Comment by jtorkkola** [comment]
Buck now stores the Java version it was compiled against in its package metadata. A version of Buck compiled against Java 11 should run on Java 11 without the user having to do anything special. This is why `--java11-test-mode` was removed. How did you build the version of Buck you're trying to run on Java 11? Java 8 builds of buck will not run on Java 11.

**Comment by shs96c** [comment]
"Java 8 builds of Buck will not run on Java 11"? That seems back-to-front:
Java 11 builds shouldn't run on Java 8, but vice versa is a real surprise.

**Comment by jtorkkola** [comment]
There have been numerous breaking changes (interface, structural, behavioral) between Java 8 and 11, rendering running Java 8 Buck on Java 11 impossible. Buck is particularly badly affected since it reaches into compiler internals for some aspects of Java compilation.

**Comment by brettwooldridge** [comment]
I’m fine with that.  It was working (Java 8 buck running on Java 11).  Given the change, it would be nice if Facebook provided official Java 11 releases.  We would prefer to run off of official binaries than our own custom builds.

**Comment by jtorkkola** [comment]
It was never fully working (certain parts of Java compilation can never work with Java 8 buck running on Java 11). Once we've completed the migration, Buck will require Java 11, and all official binaries will be compiled against Java 11. For now, if you want to run on Java 11, you'll need to build against Java 11 yourself.

**Comment by shepting** [comment]
@brettwooldridge Could you update `jitpack.yml` to specify the Java version? https://jitpack.io/docs/BUILDING/#java-version

**Comment by styurin** [comment]
@jtorkkola it should be possible to build buck package with java11 to be run on java8, java9+ supports versioning of class files per java version. This may require some time to implement and given that we are moving to Java 11 soon may not be something we want to do for java 8, but this still might be useful for future versions of java.

**Comment by shs96c** [comment]
The easiest way to support multi-release jars would be to jar all class
files into their expected multi-jar location (that is, Java < 9 at the root
of the jar, Java 9 at "META-INF/versions/9", and so on. That way, it would
be possible to release a buck version that ran equally well on both Java 8
and 11.

**Comment by jtorkkola** [comment]
@styurin Agreed that this may be useful in the future. I don't plan on doing this for Java 8.
