### ISSUE TITLE
Problem with nailgun: "Caught NGExitException"

### ISSUE THREAD

**Issue by bmihai** [facebook/buck#226]
I recently pulled from somewhere around 2014-11-13 to today's repository (2014-12-16), and things stopped working for me.

I tried bisecting it, and there seems to be a problem on my machine with commit fad16418309d. Things seem to work with 4091360050a7c, but fad164 (and all commits after it) does this after an `ant clean && ant && ./bin/buck --help`:

```
Buck does not appear to have been built -- building Buck!
Shutting down nailgun server...
Using watchman.
Using buckd.
buck build tool
usage:
  buck [options]
  buck command --help
  buck command [command-options]
available commands:
  audit       lists the inputs for the specified target
  build       builds the specified target
  cache       makes calls to the artifact cache
  clean       deletes any generated files
  install     builds and installs an APK
  project     generates project configuration files for an IDE
  quickstart  generates a default project directory
  run         runs a target as a command
  targets     prints the list of buildable targets
  test        builds and runs the tests for the specified target
  uninstall   uninstalls an APK
options:
 --help         : Shows this screen and exits.
 --version (-V) : Show version number.
[2014-12-16 21:10:54.674][error][command:null][tid:13][class com.martiansoftware.nailgun.NGSession] Caught NGExitException, cleaning up session and writing exit command to client.
com.martiansoftware.nailgun.NGExitException: ExitException: status 1
	at com.martiansoftware.nailgun.NGSecurityManager.checkExit(NGSecurityManager.java:56)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:962)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:980)
	at com.facebook.buck.cli.Main.nailMain(Main.java:996)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

**Comment by bmihai** [comment]
Seems fixed as of 000aca10393d9a0fc133715650b9baa84fd5457a.
