### ISSUE TITLE
Create a example by android studio with Kotlin, and build failed

### ISSUE THREAD

**Issue by jichre** [facebook/buck#2274]
I got this error:
```
[2019-06-01 15:12:18.352][debug][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:39][com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder] Building locally: //app:src_debug
[2019-06-01 15:12:26.399][debug][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:35][com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder] Building rule [//app:src_debug] failed.
com.facebook.buck.step.StepFailedException: Command failed with exit code 1.
stderr: 
  When running <javac>.
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithException(StepFailedException.java:57)
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:51)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1438)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1400)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:838)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.buck.core.exceptions.HumanReadableException: Command failed with exit code 1.
stderr: 
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:52)
	... 17 more

[2019-06-01 15:12:26.432][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:28][com.facebook.buck.event.listener.LoggingBuildListener] Build finished at 2019-06-01 15:12:26.431
[2019-06-01 15:12:26.448][debug][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:24][com.facebook.buck.util.perf.ProcessTracker] shutDown
[2019-06-01 15:12:26.449][debug][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:23][com.google.common.util.concurrent.ServiceManager] Service PerfStatsTracking [TERMINATED] has terminated. Previous state was: STOPPING
[2019-06-01 15:12:26.452][debug][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:24][com.google.common.util.concurrent.ServiceManager] Service ProcessTracker [TERMINATED] has terminated. Previous state was: STOPPING
[2019-06-01 15:12:26.456][debug][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.event.listener.SuperConsoleEventBusListener] Stopping render scheduler
[2019-06-01 15:12:26.457][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of PROJECT executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2019-06-01 15:12:26.457][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated PROJECT executor service.
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of NETWORK executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated NETWORK executor service.
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of CPU executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated CPU executor service.
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of ScheduledExecutorService executor service. Waiting for all jobs to complete, or up to maximum of 60 seconds...
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated ScheduledExecutorService executor service.
[2019-06-01 15:12:26.459][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of CounterAggregatorExecutor executor service. Waiting for all jobs to complete, or up to maximum of 20 seconds...
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated CounterAggregatorExecutor executor service.
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of HTTP Read executor service. Waiting for all jobs to complete, or up to maximum of 1800 seconds...
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated HTTP Read executor service.
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of Download Heavy Build HTTP Read executor service. Waiting for all jobs to complete, or up to maximum of 1800 seconds...
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated Download Heavy Build HTTP Read executor service.
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of HTTP Write executor service. Waiting for all jobs to complete, or up to maximum of 1800 seconds...
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated HTTP Write executor service.
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Awaiting termination of Disk IO executor service. Waiting for all jobs to complete, or up to maximum of 10 seconds...
[2019-06-01 15:12:26.460][info ][command:c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7][tid:13][com.facebook.buck.cli.Main] Successfully terminated Disk IO executor service.
[2019-06-01 15:12:26.462][debug][command:null][tid:125][com.facebook.buck.io.AsynchronousDirectoryContentsCleaner] Starting to clean buck-out/.trash
[2019-06-01 15:12:26.462][debug][command:null][tid:125][com.facebook.buck.io.AsynchronousDirectoryContentsCleaner] Starting to clean buck-out/.trash
[2019-06-01 15:12:26.463][debug][command:null][tid:125][com.facebook.buck.io.AsynchronousDirectoryContentsCleaner] Done cleaning buck-out/.trash
[2019-06-01 15:12:26.463][debug][command:null][tid:125][com.facebook.buck.io.AsynchronousDirectoryContentsCleaner] Done cleaning buck-out/.trash
[2019-06-01 15:12:26.476][debug][command:null][tid:129][com.facebook.buck.event.listener.ChromeTraceBuildListener] Writing Chrome trace to buck-out/log/2019-06-01_07h11m30s_buildcommand_c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7/build.2019-06-01.15-11-30.c38ad06a-1dd0-4a3b-b04e-a888d8c27cb7.trace
[2019-06-01 15:12:26.477][warn ][command:null][tid:13][com.facebook.buck.cli.Main] Command failed:
com.facebook.buck.command.Build$BuildExecutionException: com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: When building rule //app:src_debug.
	at com.facebook.buck.command.Build.waitForBuildToFinish(Build.java:323)
	at com.facebook.buck.command.Build.waitForBuildToFinishAndPrintFailuresToEventBus(Build.java:421)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:144)
	at com.facebook.buck.command.LocalBuildExecutor.buildTargets(LocalBuildExecutor.java:147)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:761)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:458)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:372)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:338)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:242)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1299)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:463)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
Caused by: com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: When building rule //app:src_debug.
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.addBuildRuleContextToException(CachingBuildRuleBuilder.java:1208)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.lambda$build$5(CachingBuildRuleBuilder.java:405)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:172)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:159)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:112)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1016)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:867)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:713)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:97)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.buck.step.StepFailedException: Command failed with exit code 1.
stderr: 
  When running <javac>.
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithException(StepFailedException.java:57)
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:51)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1438)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1400)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:838)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	... 9 more
Caused by: com.facebook.buck.core.exceptions.HumanReadableException: Command failed with exit code 1.
stderr: 
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:52)
	... 17 more

[2019-06-01 15:12:26.480][warn ][command:null][tid:13][com.facebook.buck.util.Console] Command failure: Command failed with exit code 1.
stderr: 
    When running <javac>.
    When building rule //app:src_debug.
[2019-06-01 15:12:26.486][debug][command:null][tid:13][com.facebook.buck.cli.Main] Done.
```

**Comment by jichre** [comment]
If the example was java,build success

**Comment by v-jizhang** [comment]
I've created a sample project at https://github.com/v-jizhang/BuckAndroidKotlinSample, but could repro the issue. Do you still see the error? Thanks.

**Comment by ronnie-o-sullivan** [comment]
Same error ! How do you resolve it?
