### ISSUE TITLE
Exception parsing checksums for Kotlin classes nested in backtick functions

### ISSUE THREAD

**Issue by elucash** [facebook/buck#2286]
When there are any local/anonymous/lambda classes are used in Kotlin functions with names containing spaces 

```kotlin
fun `my test name with spaces`() {
  val j = object : Consumer<String> {
    override fun accept(t: String) {}
  }
}
```

```
Buck encountered an internal error

java.lang.IllegalStateException

 at com.google.common.base.Preconditions.checkState(Preconditions.java:485)
 at com.facebook.buck.jvm.java.AccumulateClassNamesStep.parseClassHashes(AccumulateClassNamesStep.java:167)
 at com.facebook.buck.jvm.java.JavaLibraryRules.initializeFromDisk(JavaLibraryRules.java:62)
 at com.facebook.buck.jvm.java.DefaultJavaLibrary.initializeFromDisk(DefaultJavaLibrary.java:375)
 at com.facebook.buck.jvm.java.DefaultJavaLibrary.initializeFromDisk(DefaultJavaLibrary.java:84)
 at com.facebook.buck.core.rules.attr.BuildOutputInitializer.initializeFromDisk(BuildOutputInitializer.java:57)
 at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.doInitializeFromDisk(CachingBuildRuleBuilder.java:1304)
 at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.finalizeBuildRule(CachingBuildRuleBuilder.java:549)
 at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.lambda$build$4(CachingBuildRuleBuilder.java:412)
 at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder.lambda$ruleAsyncFunction$25(CachingBuildRuleBuilder.java:1346)
 at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
 at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
 at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
 ... 10 more

    When building rule //some:test#testsjar.
```

Seems like checksum parser chokes on extra spaces in `<filename> <checksum>` lines. Maybe it would be better if the compiler would not emit classes with spaces and derive bytecode class names differently.

**Comment by NickFirmani** [comment]
A duplicate of #1621 ?

**Comment by elucash** [comment]
@NickFirmani  I believe it's the same issue, I'll add the info as more context.
Closing as duplicate
