### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by 79144876** [facebook/buck#229]
lius-MacBook-Pro:ReviewProject liupeng$ buck install --run demo
Using buckd.
[+] PARSING BUCK FILES...0.5s
No library manifests found. Aborting manifest merge step.
BUILD FAILED: //:manifest failed with exit code 1:
generate_manifest
[2014-12-30 20:38:02.749][error][command:bcb37a6f-f311-4aa5-9982-7baec7709353][tid:239][com.facebook.buck.event.listener.LoggingBuildListener] The following resources were not found when processing libprojects/library/res: 
RDotTxtEntry{idType=int, type=dimen, name=abs__action_bar_default_height, idValue=0x00000000}
RDotTxtEntry{idType=int, type=dimen, name=abs__action_bar_icon_vertical_padding, idValue=0x00000000}

java.lang.RuntimeException
[2014-12-30 20:38:02.750][error][command:bcb37a6f-f311-4aa5-9982-7baec7709353][tid:251][com.google.common.util.concurrent.Futures$CombinedFuture] input future failed.
com.facebook.buck.step.StepFailedException: //:ui-res failed with exit code 1:
generate_resource_ids
        at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:57)
        at com.facebook.buck.step.DefaultStepRunner.runStepInternal(DefaultStepRunner.java:105)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:83)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:501)
        at com.facebook.buck.rules.CachingBuildEngine.buildOnceDepsAreBuilt(CachingBuildEngine.java:380)
        at com.facebook.buck.rules.CachingBuildEngine.access$3(CachingBuildEngine.java:304)
        at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:181)
        at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:1)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

lius-MacBook-Pro:ReviewProject liupeng$

**Comment by 79144876** [comment]
@sdwilsh I have put my project here : https://github.com/79144876/FacebookBuckExample
You can clone it ,and then run buck build.it will error again.
May be you will find some error.
Thanks.

**Comment by sdwilsh** [comment]
I can't run that:
* Compilation error: `*** No rule to make target `/Users/liupeng/Documents/workspace/eudic//lib/tool/base64c.cpp', needed by `/Users/sdwilsh/code/FacebookBuckExample/buck-out/bin/fr/jni/__librecite-ndk//local/armeabi/objs/_jni_recite/lib/tool/base64c.o'.  Stop.`
* You checked in `.buckd` and `local.properties` (I removed them locally to get past the error at least)

With that said, I think your error is that you needed to declare all of your dependencies and not rely on transitive dependencies.  Buck requires that you specify all dependencies of your dependencies as well (it's part of what makes Buck fast: http://facebook.github.io/buck/concept/what_makes_buck_so_fast.html).

**Comment by 79144876** [comment]
Oh.i fix it at last night .(https://github.com/facebook/buck/issues/231#issuecomment-68563018)
thanks @natthu and @sdwilsh !

**Comment by sdwilsh** [comment]
Closing per last comment.
