### ISSUE TITLE
Exception in Plugin Buck for IDEA (Android Studio

### ISSUE THREAD

**Issue by SeanRenet** [facebook/buck#2295]
macOS Mojave 10.14.5
Android Studio 3.4.2 (new install)
Buck for IDEA v3.5.2

When opening new or existing project Buck throws the following error.

java.lang.NullPointerException
	at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:532)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:572)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:719)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.send(WebSocketUpgradeRequest.java:542)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.sendAsync(WebSocketUpgradeRequest.java:547)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:401)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:327)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:309)
	at com.facebook.buck.intellij.ideabuck.ws.BuckClient.connectToWebServer(BuckClient.java:139)
	at com.facebook.buck.intellij.ideabuck.ws.BuckClient.access$200(BuckClient.java:33)
	at com.facebook.buck.intellij.ideabuck.ws.BuckClient$2.run(BuckClient.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jackmaris** [comment]
Me as well (same error message)

Mojave 10.14.6
Android Studio 3.4.2
Buck for IDEA v3.5.2

**Comment by nickbreen** [comment]
```2019-12-18 09:51:29,067 [   4524]  ERROR - r.PlatformComponentManagerImpl - IntelliJ IDEA 2019.3.1  Build #IU-193.5662.46 
2019-12-18 09:51:29,067 [   4524]  ERROR - r.PlatformComponentManagerImpl - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-12-18 09:51:29,067 [   4524]  ERROR - r.PlatformComponentManagerImpl - OS: Linux 
2019-12-18 09:51:29,067 [   4524]  ERROR - r.PlatformComponentManagerImpl - Plugin to blame: Buck for IDEA version: 3.5.2 
2019-12-18 09:51:29,067 [   4524]  ERROR - r.PlatformComponentManagerImpl - Last Action:  
2019-12-18 09:51:44,058 [  19515]  ERROR - ntellij.ideabuck.ws.BuckClient - null 
java.lang.NullPointerException
	at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:532)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:572)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:719)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.send(WebSocketUpgradeRequest.java:542)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.sendAsync(WebSocketUpgradeRequest.java:547)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:401)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:327)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:309)
	at com.facebook.buck.intellij.ideabuck.ws.BuckClient.connectToWebServer(BuckClient.java:139)
	at com.facebook.buck.intellij.ideabuck.ws.BuckClient.access$200(BuckClient.java:33)
	at com.facebook.buck.intellij.ideabuck.ws.BuckClient$2.run(BuckClient.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
