### ISSUE TITLE
Cannot run buck project on OpenJDK11 when target_level = 11

### ISSUE THREAD

**Issue by davidtron** [facebook/buck#2310]
Cannot generate buck project when using java 11 source and target levels (either command line or .buckconfig)

```
[java]
    source_level = 11
    target_level = 11
    jar_spool_mode = direct_to_jar
```

Java Version : OpenJDK 11.0.3
Buck release : v2019.09.12.01

Results in

Buck encountered an internal error
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.facebook.buck.jvm.java.JavaFileParser.createJavaFileParser(JavaFileParser.java:459)
	at com.facebook.buck.features.project.intellij.IjProjectCommandHelper.writeProjectAndGetRequiredBuildTargets(IjProjectCommandHelper.java:263)
	at com.facebook.buck.features.project.intellij.IjProjectCommandHelper.runIntellijProjectGenerator(IjProjectCommandHelper.java:221)
	at com.facebook.buck.features.project.intellij.IjProjectCommandHelper.parseTargetsAndRunProjectGenerator(IjProjectCommandHelper.java:208)
	at com.facebook.buck.features.project.intellij.IjProjectSubCommand.run(IjProjectSubCommand.java:211)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:146)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:257)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:81)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1344)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:456)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

**Comment by philipjameson** [comment]
@jtorkkola

**Comment by MuminKhan** [comment]
@philipjameson @jtorkkola, I'm encountering a similar issue on `buck version 2019.10.17.01`: 

```
Not using buckd because watchman isn't installed.
Building: finished in 0.9 sec (100%) 1/1 jobs, 1 updated
  Total time: 1.4 sec
Buck encountered an internal error
java.lang.IllegalArgumentException: invalid source release: 11
        at com.sun.tools.javac.main.OptionHelper$GrumpyHelper.error(OptionHelper.java:103)
        at com.sun.tools.javac.main.Option$11.process(Option.java:204)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:217)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:156)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64)
        at com.facebook.buck.jvm.java.plugin.api.BuckJavacTaskProxy.getTask(BuckJavacTaskProxy.java:48)
        at com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.getJavacTask(Jsr199JavacInvocation.java:570)
        at com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.buildClasses(Jsr199JavacInvocation.java:338)
        at com.facebook.buck.jvm.java.Jsr199JavacInvocation.buildClasses(Jsr199JavacInvocation.java:174)
        at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:112)
        at com.facebook.buck.step.StepRunner.runStep(StepRunner.java:58)
        ... 16 more

    When running <javac>.
```

Is this related?

**Comment by MuminKhan** [comment]
I've opened #2339 to track this issue.

**Comment by jtorkkola** [comment]
@MuminKhan, that is unrelated. Replied on the other issue.
