### ISSUE TITLE
cxx flavor does not overwrite original cxx label

### ISSUE THREAD

**Issue by AlexDreyfuss** [facebook/buck#2344]
When i configure cxxpp and cxx in a flavor for cxx it still uses the original cxx g++.
[cxx]
  cxxpp = 
  cxx =   

[cxx#pc]
  cxxpp = /path to my g++
  cxx =   /path to my g++
if i use the same g++ in [cxx] it mixes up all the flags from both the flavor and the original
The same happens when save the flavor in a include file

When i leave it blank it uses the local g++. when i remove the [cxx] it results in an internal error:
Buck encountered an internal error
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.facebook.buck.parser.TargetSpecResolver.collectTargets(TargetSpecResolver.java:297)
	at com.facebook.buck.parser.TargetSpecResolver.resolveTargetSpecs(TargetSpecResolver.java:195)
	at com.facebook.buck.parser.ParserWithConfigurableAttributes.collectBuildTargetsFromTargetNodeSpecs(ParserWithConfigurableAttributes.java:317)
	at com.facebook.buck.parser.AbstractParser.buildTargetGraphForTargetNodeSpecs(AbstractParser.java:266)
	at com.facebook.buck.parser.AbstractParser.buildTargetGraphWithoutTopLevelConfigurationTargets(AbstractParser.java:240)
	at com.facebook.buck.cli.BuildCommand.createUnversionedTargetGraph(BuildCommand.java:654)
	at com.facebook.buck.cli.BuildCommand.createGraphsAndTargets(BuildCommand.java:368)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:425)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:344)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelpInternal(BuildCommand.java:292)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:274)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:269)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:90)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1379)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:474)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:507)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
	at com.facebook.buck.parser.TargetSpecResolver.collectTargets(TargetSpecResolver.java:291)
	... 21 more
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:486)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:775)
	at com.facebook.buck.json.BuildFilePythonResultDeserializer.deserializeList(BuildFilePythonResultDeserializer.java:113)
	at com.facebook.buck.json.BuildFilePythonResultDeserializer.deserializeRecursive(BuildFilePythonResultDeserializer.java:127)
	at com.facebook.buck.json.BuildFilePythonResultDeserializer.deserializeObject(BuildFilePythonResultDeserializer.java:101)
	at com.facebook.buck.json.BuildFilePythonResultDeserializer.deserializeObjectList(BuildFilePythonResultDeserializer.java:88)
	at com.facebook.buck.json.BuildFilePythonResultDeserializer.deserialize(BuildFilePythonResultDeserializer.java:62)
	at com.facebook.buck.json.BuildFilePythonResultDeserializer.deserialize(BuildFilePythonResultDeserializer.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1729)
	at com.facebook.buck.parser.PythonDslProjectBuildFileParser.performJsonRequest(PythonDslProjectBuildFileParser.java:623)
	at com.facebook.buck.parser.PythonDslProjectBuildFileParser.getAllRulesInternal(PythonDslProjectBuildFileParser.java:448)
	at com.facebook.buck.parser.PythonDslProjectBuildFileParser.getBuildFileManifest(PythonDslProjectBuildFileParser.java:386)
	at com.facebook.buck.json.TargetCountVerificationParserDecorator.getBuildFileManifest(TargetCountVerificationParserDecorator.java:73)
	at com.facebook.buck.parser.decorators.EventReportingProjectBuildFileParser.getBuildFileManifest(EventReportingProjectBuildFileParser.java:69)
	at com.facebook.buck.parser.ProjectBuildFileParserPool.lambda$getBuildFileManifest$0(ProjectBuildFileParserPool.java:94)
	at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:136)
	at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:128)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AlexDreyfuss** [comment]
in the .buckconfig doc theres a config:
[apple]
  use_flavored_cxx_sections = true


this works also without and not building for apple
