### ISSUE TITLE
Kotlin external compiler option is broken

### ISSUE THREAD

**Issue by i-tatsenko** [facebook/buck#2349]
Given a simple kotlin project:
```
$: buck --version
buck version 2019.10.17.01

$: which kotlinc
/usr/local/bin/kotlinc

$: ls -la
total 24
drwxr-xr-x   7 itatsenko  staff  224 Nov 19 11:03 .
drwxr-xr-x   4 itatsenko  staff  128 Nov 19 10:45 ..
-rw-r--r--   1 itatsenko  staff   63 Nov 19 11:02 .buckconfig
-rw-r--r--   1 itatsenko  staff   57 Nov 19 10:48 BUCK
-rw-r--r--   1 itatsenko  staff   41 Nov 19 10:45 Main.kt

$: cat .buckconfig
[kotlin]
  external = true
  kotlinc = /usr/local/bin/kotlinc

$: cat Main.kt
fun main() {
  println("Hello world!")
}
```
On a buck build, the following error happens:
```
$: buck build //...
Building: finished in 0.0 sec (100%) 0/1 jobs, 0 updated
  Total time: 0.0 sec
Buck encountered an internal error
java.lang.IllegalStateException: AddToRuleKey can only be applied to methods of Immutables. It cannot be applied to com.facebook.buck.jvm.kotlin.ExternalKotlinc.getKotlinCompilerVersion(...)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:817)
	at com.facebook.buck.rules.keys.ReflectiveAlterKeyLoader.getExtractorsForObject(ReflectiveAlterKeyLoader.java:135)
	at com.facebook.buck.rules.keys.ReflectiveAlterKeyLoader.load(ReflectiveAlterKeyLoader.java:81)
	at com.facebook.buck.rules.keys.ReflectiveAlterKeyLoader.load(ReflectiveAlterKeyLoader.java:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 120 more

    When amending kotlinc.
    When amending configuredCompiler.
    When amending jarBuildStepsFactory.
    When amending buildableForRuleKey.
    When computing rulekey for //:test.
```

If I set `external` to `false` in the `.buckconfig` the project can be normally built. 

Thank you.

**Comment by v-jizhang** [comment]
Fixed in PR https://github.com/facebook/buck/pull/2354
