### ISSUE TITLE
Exception in ideabuck

### ISSUE THREAD

**Issue by nickbreen** [facebook/buck#2358]
```2019-12-18 09:51:29,062 [   4519]  ERROR - r.PlatformComponentManagerImpl - IntelliJ IDEA 2019.3.1  Build #IU-193.5662.46 
2019-12-18 09:51:29,062 [   4519]  ERROR - r.PlatformComponentManagerImpl - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-12-18 09:51:29,062 [   4519]  ERROR - r.PlatformComponentManagerImpl - OS: Linux 
2019-12-18 09:51:29,065 [   4522]  ERROR - r.PlatformComponentManagerImpl - Plugin to blame: Buck for IDEA version: 3.5.2 
2019-12-18 09:51:29,065 [   4522]  ERROR - r.PlatformComponentManagerImpl - Last Action:  
2019-12-18 09:51:29,066 [   4523]  ERROR - r.PlatformComponentManagerImpl - getComponentAdapterOfType is used to get com.facebook.buck.intellij.ideabuck.config.BuckExecutableDetector (requestorClass=com.facebook.buck.intellij.ideabuck.config.BuckProjectSettingsProvider, requestorConstructor=com.facebook.buck.intellij.ideabuck.config.BuckProjectSettingsProvider(com.intellij.openapi.project.Project,com.facebook.buck.intellij.ideabuck.config.BuckExecutableDetector)).

Probably constructor should be marked as NonInjectable. [Plugin: intellij.buck.plugin] 
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.facebook.buck.intellij.ideabuck.config.BuckExecutableDetector (requestorClass=com.facebook.buck.intellij.ideabuck.config.BuckProjectSettingsProvider, requestorConstructor=com.facebook.buck.intellij.ideabuck.config.BuckProjectSettingsProvider(com.intellij.openapi.project.Project,com.facebook.buck.intellij.ideabuck.config.BuckExecutableDetector)).

Probably constructor should be marked as NonInjectable. [Plugin: intellij.buck.plugin]
	at com.intellij.serviceContainer.ConstructorParameterResolver.findTargetAdapter(ConstructorParameterResolver.kt:111)
	at com.intellij.serviceContainer.ConstructorParameterResolver.isResolvable(ConstructorParameterResolver.kt:39)
	at com.intellij.serviceContainer.ConstructorInjectionKt.getGreediestSatisfiableConstructor(constructorInjection.kt:106)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:36)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getComponent(PlatformComponentManagerImpl.kt:273)
	at com.facebook.buck.intellij.ideabuck.config.BuckProjectSettingsProvider.getInstance(BuckProjectSettingsProvider.java:46)
	at com.facebook.buck.intellij.ideabuck.util.BuckCellFinder.<init>(BuckCellFinder.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:315)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:624)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareProject(PlatformProjectOpenProcessor.java:315)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$openExistingProject$0(PlatformProjectOpenProcessor.java:241)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$1.run(ProjectFrameAllocator.kt:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by v-jizhang** [comment]
From Ideabuck team: "Should be fixed in D20777708", which was committed on 4/1/2020.
