### ISSUE TITLE
Buck encountered an internal error: java.lang.NoSuchMethodError: okhttp3.OkHttpClient while running Buck build in Android 

### ISSUE THREAD

**Issue by AkashDhanwani** [facebook/buck#2395]
Hi people,

While trying to run Buck build on my project, it's throwing the following error
```
Buck encountered an internal error
java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder;
	at com.facebook.buck.artifact_cache.ArtifactCaches.setTimeouts(ArtifactCaches.java:746)
	at com.facebook.buck.artifact_cache.ArtifactCaches.createHttpArtifactCache(ArtifactCaches.java:571)
	at com.facebook.buck.artifact_cache.ArtifactCaches.createRetryingArtifactCache(ArtifactCaches.java:522)
	at com.facebook.buck.artifact_cache.ArtifactCaches.initializeDistributedCaches(ArtifactCaches.java:438)
	at com.facebook.buck.artifact_cache.ArtifactCaches.newInstanceInternal(ArtifactCaches.java:315)
	at com.facebook.buck.artifact_cache.ArtifactCaches.newInstanceInternal(ArtifactCaches.java:212)
	at com.facebook.buck.artifact_cache.ArtifactCaches.newInstance(ArtifactCaches.java:194)
	at com.facebook.buck.command.BuildExecutor.<init>(BuildExecutor.java:110)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:870)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:494)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:361)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelpInternal(BuildCommand.java:303)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:285)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:277)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:90)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1444)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:479)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

I tried deleting the caches inside .gradle and .buck, also tried deleting the directory itself, that also didn't worked.

Please can anyone help me on this.

**Comment by v-jizhang** [comment]
Could you update to the latest buck and try again?

**Comment by AkashDhanwani** [comment]
Thanks v-jizhang.

I tried with cloning the same repo on a different location and cleared all the caches. That helped and now it is working fine.
