### ISSUE TITLE
[Kotlin Class ABI Jars] Invalid ABI jar generated for some Kotlin/Intellij Jars.

### ISSUE THREAD

**Issue by tyvsmith** [facebook/buck#2410]
When using compile_against_abis for kotlin, some jetbrains/android artifacts contain a javaslang package, it looks like the PatternsProcessor class isn't being accurately represented in the ABI jar that's generated. The class itself doesn't seem like anything special, so not sure why it's failing.

Using
```
[kotlin]
    compile_against_abis = true
```

Prebuilt Jars pulled:

 - org.jetbrains.kotlin:kotlin-compiler-embeddable:jar:1.3.61
 - com.android.tools.external.com-intellij:intellij-core:jar:26.6.0-rc02

Stacktrace:

```
exception: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javaslang/match/PatternsProcessor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:51)
	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:44)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension$loadProcessors$efficientProcessorLoader$1.doLoadProcessors(Kapt3Extension.kt:83)
	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors(ProcessorLoader.kt:45)
	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors$default(ProcessorLoader.kt:28)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.loadProcessors(Kapt3Extension.kt:88)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:171)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:557)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:548)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:213)
	at com.facebook.buck.jvm.kotlin.KotlincStep.execute(KotlincStep.java:101)
	at com.facebook.buck.step.StepRunner.runStep(StepRunner.java:62)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1418)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1395)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:859)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Decompiled class for reference.
```
package javaslang.match;

import java.io.IOException;
import java.io.Writer;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javaslang.match.generator.Generator;
import javaslang.match.model.ClassModel;
import javaslang.match.model.MethodModel;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.tools.Diagnostic;

public class PatternsProcessor
  extends AbstractProcessor
{
  public Set<String> getSupportedAnnotationTypes() { return Collections.singleton(javaslang.match.annotation.Patterns.class.getName()); }

  public SourceVersion getSupportedSourceVersion() { return SourceVersion.latestSupported(); }

  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    if (!annotations.isEmpty()) {

      Set<TypeElement> typeElements = (Set)roundEnv.getElementsAnnotatedWith(javaslang.match.annotation.Patterns.class).stream().filter(element -> element instanceof TypeElement).map(element -> (TypeElement)element).collect(Collectors.toSet());
      if (!typeElements.isEmpty()) {
        Set<ClassModel> classModels = transform(typeElements);
        if (!classModels.isEmpty()) {
          generate(classModels);
        }
      } 
    } 
    return true;
  }

  private Set<ClassModel> transform(Set<TypeElement> typeElements) {
    Set<ClassModel> classModels = new HashSet<ClassModel>();
    Elements elementUtils = this.processingEnv.getElementUtils();
    Messager messager = this.processingEnv.getMessager();
    for (TypeElement typeElement : typeElements) {
      ClassModel classModel = ClassModel.of(elementUtils, typeElement);

      
      List<MethodModel> methodModels = (List)classModel.getMethods().stream().filter(method -> method.isAnnotatedWith(javaslang.match.annotation.Unapply.class)).collect(Collectors.toList());
      if (methodModels.isEmpty()) {
        messager.printMessage(Diagnostic.Kind.WARNING, "No @Unapply methods found.", classModel.typeElement()); continue;
      } 
      boolean methodsValid = ((Boolean)methodModels.stream().reduce(Boolean.valueOf(true), (bool, method) -> Boolean.valueOf((bool.booleanValue() && UnapplyChecker.isValid(method.getExecutableElement(), messager))), (b1, b2) -> Boolean.valueOf((b1.booleanValue() && b2.booleanValue())))).booleanValue();
      if (methodsValid) {
        classModels.add(classModel);
      }
    } 
    
    return classModels;
  }

  private void generate(Set<ClassModel> classModels) {
    Filer filer = this.processingEnv.getFiler();
    for (ClassModel classModel : classModels) {
      String derivedClassName = deriveClassName(classModel);
      String code = Generator.generate(derivedClassName, classModel);
      String fqn = (classModel.hasDefaultPackage() ? "" : (classModel.getPackageName() + ".")) + derivedClassName; 
      try { writer = filer.createSourceFile(fqn, new Element[] { classModel.typeElement() }).openWriter(); throwable = null; 
        try { writer.write(code); } catch (Throwable throwable1) { throwable = throwable1 = null; throw throwable1; }
        finally { if (writer != null) if (throwable != null) { try { writer.close(); } catch (Throwable throwable1) { throwable.addSuppressed(throwable1); }  } else { writer.close(); }   }  } catch (IOException x)
      { throw new Error("Error writing " + fqn, x); }
    
    } 
  }
  
  private String deriveClassName(ClassModel classModel) {
    String name = classModel.getClassName();
    return ("$".equals(name) ? "" : (name.endsWith(".$") ? name.substring(0, name.length() - 2) : name))
      .replaceAll("\\.", "_") + javaslang.match.annotation.Patterns.class
      .getSimpleName();
  }
}
```

**Comment by tyvsmith** [comment]
FYI @IanChilds

**Comment by v-jizhang** [comment]
@tyvsmith The generated abi looks good too, it must be something else. Do you have a repro that can be shared? Thanks.

```
package javaslang.match;

import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.TypeElement;
import javax.lang.model.SourceVersion;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;

public class PatternsProcessor extends AbstractProcessor
{
    public PatternsProcessor();
    
    @Override
    public Set<String> getSupportedAnnotationTypes();
    
    @Override
    public SourceVersion getSupportedSourceVersion();
    
    @Override
    public boolean process(final Set<? extends TypeElement> p0, final RoundEnvironment p1);
}
```

**Comment by IanChilds** [comment]
Sorry, I missed this
