### ISSUE TITLE
Prebuilt_jars : generate_abis = False breaks transitive deps.

### ISSUE THREAD

**Issue by tyvsmith** [facebook/buck#2411]
Cache Keys seem to rely on the existence of the abi jars to use the class hashes in the manifest.

Those exist in abi-jars and do not exist in regular jars. Example from auto-common class-abi jar:

```
Name: META-INF/maven/com.google.auto/auto-common/pom.properties
Murmur3-128-Digest: f0a85b9e5b58819ae2fb78dcae1fd8fe

Name: META-INF/maven/com.google.auto/auto-common/pom.xml
Murmur3-128-Digest: 23d7b80d435851d717f5aafe4b6c9093

Name: com/google/auto/common/AnnotationMirrors.class
Murmur3-128-Digest: 01ddba71bc0e914c39ea3150c5b091f3
...
```

When turning generate_abis = False on the prebuilt_jar the following error occurs. (even when compile_against_abis = false)

This doesn't happen when compiling the target directly or when it's used as a direct dep. It occurs when it's a transitive grandchild dep is marked to not generate_abis and that is referenced in code by the direct child.

```
Buck encountered an internal error
com.facebook.buck.command.Build$BuildExecutionException: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When finalizing rule.: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When amending buildableForRuleKey.: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When amending jarBuildStepsFactory.: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When amending abiClasspath.: java.lang.UnsupportedOperationException: Cache does not know how to return hash codes for archive members except when the archive contains a META-INF/MANIFEST.MF with Murmur3-128-Digest attributes for each file.
	at com.facebook.buck.command.Build.waitForBuildToFinish(Build.java:297)
	at com.facebook.buck.command.Build.waitForBuildToFinishAndPrintFailuresToEventBus(Build.java:394)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:136)
	at com.facebook.buck.command.BuildExecutor.buildTargets(BuildExecutor.java:111)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:899)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:494)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:363)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelpInternal(BuildCommand.java:305)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:287)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:280)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:90)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1446)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:477)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

**Comment by tyvsmith** [comment]
FYI @IanChilds

**Comment by v-jizhang** [comment]
The commit 14d852ac36ab48ed6f080cbee51c249845fe2216 set generate_abi to true.
```
    // TODO T55723624 remove this
    @Value.Default
    default boolean getGenerateAbi() {
      return true;
    }
```
That should have temporarily solved this issue.

**Comment by IanChilds** [comment]
Feels weird that this was having an effect even with `compile_against_abis = False`

**Comment by IanChilds** [comment]
But actually IIRC there is a bug where we do some comparison for caching purposes with the ABI jar even if we're not going to build against it :(
