### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by jonathan-lmax** [facebook/buck#2416]
I have read a few of the other issues here regarding Java 11. I'm running with tools.javac = jdk11 but it makes caching almost impossible hence some very slow builds. Is this a known issue? Also, I've tried compiling the Buck pex with Java 11 but this doesn't seem to work - still get the "You're running Java 11 but Buck only plays nicely with Java 8" message. Any advice here would be appreciated. Lastly, just out of interest, is there a roadmap / timeline for the migration to full Java 11 support? Thanks.

**Comment by v-jizhang** [comment]
When compiling buck, you need set source level and target level.
./bin/buck build --config java.target_level=11 --config java.source_level=11 buck

**Comment by jonathan-lmax** [comment]
@v-jizhang perfect! thank you!

**Comment by brettwooldridge** [comment]
@v-jizhang @jonathan-lmax I am getting this same error ("You're running Java 11 but Buck only plays nicely with Java 8") on *master* even when invoking the phase 2 build as recommended:
``./bin/buck build --config java.target_level=11 --config java.source_level=11 buck``

Output:
```
Not using buckd because watchman isn't installed.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.Error: java.lang.NullPointerException
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:141)
        ...
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.toPath(File.java:2290)
        ...
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:131)
	... 34 more
You're using Java 11, but Buck requires Java 8.
```

Java:
```
[root@loadtest buck]# java -version
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```

**Comment by brettwooldridge** [comment]
Nevermind. Turned out to be a Linux "alternatives" configuration issue, whereby "java" was being picked up from JDK11, but "javac" was being picked up from JDK 1.8. JDK11 jre only installed, not full devel package.
