### ISSUE TITLE
Is dx-from-kitkat outdated for android L?

### ISSUE THREAD

**Issue by minid33** [facebook/buck#242]
I'm not certain this is the explicit cause but when building with the android_binary target:
`target = 'Google Inc.:Google APIs:21'` 
buck selects `buck/third-party/java/dx-from-kitkat/etc/dx` to run as the dexguard application, there is obviously a version mismatch here.

In our codebase this results in:
```
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:504)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:301)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:512)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:173)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:194)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:462)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:307)
	at com.android.dx.command.dexer.Main.run(Main.java:243)
	at com.android.dx.command.dexer.Main.run(Main.java:213)
	at com.android.dx.command.dexer.Main.main(Main.java:195)
	at com.android.dx.command.Main.main(Main.java:103)
```

This exception isn't thrown when using `android-sdk-macosx/build-tools/21.1.2/dx`.

Workaround:
`ln -s ${ANDROID_HOME}/build-tools/21.1.2/dx ${BUCK_REPO}buck/third-party/java/dx-from-kitkat/etc/dx`

**Comment by minid33** [comment]
This can also be because we're using guava which defines many many methods.

**Comment by sdwilsh** [comment]
Yeah, you are hitting the 65k dex limit, and it's unrelated to the version of dx.  We are working on updating it to a newer version, however!
