### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.buck.util.environment.MacWifiSsidFinder

### ISSUE THREAD

**Issue by s3lvin** [facebook/buck#2491]
```
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.buck.util.environment.MacWifiSsidFinder
	at com.facebook.buck.util.environment.NetworkInfo.getWifiSsid(NetworkInfo.java:77)
	at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getWifiSsid(DefaultExecutionEnvironment.java:79)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1176)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:476)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```
This error happens when I try to generate the Xcode project, after upgrading to Mac OS Big sur. Any idea what could have gone wrong?

**Comment by v-jizhang** [comment]
Looks like something broken after you upgrading MacOS. Please check your environment, re-install buck and try again. Thanks

**Comment by v-jizhang** [comment]
@s3lvin, We do not support Mac OS Big sur yet but we will keep this issue open until Big sur is released. If it is a buck issue, we will fix it. Thank you.

**Comment by victorpanitz** [comment]
@v-jizhang Is there any buck internal stuff not supporting MacOS Big Sur or the non-compatibility is totally related to homebrew compatibility ?

**Comment by v-jizhang** [comment]
Should not, but we haven't fully tested buck on Big sur yet.

**Comment by voshk** [comment]
Same issue on Mac OS Big sur...

**Comment by shepting** [comment]
My coworker was able to work around this issue in case others are looking for a temporary workaround: https://github.com/airbnb/buck/pull/24/files

**Comment by rootblack45** [comment]
Any update for Mac OS Big Sur?

**Comment by brettwooldridge** [comment]
@v-jizhang @kageiit All of the developers in my company are broken as of today. Any help?

**Comment by rootblack45** [comment]
@brettwooldridge Found an update for Big Sur [here](https://github.com/facebook/buck/commit/a2912b9c46bba1dc1b317d8532a5e04d3aa52389). Just wait for the next release of Buck.

**Comment by brettwooldridge** [comment]
@rootblack45 That code is on the *dev* branch. Even before your comment, I suspected the issue was likely fixed on *dev*, and attempted to build it. Unfortunately, I am unable to build *dev* locally because of #2416. See [my comment](https://github.com/facebook/buck/issues/2416#issuecomment-727240437) on that issue.

**Comment by EngineHG** [comment]
@brettwooldridge how to build the dev branch

**Comment by zion001** [comment]
> @rootblack45 That code is on the _dev_ branch. Even before your comment, I suspected the issue was likely fixed on _dev_, and attempted to build it. Unfortunately, I am unable to build _dev_ locally because of #2416. See [my comment](https://github.com/facebook/buck/issues/2416#issuecomment-727240437) on that issue.
> 
> EDIT: Nevermind, I solved the buck compilation issue. I was able to build the _dev_ branch, and it appears to work on Big Sur.

hi , may I bother to ask how did you get it .

**Comment by brettwooldridge** [comment]
@zion001 Using JDK 11.0.9+7-LTS...
```
cd buck
git checkout 0dd10c43474a5edd04e536cd1ac39948854d33a8
ant clean ; ant
./bin/buck build --config java.target_level=11 --config java.source_level=11 buck --show-output
```
