### ISSUE TITLE
com.facebook.buck.io.watchman.FileSystemNotWatchedException

### ISSUE THREAD

**Issue by qyang-nj** [facebook/buck#2494]
We recently upgraded our buck to the latest master (3283f1ca2bb3ce3aa809da5f516c42009ec3a1d9, to be exact), and ran into an issue with `buck targets //...` and a few other commands.

```
$ buck targets //...
Not using buckd because watchman isn't installed.
Buck encountered an internal error
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.io.watchman.FileSystemNotWatchedException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at com.facebook.buck.parser.TargetSpecResolver.groupSpecsByBuildFile(TargetSpecResolver.java:291)
	at com.facebook.buck.parser.TargetSpecResolver.resolveTargetSpecs(TargetSpecResolver.java:221)
	at com.facebook.buck.parser.ParserWithConfigurableAttributes.collectBuildTargetsFromTargetNodeSpecs(ParserWithConfigurableAttributes.java:352)
	at com.facebook.buck.parser.AbstractParser.buildTargetGraphForTargetNodeSpecs(AbstractParser.java:297)
	at com.facebook.buck.parser.AbstractParser.buildTargetGraphWithTopLevelConfigurationTargets(AbstractParser.java:281)
	at com.facebook.buck.cli.TargetsCommand.buildTargetGraphAndTargets(TargetsCommand.java:797)
	at com.facebook.buck.cli.TargetsCommand.runWithExecutor(TargetsCommand.java:514)
	at com.facebook.buck.cli.TargetsCommand.runWithoutHelp(TargetsCommand.java:369)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:281)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:90)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1448)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:476)
	at com.facebook.buck.cli.MainWithoutNailgun.main(MainWithoutNailgun.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)
Caused by: com.facebook.buck.io.watchman.FileSystemNotWatchedException
	at com.facebook.buck.core.parser.WatchmanBuildPackageComputation.<init>(WatchmanBuildPackageComputation.java:85)
	at com.facebook.buck.parser.TargetSpecResolver.lambda$createWithWatchmanCrawler$2(TargetSpecResolver.java:195)
	at com.facebook.buck.parser.TargetSpecResolver.lambda$new$0(TargetSpecResolver.java:114)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:154)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 22 more
```

It's only happening when watchman is not installed. From the documentation, watchman is recommended but not required, so it's not installed on our CI machines.

**Comment by v-jizhang** [comment]
@qyang-nj What is your platform please?

**Comment by qyang-nj** [comment]
@v-jizhang It's happening on both macOS 10.15.2 and 10.15.5, not sure about other versions.

**Comment by v-jizhang** [comment]
@qyang-nj, I could not create a repro but looked into the buck code. What I found is that without watchman, createWithFileSystemCrawler should be called but in your error log,  createWithWatchmanCrawler is called. That makes me think you have changed your .buckconfig file. Please check the `[project]` section and make sure build_file_search_method is either NOT defined or defined as `build_file_search_method = filesystem_crawl`
Hope this helps.

**Comment by qyang-nj** [comment]
@v-jizhang Aha, that's it. We currently set it to `watchman`, which explains the problem. After changing it to `filesystem_crawl`, the problem is fixed. But I swear we didn't see this crash in an early buck version (a commit in January).

Thanks a lot for the help. Feel free to close this.

**Comment by v-jizhang** [comment]
@qyang-nj  You are right, there is a commit in Jan. changed it. https://github.com/facebook/buck/commit/b269f54e853344d4772afe3a5e09a281c21cf6ed
