### ISSUE TITLE
Buck fails to build .pex binaries due to Python2 type hint syntax errors

### ISSUE THREAD

**Issue by ajrpeggio** [facebook/buck#2505]
Buck build recently started failing for me when I pushed a re-install of Python3.8 on my laptop. It make be worth noting that python 2to3 is also installed.

In the example, I created a prebuilt_python_library for aiohttp and am importing in to a binary. 

It appears that any code with **type hinting** cause build failures.

Output: 
```console
username@mylaptop$ buck build <scrub>/aiohttp:main
Invalidating internal cached state: Buck configuration options changed between invocations. This may cause slower builds.
  Removed value download.in_build='true'
Traceback (most recent call last):
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 328, in execute
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 261, in _wrap_coverage
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 293, in _wrap_profiling
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 371, in _execute
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 429, in execute_entry
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 434, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/src/com/facebook/buck/features/python/make_pex.py", line 193, in <module>
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/src/com/facebook/buck/features/python/make_pex.py", line 190, in main
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/pex_builder.py", line 402, in build
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/pex_builder.py", line 389, in freeze
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/pex_builder.py", line 332, in _precompile_source
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/compiler.py", line 102, in compile
pex.compiler.Error: Encountered 45 errors compiling 160 files:
  aiohttp/payload_streamer.py:   File "aiohttp/payload_streamer.py", line 37
    coro: Callable[..., Awaitable[None]],
        ^
SyntaxError: invalid syntax

  yarl/__init__.py:   File "yarl/__init__.py", line 136
    def __new__(cls, val="", *, encoded=False, strict=None):
                              ^
SyntaxError: invalid syntax

  aiohttp/web_urldispatcher.py:   File "aiohttp/web_urldispatcher.py", line 78
    def __init__(self, *, name: Optional[str]=None) -> None:
                        ^
SyntaxError: invalid syntax

  aiohttp/tracing.py:   File "aiohttp/tracing.py", line 55
    trace_config_ctx_factory: Type[SimpleNamespace]=SimpleNamespace
                            ^
SyntaxError: invalid syntax

  aiohttp/connector.py:   File "aiohttp/connector.py", line 80
    def __init__(self, awaitable: Awaitable[Any]) -> None:
                                ^
...
Deleted some syntax errors to save linespace
...
SyntaxError: invalid syntax

  aiohttp/worker.py:   File "aiohttp/worker.py", line 38
    def __init__(self, *args: Any, **kw: Any) -> None:  # pragma: no cover
                            ^
SyntaxError: invalid syntax

  aiohttp/http_parser.py:   File "aiohttp/http_parser.py", line 51
    HDRRE = re.compile(rb'[\x00-\x1F\x7F()<>@,;:\[\]={} \t\\\\\"]')
                                                                 ^
SyntaxError: invalid syntax

Parsing buck files: finished in 0.8 sec
Building: finished in 0.9 sec (100%) 8/8 jobs, 1 updated
  Total time: 1.8 sec
Command failed with exit code 1.

command: [/usr/bin/python2, /Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex, --python, /usr/bin/python2, --python-version, CPython 2.7, --entry-point, <scrub>>.aiohttp.main, buck-out/gen/<scrub>/aiohttp/main.pex]

stderr: Traceback (most recent call last):
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 328, in execute
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 261, in _wrap_coverage
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 293, in _wrap_profiling
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 371, in _execute
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 429, in execute_entry
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/.bootstrap/_pex/pex.py", line 434, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/src/com/facebook/buck/features/python/make_pex.py", line 193, in <module>
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/src/com/facebook/buck/features/python/make_pex.py", line 190, in main
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/pex_builder.py", line 402, in build
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/pex_builder.py", line 389, in freeze
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/pex_builder.py", line 332, in _precompile_source
  File "/Users/<scrub>/.buckd/resources/2020.06.29.01/buck-modules-resources/python/pex.pex/pex/compiler.py", line 102, in compile
pex.compiler.Error: Encountered 45 errors compiling 160 files:
  aiohttp/payload_streamer.py:   File "aiohttp/payload_streamer.py", line 37
    coro: Callable[..., Awaitable[None]],
        ^
SyntaxError: invalid syntax

  yarl/__init__.py:   File "yarl/__init__.py", line 136
    def __new__(cls, val="", *, encoded=False, strict=None):
                              ^
SyntaxError: invalid syntax

  aiohttp/web_urldispatcher.py:   File "aiohttp/web_urldispatcher.py", line 78
    def __init__(self, *, name: Optional[str]=None) -> None:
                        ^
SyntaxError: invalid syntax

  aiohttp/tracing.py:   File "aiohttp/tracing.py", line 55
    trace_config_ctx_factory: Type[SimpleNamespace]=SimpleNamespace
                            ^
SyntaxError: invalid syntax

  aiohttp/connector.py:   File "aiohttp/connector.py", line 80
    def __init__(self, awaitable: Awaitable[Any]) -> None:
                                ^
...
Deleted some syntax errors to save linespace
...
SyntaxError: invalid syntax

  aiohttp/worker.py:   File "aiohttp/worker.py", line 38
    def __init__(self, *args: Any, **kw: Any) -> None:  # pragma: no cover
                            ^
SyntaxError: invalid syntax

  aiohttp/http_parser.py:   File "aiohttp/http_parser.py", line 51
    HDRRE = re.compile(rb'[\x00-\x1F\x7F()<>@,;:\[\]={} \t\\\\\"]')
                                                                 ^
SyntaxError: invalid syntax



    When running <pex>.
    When building rule //<scrub>/aiohttp:main.
```

Laptop:
- MBPro 16" 2019
- macOS Catalina 10.15.6

Apps:

- python2:
-- 2.7.16

- python3:
-- 3.8.4

- 2to3:
-- 2to3
-- 2to3-
-- 2to3-2.7
-- 2to3-3
-- 2to3-3.8

**Comment by v-jizhang** [comment]
Looks like you are still using python2, could you try python3? Thanks

**Comment by ajrpeggio** [comment]
Jinlin,

Buck build is using python2 in the build process and I don’t have immediate control over that process in the build.

Sent from my iPhone

On Jul 27, 2020, at 5:19 PM, Jinlin Zhang <notifications@github.com> wrote:

﻿

Looks like you are still using python2, could you try python3? Thanks

**Comment by v-jizhang** [comment]
Buck may use py2 to run internal tools but you should see the target interpreter is p3 in the parameter list:
`--python, <path to python3>, --python-version, CPython 3.x.x`
Please create a py3 virtualenv, make sure "python --version" prints p3 version and run your build.
Thanks.

**Comment by ajrpeggio** [comment]
Interesting. I definitely see python2 options being used in the TARGET interpreter for aiohttp library. Here is the console text I have:

arasmussen@17354A-arasmussen zourcecode % python --version
Python 2.7.16
arasmussen@17354A-arasmussen zourcecode % python3 --version
Python 3.8.4
arasmussen@17354A-arasmussen zourcecode % python3 -m venv venv
arasmussen@17354A-arasmussen zourcecode % source venv/bin/activate
(venv) arasmussen@17354A-arasmussen zourcecode % python --version
Python 3.8.4
(venv) arasmussen@17354A-arasmussen zourcecode % buck fetch python/wheel/aiohttp:aiohttp
Action graph will be rebuilt because files have been added or removed.
Building: finished in 0.0 sec (100%) 7/7 jobs, 0 updated
  Total time: 0.0 sec
(venv) arasmussen@17354A-arasmussen zourcecode % buck build experimental/arasmussen/aiohttp:main
Invalidating internal cached state: Buck configuration options changed between invocations. This may cause slower builds.
  Removed value download.in_build='true'
Traceback (most recent call last):

 <same errors as above>

**Comment by v-jizhang** [comment]
I'll look into it. Thanks

**Comment by v-jizhang** [comment]
@ajrpeggio 
Please specify python interpreter in .buckconfig and try again. Thanks
```
[python#py3]
    interpreter = <path to py3>
```

**Comment by v-jizhang** [comment]
#2512 Make Python3 the default interpreter.

**Comment by ajrpeggio** [comment]
My buck config was already pointing to the python3 interpreter. I updated the header to match what you posted but build is still failing once it reaches type hinting. I'll keep following your PR to make python3 the default.

**Comment by ajrpeggio** [comment]
The PR to make python3 the default interp. fixed my issue. Thank you so much!
