### ISSUE TITLE
Buck fail to download mvn url file

### ISSUE THREAD

**Issue by tkruse** [facebook/buck#2516]
On Ubuntu 18.04.4. This used to work (using v2017.03.29.01):
```
prebuilt_jar(
  name = 'junit',
  binary_jar = ':junit-jar'
)

remote_file(
  name = 'junit-jar',
  sha1 = '4e031bb61df09069aeb2bffb4019e7a5034a4ee0',
  url = 'mvn:junit:junit:jar:4.11',
  out = 'junit.jar',
)
```

Now I get (with the same version of buck), on Ubuntu 18.0.4:
```
$ buck fetch //:junit
Unable to download: mvn:junit:junit:jar:4.11
BUILD FAILED: //:junit-jar failed with exit code -1:
curl
```

using buck v2017.03.29.01, v2017.05.31.01. Newer versions starting 2018 have different error:

```
$ buck fetch //:junit
[Errno 2] No such file or directory: '/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/ant-out/buck-info.json'
Traceback (most recent call last):
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/bin/../programs/buck.py", line 249, in <module>
    exit_code = main(sys.argv, reporter)
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/bin/../programs/buck.py", line 221, in main
    with get_repo(project) as buck_repo:
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/bin/../programs/buck.py", line 208, in get_repo
    return BuckRepo(THIS_DIR, p, reporter)
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/programs/buck_repo.py", line 61, in __init__
    super(BuckRepo, self).__init__(buck_project, buck_reporter)
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/programs/buck_tool.py", line 199, in __init__
    self._package_info = self._get_package_info()
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/programs/buck_repo.py", line 89, in _get_package_info
    return json.loads(self.__read_file(BUCK_INFO_LOCATION))
  File "/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/programs/buck_repo.py", line 92, in __read_file
    with open(os.path.join(self.buck_dir, filename)) as file:
IOError: [Errno 2] No such file or directory: '/home/kruset/work/java/build-bench/caches/buck/buckv2019.05.14.01/ant-out/buck-info.json'
```

For other versions, the missing file is e.g.: `buckv2018.02.16.01/build/buck-info.json`

**Comment by v-jizhang** [comment]
@tkruse 
You have to set maven_repo in .buckconfig under section [download], https://buck.build/files-and-dirs/buckconfig.html#download
```
[download]
    maven_repo = https://repo1.maven.org/maven2
    max_number_of_retries = 3
```

**Comment by tkruse** [comment]
Ah, it had been set to http://, not https://

**Comment by tkruse** [comment]
thanks
