### ISSUE TITLE
Lastest versions of Buck refuses to run in Docker

### ISSUE THREAD

**Issue by MuminKhan** [facebook/buck#2520]
Hello,

I had built a dockerfile that builds Buck against openjdk11. Something in recent builds broke it. 

Dockerfile:

```dockerfile
FROM openjdk:11

#ARG BUCK_VERSION="master"
ARG BUCK_VERSION="v2020.06.29.01"

RUN apt-get update && \
    apt-get install --yes \
        ant \
        build-essential \
        git \
        git-lfs \ 
        python3 \ 
        python3-pip && \ 
    apt-get clean && \
    mkdir -p /opt/local/java && \ 
    ln -s -T /usr/local/openjdk-11 /opt/local/java/jdk11

# Install buck
RUN wget https://github.com/facebook/buck/archive/${BUCK_VERSION}.tar.gz && \
    mkdir buck && \
    tar -xvf ${BUCK_VERSION}.tar.gz --directory buck --strip-components=1 && \  
    cd buck && \
    ant && \
    ./bin/buck build --show-output buck && \ 
    mv /buck/buck-out/gen/ce9b6f2e/programs/buck.pex /usr/local/bin/buck && \
    #ln -s /buck/bin/buck /usr/local/bin/buck && \
    cd / && \
    rm -f ${BUCK_VERSION}.tar.gz && \
    #rm -rf /buck && \
    buck --version

CMD ["bin/bash"]

```

I was just using the buck built by ant, and not the bootstrapped buck.pex. Running buck build results in:

```bash
root@17f37bc35e61:/workspaces/proj# buck build //...
Not using buckd because watchman isn't installed.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.Error: java.lang.NullPointerException
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:133)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:102)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:100)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:100)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:94)
        at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:182)
        at java.base/java.io.File.toPath(File.java:2292)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:813)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:758)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:751)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:750)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:725)
        at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:493)
        at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:476)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:475)
        at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:444)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:313)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:695)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
Caused by: java.lang.NullPointerException
        at java.base/java.io.File.toPath(File.java:2292)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:813)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:758)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:751)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:750)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:725)
        at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:493)
        at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:476)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:475)
        at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:444)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:313)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:695)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:123)
        ... 34 more
You're using Java 11, but Buck requires Java 8.
```

This should work, but I'm not sure what's gone wrong. I thought buck officially supports Java 11?

Also, the ant-built buck in `buck/bin/` reports `buck version v2018.06.25.01`...

**Comment by v-jizhang** [comment]
Have you set JAVA_HOME?

**Comment by MuminKhan** [comment]
Yes

```bash
root@17f37bc35e61:/buck/bin# echo $JAVA_HOME
/usr/local/openjdk-11
```

**Comment by v-jizhang** [comment]
"You're using Java 11, but Buck requires Java 8." means buck was built with java 8 and the running environment is java 11.
That suggests you have either built buck using java 8 or had another old version of buck in your PATH. Please check your docker configuration.

**Comment by MuminKhan** [comment]
Not possible, as the only java in that container is 11. It's pulled from `openjdk:11` which is Debian Buster. openjdk8 isn't even available in the standard repos.

**Comment by kageiit** [comment]
This is the problem `./bin/buck build --show-output buck && \ `

It should be `./bin/buck --config java.target_level=11 --config java.source_level=11 build --show-output buck && \ `

See https://github.com/facebook/buck/blob/master/jitpack.yml#L14 for example

**Comment by kageiit** [comment]
@v-jizhang It might be worth it to auto set these configs based on jdk

**Comment by v-jizhang** [comment]
Thank you @kageiit, I think it is already automated by setting JAVA_HOME. I'll double check.

**Comment by MuminKhan** [comment]
Maybe I'm missing something but the command that @kageiit recommended doesn't work:

```
root@eb74c53355a5:/buck# ./bin/buck --config java.target_level=11 --config java.source_level=11 build --show-output buck
Not using buckd because watchman isn't installed.
BAD ARGUMENTS: "--config" is not a valid option
For help see 'buck --help'.
```

**Comment by v-jizhang** [comment]
`./bin/buck build --config java.target_level=11 --config java.source_level=11 --show-output buck`
`--config `is an option of `build`

**Comment by kageiit** [comment]
> Maybe I'm missing something but the command that @kageiit recommended doesn't work:
> 
> ```
> root@eb74c53355a5:/buck# ./bin/buck --config java.target_level=11 --config java.source_level=11 build --show-output buck
> Not using buckd because watchman isn't installed.
> BAD ARGUMENTS: "--config" is not a valid option
> For help see 'buck --help'.
> ```

oops. missed the `build` command. Edited now. Seems like @v-jizhang already came to the rescue :)

**Comment by MuminKhan** [comment]
Thank you @v-jizhang, @kageiit that seems to have fixed it. Any idea why the version number remains wrong though? 

`buck version v2018.06.25.01`

**Comment by v-jizhang** [comment]
Ah, that's a bug in the last release. the file .buckrelease should be updated.
