### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shaomaicheng** [facebook/buck#2524]
mac os, JAVA_HOME is jdk 1.8:

```shell
$echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home
```

use

```
./bin/buck build --show-output buck
```
command. but has a error:

```
 buck ./bin/buck build --show-output buck
Buck encountered an internal error
com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: com/facebook/buck/remoteexecution/proto/RESessionID has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at com.facebook.buck.core.config.ConfigViewCache.getView(ConfigViewCache.java:46)
	at com.facebook.buck.core.config.BuckConfig.getView(BuckConfig.java:101)
	at com.facebook.buck.cli.MainRunner.isRemoteExecutionAutoEnabled(MainRunner.java:1785)
	at com.facebook.buck.cli.MainRunner.isRemoteExecutionBuild(MainRunner.java:1796)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:762)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:476)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
Caused by: java.lang.UnsupportedClassVersionError: com/facebook/buck/remoteexecution/proto/RESessionID has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.facebook.buck.core.config.ConfigViewCache$ConfigViewCacheLoader.load(ConfigViewCache.java:67)
	at com.facebook.buck.core.config.ConfigViewCache$ConfigViewCacheLoader.load(ConfigViewCache.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 17 more
```

I use `ant` to compiler buck use jdk1.8. because if my JAVA_HOME is not 1.8. ant build has error, so  I use 52 and  ant build success.

so, why this command tell me I used 57 version ???

**Comment by v-jizhang** [comment]
Please try `ant clean `and rerun `ant` build. Please make sure `javac -version ` prints java 1.8.

**Comment by shaomaicheng** [comment]
![image](https://user-images.githubusercontent.com/11388037/90582585-a6878c80-e200-11ea-960f-99ee94d7d365.png)
![image](https://user-images.githubusercontent.com/11388037/90582620-bdc67a00-e200-11ea-94c2-f8830f9621b3.png)

also can not work success, so why?

**Comment by v-jizhang** [comment]
That's weird. Let's do this, delete the `ant-out `and try again.
`rm -r -f ant-out`

**Comment by shaomaicheng** [comment]
it can resloive， but when i build success and follow the document to the next step:
```
./bin/buck build --show-output buck
```

i have a new problem:

![image](https://user-images.githubusercontent.com/11388037/90707230-b028f700-e2c9-11ea-9cbf-798f4f5f7e49.png)

how can I resolve this?

**Comment by v-jizhang** [comment]
It's an old issue that I'm unable to repro. If you just want use buck, install the binary would be adequate for you:
```
brew tap facebook/fb
brew install buck
```
I'll continue keep an eye on this issue. Thanks

**Comment by shaomaicheng** [comment]
ok, thaks 👍
