### ISSUE TITLE
Error using watchman

### ISSUE THREAD

**Issue by amitkot** [facebook/buck#261]
I followed the Quickstart guide and after creating the project ran:
```
buck install app
```

Getting this message:
```
Not using buckd because watchman isn't installed.
```

I followed by installing `watchman` as instructed:
```
brew install --HEAD watchman
```

Now, running `buck install app` I'm getting:
```
Using watchman.
1424790001: tid=2072961792 unable to talk to your watchman on /usr/local/Cellar/watchman/HEAD/var/run/watchman/amit!
Traceback (most recent call last):
  File "/opt/buck/bin/../programs/buck.py", line 52, in <module>
    sys.exit(main(sys.argv))
  File "/opt/buck/bin/../programs/buck.py", line 45, in main
    return buck_repo.launch_buck(build_id)
  File "/opt/buck/programs/buck_tool.py", line 122, in launch_buck
    self.launch_buckd(buck_version_uid=buck_version_uid)
  File "/opt/buck/programs/buck_tool.py", line 169, in launch_buckd
    self._setup_watchman_watch()
  File "/opt/buck/programs/buck_tool.py", line 303, in _setup_watchman_watch
    stderr=subprocess.STDOUT)
  File "/opt/buck/programs/buck_tool.py", line 476, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
buck_tool.CalledProcessError: Command '['watchman', 'watch', '/private/tmp/ccc']' returned non-zero exit status 1
```

**Comment by Coneko** [comment]
Can you try to install `brew install watchman` to install the stable version?

**Comment by amitkot** [comment]
With the stable version I'm getting this error:

```
$ buck build app
                                   ⏎
Using watchman.
/Users/amit/Library/LaunchAgents/com.github.facebook.watchman.plist:
Operation already in progress
1425199381: tid=2072961792 unable to talk to your watchman!
Traceback (most recent call last):
  File "/opt/buck/bin/../programs/buck.py", line 52, in <module>
    sys.exit(main(sys.argv))
  File "/opt/buck/bin/../programs/buck.py", line 45, in main
    return buck_repo.launch_buck(build_id)
  File "/opt/buck/programs/buck_tool.py", line 122, in launch_buck
    self.launch_buckd(buck_version_uid=buck_version_uid)
  File "/opt/buck/programs/buck_tool.py", line 169, in launch_buckd
    self._setup_watchman_watch()
  File "/opt/buck/programs/buck_tool.py", line 303, in _setup_watchman_watch
    stderr=subprocess.STDOUT)
  File "/opt/buck/programs/buck_tool.py", line 476, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
buck_tool.CalledProcessError: Command '['watchman', 'watch',
'/private/tmp/ddd/trial']' returned non-zero exit status 1
```

**Comment by amitkot** [comment]
With the stable version I'm getting this error:

```bash
$ buck build app
Using watchman.
/Users/amit/Library/LaunchAgents/com.github.facebook.watchman.plist:
Operation already in progress
1425199381: tid=2072961792 unable to talk to your watchman!
Traceback (most recent call last):
  File "/opt/buck/bin/../programs/buck.py", line 52, in <module>
    sys.exit(main(sys.argv))
  File "/opt/buck/bin/../programs/buck.py", line 45, in main
    return buck_repo.launch_buck(build_id)
  File "/opt/buck/programs/buck_tool.py", line 122, in launch_buck
    self.launch_buckd(buck_version_uid=buck_version_uid)
  File "/opt/buck/programs/buck_tool.py", line 169, in launch_buckd
    self._setup_watchman_watch()
  File "/opt/buck/programs/buck_tool.py", line 303, in _setup_watchman_watch
    stderr=subprocess.STDOUT)
  File "/opt/buck/programs/buck_tool.py", line 476, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
buck_tool.CalledProcessError: Command '['watchman', 'watch',
'/private/tmp/ddd/trial']' returned non-zero exit status 1
```

**Comment by bolinfest** [comment]
In any event, I think we want to drop --HEAD from the docs. I'm pretty sure
our fixes are in brew now.

**Comment by amitkot** [comment]
Any idea why this doesn't work, or what workaround can I use?

**Comment by Coneko** [comment]
Have you tried rebooting your computer?

What does `watchman watch-list` show?

**Comment by amitkot** [comment]
@Coneko After reboot it works using stable version. Thanks!
