### ISSUE TITLE
make_pex.py failed on Building in WSL:Ubuntu

### ISSUE THREAD

**Issue by mh884** [facebook/buck#2635]
Build the project by using ./bin/buck build --show-output buck it throw error 
common.py should handle the permission but for some reason there is something is not right  
Python 3.8.5
buck version 87135f8e0de092a6be12736c5254c0c125a2b238

`Building: finished in 4.1 sec (100%) 202/1853 jobs, 77 updated
  Total time: 4.1 sec
Command failed with exit code 1.

command: [/usr/bin/python3, /mnt/c/buck/ant-out/buck-modules-resources/python/make_pex.py, --python-shebang=/usr/bin/env python3, --python, /usr/bin/python3, --python-version, CPython 3.8, --entry-point, programs.gen_buck_info, buck-out/gen/ce9b6f2e/programs/gen_buck_info.pex]

stderr: Traceback (most recent call last):
  File "/mnt/c/buck/ant-out/buck-modules-resources/python/make_pex.py", line 193, in <module>
    sys.exit(main())
  File "/mnt/c/buck/ant-out/buck-modules-resources/python/make_pex.py", line 190, in main
    pex_builder.build(output)
  File "/mnt/c/buck/third-party/py/pex/pex/pex_builder.py", line 418, in build
    chmod_plus_x(filename)
  File "/mnt/c/buck/third-party/py/pex/pex/common.py", line 153, in chmod_plus_x
    os.chmod(path, path_mode)
PermissionError: [Errno 1] Operation not permitted: 'buck-out/gen/ce9b6f2e/programs/gen_buck_info.pex'

    When running <pex>.
    When building rule //programs:gen_buck_info.`

**Comment by KapJI** [comment]
Basically chmod on `buck-out/gen/ce9b6f2e/programs/gen_buck_info.pex` failed. Can you check file permissions on that file? Who owns it? Can your current user modify permissions of that file?
