### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by terryyhl** [facebook/buck#314]
BUILD FAILED: Google APIs not found in /Users/terryyhl/Documents/adt-bundle-mac-x86_64-20131030/sdk/add-ons/addon-google_apis-google-21/libs.
Please run '/Users/terryyhl/Documents/adt-bundle-mac-x86_64-20131030/sdk/tools/android sdk' and select both 'SDK Platform' and 'Google APIs' under Android (API 21)
yanghailongdeMacBook-Air:115office terryyhl$ buck test
Not using buckd because watchman isn't installed.
[+] PARSING BUCK FILES...1.7s
Traceback (most recent call last):
  File "/Users/terryyhl/Documents/CompanySource/115office/buck-out/tmp/buck_run.ZyRYYG/buck974033061923600364.py", line 1423, in <module>
    main()
  File "/Users/terryyhl/Documents/CompanySource/115office/buck-out/tmp/buck_run.ZyRYYG/buck974033061923600364.py", line 495, in main
    values = buildFileProcessor.process(build_file.rstrip())
  File "/Users/terryyhl/Documents/CompanySource/115office/buck-out/tmp/buck_run.ZyRYYG/buck974033061923600364.py", line 407, in process
    implicit_includes=self._implicit_includes)
  File "/Users/terryyhl/Documents/CompanySource/115office/buck-out/tmp/buck_run.ZyRYYG/buck974033061923600364.py", line 399, in _process_build_file
    implicit_includes=implicit_includes)
  File "/Users/terryyhl/Documents/CompanySource/115office/buck-out/tmp/buck_run.ZyRYYG/buck974033061923600364.py", line 363, in _process
    exec(code, module.__dict__)
  File "/Users/terryyhl/Documents/CompanySource/115office/BUCK", line 1, in <module>
    va_library(
NameError: name 'va_library' is not defined
[2015-05-26 16:28:36.650][error][command:2a980498-2ec5-4616-8556-123bca8f9db2][tid:01][com.facebook.buck.json.ProjectBuildFileParser] Process java.lang.UNIXProcess@be64738 exited with error code 1
BUILD FAILED: Parse error for build file /Users/terryyhl/Documents/CompanySource/115office/BUCK: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was END_DOCUMENT at line 1 column 1667

**Comment by marcinkosiba** [comment]
Looks like you have a syntax error in '/Users/terryyhl/Documents/CompanySource/115office/BUCK' line 1. NameError: name 'va_library' is not defined. Did you accidentally delete some characters? Should line 1 be `java_library` instead?

Can't really help you other than that as your bug report doesn't contain any way to reproduce your issue/

**Comment by marcinkosiba** [comment]
assuming this is solved. If not please provide repro steps.
