### ISSUE TITLE
docs/soyweb-local.sh can't find globals.json

### ISSUE THREAD

**Issue by bmihai** [facebook/buck#315]
Commit 98c6630471f introduced a change that makes running `docs/soyweb-local.sh` fail with
    ```Exception in thread "main" java.lang.RuntimeException: Could not find file: /globals.json
at org.plovr.cli.SoyWebCommand.runCommandWithOptions(SoyWebCommand.java:34)
at org.plovr.cli.SoyWebCommand.runCommandWithOptions(SoyWebCommand.java:18)
at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
at org.plovr.cli.Command.execute(Command.java:47)
at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
at org.plovr.cli.Main.main(Main.java:30)```
This seems to still be a problem at commit 5eef2cf1609d75529.

**Comment by sdwilsh** [comment]
Whoops.  I *almost* had the right fix there.  If you modify that script to replace the last line with `java -jar plovr-81ed862.jar soyweb --dir . --globals docs/globals.json`, that should unblock you.  I'll get a fix out soon.

**Comment by sdwilsh** [comment]
Actually, that should just be `java -jar plovr-81ed862.jar soyweb --dir . --globals globals.json`

**Comment by bmihai** [comment]
Yup, that works! Thank you.

(I'll let you close the bug report when you wish, in case you want the report to stay up until the fix is made public).

**Comment by sdwilsh** [comment]
Yeah, the fix should go out tomorrow and the commit will close the issue.  Sorry about that!
