### ISSUE TITLE
New android tools: parsing version string "23.0.0_rc1"

### ISSUE THREAD

**Issue by zserge** [facebook/buck#326]
I've updated all android tools today and now when trying to build the project with Buck I get the following exception:

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Invalid version string: 23.0.0_rc1
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.facebook.buck.command.Build.executeBuild(Build.java:239)
        at com.facebook.buck.command.Build.executeAndPrintFailuresToConsole(Build.java:270)
        at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:329)
        at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:127)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:133)
        at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:652)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:985)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1042)
        at com.facebook.buck.cli.Main.nailMain(Main.java:1071)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.lang.RuntimeException: Invalid version string: 23.0.0_rc1
        at com.facebook.buck.util.VersionStringComparator.compare(VersionStringComparator.java:36)
        at com.facebook.buck.android.AndroidPlatformTarget$3.compare(AndroidPlatformTarget.java:334)
        at com.facebook.buck.android.AndroidPlatformTarget$3.compare(AndroidPlatformTarget.java:1)
        at java.util.TimSort.binarySort(TimSort.java:292)
        at java.util.TimSort.sort(TimSort.java:217)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at java.util.Collections.sort(Collections.java:175)
        at com.facebook.buck.android.AndroidPlatformTarget.pickNewestBuildToolsDir(AndroidPlatformTarget.java:329)
        at com.facebook.buck.android.AndroidPlatformTarget.createFromDefaultDirectoryStructure(AndroidPlatformTarget.java:271)
        at com.facebook.buck.android.AndroidPlatformTarget$AndroidWithGoogleApisFactory.newInstance(AndroidPlatformTarget.java:408)
        at com.facebook.buck.android.AndroidPlatformTarget.getTargetForId(AndroidPlatformTarget.java:196)
        at com.facebook.buck.cli.Main$1.get(Main.java:749)
        at com.facebook.buck.cli.Main$1.get(Main.java:1)
        at com.facebook.buck.step.ExecutionContext.getAndroidPlatformTarget(ExecutionContext.java:170)
        at com.facebook.buck.android.AaptStep.getShellCommandInternal(AaptStep.java:94)
        at com.facebook.buck.shell.ShellStep.getShellCommand(ShellStep.java:202)
        at com.facebook.buck.shell.ShellStep.getDescription(ShellStep.java:233)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:56)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:616)
        at com.facebook.buck.rules.CachingBuildEngine.buildOnceDepsAreBuilt(CachingBuildEngine.java:431)
        at com.facebook.buck.rules.CachingBuildEngine.access$3(CachingBuildEngine.java:349)
        at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:202)
        at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:1)
        at com.facebook.buck.util.concurrent.MoreFutures$1.onSuccess(MoreFutures.java:130)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Looks like the regexp used in VersionStringComparator doesn't fit for the new versioning format.

**Comment by zserge** [comment]
Moreover, the structure in $ANDROID_HOME/build-tools/23.0.0_rc1 has been changed, too.
For example they have moved aapt into bin subdirectory.

**Comment by sdwilsh** [comment]
This isn't the first time they have broken this for us.  I'll get a fix up soon.

**Comment by sdwilsh** [comment]
Through a series of patches, I have the fix landed internally.  It'll go out Wednesday.

**Comment by sdwilsh** [comment]
Thanks for the report.  Let me know if you are having trouble with it still.

**Comment by kargs** [comment]
I've just tried the quickstart and I experienced the same issue, but the version string is `latest` instead. Seems like it's a symlink in my SDK:

```
➜  buck-quickstart  ls -la $ANDROID_HOME/build-tools/
total 8
drwxr-xr-x   5 kargs  staff  170 May 13 17:25 .
drwxr-xr-x  12 kargs  staff  408 Jun 24 09:00 ..
drwxr-xr-x  20 kargs  staff  680 Feb  9 16:09 20.0.0
drwxr-xr-x  26 kargs  staff  884 Feb  3 14:24 21.1.2
lrwxr-xr-x   1 kargs  staff    6 May 13 17:25 latest -> 21.1.2
```

**Comment by sdwilsh** [comment]
@kargs - what version of Buck are you using?

**Comment by kargs** [comment]
@sdwilsh I just followed the quickstart instructions at http://buckbuild.com/setup/quick_start.html, so I assume today's master.
