### ISSUE TITLE
Update the exopackage walkthrough to work with the latest version of Buck

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#355]
I am doing the Exopackage walkthrough.

I tried using the fully complete project and attempting to install the project:

```python
git checkout 340814588800efdd06d147ebfb04005dd4070f92
cp ~/.android/debug.keystore keystore/debug.keystore
buck install --run antennapod
```

However I get an error output:

```java
[+] PARSING BUCK FILES...0.2s
Traceback (most recent call last):
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/buck-out/tmp/buck_run._BrpqT/buck4138158139799913581.py", line 1455, in <module>
    main()
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/buck-out/tmp/buck_run._BrpqT/buck4138158139799913581.py", line 501, in main
    values = buildFileProcessor.process(build_file.rstrip())
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/buck-out/tmp/buck_run._BrpqT/buck4138158139799913581.py", line 413, in process
    implicit_includes=self._implicit_includes)
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/buck-out/tmp/buck_run._BrpqT/buck4138158139799913581.py", line 405, in _process_build_file
    implicit_includes=implicit_includes)
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/buck-out/tmp/buck_run._BrpqT/buck4138158139799913581.py", line 369, in _process
    exec(code, module.__dict__)
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/BUCK", line 129, in <module>
    ':application-lib',
  File "/Users/anthonyuccello/Desktop/androidTests/AntennaPod/buck-out/tmp/buck_run._BrpqT/buck4138158139799913581.py", line 95, in invoke
    return self.func(*args, **updated_kwargs)
TypeError: android_binary() got an unexpected keyword argument 'target'
[2015-06-18 16:53:58.260][error][command:f00dfb58-8f4c-46d3-80f1-0a3a355da000][tid:01][com.facebook.buck.json.ProjectBuildFileParser] Process java.lang.UNIXProcess@30b7c004 exited with error code 1
BUILD FAILED: Parse error for build file /Users/anthonyuccello/Desktop/androidTests/AntennaPod/BUCK: End of input at line 1 column 1
```

**Comment by k21** [comment]
The `android_binary` no longer accepts the `target` parameter, you should instead [specify it in .buckconfig](http://buckbuild.com/concept/buckconfig.html#android). Can you please tell us where you found the walkthrough you are following so we can update it as appropriate?

**Comment by sdwilsh** [comment]
It's at http://buckbuild.com/article/exopackage.html

**Comment by AnthonyUccello** [comment]
Its also missing the localproperties file to point to the Android SDK.

Even after removing target from the binary, setting the Android SDK path I get this error output when I run buck install --run antennapod

```
buck install --run antennapod
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.2s
[-] BUILDING...FINISHED 8.3s (52/54 JOBS, 40 UPDATED, 0.0% CACHE HITS)
[+] INSTALLING...1.0s
Log:
built APK for //:antennapod at buck-out/gen/antennapod.apk
BUILD FAILED: Failed: install exopackage
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to install exopackage on ZX1G22HW4P
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.facebook.buck.cli.AdbHelper.adbCall(AdbHelper.java:294)
	at com.facebook.buck.cli.ExopackageInstaller.install(ExopackageInstaller.java:154)
	at com.facebook.buck.cli.InstallCommand.installApk(InstallCommand.java:213)
	at com.facebook.buck.cli.InstallCommand.runWithoutHelp(InstallCommand.java:164)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:133)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:654)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:989)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1046)
	at com.facebook.buck.cli.Main.main(Main.java:1064)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:48)
Caused by: java.lang.RuntimeException: Failed to install exopackage on ZX1G22HW4P
	at com.facebook.buck.cli.ExopackageInstaller$1.call(ExopackageInstaller.java:161)
	at com.facebook.buck.cli.AdbHelper$AdbCallable$1.call(AdbHelper.java:360)
	at com.facebook.buck.cli.AdbHelper$AdbCallable$1.call(AdbHelper.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.cli.AdbHelper$CommandFailedException: Command 'pm path com.facebook.buck.android.agent && dumpsys package com.facebook.buck.android.agent' failed with code 1.  Output:

	at com.facebook.buck.cli.AdbHelper.checkReceiverOutput(AdbHelper.java:477)
	at com.facebook.buck.cli.AdbHelper.executeCommandWithErrorChecking(AdbHelper.java:460)
	at com.facebook.buck.cli.ExopackageInstaller$SingleDeviceInstaller.getPackageInfo(ExopackageInstaller.java:389)
	at com.facebook.buck.cli.ExopackageInstaller$SingleDeviceInstaller.installAgentIfNecessary(ExopackageInstaller.java:401)
	at com.facebook.buck.cli.ExopackageInstaller$SingleDeviceInstaller.doInstall(ExopackageInstaller.java:207)
	at com.facebook.buck.cli.ExopackageInstaller$1.call(ExopackageInstaller.java:159)
	... 6 more
```

**Comment by sdwilsh** [comment]
What phone are you running on?  Samsung devices, in particular, do 
things very differently than everything else out there :/

**Comment by AnthonyUccello** [comment]
While Samsung has always been a thorn in my side, this one is a Nexus 6.

**Comment by sdwilsh** [comment]
@natthu - any idea why the agent isn't already available?

**Comment by natthu** [comment]
Fixed in 755b86bb1cb4db447a3358b03248a3b7ccae8aaa .

**Comment by Stoff81** [comment]
Hey @k21 Im just running through this tutorial: https://buckbuild.com/setup/manual_quick_start.html and am getting the same error. You may want to update this doc as well.

**Comment by k21** [comment]
Thanks @Stoff81, you are right, I have filed #681 for that.
