### ISSUE TITLE
Invalid resource type '<public>' in '/res/values/public.xml'

### ISSUE THREAD

**Issue by youyuo** [facebook/buck#372]
I have run into problem when I use buck compile my project,
and below is the 'public.xml' file contents,the command I have run,the error informatiom.
thank you~

'public.xml' file contents:
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <public id="0x7f080023" name="string1" type="id"/>
    <public id="0x7f080024" name="string2" type="id"/>
    <public id="0x7f080025" name="string3" type="id" />
</resources>

command: buck build app

error:
com.facebook.buck.android.aapt.MiniAapt$ResourceParseException: Invalid resource type '<public>' in '/res/values/public.xml'.
	at com.facebook.buck.android.aapt.MiniAapt.processValuesFile(MiniAapt.java:320)
	at com.facebook.buck.android.aapt.MiniAapt.processValues(MiniAapt.java:264)
	at com.facebook.buck.android.aapt.MiniAapt.collectResources(MiniAapt.java:219)
	at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:140)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:62)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:616)
	at com.facebook.buck.rules.CachingBuildEngine.buildOnceDepsAreBuilt(CachingBuildEngine.java:431)
	at com.facebook.buck.rules.CachingBuildEngine.access$3(CachingBuildEngine.java:349)
	at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:202)
	at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:1)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onSuccess(MoreFutures.java:130)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
BUILD FAILED: //app:res failed with exit code 1:
generate_resource_ids

**Comment by youyuo** [comment]
I found this code in file 'MiniAapt.java'
if (!RESOURCE_TYPES.containsKey(resourceType)) {
          throw new ResourceParseException(
              "Invalid resource type '<%s>' in '%s'.",
              resourceType,
              valuesFile);
        }

**Comment by sdwilsh** [comment]
Just so I understand it, you have an xml file that just contains ` <?xml version="1.0" encoding="utf-8"?>`?

**Comment by youyuo** [comment]
The other xml file in my project is all contains <?xml version="1.0" encoding="utf-8"?>, and they didn't throw exception. If I delete the 'public.xml' file,the project can compile successfully and run correct,just the project will crash when I click some function.

By the way, does buck support utf-8 code?
Because my project has some chinese，and when my compile with buck will have below warning:
....../test.java:62: ??: ??ASCII???????* ??????????????????????????????????test?????????????????????????????????????????????????????????????
thank you for your answer~~

**Comment by youyuo** [comment]
I just found that the public.xml is copy error,and the content is like that:
<?xml version="1.0" encoding='utf-8'?>
<resources>
    <public id="0x7f080023" name="string1" type="id" />
     <public id="0x7f080024" name="string2" type="id" />
      <public id="0x7f080025" name="string3" type="id" />
</resources>

And I just trid change the encoding to 'us-ascii',also have the same error.

**Comment by youyuo** [comment]
<?xml version="1.0" encoding="utf-8"?>
<resources>  
    <public id="0x7f080023" name="string1" type="id" />
     <public id="0x7f080024" name="string2" type="id" />
      <public id="0x7f080025" name="string3" type="id" />
</resources>

**Comment by nayrmi** [comment]
Closing issue since it was a copy error. Thanks!
