### ISSUE TITLE
android_prebuilt_aar attrs from R.txt missing

### ISSUE THREAD

**Issue by tgummerer** [facebook/buck#375]
I've been trying to use the new design library in a project, but it keeps crashing, because some resources can not be found, resulting in the following exception.  The resources seem to be only declared in the R.txt file in the aar.

I think it is different from #367, as buck compiles the project just fine, but can't find some of the resources afterwards.

```
E/AndroidRuntime( 2579): java.lang.NoSuchFieldError: android.support.design.R$attr.colorControlHighlight
E/AndroidRuntime( 2579): 	at android.support.design.internal.NavigationMenuItemView.createDefaultBackground(NavigationMenuItemView.java:77)
E/AndroidRuntime( 2579): 	at android.support.design.internal.NavigationMenuItemView.initialize(NavigationMenuItemView.java:65)
E/AndroidRuntime( 2579): 	at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.getView(NavigationMenuPresenter.java:286)
E/AndroidRuntime( 2579): 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
E/AndroidRuntime( 2579): 	at android.widget.AbsListView.obtainView(AbsListView.java:2033)
E/AndroidRuntime( 2579): 	at android.widget.ListView.makeAndAddView(ListView.java:1772)
E/AndroidRuntime( 2579): 	at android.widget.ListView.fillDown(ListView.java:672)
E/AndroidRuntime( 2579): 	at android.widget.ListView.fillFromTop(ListView.java:732)
E/AndroidRuntime( 2579): 	at android.widget.ListView.layoutChildren(ListView.java:1625)
E/AndroidRuntime( 2579): 	at android.widget.AbsListView.onLayout(AbsListView.java:1863)
````

**Comment by marcinkosiba** [comment]
Could you provide repro steps? I've seen an aar-related change that Shawn landed recently that could help.

**Comment by tgummerer** [comment]
I've uploaded a small sample repository with which it is possible to reproduce: https://github.com/tgummerer/aar_repro.  Running `buck install --run app`, with the latest master of buck, the app crashes immediately with the above exception.

**Comment by tgummerer** [comment]
I now tried to update the design library to version 22.2.1, but that seems to make things even worse.  That version fails at the compilation step with:

```
$ buck build lib:design-library
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[+] BUILDING...0.6s (4/8 JOBS, 2 UPDATED, 0.0% CACHE HITS)
 |=> IDLE
 |=> //lib:design-library#aar_android_resource...  0.1s (running generate_resource_ids[0.0s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
[2015-07-23 16:19:54.586][error][command:30dace5d-e02a-4b63-aa4c-e4b4946f3d91][tid:15][com.facebook.buck.event.listener.LoggingBuildListener] The following resources were not found when processing buck-out/bin/lib/__unpack_design-library#aar_unzip__/res: 
RDotTxtEntry{idType=int, type=style, name=TextAppearance_AppCompat_Body2, idValue=0x00000000}

java.lang.RuntimeException
java.lang.RuntimeException
	at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:151)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:62)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:730)
	at com.facebook.buck.rules.CachingBuildEngine.access$4(CachingBuildEngine.java:705)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:272)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //lib:design-library#aar_android_resource failed with exit code 1:
generate_resource_ids
```

**Comment by sdwilsh** [comment]
I think 0cbe56eaa53ed346bc51d122099de3fa1530d8c1 will fix this for you, but let us know!

**Comment by tgummerer** [comment]
@sdwilsh thanks for looking into it.  Unfortunately it doesn't fix my problem yet.  I'm trying to look into it myself now, as I'm kind of blocked on this, and it seems it has more to do with #367 and #328 than I thought.  I think the problem is that the resources are defined in the appcompat library, but used in the design library.  So far I've managed to fix the compilation failure, which turned out to be pretty simple to fix, but the app still crashes.  I'll update if I have more, and any pointers are appreciated :)

```diff
diff --git a/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java b/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java
index d5c1cb5..c434c61 100644
--- a/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java
+++ b/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java
@@ -159,7 +159,7 @@ public class AndroidPrebuiltAarDescription
         /* buildTarget */ BuildTargets.createFlavoredBuildTarget(
             params.getBuildTarget().checkUnflavored(),
             ImmutableFlavor.of("aar_android_resource")),
-        /* declaredDeps */ Suppliers.ofInstance(ImmutableSortedSet.<BuildRule>of()),
+        /* declaredDeps */ Suppliers.ofInstance(deps),
         /* extraDeps */ Suppliers.ofInstance(ImmutableSortedSet.<BuildRule>of(unzipAar)));
 
     return new AndroidResource(
```

**Comment by tgummerer** [comment]
So I think I fixed the problem locally.  The diff is below.  I'm not sure this is the best way to solve the problem, but if it looks acceptable, I'll clean it up and turn it into a pull request.

```diff
diff --git a/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java b/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java
index d5c1cb5..255d90e 100644
--- a/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java
+++ b/src/com/facebook/buck/android/AndroidPrebuiltAarDescription.java
@@ -106,7 +106,11 @@ public class AndroidPrebuiltAarDescription
             pathResolver,
             ImmutableSortedSet.<BuildRule>copyOf(javaDeps)));
     AndroidResource androidResource = buildRuleResolver.addToIndex(
-        createAndroidResource(unzipAar, params, pathResolver));
+        createAndroidResource(
+            unzipAar,
+            params,
+            pathResolver,
+            buildRuleResolver.getAllRules(args.deps.get())));
     return buildRuleResolver.addToIndex(new AndroidPrebuiltAar(
         /* androidLibraryParams */ params.copyWithDeps(
             /* declaredDeps */ Suppliers.ofInstance(ImmutableSortedSet.<BuildRule>of(
@@ -154,12 +158,13 @@ public class AndroidPrebuiltAarDescription
   private AndroidResource createAndroidResource(
       AndroidPrebuiltAarGraphEnhancer.UnzipAar unzipAar,
       BuildRuleParams params,
-      SourcePathResolver resolver) {
+      SourcePathResolver resolver,
+      ImmutableSortedSet<BuildRule> deps) {
     BuildRuleParams buildRuleParams = params.copyWithChanges(
         /* buildTarget */ BuildTargets.createFlavoredBuildTarget(
             params.getBuildTarget().checkUnflavored(),
             ImmutableFlavor.of("aar_android_resource")),
-        /* declaredDeps */ Suppliers.ofInstance(ImmutableSortedSet.<BuildRule>of()),
+        /* declaredDeps */ Suppliers.ofInstance(deps),
         /* extraDeps */ Suppliers.ofInstance(ImmutableSortedSet.<BuildRule>of(unzipAar)));
 
     return new AndroidResource(
diff --git a/src/com/facebook/buck/android/AndroidResource.java b/src/com/facebook/buck/android/AndroidResource.java
index abb640a..f0e5804 100644
--- a/src/com/facebook/buck/android/AndroidResource.java
+++ b/src/com/facebook/buck/android/AndroidResource.java
@@ -44,6 +44,7 @@ import com.facebook.buck.step.Step;
 import com.facebook.buck.step.fs.MakeCleanDirectoryStep;
 import com.facebook.buck.util.HumanReadableException;
 import com.google.common.annotations.VisibleForTesting;
+import com.google.common.base.Function;
 import com.google.common.base.Optional;
 import com.google.common.base.Preconditions;
 import com.google.common.base.Supplier;
@@ -157,6 +158,16 @@ public class AndroidResource extends AbstractBuildRule
 
   private final AtomicReference<String> rDotJavaPackage;
 
+  private final Function<HasAndroidResourceDeps, Path> resourceDirectoryFunction =
+      new Function<HasAndroidResourceDeps, Path>() {
+        @Override
+        public Path apply(HasAndroidResourceDeps input) {
+          return Optional.fromNullable(input.getRes())
+          .transform(getResolver().getPathFunction())
+          .get();
+        }
+      };
+
   public AndroidResource(
       BuildRuleParams buildRuleParams,
       SourcePathResolver resolver,
@@ -317,9 +328,17 @@ public class AndroidResource extends AbstractBuildRule
         .transform(GET_RES_SYMBOLS_TXT)
         .toSet();
 
+    ImmutableList<Path> nonEmptyResourceDirs = FluentIterable.from(getNonEmptyResourceDeps())
+        .transform(resourceDirectoryFunction)
+        .toList();
+
+    ImmutableList.Builder<Path> resourceDirBuilder = ImmutableList.builder();
+    resourceDirBuilder.addAll(nonEmptyResourceDirs);
+    resourceDirBuilder.add(getResolver().getPath(res));
+
     steps.add(
         new MiniAapt(
-            getResolver().getPath(Preconditions.checkNotNull(res)),
+            resourceDirBuilder.build(),
             Preconditions.checkNotNull(pathToTextSymbolsFile),
             pathsToSymbolsOfDeps));
 
diff --git a/src/com/facebook/buck/android/aapt/MiniAapt.java b/src/com/facebook/buck/android/aapt/MiniAapt.java
index 0cbe909..a876889 100644
--- a/src/com/facebook/buck/android/aapt/MiniAapt.java
+++ b/src/com/facebook/buck/android/aapt/MiniAapt.java
@@ -92,16 +92,16 @@ public class MiniAapt implements Step {
     }
   };
 
-  private final Path resDirectory;
+  private final ImmutableList<Path> resDirectories;
   private final Path pathToTextSymbolsFile;
   private final ImmutableSet<Path> pathsToSymblolsOfDeps;
   private final AaptResourceCollector resourceCollector;
 
   public MiniAapt(
-      Path resDirectory,
+      ImmutableList<Path> resDirectories,
       Path pathToTextSymbolsFile,
       ImmutableSet<Path> pathsToSymblolsOfDeps) {
-    this.resDirectory = resDirectory;
+    this.resDirectories = resDirectories;
     this.pathToTextSymbolsFile = pathToTextSymbolsFile;
     this.pathsToSymblolsOfDeps = pathsToSymblolsOfDeps;
     this.resourceCollector = new AaptResourceCollector();
@@ -140,7 +140,7 @@ public class MiniAapt implements Step {
       collectResources(filesystem, context.getBuckEventBus());
       processXmlFilesForIds(filesystem, references);
     } catch (IOException | XPathExpressionException | ResourceParseException e) {
-      context.logError(e, "Error parsing resources to generate resource IDs for %s.", resDirectory);
+      context.logError(e, "Error parsing resources to generate resource IDs for %s.", resDirectories);
       return 1;
     }
 
@@ -150,12 +150,12 @@ public class MiniAapt implements Step {
         context.logError(
             new RuntimeException(),
             "The following resources were not found when processing %s: \n%s\n",
-            resDirectory,
+            resDirectories,
             Joiner.on('\n').join(missing));
         return 1;
       }
     } catch (IOException e) {
-      context.logError(e, "Error verifying resources for %s.", resDirectory);
+      context.logError(e, "Error verifying resources for %s.", resDirectories);
       return 1;
     }
 
@@ -202,25 +202,27 @@ public class MiniAapt implements Step {
    */
   private void collectResources(ProjectFilesystem filesystem, BuckEventBus eventBus)
       throws IOException, ResourceParseException {
-    Collection<Path> contents = filesystem.getDirectoryContents(resDirectory);
-    for (Path dir : contents) {
-      if (!filesystem.isDirectory(dir) && !filesystem.isIgnored(dir)) {
-        if (!shouldIgnoreFile(dir, filesystem)) {
-          eventBus.post(ConsoleEvent.warning("MiniAapt [warning]: ignoring file '%s'.", dir));
+    for (Path resDirectory : resDirectories) {
+      Collection<Path> contents = filesystem.getDirectoryContents(resDirectory);
+      for (Path dir : contents) {
+        if (!filesystem.isDirectory(dir) && !filesystem.isIgnored(dir)) {
+          if (!shouldIgnoreFile(dir, filesystem)) {
+            eventBus.post(ConsoleEvent.warning("MiniAapt [warning]: ignoring file '%s'.", dir));
+          }
+          continue;
         }
-        continue;
-      }
 
-      String dirname = dir.getFileName().toString();
-      if (dirname.startsWith("values")) {
-        if (!isAValuesDir(dirname)) {
-          throw new ResourceParseException("'%s' is not a valid values directory.", dir);
+        String dirname = dir.getFileName().toString();
+        if (dirname.startsWith("values")) {
+          if (!isAValuesDir(dirname)) {
+            throw new ResourceParseException("'%s' is not a valid values directory.", dir);
+          }
+          processValues(filesystem, eventBus, dir);
+        } else {
+          processFileNamesInDirectory(filesystem, dir);
         }
-        processValues(filesystem, eventBus, dir);
-      } else {
-        processFileNamesInDirectory(filesystem, dir);
-      }
 
+      }
     }
   }
 
@@ -368,13 +370,15 @@ public class MiniAapt implements Step {
       ProjectFilesystem filesystem,
       ImmutableSet.Builder<RDotTxtEntry> references)
       throws IOException, XPathExpressionException, ResourceParseException {
-    for (Path path : filesystem.getFilesUnderPath(resDirectory, ENDS_WITH_XML)) {
-      String dirname = resDirectory.relativize(path).getName(0).toString();
-      if (isAValuesDir(dirname)) {
-        // Ignore files under values* directories.
-        continue;
+    for (Path resDirectory : resDirectories) {
+      for (Path path : filesystem.getFilesUnderPath(resDirectory, ENDS_WITH_XML)) {
+        String dirname = resDirectory.relativize(path).getName(0).toString();
+        if (isAValuesDir(dirname)) {
+          // Ignore files under values* directories.
+          continue;
+        }
+        processXmlFile(filesystem, path, references);
       }
-      processXmlFile(filesystem, path, references);
     }
   }
 
@@ -500,7 +504,7 @@ public class MiniAapt implements Step {
 
   @Override
   public String getDescription(ExecutionContext context) {
-    return getShortName() + " " + resDirectory;
+    return getShortName() + " " + resDirectories;
   }
 
   @SuppressWarnings("serial")
```

**Comment by sdwilsh** [comment]
It's hard to comment on that as-is, but I think it's probably close to what we need.  It might even fix some of those issues you mentioned.

**Comment by tgummerer** [comment]
Thanks for having a look, I'll clean it up a bit and submit a pull request, but it will have to wait until tomorrow.

It does solve the issues I mentioned, I was just wondering if someone more familiar with the system offhand knows a better solution :)

**Comment by sdwilsh** [comment]
It'll be easier for me to look at once it's in an actual request so I can see more context.  I started to look at this, but had to keep jumping between my IDE and github, which got old fast :)

No rush; take your time.

**Comment by tgummerer** [comment]
Hehe yeah I understand :) Submitted the pull request now, #391

**Comment by tgummerer** [comment]
4cf0eb7 fixed this.

**Comment by reondz** [comment]
https://github.com/reondz/Buck_aar_res_not_find 
@tgummerer I still have this issue,above is my demo project.

**Comment by tgummerer** [comment]
Just in case anyone finds this thread first, I answered @reondz's question in https://github.com/facebook/buck/issues/367#issuecomment-140715441
