### ISSUE TITLE
buck test --dry-run throws NullPointerException when tests are cached

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#399]
Repro (on our fork https://github.com/liuyang-li/buck/commit/751fc167e05e43d0e50b516501daac5c2ffabcae , but I don't think it's significantly different?):
1. `buck test`
2. `buck test --dry-run`

Expected: shows information from a dry run.
Actual: Fails with the message
```
====STANDARD OUT====

====STANDARD ERR====

FAIL    <100ms  0 Passed   0 Skipped   1 Failed   //module:test
FAILURE //module:test main: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.facebook.buck.java.JavaTest$1.call(JavaTest.java:396)
	at com.facebook.buck.java.JavaTest$1.call(JavaTest.java:1)
	at com.facebook.buck.cli.TestRunning$6.call(TestRunning.java:555)
	at com.facebook.buck.cli.TestRunning$6.call(TestRunning.java:1)
	at com.facebook.buck.step.DefaultStepRunner$1.call(DefaultStepRunner.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

We are using TestNG instead of JUnit, so I don't know if this is happening with JUnit. If someone could confirm whether or not this works in JUnit (or on current Buck master), that'd be great :)

**Comment by jiangty-addepar** [comment]
@liuyang-li has a fix that he'll open a PR for soon!

**Comment by LegNeato** [comment]
:beers:

**Comment by jiangty-addepar** [comment]
https://github.com/facebook/buck/pull/401

**Comment by LegNeato** [comment]
This is fixed, right?

**Comment by liuyang-li** [comment]
Yes, this is fixed.

**Comment by jiangty-addepar** [comment]
Not fixed for me

**Comment by sdwilsh** [comment]
I can confirm this is still a bug.

**Comment by jiangty-addepar** [comment]
@Coneko was this fixed?

**Comment by Coneko** [comment]
Yes, although we are removing `--dry-run` altogether so you shouldn't use it.
