### ISSUE TITLE
NullPointerException in Checker Framework

### ISSUE THREAD

**Issue by mread** [facebook/buck#403]
As mentioned briefly here 5668382cec9e0e17b32e82a9a11df9b41b38903e, we've been seeing NPEs when compiling with the checker framework annotation processors. Our suspicion is that it's a threading issue with checker that's triggered by the parallel compiles that buck achieves but we've made no more progress than that.

We've reverted back to a singleton classloader in order to work around this issue (8cba4a28635f9cd10e40b4f4ea2f258ff0747b75).

Our intention is to log an issue with the checker framework but I thought I'd create one here too in case anyone has any insight and to track progress.

The stacktrace is as follows:

```
java.lang.RuntimeException: java.lang.NullPointerException
    at com.sun.tools.javac.main.Main.compile(Main.java:559)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at com.facebook.buck.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:191)
    at com.facebook.buck.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:148)
    at com.facebook.buck.java.JavacStep.execute(JavacStep.java:133)
    at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
    at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:851)
    at com.facebook.buck.rules.CachingBuildEngine.access$7(CachingBuildEngine.java:826)
    at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:328)
    at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
    at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:885)
    at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:452)
    at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:205)
    at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
    at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

**Comment by sdwilsh** [comment]
cc @jkeljo who authored the original commit

**Comment by jkeljo** [comment]
What revision of checkerframework are you using? How frequent is this NPE?

I saw an issue once where an annotation processor that loaded resources would, very occasionally, fail to do so when run inside buckd as part of a very large build. I was never quite able to bottom it out, but it went away if I removed the close() call on the classloader. It seemed to be that closing one class loader was somehow invalidating resources used by another. (Since the class loaders were referencing the same files, this seems not entirely crazy.) If switching to a singleton fixes the issue for you, it sounds like it might be related.

**Comment by mread** [comment]
Yes, your decription matches exactly what we see. I might try a standalone test to see what happens when you access a variable that references a class that has been unloaded via classloader.close().

**Comment by mread** [comment]
We've tried a few simple tests and as the Javadoc for URLClassLoader.close() states "any classes or resources that are already loaded, are still accessible." We can't reproduce a situation where closing the classloader of a loaded class causes a NPE.

**Comment by sdwilsh** [comment]
@jkeljo - any other ideas?

**Comment by jkeljo** [comment]
For me the problem only cropped up in buckd with lots of parallelism. Running `env NO_BUCKD=1 buck build` or `buck build -j1` both seemed to make the issue much harder to repro. I'd be curious to see exactly what is NPEing...what revision of the checker framework source should I be looking at for that stack trace?

@sdwilsh, the change to annotation processor classloader behavior we were discussing yesterday should probably mitigate this (it's effectively what @mread mentions they've done locally but with allowances for annotation processors that can't handle parallel builds in one process).

**Comment by mread** [comment]
> What revision of checkerframework are you using? 
v1.9.4

> How frequent is this NPE?
Pretty much guaranteed to happen as soon as we get a reasonable degree of parallel javac's happening. I can explore this in more detail if you think it would be helpful?

> I'd be curious to see exactly what is NPEing
See stacktrace at the top of this issue (v1.9.4)

**Comment by sdwilsh** [comment]
ping @jkeljo

**Comment by jkeljo** [comment]
Sorry, missed that reply. Looking at the source for that revision of checkerframework, it looks like the NPE is that the `visitor` field of some `SourceChecker` is `null`, and exactly how that could happen depends on which particular `SourceChecker` is actually involved in the stack trace. Regardless, seems like the right thing to do in Buck here is to reuse `ClassLoader`s whenever it is safe to do so.

**Comment by grumpyjames** [comment]
That rather goes against the spirit of the comment in `Jsr199Javac`:

<pre>
    // N.B. You might think that we could avoid some overhead by using the same classloader every
    // time we create an instance of annotation processor.  In an ideal world, that would work well,
    // but many annotation processors aren't thread-safe, and they store state in class-static
    // variables.  In the interest of maximum safety, we'll create a new ClassLoader every time we
    // need an annotation processor.
</pre>

That looks like Buck attempting to make up for the shortcomings of annotation processors; perhaps it could be made less friendly?

**Comment by jkeljo** [comment]
Yeah, making it less friendly is exactly the idea. Or at least giving you a way to opt out of the friendliness, either globally or per-processor.
