### ISSUE TITLE
OutOfMemoryError when do release

### ISSUE THREAD

**Issue by llj098** [facebook/buck#405]
build with:

```
android_binary(
  name = 'release',
  manifest = ':manifest',
  keystore = '//keystores:release',
  package_type = 'release',
  deps = [
    ':application-lib',
    ':res',
    ':src',
  ],
  proguard_config = 'prog.pro',
)
```

```
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.android.dx.rop.code.ThrowingInsn.withNewRegisters(ThrowingInsn.java:116)
	at com.android.dx.ssa.NormalSsaInsn.toRopInsn(NormalSsaInsn.java:126)
	at com.android.dx.ssa.back.SsaToRop.convertInsns(SsaToRop.java:341)
	at com.android.dx.ssa.back.SsaToRop.convertBasicBlock(SsaToRop.java:322)
	at com.android.dx.ssa.back.SsaToRop.convertBasicBlocks(SsaToRop.java:259)
	at com.android.dx.ssa.back.SsaToRop.convert(SsaToRop.java:123)
	at com.android.dx.ssa.back.SsaToRop.convertToRopMethod(SsaToRop.java:69)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:101)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:72)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:297)
	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:137)
	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:93)
	at com.android.dx.command.dexer.Main.processClass(Main.java:729)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
```

- buck version *92f4a5486d4531d0ba8535529ab8f0cada2d3651
- java version "1.8.0_45"
- Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
- Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
- mac os 10.10.5

**Comment by sdwilsh** [comment]
Are you specifying any `-Xmx` in `.buckjavaargs`?  For larger applications, you may need to bump this up (we use `-Xmx3g` for our Android stuff).

**Comment by llj098** [comment]
Thanks @sdwilsh , I have tried the `BUCK_EXTRA_JAVA_ARGS` I will try  `.buckjavaargs`.

**Comment by sdwilsh** [comment]
The benefit is that you can check that in and everyone uses that value.

**Comment by llj098** [comment]
I found the problem, I failed in the `smart_dex` step, it runs the android sdk's `dx`, the default `Mmx` of it is 1024M.

**Comment by ldjhust** [comment]
@llj098 how do you solve the problem? I just have the same problem too

Thank you
