### ISSUE TITLE
Can't quickstart an iOS project from a template

### ISSUE THREAD

**Issue by vhbit** [facebook/buck#421]
`buck` was installed through homebrew.

trying to create a test iOS project I get:
```
mkdir qs && cd qs && touch .buckconfig
buck quickstart --type ios --dest-dir .
```

```
[2015-09-15 11:26:22.439][error][command:17850afd-f86f-427b-91fe-db1f94b0639a][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.nio.file.NoSuchFileException: /Users/vhbit/projects/qs/src/com/facebook/buck/cli/quickstart/ios
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1734)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2659)
	at java.nio.file.Files.walkFileTree(Files.java:2739)
	at com.facebook.buck.io.MoreFiles.copyRecursively(MoreFiles.java:150)
	at com.facebook.buck.io.MoreFiles.copyRecursively(MoreFiles.java:101)
	at com.facebook.buck.cli.QuickstartCommand.runWithoutHelp(QuickstartCommand.java:207)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:153)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:766)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1136)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1193)
	at com.facebook.buck.cli.Main.main(Main.java:1211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
```

Looks like `buck` tries to get templates from the current directory

**Comment by sdwilsh** [comment]
I'm guessing we are not packaging this properly, @Coneko.  Of course our tests do it from in-tree so we wouldn't have seen this.

@vhbit, if you do the manual setup and install process it should work for you.

**Comment by sdwilsh** [comment]
If you update to the head of Buck with homebrew, this should work for you.  Thanks for the report!

**Comment by petersibley** [comment]
I'm seeing this same issue with the updated homebrew package from facebook/fb HEAD tap.

**Comment by sdwilsh** [comment]
@petersibley, can you provide more details?  @marcinkosiba can hopefully help you out tomorrow.

**Comment by petersibley** [comment]
This appears to be fixed as of last night
