### ISSUE TITLE
"Invalid version string: build-tools-17.0.0"

### ISSUE THREAD

**Issue by ndahlquist** [facebook/buck#425]
Historically, the Android SDK had two different naming schemes for the build tools directory. Thus, my build-tools directory looks like this:

```sh
> ls ~/.android-sdk/build-tools/
…ld-tools/20.0.0/  …ld-tools/22.0.1/              …ld-tools/build-tools-18.1.1/  …ld-tools/build-tools-19.0.3/  …ld-tools/build-tools-21.0.1/  
…ld-tools/21.1.1/  …ld-tools/build-tools-17.0.0/  …ld-tools/build-tools-19.0.0/  …ld-tools/build-tools-19.1.0/  …ld-tools/build-tools-21.0.2/  
…ld-tools/21.1.2/  …ld-tools/build-tools-18.0.1/  …ld-tools/build-tools-19.0.1/  …ld-tools/build-tools-20.0.0/  …ld-tools/build-tools-21.1.0/  
…ld-tools/22.0.0/  …ld-tools/build-tools-18.1.0/  …ld-tools/build-tools-19.0.2/  …ld-tools/build-tools-21.0.0/  …ld-tools/build-tools-22.0.1/  
```

It appears that Buck only parses the `/xx.x.x/` style of name:

```
BUILD FAILED: Invalid version string: build-tools-17.0.0
java.lang.RuntimeException: Invalid version string: build-tools-17.0.0
java.lang.RuntimeException: Invalid version string: build-tools-17.0.0
	at com.facebook.buck.util.VersionStringComparator.compare(VersionStringComparator.java:47)
	at com.facebook.buck.android.AndroidPlatformTarget$3.compare(AndroidPlatformTarget.java:369)
	at com.facebook.buck.android.AndroidPlatformTarget$3.compare(AndroidPlatformTarget.java:1)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:329)
	at java.util.TimSort.sort(TimSort.java:189)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at com.facebook.buck.android.AndroidPlatformTarget.pickNewestBuildToolsDir(AndroidPlatformTarget.java:364)
	at com.facebook.buck.android.AndroidPlatformTarget.createFromDefaultDirectoryStructure(AndroidPlatformTarget.java:298)
	at com.facebook.buck.android.AndroidPlatformTarget$AndroidWithGoogleApisFactory.newInstance(AndroidPlatformTarget.java:443)
	at com.facebook.buck.android.AndroidPlatformTarget.getTargetForId(AndroidPlatformTarget.java:200)
	at com.facebook.buck.cli.Main$1.get(Main.java:872)
	at com.facebook.buck.cli.Main$1.get(Main.java:1)
	at com.facebook.buck.step.ExecutionContext.getAndroidPlatformTarget(ExecutionContext.java:167)
	at com.facebook.buck.android.DxStep.getShellCommandInternal(DxStep.java:129)
	at com.facebook.buck.shell.ShellStep.getShellCommand(ShellStep.java:210)
	at com.facebook.buck.shell.ShellStep.getDescription(ShellStep.java:241)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:56)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:958)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:941)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:367)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
```

Removing the old build-tools versions allows the build to pass, but it probably makes sense to parse both directory formats.

**Comment by sdwilsh** [comment]
*groan*

This code is already pretty complicated because Google keeps moving stuff around: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/AndroidPlatformTarget.java#L278

I guess we'd have to do something like `ANDROID_VERSION_PREFIX` here: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/AndroidPlatformTarget.java#L343
