### ISSUE TITLE
Issue installing Buck

### ISSUE THREAD

**Issue by mremick** [facebook/buck#429]
I'm trying to install buck and I'm getting the following error: 

M00972632:~ blah$ brew install --HEAD buck
==> Installing buck from facebook/homebrew-fb
==> Cloning https://github.com/facebook/buck.git
Updating /Library/Caches/Homebrew/buck--git
==> Checking out branch master
==> ant
==> ./bin/buck build buck
Last 15 lines from /Users/blah/Library/Logs/Homebrew/buck/02.buck:
	at com.facebook.buck.shell.Genrule$2.addEnvironmentVariables(Genrule.java:303)
	at com.facebook.buck.shell.AbstractGenruleStep.getEnvironmentVariables(AbstractGenruleStep.java:67)
	at com.facebook.buck.shell.ShellStep.getDescription(ShellStep.java:231)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:56)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:958)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:941)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:367)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[-] BUILDING...FINISHED 3.6s

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/facebook/homebrew-fb/issues

I've made sure to update and install the Buck page asks for. Thanks in advance.

**Comment by sdwilsh** [comment]
That stacktrace is truncated.  Can you get the full stacktrace from the log?

**Comment by mremick** [comment]
BUILD FAILED: Environment variable ANDROID_HOME points to invalid path [/Applications/Android Studio.app/sdk].
java.lang.RuntimeException: Environment variable ANDROID_HOME points to invalid path [/Applications/Android Studio.app/sdk].
java.lang.RuntimeException: Environment variable ANDROID_HOME points to invalid path [/Applications/Android Studio.app/sdk].
	at com.facebook.buck.util.DefaultPropertyFinder.findDirectoryByPropertiesThenEnvironmentVariable(DefaultPropertyFinder.java:122)
	at com.facebook.buck.util.DefaultPropertyFinder.findDirectoryByPropertiesThenEnvironmentVariable(DefaultPropertyFinder.java:65)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.getSdkPathFromSdkDir(DefaultAndroidDirectoryResolver.java:115)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.access$0(DefaultAndroidDirectoryResolver.java:113)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver$1.get(DefaultAndroidDirectoryResolver.java:59)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver$1.get(DefaultAndroidDirectoryResolver.java:1)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.findAndroidSdkDirSafe(DefaultAndroidDirectoryResolver.java:74)
	at com.facebook.buck.cli.Main$1.get(Main.java:852)
	at com.facebook.buck.cli.Main$1.get(Main.java:1)
	at com.facebook.buck.step.ExecutionContext.getAndroidPlatformTarget(ExecutionContext.java:167)
	at com.facebook.buck.shell.Genrule.addEnvironmentVariables(Genrule.java:233)
	at com.facebook.buck.shell.Genrule$2.addEnvironmentVariables(Genrule.java:303)
	at com.facebook.buck.shell.AbstractGenruleStep.getEnvironmentVariables(AbstractGenruleStep.java:67)
	at com.facebook.buck.shell.ShellStep.getDescription(ShellStep.java:231)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:56)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:958)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:941)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:367)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[-] BUILDING...FINISHED 5.3s

I don't have Android Studio installed on my computer anymore.

**Comment by mremick** [comment]
I unset the environment variable 'ANDROID_HOME' and it installed. Thanks for the help!

**Comment by sdwilsh** [comment]
Glad to be of assistance :)
