### ISSUE TITLE
Experimental IJ project generator encounters a null check in the JavaFileParser

### ISSUE THREAD

**Issue by strangemonad** [facebook/buck#444]
This is related to #350. I currently run into the following error:

[2015-10-01 23:00:43.226][error][command:65b949e6-99f9-4c2b-a6ea-08824173e257][tid:379][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.facebook.buck.java.JavaFileParser.createJavaFileParser(JavaFileParser.java:68)
	at com.facebook.buck.cli.ProjectCommand.runExperimentalIntellijProjectGenerator(ProjectCommand.java:535)
	at com.facebook.buck.cli.ProjectCommand.runIntellijProjectGenerator(ProjectCommand.java:573)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:425)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:153)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:792)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1168)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1225)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)

I've tried this with verbose logging (-v = 10). Here are a few snippets that seem relevant:

[2015-10-01 23:00:42.699][debug][command:65b949e6-99f9-4c2b-a6ea-08824173e257][tid:379][com.facebook.buck.json.ProjectBuildFileParser] Starting buck.py command: [/usr/bin/python, -u, /Users/shawn/Dropbox/Development/myproj/.buckd/tmp/buck_run.TuMiWn/buck5883202559706827887.py, --allow_empty_globs, --watchman_watch_root, /Users/shawn/Dropbox/Development/myproj, --project_root, /Users/shawn/Dropbox/Development/myproj, --build_file_name, BUCK, --include, //build/myproj.defs] environment: Optional.of({BUCK_ORIG_TMPDIR=/var/folders/sl/68wd6hc911d03m1lq98t1pkw0000gn/T/, NAILGUN_FILESEPARATOR=/, VERSIONER_PYTHON_VERSION=2.7, NAILGUN_TTY_2=0, NAILGUN_TTY_1=0, PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Users/shawn/google-cloud-sdk/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Users/shawn/Dropbox/configuration/bin/mac:/Users/shawn/Dropbox/configuration/bin/no-arch:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/opt/go/libexec/bin:/Users/shawn/Dropbox/Development/myproj/bin:/Users/shawn/Dropbox/Development/plan9port/bin:/Users/shawn/Dropbox/Development/myproj/vendor/buck/bin, GOPATH=/Users/shawn/Dropbox/Development/myproj, NAILGUN_TTY_0=0, LC_CTYPE=en_US.UTF-8, LOGNAME=shawn, TERM_PROGRAM=iTerm.app, myproj_ROOT=/Users/shawn/Development/myproj, SHELL=/bin/bash, GOPATH_HACK=/Users/shawn/Dropbox/Development/myproj, GIT_PAGER=, CONFIGURATION_DIR=/Users/shawn/Dropbox/configuration, __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, LANG=en_US.UTF-8, COLORFGBG=12;8, LSCOLORS=gxfxxxxxcxxxxxCdCdExEd, HOME=/Users/shawn, DROPBOX_ROOT=/Users/shawn/Dropbox, TMPDIR=/var/folders/sl/68wd6hc911d03m1lq98t1pkw0000gn/T/, EDITOR=subl -w, PLAN9=/Users/shawn/Dropbox/Development/plan9port, CLICOLOR=YES, NAILGUN_PATHSEPARATOR=:, USER=shawn, JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home, TERM=xterm-256color, _=/usr/local/bin/babushka, VERSIONER_PYTHON_PREFER_32_BIT=no})

**Comment by Coneko** [comment]
cc @marcinkosiba

**Comment by marcinkosiba** [comment]
This happens if you target java 1.8. I have a fix for it internally - it's super-trvial - just add a 1.8 entry to the map in JavaFileParser.

**Comment by strangemonad** [comment]
@marcinkosiba thanks for the pointer, I'll try that out. Any idea when the actual fix will land for proper java 8 support?

**Comment by sdwilsh** [comment]
I think it was https://github.com/facebook/buck/commit/ddba2954e0f936d60011dc3cafdc501613435287

**Comment by strangemonad** [comment]
@sdwilsh cool, that looks like it fixes that issue. There are still several other issues I'm running into with the project generation but I'll track those separately
