### ISSUE TITLE
Maven resolver doesn't work for spark

### ISSUE THREAD

**Issue by mikekap** [facebook/buck#456]
```shell
$ java -jar /tmp/resolver.jar . thirdparty /tmp/mvn/ http://repo1.maven.org/maven2 org.apache.spark:spark-core_2.11:1.3.1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.apache.hadoop:hadoop-yarn-client:jar:1.0.4, org.apache.hadoop:hadoop-yarn-api:jar:1.0.4, org.apache.hadoop:hadoop-yarn-common:jar:1.0.4: Could not find artifact org.apache.hadoop:hadoop-yarn-client:jar:1.0.4 in http://repo1.maven.org/maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at com.facebook.buck.maven.Resolver.getRunTimeTransitiveDeps(Resolver.java:435)
	at com.facebook.buck.maven.Resolver.resolve(Resolver.java:121)
	at com.facebook.buck.maven.Resolver.main(Resolver.java:482)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache.hadoop:hadoop-yarn-client:jar:1.0.4, org.apache.hadoop:hadoop-yarn-api:jar:1.0.4, org.apache.hadoop:hadoop-yarn-common:jar:1.0.4: Could not find artifact org.apache.hadoop:hadoop-yarn-client:jar:1.0.4 in http://repo1.maven.org/maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 3 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.hadoop:hadoop-yarn-client:jar:1.0.4 in http://repo1.maven.org/maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I don't know enough about java artifact resolution, but some googling suggests that `hadoop.version` isn't being propagated correctly and is defaulting to 1.0.4 in the spark pom (and `hadoop-yarn-client` doesn't exist on 1.0.4).

**Comment by mikekap** [comment]
Seems I managed to make it work, but I don't know why. @shs96c do you have any context re: why we manually add direct dependencies to the collect request on passed in artifacts?

```patch
diff --git a/src/com/facebook/buck/maven/Resolver.java b/src/com/facebook/buck/maven/Resolver.java
index a534ede..76e5d8c 100644
--- a/src/com/facebook/buck/maven/Resolver.java
+++ b/src/com/facebook/buck/maven/Resolver.java
@@ -405,28 +405,6 @@ public class Resolver {
     for (String coord : mavenCoords) {
       DefaultArtifact artifact = new DefaultArtifact(coord);
       collectRequest.addDependency(new Dependency(artifact, JavaScopes.RUNTIME));
-
-      ArtifactDescriptorRequest descriptorRequest = new ArtifactDescriptorRequest();
-      descriptorRequest.setArtifact(artifact);
-      // Setting this appears to have exactly zero effect on the returned values. *sigh*
-//      descriptorRequest.setRequestContext(JavaScopes.RUNTIME);
-      descriptorRequest.setRepositories(repos);
-      ArtifactDescriptorResult descriptorResult = repoSys.readArtifactDescriptor(
-          session,
-          descriptorRequest);
-
-      for (Dependency dependency : descriptorResult.getDependencies()) {
-        if (isTestTime(dependency)) {
-          continue;
-        }
-        collectRequest.addDependency(dependency);
-      }
-      for (Dependency dependency : descriptorResult.getManagedDependencies()) {
-        if (isTestTime(dependency)) {
-          continue;
-        }
-        collectRequest.addManagedDependency(dependency);
-      }
     }

     DependencyFilter filter = DependencyFilterUtils.classpathFilter(JavaScopes.RUNTIME);
```

**Comment by neeraj541** [comment]
Looking at the dependency graph of spark-core-1.3.1

spark-core-1.3.1 -> haddop-client-2.2.0 -> hadoop-map-reduce-client-2.2.0 -> yarn-client-2.2.0 
        |
spark-parent-1.3.1 -> yarn-client-1.0.4 (Does not exist in maven central)

hadoop-yarn-client-1.0.4 does not exist in maven central. While resolving the transitive dependency, aether is trying to get yarn-client-1.0.4. This is causing the  exception.

In the latest release of spark-core i.e. 1.5.2, they have updated the spark-parent to 1.5.2 which depends on hadoop-yarn-client 2.2.0. So spark-core 1.5.2 is working fine with our resolver.

So I don't think  there is any problem with resolver.

**Comment by mikekap** [comment]
Depending on spark 1.3.1 works with pom.xml, so there is definitely a bug somewhere that's not the spark package.

As mentioned in the PR, adding the direct dependencies without proper evaluation of $variables/profiles/etc is causing this scenario - spark-parent-1.3.1 likely uses something like ${hadoop_version:-1.0.4}. Yarn didn't exist on hadoop 1.0.4, so that default is terrible, but never actually used by maven.

As another test case - this fails in an even worse way:
```buck run src/com/facebook/buck/maven:resolver -- /tmp/buck_repo/ thirdparty/jvm /tmp/mvn/ http://repo1.maven.org/maven2 io.netty:netty-all:4.0.24.Final```
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:1.1.30.Fork2 in http://repo1.maven.org/maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at com.facebook.buck.maven.Resolver.getRunTimeTransitiveDeps(Resolver.java:435)
	at com.facebook.buck.maven.Resolver.resolve(Resolver.java:121)
	at com.facebook.buck.maven.Resolver.main(Resolver.java:482)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:1.1.30.Fork2 in http://repo1.maven.org/maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 3 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:1.1.30.Fork2 in http://repo1.maven.org/maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Notice ${os.detected.classifier} is in the package descriptor - something that should have been evaluated by maven and changed to something else.
