### ISSUE TITLE
Error parsing resources to generate resource IDs for res

### ISSUE THREAD

**Issue by zjzxzhang** [facebook/buck#460]
com.facebook.buck.android.aapt.MiniAapt.ResourceParseException: 'res/.svn' is not a valid resource sub-directory.
com.facebook.buck.android.aapt.MiniAapt$ResourceParseException: 'res/.svn' is not a valid resource sub-directory.
    at com.facebook.buck.android.aapt.MiniAapt.processFileNamesInDirectory(MiniAapt.java:238)
    at com.facebook.buck.android.aapt.MiniAapt.collectResources(MiniAapt.java:223)
    at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:142)
    at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
    at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:967)
    at com.facebook.buck.rules.CachingBuildEngine.access$600(CachingBuildEngine.java:88)
    at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:367)
    at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:239)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
    at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //:res failed with exit code 1:
generate_resource_ids

 .watchmanconfig file config:
{
  "ignore_dirs": [
    ".svn"
  ],
  "ignore_vcs": [
    ".svn"
  ]
}

also, .buckconfig config:
[java]
  src_roots = java, resources
[cache]
  mode = dir
  dir = buck-out/cache
[project]
  ignore = .svn

[android]
  target = android-21

**Comment by sdwilsh** [comment]
Possibly related to #208, but we should be ignoring this already: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/AaptStep.java#L55

**Comment by ASCE1885** [comment]
you have to be aware that 'res/.svn' is not a file but a directory, in AaptStep.java:

```java
public static boolean isSilentlyIgnored(Path path) {
    String fileName = path.getFileName().toString();
    return ".gitkeep".equalsIgnoreCase(fileName) ||
        ".svn".equalsIgnoreCase(fileName) ||
        ".git".equalsIgnoreCase(fileName) ||
        ".ds_store".equalsIgnoreCase(fileName) ||
        MoreStrings.endsWithIgnoreCase(fileName, ".scc") ||
        "cvs".equalsIgnoreCase(fileName) ||
        "thumbs.db".equalsIgnoreCase(fileName) ||
        "picasa.ini".equalsIgnoreCase(fileName) ||
        fileName.endsWith("~");
  }
```

what it ignore is just file, and this cannot solve the problem,the code cause this exception is:

```java
void processFileNamesInDirectory(ProjectFilesystem filesystem, Path dir)
      throws IOException, ResourceParseException {
    String dirname = dir.getFileName().toString();
    int dashIndex = dirname.indexOf('-');
    if (dashIndex != -1) {
      dirname = dirname.substring(0, dashIndex);
    }

    if (!RESOURCE_TYPES.containsKey(dirname)) {
      throw new ResourceParseException("'%s' is not a valid resource sub-directory.", dir);
    }

...
```

and RESOURCE_TYPES is one of this:

```java
public static enum RType {
    ANIM,
    ANIMATOR,
    ARRAY,
    ATTR,
    BOOL,
    COLOR,
    DIMEN,
    DRAWABLE,
    FRACTION,
    ID,
    INTEGER,
    INTERPOLATOR,
    LAYOUT,
    MENU,
    MIPMAP,
    PLURALS,
    RAW,
    STRING,
    STYLE,
    STYLEABLE,
    TRANSITION,
    XML;

    @Override
    public String toString() {
      return super.toString().toLowerCase();
    }
  }
```

so maybe we should not throw an exception when meet '.svn' dir,but just ignore it and return.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
