### ISSUE TITLE
NullPointerException when generating Xcode project

### ISSUE THREAD

**Issue by lucidsheep** [facebook/buck#468]
I'm currently trying to generate an Xcode project for a build target and am hitting this error:

```
[2015-10-15 13:10:25.554][error][command:d460f5e8-8e3a-4500-86df-c928b9f7e0d4][tid:700][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException
	at com.facebook.buck.apple.SchemeGenerator.writeScheme(SchemeGenerator.java:133)
	at com.facebook.buck.apple.WorkspaceAndProjectGenerator.writeWorkspaceSchemes(WorkspaceAndProjectGenerator.java:845)
	at com.facebook.buck.apple.WorkspaceAndProjectGenerator.generateWorkspaceAndDependentProjects(WorkspaceAndProjectGenerator.java:413)
	at com.facebook.buck.cli.ProjectCommand.generateWorkspacesForTargets(ProjectCommand.java:808)
	at com.facebook.buck.cli.ProjectCommand.runXcodeProjectGenerator(ProjectCommand.java:707)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:432)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:153)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:792)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1168)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1225)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)

```

I'm unsure exactly what's causing this to happen - I will update if I have more exact steps to repro.

**Comment by sdwilsh** [comment]
@Coneko would probably be the best person to look at this.

**Comment by Coneko** [comment]
Did you solve this issue? Did you find out how to repro it?

**Comment by lucidsheep** [comment]
Unfortunately not. I tried generating a fresh project on a different machine and got a different stack:
```
[2015-10-29 14:04:59.626][error][command:95ec69fd-030f-42ea-82d8-09de65141931][tid:169][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.ArrayIndexOutOfBoundsException: 0
    at sun.nio.fs.UnixPath.normalize(UnixPath.java:508)
    at com.facebook.buck.apple.WorkspaceGenerator$1.visitFile(WorkspaceGenerator.java:232)
    at com.facebook.buck.apple.WorkspaceGenerator$1.visitFile(WorkspaceGenerator.java:1)
    at com.facebook.buck.apple.WorkspaceGenerator.walkNodeTree(WorkspaceGenerator.java:175)
    at com.facebook.buck.apple.WorkspaceGenerator.writeWorkspace(WorkspaceGenerator.java:252)
    at com.facebook.buck.apple.WorkspaceAndProjectGenerator.generateWorkspaceAndDependentProjects(WorkspaceAndProjectGenerator.java:378)
    at com.facebook.buck.cli.ProjectCommand.generateWorkspacesForTargets(ProjectCommand.java:825)
    at com.facebook.buck.cli.ProjectCommand.runXcodeProjectGenerator(ProjectCommand.java:710)
    at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:430)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:154)
    at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:846)
    at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1211)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1272)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1301)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
```

Some notes about my setup:
* I'm making an Xcode project with a single apple_bundle as its target
* We don't currently have any tests in the project
* I'm creating the project with --build-with-buck. Full command is "buck project //:targetName --build-with-buck"
* The Xcode project mostly generates. I can open the .xcworkspace and it has all targets, but no schemes. I can manually create the schemes and the project will run
* The .xcodeproj file does not have a name (it generates as ".xcodeproj" instead of "targetName.xcodeProj")
* Project generation works fine on the sample buck ios project
* Buck version is a965937ccdadf8119a98ab766c3feb0708dc424e

Sorry, I wish I had more specifics! I will update if I make any more progress on the issue.

**Comment by Coneko** [comment]
Try creating a project with a target that isn't at the top level of your repo, so instead of `buck project //:targetName` it ends up with `buck project //Apps:targetName`.

There are some weird issues with creating projects with targets in the root of the repo, we should probably make it fail with an error message.

**Comment by lucidsheep** [comment]
Good call! Taking the target out of the top level fixed the issue. The project generates with no problems. It would be good to note this in documentation or with an error message, like you said.

Thanks for your help!

**Comment by Coneko** [comment]
Yeah sorry, it's a funny bug.

**Comment by jbrownson** [comment]
@Coneko Great to make it an error rather than a crash, but are there bigger plans to make projects at the root work too? Would you consider a pr if it's not a priority for you guys?

**Comment by Coneko** [comment]
Sure, PRs are always welcome.

Generally send out a draft of the PR first so we can comment on general approach and high level design. No need to flesh it out we know which direction we should go in.

For project generation specifically look at the `--combined-project` and `--build-with-buck` flags, those are the future in some sense.

**Comment by brentleyjones** [comment]
This is still happening btw.
