### ISSUE TITLE
Buck looks at the wrong path for uber classes?

### ISSUE THREAD

**Issue by edisonw** [facebook/buck#475]
The file "classes.jar" exists in: 
./buck-out/bin/__uber_classes_LIRBRARY#aar_unzip__ but buck looks at 
./buck-out/bin/__unpack_LIBRARY#aar_unzip__/classes.jar

-So copy actually happened successfully? 

Failed to copy from buck-out/bin/__unpack_LIBRARY#aar_unzip__/classes.jar to buck-out/bin/__uber_classes_LIBRARY#aar_unzip__/classes.jar
java.nio.file.NoSuchFileException: ./buck-out/bin/__unpack_LIBRARY#aar_unzip__/classes.jar
java.nio.file.NoSuchFileException: ./buck-out/bin/__unpack_LIBRARY#aar_unzip__/classes.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:520)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1225)
	at com.facebook.buck.io.ProjectFilesystem.copy(ProjectFilesystem.java:831)
	at com.facebook.buck.android.UnzipAar$1.execute(UnzipAar.java:123)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:955)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:938)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:355)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by sdwilsh** [comment]
I'm guessing you resolved this?

**Comment by edisonw** [comment]
Yea, this happens only when I use a re-zipped aar file. :D aar the correct way will not confuse BUCK.

**Comment by edisonw** [comment]
@sdwilsh btw, the transitive aar stuff works now perfectly, thanks again. : )

**Comment by sdwilsh** [comment]
Thank @tgummerer and @natthu more than me!  I just helped make sure it all got in :)
