### ISSUE TITLE
`buck run` parses -v after --

### ISSUE THREAD

**Issue by mikekap** [facebook/buck#493]
```shell
$ buck run src/com/facebook/buck/maven:resolver -- -v bye
[2015-11-03 16:42:41.701][error][command:169c085d-6632-40a2-b36b-0395103e3541][tid:14][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NumberFormatException: For input string: "bye"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.facebook.buck.cli.VerbosityParser.parse(VerbosityParser.java:44)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:429)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1043)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1100)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
```

**Comment by sdwilsh** [comment]
I wonder if this is a bug with `args4j` :/

**Comment by Coneko** [comment]
No, it's because we parse the verbosity with `VerbosityParser.parse`.

I'm not sure why it exists.
