### ISSUE TITLE
BUILD FAILED: //:pumpup#dex_merge failed with exit code 1: smart_dex

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#500]
Howdy!

Getting really close to getting Buck working for our project.

However it is throwing an error at the end that I'm not sure whats up.

```
There was an error in smart dexing step.
com.facebook.buck.step.StepFailedException: Failed on step dx_&&_write_file with an exception:
Multiple dex files define Lco/pumpup/app/AppShell;
com.android.dex.DexException: Multiple dex files define Lco/pumpup/app/AppShell;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:601)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:557)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:538)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:177)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:195)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:484)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:330)
	at com.android.dx.command.dexer.Main.run(Main.java:266)
	at com.android.dx.command.dexer.Main.run(Main.java:236)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:193)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:176)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:42)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:42)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:124)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:121)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.facebook.buck.step.StepFailedException: Failed on step dx_&&_write_file with an exception:
Multiple dex files define Lco/pumpup/app/AppShell;
com.android.dex.DexException: Multiple dex files define Lco/pumpup/app/AppShell;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:601)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:557)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:538)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:177)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:195)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:484)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:330)
	at com.android.dx.command.dexer.Main.run(Main.java:266)
	at com.android.dx.command.dexer.Main.run(Main.java:236)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:193)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:176)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:42)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:42)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:124)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:121)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


	at com.facebook.buck.step.StepFailedException.createForFailingStepWithException(StepFailedException.java:80)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:65)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:124)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:121)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //:pumpup#dex_merge failed with exit code 1:
smart_dex
```

Here is my BUCK file

```
import re

### ALL jars are handled up here.

# xwalk_core_library jars
prebuilt_jar(
  name = 'xwalk-app-lib',
  binary_jar = 'xwalk_core_library/libs/xwalk_core_library_java_app_part.jar',
)

prebuilt_jar(
  name = 'xwalk-library-lib',
  binary_jar = 'xwalk_core_library/libs/xwalk_core_library_java_library_part.jar',
)

# Gets the jars in the libs folder
jar_deps = []
for jarfile in glob(['libs/*.jar']):
  name = 'jars__' + re.sub(r'^.*/([^/]+)\.jar$', r'\1', jarfile)
  jar_deps.append(':' + name)
  prebuilt_jar(
    name = name,
    binary_jar = jarfile,
  )

### External Libs

#appcompat

prebuilt_jar(
  name = 'appcompat-v7-22.0.0-jar',
  binary_jar = 'ExternalLibs/appcompat-v7-22.0.0/android-support-v7-appcompat.jar',
)

prebuilt_jar(
  name = 'appcompat-v4-22.0.0-jar',
  binary_jar = 'ExternalLibs/appcompat-v7-22.0.0/android-support-v4.jar',
)

android_resource(
  name = 'appcompat-v7-22.0.0-res',
  package = 'android.support.v7.appcompat',
  res = 'ExternalLibs/appcompat-v7-22.0.0/res',
)

android_library(
  name = 'appcompat-v7-22.0.0-lib',
  deps = [
    ':appcompat-v7-22.0.0-jar',
    ':appcompat-v4-22.0.0-jar',
    ':appcompat-v7-22.0.0-res',
  ],
)

#google play services 

prebuilt_jar(
  name = 'google-play-services-jar',
  binary_jar = 'ExternalLibs/google-play-services_lib/google-play-services.jar'
)

android_resource(
  name = 'google-play-services-res',
  package = 'com.google.android.gms',
  res = 'ExternalLibs/google-play-services_lib/res',
)

android_library(
  name = 'google-play-services-lib',
  deps = [
    ':google-play-services-jar',
    ':google-play-services-res',
  ],
)

#multi-dex

prebuilt_jar(
  name = 'multidex-jar',
  binary_jar = 'ExternalLibs/multidex/android-support-multidex.jar'
)

android_library(
  name = 'multidex-lib',
  deps = [
    ':multidex-jar',
  ],
)

# Gets the External Library jars

# Builds all the dep jars as a one jar
# bolts and android-support-v4 are from the com.phonegap.plugins.facebook BUCK file
# also depends on xwalk prebuilt jars
android_library(
  name = 'all-lib-jars',
  exported_deps = jar_deps,
  deps = [
  '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:bolts',
  '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:android-support-v4',
  ':xwalk-app-lib',
  ':xwalk-library-lib',
  ':appcompat-v7-22.0.0-lib'
  ],
)

### com.phonegap.plugins.facebook

# gets the res folder
android_resource(
  name = 'facebook-plugin-res',
  package = 'com.facebook.android',
  res = 'com.phonegap.plugins.facebookconnect/app-FacebookLib/res',
)

## gets the Java files, will depend on the all-lib-jars AND resources
android_library(
  name = 'facebook-plugin',
  srcs = glob(['com.phonegap.plugins.facebookconnect/app-FacebookLib/src/**/*.java']),
  deps =[
    ':all-lib-jars',
    ':facebook-plugin-res',
    '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:facebook_build_config',
    '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:bolts',
    '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:android-support-v4',
    '//:xwalk-library-lib',
  ]
)

### xwalk

android_resource(
  name = 'xwalk-lib-res',
  package = 'org.xwalk.core',
  res = 'xwalk_core_library/src/main/res',
)

android_library(
  name = 'xwalk-lib',
  srcs = glob(['xwalk_core_library/src/**/*.java']),
  deps =[
    ':all-lib-jars',
    ':xwalk-lib-res',
  ]
)

### CordovaLib

android_resource(
  name = 'cordova-lib-res',
  package = 'org.apache.cordova',
  res = 'CordovaLib/res',
  assets = 'CordovaLib/assets',
)

android_library(
  name = 'cordova-lib',
  srcs = glob(['CordovaLib/src/**/*.java']),
  deps = [
    ':all-lib-jars',
    ':cordova-lib-res',
    ':xwalk-app-lib',
    ':xwalk-library-lib',
  ],
)

### Keystore

keystore(
  name = 'debug_keystore',
  store = 'keystore/debug.keystore',
  properties = 'keystore/debug.keystore.properties',
)

### Making The APK

android_build_config(
  name = 'build-config',
  package = 'co.pumpup.app',
)

# main resources

android_resource(
  name = 'res',
  package = 'co.pumpup.app',
  res = 'res',
  assets = 'assets',
)

android_library(
  name = 'main-lib',
  srcs = glob(['src/**/*.java']),
  deps =[
    ':appcompat-v7-22.0.0-lib',
    ':multidex-lib',
    '//:multidex-jar',
    ':google-play-services-lib',
    ':cordova-lib',
    ':xwalk-lib',
    ':all-lib-jars',
    ':facebook-plugin',
    '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:android-support-v4',
    '//:xwalk-library-lib',
    '//com.phonegap.plugins.facebookconnect/app-FacebookLib/libs:bolts',
    '//:xwalk-app-lib',
    '//:google-play-services-jar',
    ':res',
  ]
)

# Exopackge Entry

APP_CLASS_SOURCE = 'src/co/pumpup/app/AppShell.java'

## Depends on build config and the buck support library
android_library(
  name = 'application-lib',
  srcs = [APP_CLASS_SOURCE],
  deps = [
    ':build-config',
    ':jars__buck-android-support',
  ],
)

android_binary(
  name = 'pumpup',
  linear_alloc_hard_limit = 16 * 1024 * 1024,
  use_linear_alloc_split_dex = True,
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  use_split_dex = True,
  exopackage_modes = ['secondary_dex'],
  primary_dex_patterns = [
    '^co/pumpup/app/AppShell^',
    '^co/pumpup/app/BuildConfig^',
    '^com/facebook/buck/android/support/exopackage/',
  ],
  deps = [
    ':main-lib',
    ':application-lib',
  ],
)
```

**Comment by tgummerer** [comment]
I think you should exclude `AppShell.java` in the main lib, using something like `srcs = glob(['src/**/*.java'], excludes = [APP_CLASS_SOURCE]),`.

Otherwise it is defined in two libraries when doing the dex merge in `android_binary`, so buck won't know which one to use.

**Comment by AnthonyUccello** [comment]
Yes that fixed this issue. Its cropping up but for different files. But as you've said the core is this duplication issue. Will close this for now. Thank you.

**Comment by marcinkosiba** [comment]
Thanks @tgummerer !
