### ISSUE TITLE
Uncaught exception when generating XCode C++ workspace

### ISSUE THREAD

**Issue by twoism** [facebook/buck#504]
I have a C++ project that builds correctly when using `buck build src/my:target` but when I attempt to generate an xcode project I get a `java.lang.IllegalStateException`.

The `BUCK` file for the project and directory structure is as follows.

```python
xcode_workspace_config(
   name='my_project',
   src_target='//src/<project name>:target',
   visibility=['PUBLIC'],
)
```

```
.
├── BUCK <- xcode_workspace_config
└── src
    └── <project name>
        └── BUCK <- <project name>:target
```

From the error it seems that a `Precondition` is failing to be met but I can't seem to find anything else in the docs that I am missing.

The full command and error message:

```bash
buck project --ide xcode
Using buckd.
[+] PROCESSING BUCK FILES...0.2s [100%]
[-] GENERATING PROJECT...FINISHED 0.0s
[2015-11-11 11:05:33.422][error][command:4b5ac7e3-fbcb-46be-b6ce-dfe28db2afc4][tid:649][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at com.facebook.buck.apple.WorkspaceAndProjectGenerator$2.apply(WorkspaceAndProjectGenerator.java:394)
	at com.facebook.buck.apple.WorkspaceAndProjectGenerator$2.apply(WorkspaceAndProjectGenerator.java:384)
	at com.google.common.base.Present.transform(Present.java:71)
	at com.facebook.buck.apple.WorkspaceAndProjectGenerator.writeWorkspaceSchemes(WorkspaceAndProjectGenerator.java:831)
	at com.facebook.buck.apple.WorkspaceAndProjectGenerator.generateWorkspaceAndDependentProjects(WorkspaceAndProjectGenerator.java:413)
	at com.facebook.buck.cli.ProjectCommand.generateWorkspacesForTargets(ProjectCommand.java:808)
	at com.facebook.buck.cli.ProjectCommand.runXcodeProjectGenerator(ProjectCommand.java:707)
	at com.facebook.buck.cli.ProjectCommand.runWithoutHelp(ProjectCommand.java:432)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:154)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:827)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1202)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1263)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
```

**Comment by Coneko** [comment]
That's because the `BUCK` file is in the root of the repo probably, try to move it into a subdirectory.

**Comment by twoism** [comment]
Thanks for the help! We we able to fix it by changing `cxx_binary` to `cxx_library`. Should `cxx_binary` work for XCode projects?

**Comment by sdwilsh** [comment]
Not currently, no.  This just came up in our discussion group as well: https://groups.google.com/forum/#!topic/buck-build/6uQ0yhqqR0I

**Comment by twoism** [comment]
OK, I'll close this then. Thanks!
