### ISSUE TITLE
BUILD FAILED: Environment variable ANDROID_HOME points to invalid path

### ISSUE THREAD

**Issue by Timeszoro** [facebook/buck#511]
I run the script like this 

genrule(
  name = 'gen',
  out = 'out.txt',
  cmd = 'cp $(location //some/other:rule) $OUT',
)

but get error below while i run other rules successfully

BUILD FAILED: Environment variable ANDROID_HOME points to invalid path [~/Library/Android/sdk].
java.lang.RuntimeException: Environment variable ANDROID_HOME points to invalid path [~/Library/Android/sdk].
java.lang.RuntimeException: Environment variable ANDROID_HOME points to invalid path [~/Library/Android/sdk].
	at com.facebook.buck.util.DefaultPropertyFinder.findDirectoryByPropertiesThenEnvironmentVariable(DefaultPropertyFinder.java:122)
	at com.facebook.buck.util.DefaultPropertyFinder.findDirectoryByPropertiesThenEnvironmentVariable(DefaultPropertyFinder.java:65)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.getSdkPathFromSdkDir(DefaultAndroidDirectoryResolver.java:115)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.access$0(DefaultAndroidDirectoryResolver.java:113)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver$1.get(DefaultAndroidDirectoryResolver.java:59)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver$1.get(DefaultAndroidDirectoryResolver.java:1)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.findAndroidSdkDirSafe(DefaultAndroidDirectoryResolver.java:74)
	at com.facebook.buck.cli.Main$2.get(Main.java:1015)
	at com.facebook.buck.cli.Main$2.get(Main.java:1)
	at com.facebook.buck.step.ExecutionContext.getAndroidPlatformTarget(ExecutionContext.java:170)
	at com.facebook.buck.shell.Genrule.addEnvironmentVariables(Genrule.java:223)
	at com.facebook.buck.shell.Genrule$2.addEnvironmentVariables(Genrule.java:293)
	at com.facebook.buck.shell.AbstractGenruleStep.getEnvironmentVariables(AbstractGenruleStep.java:67)
	at com.facebook.buck.shell.ShellStep.getDescription(ShellStep.java:231)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:56)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:954)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:937)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:354)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Coneko** [comment]
Do you have an android sdk in `~/Library/Android/sdk`? If not, unset the `ANDROID_HOME` environment variable.

**Comment by Timeszoro** [comment]
it has an android sdk in  ~/Library/Android/sdk

**Comment by k21** [comment]
It looks like your shell did not expand `~` to the absolute path to your home directory when the variable was assigned. Buck does not do this expansion, so you will have to change the contents of `ANDROID_HOME` to contain the absolute path. Use either `export ANDROID_HOME="${HOME}/Library/Android/sdk"` or `export ANDROID_HOME=~/Library/Android/sdk` to do that (in the second case note that there cannot be quotes around `~`, otherwise the shell won't expand it).

**Comment by Timeszoro** [comment]
thanks

**Comment by semassel-medlamine** [comment]
Still have the problem
