### ISSUE TITLE
Buck CI: Turn it off or fix

### ISSUE THREAD

**Issue by davido** [facebook/buck#571]
Travis-CI is currently broken and is spamming PR authors with unrelated failures, e.g.:

PR: https://github.com/facebook/buck/pull/558
CI-log:  Unrelated CI breakage: https://travis-ci.org/facebook/buck/builds/96222509

```
FAIL     17.0s  0 Passed   0 Skipped   6 Failed   com.facebook.buck.js.AndroidReactNativeLibraryIntegrationTest
FAILURE com.facebook.buck.js.AndroidReactNativeLibraryIntegrationTest testApkContainsJSAssetAndDrawables: Expected exit code 0 but was 1.
java.lang.AssertionError: Expected exit code 0 but was 1.
	at org.junit.Assert.fail(Assert.java:88)
	at com.facebook.buck.testutil.integration.ProjectWorkspace$ProcessResult.assertExitCode(ProjectWorkspace.java:638)
	at com.facebook.buck.testutil.integration.ProjectWorkspace$ProcessResult.assertSuccess(ProjectWorkspace.java:599)
	at com.facebook.buck.js.AndroidReactNativeLibraryIntegrationTest.testApkContainsJSAssetAndDrawables(AndroidReactNativeLibraryIntegrationTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.facebook.buck.testrunner.SameThreadFailOnTimeout$1.call(SameThreadFailOnTimeout.java:45)
	at com.facebook.buck.testrunner.SameThreadFailOnTimeout$1.call(SameThreadFailOnTimeout.java:41)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by k21** [comment]
I think I have a fix for the failing Android tests in #572.

**Comment by davido** [comment]
Thanks. This would be very much appreciated.

**Comment by sdwilsh** [comment]
Indeed, our Travis build has gone green again.
