### ISSUE TITLE
`SuperConsoleEventBusListenerTest` fails because of OS decimal separator setting

### ISSUE THREAD

**Issue by saper** [facebook/buck#58]
I was running "ant test" under FreeBSD with `LANG` set to `pl_PL.UTF-8` (which has comma as the decimal separator), and this fails:

```
    [junit] Testcase: testSimpleBuild took 0,008 sec
    [junit]     FAILED
    [junit] expected:<...D FILES...FINISHED 0[.]4s
    [junit] > but was:<...D FILES...FINISHED 0[,]4s
    [junit] >
    [junit] junit.framework.AssertionFailedError: expected:<...D FILES...FINISHED 0[.]4s
    [junit] > but was:<...D FILES...FINISHED 0[,]4s
    [junit] >
    [junit]     at com.facebook.buck.event.listener.SimpleConsoleEventBusListenerTest.testSimpleBuild(SimpleConsoleEventBusListenerTest.java:89)
    [junit] 
    [junit] TEST com.facebook.buck.event.listener.SimpleConsoleEventBusListenerTest FAILED
    [junit] Testsuite: com.facebook.buck.event.listener.SuperConsoleEventBusListenerTest
    [junit] Tests run: 1, Failures: 1, Errors: 0, Time elapsed: 0,022 sec
    [junit] 
    [junit] Testcase: testSimpleBuild took 0,012 sec
    [junit]     FAILED
    [junit] expected:<[[+] PARSING BUILD FILES...0.3s]> but was:<[[+] PARSING BUILD FILES...0,3s]>
    [junit] junit.framework.AssertionFailedError: expected:<[[+] PARSING BUILD FILES...0.3s]> but was:<[[+] PARSING BUILD FILES...0,3s]>
    [junit]     at com.facebook.buck.event.listener.SuperConsoleEventBusListenerTest.validateConsole(SuperConsoleEventBusListenerTest.java:199)
    [junit]     at com.facebook.buck.event.listener.SuperConsoleEventBusListenerTest.testSimpleBuild(SuperConsoleEventBusListenerTest.java:85)
    [junit] 
    [junit] TEST com.facebook.buck.event.listener.SuperConsoleEventBusListenerTest FAILED
```

**Comment by davido** [comment]
@sdwilsh Looks like we have a regression here: #557.
