### ISSUE TITLE
How the buck solve the problem: DexIndexOverflowException?

### ISSUE THREAD

**Issue by husky-yooho** [facebook/buck#588]
My project use: buck build app 
have the problem:

BUILD FAILED: //NewsArticle:NewsArticle#dex_merge failed on step dx with an exception:
field ID not in [0, 0xffff]: 65536
com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$5.updateIndex(DexMerger.java:482)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:302)
	at com.android.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:471)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:173)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:195)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:484)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:330)
	at com.android.dx.command.dexer.Main.run(Main.java:266)
	at com.android.dx.command.dexer.Main.run(Main.java:236)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:193)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:176)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:959)
	at com.facebook.buck.rules.CachingBuildEngine.access$7(CachingBuildEngine.java:942)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:362)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

1、
The solution in gradle is adding the code:
    defaultConfig {
        // Enabling multidex support.
        multiDexEnabled true
}

compile 'com.android.support:multidex:1.0.0'

2、
Now the buck how to solve the DexIndexOverflowException problem?

**Comment by husky-yooho** [comment]
I found the solution by searching other issue.

add such code in BUCK file:
```
android_binary(
      ...
      linear_alloc_hard_limit = 16 * 1024 * 1024,
      use_split_dex = True,
      use_linear_alloc_split_dex = True,
      ...
)
```
