### ISSUE TITLE
@RunWith(Suite.class) stopped working on 168ffb7c4d

### ISSUE THREAD

**Issue by spearce** [facebook/buck#592]
https://eclipse.googlesource.com/jgit/jgit/+/master/org.eclipse.jgit.test/tst/org/eclipse/jgit/transport/WalkEncryptionTest.java uses @RunWith(Suite.class):

@RunWith(Suite.class)
@Suite.SuiteClasses({ //
		WalkEncryptionTest.Required.class, //
		WalkEncryptionTest.MinimalSet.class, //
		WalkEncryptionTest.TestablePBE.class, //
		WalkEncryptionTest.TestableTransformation.class, //
})

FAIL     244ms  0 Passed  14 Skipped   1 Failed   org.eclipse.jgit.transport.WalkEncryptionTest
FAILURE org.eclipse.jgit.transport.WalkEncryptionTest initializationError: No tests found matching TestSelectorList-filter from org.junit.runner.Request$1@59b3beac
java.lang.Exception: No tests found matching TestSelectorList-filter from org.junit.runner.Request$1@59b3beac
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.facebook.buck.testrunner.JUnitRunner.run(JUnitRunner.java:149)
	at com.facebook.buck.testrunner.BaseRunner.runAndExit(BaseRunner.java:219)
	at com.facebook.buck.testrunner.JUnitMain.main(JUnitMain.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.facebook.buck.jvm.java.runner.FileClassPathRunner.main(FileClassPathRunner.java:87)

Git bisect tracked the change down to:

commit 168ffb7c4d8a9f5d214e025e344f45e5edb1fb3f
Author: Andrew Gallagher <agallagher@fb.com>
Date:   Mon Dec 14 13:30:09 2015 -0800

    JUnitRunner: hand `@SuiteClasses` annotation properly in dry run
    
    Summary:
    Previously, we'd print results in a normal test run when a test used
    the `RunWith` and `SuiteClasses` annotations, but not when running
    the test with `--dry-run`.
    
    Test Plan: added tests
    
    Reviewed By: marcinkosiba
    
    fb-gh-sync-id: 9ace74e

**Comment by LegNeato** [comment]
:point_right: @andrewjcg

**Comment by sdwilsh** [comment]
The revert should go out soon.  Pretty much everyone on the team was on PTO, so we had a slow response time here and I feel bad about that.
