### ISSUE TITLE
buck test is broken in cross-cell context

### ISSUE THREAD

**Issue by davido** [facebook/buck#599]
With this change applied: [1] and with patched Buck with this PR applied: https://github.com/facebook/buck/pull/558, `buck test` is failing with:

```
$ buck test
:::
::: '.nobuckcheck' file is present. Not updating buck.
:::
[2016-01-04 23:42:47.618][error][command:20e72ca2-588b-4d92-a68e-eeb386083c7c][tid:1494][com.facebook.buck.cli.Main] Uncaught exception at top level
java.nio.file.FileSystemLoopException: /home/davido/projects/gerrit/lib/jgit/lib
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:149)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at com.facebook.buck.io.ProjectFilesystem.walkRelativeFileTree(ProjectFilesystem.java:495)
	at com.facebook.buck.io.ProjectFilesystem.walkRelativeFileTree(ProjectFilesystem.java:456)
	at com.facebook.buck.parser.AbstractBuildFileSpec.forEachBuildFile(AbstractBuildFileSpec.java:78)
	at com.facebook.buck.parser.BuildFileSpec.forEachBuildFile(BuildFileSpec.java:1)
	at com.facebook.buck.parser.AbstractBuildFileSpec.findBuildFiles(AbstractBuildFileSpec.java:130)
	at com.facebook.buck.parser.BuildFileSpec.findBuildFiles(BuildFileSpec.java:1)
	at com.facebook.buck.parser.Parser.resolveTargetSpecsInParallel(Parser.java:514)
	at com.facebook.buck.parser.Parser.buildTargetGraphForTargetNodeSpecs(Parser.java:433)
	at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:380)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:168)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:86)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:953)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1372)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1457)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1486)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

* [1] https://gerrit-review.googlesource.com/73000

**Comment by davido** [comment]
After talking to @sdwilsh on the IRC, it turns out to be a symbolic link problem, that was done to male cross-cell stuff working with include_defs() to resolve maven artifacts: [1].

And the failure is repoducable with `buck build` too:

```
$ buck build ...
:::
::: '.nobuckcheck' file is present. Not updating buck.
:::
[2016-01-05 00:10:39.433][error][command:b0a99aa1-0289-4944-9ba3-fe2a271b2fca][tid:17][com.facebook.buck.cli.Main] Uncaught exception at top level
java.nio.file.FileSystemLoopException: /home/davido/projects/gerrit/lib/jgit/lib
```

Creating symbolic links was a hack to make include_defs to work in cross-cell dependency context: [2]. 

So the correct solution here seems to migrate our own Maven toolchain to `buck fetch` and get rid of this includes altogether.

[1] http://paste.openstack.org/show/482980
[2] http://paste.openstack.org/show/482985

**Comment by davido** [comment]
This rises another question, how the `build file `buildfile.includes` would be resolved in cross-cell context. Consider this .buckconfig content:

```
[buildfile]
  includes = //tools/default.defs
```

This `gwt_module´ definition in gerrit/tools/default.defs:

```
def gwt_module(gwt_xml=None, **kwargs):
  kw = copy.deepcopy(kwargs)
  if 'resources' not in kw:
    kw['resources'] = []
  if gwt_xml:
    kw['resources'] += [gwt_xml]
  if 'srcs' in kw:
    kw['resources'] += kw['srcs']

  # Buck does not accept duplicate resources. Callers may have
  # included gwt_xml or srcs as part of resources, so de-dupe.
  kw['resources'] = list(set(kw['resources']))

  java_library(**kw)
```

Now, when the cell's own BUCK file would try to reference this function:

```
gwt_module(
  name = 'Edit',
  srcs = [':jgit_edit_src'],
  deps = [':edit_src'],
  visibility = ['PUBLIC'],
)
```

This can't work, because this cell doesn't have `.buckconfig` file, where `build file.includes`is defined, so that the would fail with: 

```
$ buck targets //...
<path>lib/jgit/BUCK", line 7, in <module>
    gwt_module(
NameError: name 'gwt_module' is not defined
```

When we would define `buildfile.includes` in <path>/lib/jgit/.buckconfig to be:

```
[buildfile]
  includes = //tools/default.defs
```
as it's already the case in main `.buckconfig` file, then we would get different error:

```
Parse error for build file <path>/lib/jgit/BUCK: IOError: [Errno 2] No such file or directory: '<path>/lib/jgit/tools/default.defs'
```

**Comment by davido** [comment]
Turned out, it was symlinks to parent directories problem. Buck doesn't support that.
