### ISSUE TITLE
Autodiscovery of Go compiler fails when color is enabled

### ISSUE THREAD

**Issue by nemith** [facebook/buck#631]
If i create a sample project using a go_binary on my ubuntu system using all the go defaults build fails trying to find the compiler.

It looks like Buck is properly using 'go env GOTOOLDIR' to find the path, but somehow is appending to my current working directory and ignoring the root.

```
$ buck build //simple_binary:xyzzy                                                                                                                 
Not using buckd because watchman isn't installed.
BUILD FAILED: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory$2.getAppendableRuleKey(DefaultRuleKeyBuilderFactory.java:70)
	at com.facebook.buck.rules.RuleKeyBuilder.setAppendableRuleKey(RuleKeyBuilder.java:162)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:168)
	at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:31)
	at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory.newInstance(ReflectiveRuleKeyBuilderFactory.java:78)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory.newInstance(DefaultRuleKeyBuilderFactory.java:95)
	at com.facebook.buck.rules.BuildRuleEvent$Suspended.<init>(BuildRuleEvent.java:167)
	at com.facebook.buck.rules.BuildRuleEvent.suspended(BuildRuleEvent.java:69)
	at com.facebook.buck.rules.CachingBuildEngine$11.apply(CachingBuildEngine.java:945)
	at com.facebook.buck.rules.CachingBuildEngine$11.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$2.apply(Futures.java:760)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory$2.getAppendableRuleKey(DefaultRuleKeyBuilderFactory.java:70)
	at com.facebook.buck.rules.RuleKeyBuilder.setAppendableRuleKey(RuleKeyBuilder.java:162)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:168)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:181)
	at com.facebook.buck.rules.CommandTool.appendToRuleKey(CommandTool.java:113)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory$1.load(DefaultRuleKeyBuilderFactory.java:48)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory$1.load(DefaultRuleKeyBuilderFactory.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 20 more
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
	at com.facebook.buck.rules.HashedFileTool.appendToRuleKey(HashedFileTool.java:50)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory$1.load(DefaultRuleKeyBuilderFactory.java:48)
	at com.facebook.buck.rules.keys.DefaultRuleKeyBuilderFactory$1.load(DefaultRuleKeyBuilderFactory.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 35 more
Caused by: java.nio.file.NoSuchFileException: /home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
	at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:73)
	at com.facebook.buck.rules.RuleKeyBuilder.setPath(RuleKeyBuilder.java:245)
	at com.facebook.buck.rules.HashedFileTool.appendToRuleKey(HashedFileTool.java:47)
	... 41 more

[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.2s [100%] (0/4 JOBS, 0 UPDATED, 0.0% CACHE MISS)
```

Key part seems to be here.  Note the two // in the middle and newline before /compile
```
/home/bbennett/src/test//usr/lib/go/pkg/tool/linux_amd64
/compile
```

If i specify the linker and compiler in .buckconfig it works fine.
```
$ cat .buckconfig                                                                                                                                              
[go]
linker=/usr/lib/go/pkg/tool/linux_amd64/link
compiler=/usr/lib/go/pkg/tool/linux_amd64/compile
root=/usr/lib/go
$ buck build //simple_binary:xyzzy                                                                                                                 
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.4s [100%] (1/4 JOBS, 0 UPDATED, 0.0% CACHE MISS)

**Comment by nemith** [comment]
@mikekap

**Comment by mikekap** [comment]
That path is definitely weird. I'm especially surprised about the newline at the end - are you sure it's not a wrapped line? There's an explicit trim around `go env GOTOOLDIR`.

Could you paste the output of `go env` (and maybe `go env GOTOOLDIR`) here? I'm really failing to see how $PWD got prepended to the path.

**Comment by nemith** [comment]
Somehow there are some color characters getting mixed in with the command output.  I don't see these color codes when running go env from my shell so buck is adding them somehow.

http://i.imgur.com/hvDXNzg.png

**Comment by nemith** [comment]
If i set the following in .buckconfig

```
[color]
   ui = false
```

It works fine.

**Comment by mikekap** [comment]
Ah I see; seems I forgot to say EXPECTING_STD_OUT when running `go env GOTOOLDIR`. Could you try https://github.com/mikekap/buck/tree/fix_go_discovery and let me know if it works?

**Comment by nemith** [comment]
Yeah I added it internally and it works now.  Thanks for looking!
