### ISSUE TITLE
Buck Cli Not Working

### ISSUE THREAD

**Issue by tcyrus** [facebook/buck#638]
Installed buck using brew, when I try to run it I get this:

```
$ buck --help
Not using buckd because watchman isn't installed.
[2016-01-29 11:47:35.979][error][command:f3397a50-7979-4a62-8eea-8dd718719bda][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalAccessError: tried to access field com.sun.jna.Pointer.peer from class com.sun.jna.PointerTool
    at com.sun.jna.PointerTool.getPeer(PointerTool.java:13)
    at ca.weblite.objc.mappers.NSObjectMapping.cToJ(NSObjectMapping.java:38)
    at ca.weblite.objc.TypeMapper.cToJ(TypeMapper.java:122)
    at ca.weblite.objc.RuntimeUtils.msg(RuntimeUtils.java:619)
    at ca.weblite.objc.Client.send(Client.java:164)
    at ca.weblite.objc.Client.sendProxy(Client.java:344)
    at ca.weblite.objc.Client.sendProxy(Client.java:382)
    at com.facebook.buck.util.environment.MacWifiSsidFinder.getDefaultWifiInterface(MacWifiSsidFinder.java:77)
    at com.facebook.buck.util.environment.MacWifiSsidFinder.findCurrentSsid(MacWifiSsidFinder.java:61)
    at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getWifiSsid(DefaultExecutionEnvironment.java:84)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:859)
    at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1400)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1485)
    at com.facebook.buck.cli.Main.main(Main.java:1503)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
```

Same issue happens when using watchman

```
$ buck --help
Using watchman.
[2016-01-29 11:48:43.645][error][command:992b0bda-8543-4f16-810d-da0100c15f37][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalAccessError: tried to access field com.sun.jna.Pointer.peer from class com.sun.jna.PointerTool
    at com.sun.jna.PointerTool.getPeer(PointerTool.java:13)
    at ca.weblite.objc.mappers.NSObjectMapping.cToJ(NSObjectMapping.java:38)
    at ca.weblite.objc.TypeMapper.cToJ(TypeMapper.java:122)
    at ca.weblite.objc.RuntimeUtils.msg(RuntimeUtils.java:619)
    at ca.weblite.objc.Client.send(Client.java:164)
    at ca.weblite.objc.Client.sendProxy(Client.java:344)
    at ca.weblite.objc.Client.sendProxy(Client.java:382)
    at com.facebook.buck.util.environment.MacWifiSsidFinder.getDefaultWifiInterface(MacWifiSsidFinder.java:77)
    at com.facebook.buck.util.environment.MacWifiSsidFinder.findCurrentSsid(MacWifiSsidFinder.java:61)
    at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getWifiSsid(DefaultExecutionEnvironment.java:84)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:859)
    at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1400)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1485)
    at com.facebook.buck.cli.Main.main(Main.java:1503)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
```

**Comment by Coneko** [comment]
What version of java are you using? `java -version` will tell you.

**Comment by tcyrus** [comment]
```
$ java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```

**Comment by shs96c** [comment]
I see this too, but only when running the PEX.
