### ISSUE TITLE
Multiple entries with same key when building

### ISSUE THREAD

**Issue by mremick** [facebook/buck#648]
Having a multiple entries exception while trying to set up my project. The directory it fails on is a folder of symbolic links. Also, these files were generated from cocoapods. Any help would be appreciated. Thanks!

Here's the log: 

mremick$ buck build myApp
Using buckd.
[+] PROCESSING BUCK FILES...1.3s
[2016-02-04 11:46:54.217][error][command:674ac172-1639-4b0b-b678-6ae7b0722dd3][tid:229][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalArgumentException: Multiple entries with same key: AFHTTPClient.h=/Users/mremick/Desktop/myApp/Pods/Headers/Private/AFNetworking/AFHTTPClient.h and AFHTTPClient.h=/Users/mremick/Desktop/myApp/Pods/Headers/Public/AFNetworking/AFHTTPClient.h
    at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
    at com.google.common.collect.ImmutableSortedMap.validateEntries(ImmutableSortedMap.java:300)
    at com.google.common.collect.ImmutableSortedMap.fromEntries(ImmutableSortedMap.java:286)
    at com.google.common.collect.ImmutableSortedMap$Builder.build(ImmutableSortedMap.java:408)
    at com.facebook.buck.apple.AppleDescriptions.convertToFlatCxxHeaders(AppleDescriptions.java:172)
    at com.facebook.buck.apple.AppleDescriptions.parseAppleHeadersForUseFromTheSameTarget(AppleDescriptions.java:150)
    at com.facebook.buck.apple.AppleDescriptions.convertAppleHeadersToPrivateCxxHeaders(AppleDescriptions.java:110)
    at com.facebook.buck.apple.AppleDescriptions.populateCxxConstructorArg(AppleDescriptions.java:192)
    at com.facebook.buck.apple.AppleDescriptions.populateCxxBinaryDescriptionArg(AppleDescriptions.java:234)
    at com.facebook.buck.apple.AppleBinaryDescription.createBuildRule(AppleBinaryDescription.java:81)
    at com.facebook.buck.apple.AppleBinaryDescription.createBuildRule(AppleBinaryDescription.java:36)
    at com.facebook.buck.cli.BuildTargetNodeToBuildRuleTransformer.transform(BuildTargetNodeToBuildRuleTransformer.java:60)
    at com.facebook.buck.rules.TargetGraphToActionGraph$3.visit(TargetGraphToActionGraph.java:128)
    at com.facebook.buck.rules.TargetGraphToActionGraph$3.visit(TargetGraphToActionGraph.java:119)
    at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:62)
    at com.facebook.buck.rules.TargetGraphToActionGraph.createActionGraph(TargetGraphToActionGraph.java:151)
    at com.facebook.buck.rules.TargetGraphToActionGraph.apply(TargetGraphToActionGraph.java:85)
    at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:287)
    at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:228)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:153)
    at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:769)
    at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1137)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1194)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1223)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)

**Comment by Coneko** [comment]
It's failing because you have the same header both in public and in private headers.

**Comment by sdwilsh** [comment]
We should probably make this error message better.

**Comment by GunNan** [comment]
Hi, I have a similar problem when build my app on Windows. 

Here's the log:

`BUILT 157/161 JOBS 0.9s //:jars__libs\eup_1.9.14__allproguad_rqdp.jar#dex

BUILD FAILED: Multiple entries with same key: com\tencent\feedback\proguard\E.class=HashCodeAndFileType{type=FILE,getHashCode=44cacdc0161040a4916554e84e1ceed1, children=[]} and com\tencent\feedback\proguard\e.class=HashCodeAndFileType{type=FILE,getHashCode=40bf25f328d1275b1870c8b941239427, children=[]}

java.lang.IllegalArgumentException: Multiple entries with same key: com\tencent\feedback\proguard\E.class=HashCodeAndFileType{type=FILE,getHashCode=44cacdc0161040a4916554e84e1ceed1, children=[]} and com\tencent\feedback\proguard\e.class=HashCodeAndFileType{type=FILE,getHashCode=40bf25f328d1275b1870c8b941239427, children=[]}

java.lang.IllegalArgumentException: Multiple entries with same key: com\tencent\feedback\proguard\E.class=HashCodeAndFileType{type=FILE,getHashCode=44cacdc0161040a4916554e84e1ceed1, children=[]} and com\tencent\feedback\proguard\e.class=HashCodeAndFileType{type=FILE,getHashCode=40bf25f328d1275b1870c8b941239427, children=[]}

	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.facebook.buck.util.cache.JarContentHasher.getContentHashes(JarContentHasher.java:72)
	at com.facebook.buck.util.cache.AbstractHashCodeAndFileType.getContents(AbstractHashCodeAndFileType.java:49)
	at com.facebook.buck.util.cache.HashCodeAndFileType.getContents(HashCodeAndFileType.java:215)
	at com.facebook.buck.util.cache.DefaultFileHashCache.get(DefaultFileHashCache.java:210)
	at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:111)
	at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:111)
	at com.facebook.buck.rules.RuleKeyBuilder.setArchiveMemberPath(RuleKeyBuilder.java:289)
	at com.facebook.buck.rules.keys.DefaultDependencyFileRuleKeyBuilderFactory$BuilderWrapper.addToRuleKey(DefaultDependencyFileRuleKeyBuilderFactory.java:228)
	at com.facebook.buck.rules.keys.DefaultDependencyFileRuleKeyBuilderFactory$DependencyFileRuleKeyBuilder.build(DefaultDependencyFileRuleKeyBuilderFactory.java:167)
	at com.facebook.buck.rules.keys.DefaultDependencyFileRuleKeyBuilderFactory.build(DefaultDependencyFileRuleKeyBuilderFactory.java:64)
	at com.facebook.buck.rules.CachingBuildEngine.calculateDepFileRuleKey(CachingBuildEngine.java:1367)
	at com.facebook.buck.rules.CachingBuildEngine.access$8(CachingBuildEngine.java:1345)
	at com.facebook.buck.rules.CachingBuildEngine$6.apply(CachingBuildEngine.java:616)
	at com.facebook.buck.rules.CachingBuildEngine$6.apply(CachingBuildEngine.java:1)
	at com.facebook.buck.rules.CachingBuildEngine$16.apply(CachingBuildEngine.java:1710)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$3.call(WeightedListeningExecutorService.java:102)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by SwiftlyFly** [comment]
@mremick have you solved this problm?  thanks!
