### ISSUE TITLE
RuntimeError when running fetch on Windows

### ISSUE THREAD

**Issue by janicduplessis** [facebook/buck#649]
I get this error trying to build react native with buck on Windows. It works fine on my Mac.

I'm using buck from master and python 2.7.11.

```
C:\Users\janic\Developer\react-native>buck fetch ReactAndroid/src/main/java/com/facebook/react
Not using buckd because watchman isn't installed.
Warning raised by BUCK file parser: Traceback (most recent call last):
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.unzln3\buck1494403354654771159.py", line 2279, in <module>
Warning raised by BUCK file parser:     main()
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.unzln3\buck1494403354654771159.py", line 851, in main
Warning raised by BUCK file parser:     for section, contents in bser.loads(f.read()).iteritems():
Warning raised by BUCK file parser:   File "C:/Users/janic/Developer/buck/third-party/py/pywatchman\pywatchman\pybser.py", line 292, in loads
Warning raised by BUCK file parser:     raise RuntimeError('bser data len != header len')
Warning raised by BUCK file parser: RuntimeError: bser data len != header len
Warning raised by BUCK file parser: Traceback (most recent call last):
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.unzln3\buck2963190285078485547.py", line 2279, in <module>
Warning raised by BUCK file parser:     main()
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.unzln3\buck2963190285078485547.py", line 851, in main
Warning raised by BUCK file parser:     for section, contents in bser.loads(f.read()).iteritems():
Warning raised by BUCK file parser:   File "C:/Users/janic/Developer/buck/third-party/py/pywatchman\pywatchman\pybser.py", line 292, in loads
Warning raised by BUCK file parser:     raise RuntimeError('bser data len != header len')
Warning raised by BUCK file parser: RuntimeError: bser data len != header len
Parse error for build file C:\Users\janic\Developer\react-native\ReactAndroid\src\main\java\com\facebook\react\BUCK: Parser exited unexpectedly
```

**Comment by LegNeato** [comment]
Are you using `watchman`? If so, what version? If not, does the issue go away if you install it?

**Comment by janicduplessis** [comment]
No I was not, I tried installing watchman version 3.7.0 and now I get this error

```
C:\Users\janic\Developer\react-native>buck fetch ReactAndroid/src/main/java/com/facebook/react
Using watchman.
Traceback (most recent call last):
  File "C:\Users\janic\Developer\buck\bin\..\programs\buck.py", line 54, in <module>
    propagate_failure(main(sys.argv))
  File "C:\Users\janic\Developer\buck\bin\..\programs\buck.py", line 47, in main
    return buck_repo.launch_buck(build_id)
  File "C:\Users\janic\Developer\buck\programs\buck_tool.py", line 124, in launch_buck
    self.launch_buckd(buck_version_uid=buck_version_uid)
  File "C:\Users\janic\Developer\buck\programs\buck_tool.py", line 251, in launch_buckd
    env=self._environ_for_buck())
  File "C:\Python27\lib\subprocess.py", line 663, in __init__
    raise ValueError("preexec_fn is not supported on Windows "
ValueError: preexec_fn is not supported on Windows platforms
```

**Comment by LegNeato** [comment]
OK, that makes sense...looks like this needs to be `None`:

https://github.com/facebook/buck/blob/43ee655dbf0a442fb57ef8cfc04595c0d96c0ecf/programs/buck_tool.py#L250

in order to not throw on Windows.

**Comment by janicduplessis** [comment]
I made the change you suggested and now I get the first error again.

**Comment by sdwilsh** [comment]
`buckd` doesn't work on Windows (yet - @bhamiltoncx has some patches in progress).  If you set `NO_BUCKD=1` in your environment (`$env:NO_BUCKD=1` in powershell), you should be able to get past that.

**Comment by janicduplessis** [comment]
@sdwilsh That solves the watchman / buckd issues but I still get that Parser exited unexpectedly error :(
```
buck fetch ReactAndroid/src/main/java/com/facebook/react
Warning raised by BUCK file parser: Traceback (most recent call last):
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.dns0oz\buck6697034944139676414.py", line 2279, in <module>
Warning raised by BUCK file parser:     main()
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.dns0oz\buck6697034944139676414.py", line 851, in main
Warning raised by BUCK file parser:     for section, contents in bser.loads(f.read()).iteritems():
Warning raised by BUCK file parser:   File "C:/Users/janic/Developer/buck/third-party/py/pywatchman\pywatchman\pybser.py", line 292, in loads
Warning raised by BUCK file parser:     raise RuntimeError('bser data len != header len')
Warning raised by BUCK file parser: RuntimeError: bser data len != header len
Warning raised by BUCK file parser: Traceback (most recent call last):
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.dns0oz\buck6576104595802619759.py", line 2279, in <module>
Warning raised by BUCK file parser:     main()
Warning raised by BUCK file parser:   File "C:\Users\janic\Developer\react-native\buck-out\tmp\buck_run.dns0oz\buck6576104595802619759.py", line 851, in main
Warning raised by BUCK file parser:     for section, contents in bser.loads(f.read()).iteritems():
Warning raised by BUCK file parser:   File "C:/Users/janic/Developer/buck/third-party/py/pywatchman\pywatchman\pybser.py", line 292, in loads
Warning raised by BUCK file parser:     raise RuntimeError('bser data len != header len')
Warning raised by BUCK file parser: RuntimeError: bser data len != header len
Parse error for build file C:\Users\janic\Developer\react-native\ReactAndroid\src\main\java\com\facebook\react\BUCK: Parser exited unexpectedly
Not using buckd because NO_BUCKD is set.
```

**Comment by bhamiltoncx** [comment]
Eek. I suspect an LP64 vs. LLP64 issue in pybser. Summoning @wez..

**Comment by wez** [comment]
Can we get a copy of whatever that blob is that is trying to be decoded? the subject of the f.read() call

**Comment by janicduplessis** [comment]
@wez Any tips on how to get that data? Seems to be happening in a generated script so I can't really just add a print.

**Comment by wez** [comment]
I honestly don't know the answer to that; I wrote the bser stuff but for a different project.  Buck folks, is there a way to get a hold of that data?

**Comment by janicduplessis** [comment]
I can get the string in buf from pybser.py:287 before the RuntimeError is raised. It is `'yandroidtarget'`.

**Comment by janicduplessis** [comment]
That should actually be what f.read() returned.

**Comment by wez** [comment]
Can you get that in hex?
http://stackoverflow.com/a/12214957/149111 may help

**Comment by janicduplessis** [comment]
`00:01:05:79:00:00:00:01:03:02:02:03:07:61:6e:64:72:6f:69:64:01:03:01:02:03:06:74:61:72:67:65:74:02:03`

**Comment by bhamiltoncx** [comment]
I need to get my Win32 VM up and running again, but I suspect this *might* be related to Win32 Python opening files in text mode by default.

I pushed a speculative commit to https://github.com/facebook/buck/commits/bhamiltoncx-win32-bser . Can you try cherry-picking it?

f7ccbf6bd15dfd7200d14c069a1d1e72d448aba9

**Comment by janicduplessis** [comment]
@bhamiltoncx :+1: Works now, well almost... Probably not related at all but it seems to have trouble downloading support-v4:aar:23.0.1 from maven.
```
$ buck fetch ReactAndroid/src/main/java/com/facebook/react
[-] PARSING BUCK FILES...FINISHED 0.4s [100%]
BUILT //ReactAndroid/src/main/third-party/java/okio:okio-binary-jar (1/8 JOBS)
BUILT //ReactAndroid/src/main/third-party/java/javapoet:jsr305-binary-jar (2/8 JOBS)
BUILT //ReactAndroid/src/main/third-party/java/okhttp:okhttp-ws-binary-jar (3/8 JOBS)
Unable to download: mvn:com.android.support:support-v4:aar:23.0.1
BUILT //ReactAndroid/src/main/third-party/java/okhttp:okhttp-binary-jar (5/8 JOBS)
BUILT //ReactAndroid/src/main/third-party/java/jsr-305:jsr305-binary-jar (6/8 JOBS)
BUILT //ReactAndroid/src/main/libraries/fbcore/src/main/java/com/facebook/common/logging:fbcore-binary-aar (7/8 JOBS)
BUILT //ReactAndroid/src/main/third-party/java/jackson:jackson-core-binary-jar (8/8 JOBS)
BUILD FAILED: //ReactAndroid/src/main/third-party/android/support/v4:lib-support-v4-binary-aar failed with exit code -1:
curl
[-] BUILDING...FINISHED 1.9s [100%]
Not using buckd because NO_BUCKD is set.
```

**Comment by bhamiltoncx** [comment]
That's great! The power of randomly guessing a bug fix.. ;)
2016年2月9日(火) 17:02 Janic Duplessis <notifications@github.com>:

**Comment by sdwilsh** [comment]
@janicduplessis - do you have the "Android Support Repository" and "Google Repository" downloaded from the SDK Manager under the extras section?

**Comment by janicduplessis** [comment]
@sdwilsh From what I understand it is supposed to download it right? But I have both Android Support Repository and Google Repository installed in the SDK Manager $ANDROID_HOME and $ANDROID_SDK is set too.

That is the relevant part of the buckfile that handles the support-v4 lib.
```
android_prebuilt_aar(
    name = 'lib-support-v4',
    aar = ':lib-support-v4-binary-aar',
    visibility = ['//ReactAndroid/...',],
)

remote_file(
    name = 'lib-support-v4-binary-aar',
    url = 'mvn:com.android.support:support-v4:aar:23.0.1',
    sha1 = '9e8da0e4ecf9f63258c7fbd273889252cba2d0c3',
)
```

**Comment by bhamiltoncx** [comment]
The message `Unable to download: mvn:com.android.support:support-v4:aar:23.0.1` means the HTTP downloader either returned `false` or threw an `IOException` while trying to download the file.

It looks like the `HttpDownloader` class should write to `buck-out/log/buck-0.log` when this happens. Can you look for a message like `Unable to download x: y` in that log and paste it here?

**Comment by sdwilsh** [comment]
Those should both be on-disk maven downloaders from the SDK.  For me, that library is located under `$ANDROID_HOME\extras\android\m2repository\com\android\support\support-v4\23.0.1\support-v4-23.0.1.aar`.  Does that file exist for you?

**Comment by janicduplessis** [comment]
@sdwilsh Yes the file exists at the same path as you.

@bhamiltoncx 
```
[2016-02-09 20:09:33.889][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:17][com.facebook.buck.event.listener.LoggingBuildListener] DownloadStarted(https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.aar)
[2016-02-09 20:09:34.425][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:25][sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@7038b39f5 pairs: {GET /maven2/com/squareup/okhttp/okhttp/2.5.0/okhttp-2.5.0.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_60}{Host: repo1.maven.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[2016-02-09 20:09:34.425][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:19][sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@2e8160465 pairs: {GET /maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_60}{Host: repo1.maven.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[2016-02-09 20:09:34.425][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:23][sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@1f3a74925 pairs: {GET /maven2/com/squareup/okio/okio/1.6.0/okio-1.6.0.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_60}{Host: repo1.maven.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[2016-02-09 20:09:34.428][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:24][sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@6f6945d75 pairs: {GET /maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.aar HTTP/1.1: null}{User-Agent: Java/1.8.0_60}{Host: repo1.maven.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[2016-02-09 20:09:34.431][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:21][sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@58e1d7215 pairs: {GET /maven2/com/squareup/javapoet/1.2.0/javapoet-1.2.0.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_60}{Host: repo1.maven.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[2016-02-09 20:09:34.502][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:24][sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@2a78314d19 pairs: {null: HTTP/1.1 404 Not Found}{Last-Modified: Wed, 27 Jan 2016 19:34:29 GMT}{ETag: "1fb066da6a67c7c02962f59b4b8cd1ee"}{x-amz-error-code: NoSuchKey}{x-amz-error-message: The specified key does not exist.}{x-amz-error-detail-Key: maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.aar}{Content-Type: text/html}{Via: 1.1 varnish}{Fastly-Debug-Digest: 059906442ed9b0497976706da17e9e56bd5c00068f9debecca061ad6c90d1bdc}{Content-Length: 554}{Accept-Ranges: bytes}{Date: Wed, 10 Feb 2016 01:09:37 GMT}{Via: 1.1 varnish}{Age: 291436}{Connection: keep-alive}{X-Served-By: cache-iad2141-IAD, cache-atl6248-ATL}{X-Cache: HIT, HIT}{X-Cache-Hits: 58, 15}{X-Timer: S1455066577.205095,VS0,VE0}
[2016-02-09 20:09:34.502][info ][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:24][com.facebook.buck.file.HttpDownloader] Unable to download https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.aar: Not Found
[2016-02-09 20:09:34.504][debug][command:ee4860f4-c919-4a1f-8d3a-bfe5be883f15][tid:17][com.facebook.buck.event.listener.LoggingBuildListener] DownloadFinished(https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.aar)
```

**Comment by bhamiltoncx** [comment]
OK, so it looks like it's not using the on-disk maven downloader. I think @sdwilsh seems to know more about that than I do, so I will let him chime in.

http://central.maven.org/maven2/com/google/android/support-v4/r7/support-v4-r7.jar is the correct URL for the support JAR, for what it's worth.

**Comment by sdwilsh** [comment]
@janicduplessis, can you upload your full log please?  Feel free to toss it in a gist.

**Comment by janicduplessis** [comment]
@sdwilsh Here's the log

https://gist.github.com/janicduplessis/637c419df71be012ce00

**Comment by janicduplessis** [comment]
Ok I found the issue, the problem is in `OnDiskMavenDownloader` in the `fetch` function. I removed the leading slash from the path returned by `MavenUrlDecoder.toHttpUrl(SPOOF_MAVEN_REPO, uri);`  and now `root.resolve` resolves to the right path instead of something like `file:///C:/com/android/support/support-v4/23.0.1/support-v4-23.0.1.aar
`.

**Comment by sdwilsh** [comment]
That'd be great!  We're about to get CI soon for Windows via #647, so hopefully we can start enabling more tests on Windows too.

**Comment by janicduplessis** [comment]
Thanks everyone for the help! :)

I submitted a PR to fix the last issue so I'll close this.
