### ISSUE TITLE
genrule is broken in cross-cell context

### ISSUE THREAD

**Issue by davido** [facebook/buck#654]
Given the following repository entry in `.buckconfig`:

```
[repositories]
  jgit = lib/jgit
```

and the following rule:

```
genrule(
  name = 'broken',
  cmd = 'echo $(location @jgit//:jgit) > $OUT',
  out = '__broken__fake__'
)
```

it works as expected. However, when `jgit` repository is replaced with a path outside of the current buck project (`/home/davido/projects/gerrit`):

```
jgit = /home/davido/projects/jgit
```

It's broken:

```
$ buck targets --json :broken
[+] PROCESSING BUCK FILES...0.3s [100%]
[
{
  "bash" : null,
  "buck.base_path" : "",
  "buck.direct_dependencies" : [ "//:jgit" ],
  "buck.type" : "genrule",
  "cmd" : "echo $(location @jgit//:jgit) > $OUT",
  "cmdExe" : null,
  "name" : "broken",
  "out" : "__broken__fake__",
  "srcs" : [ ],
  "visibility" : [ ]
}
]
```

The failure is:

```
$ buck build :broken
BUILD FAILED: com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.util.HumanReadableException: No known output for: //:jgit
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.util.HumanReadableException: No known output for: //:jgit
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.util.HumanReadableException: No known output for: //:jgit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory.build(ReflectiveRuleKeyBuilderFactory.java:91)
	at com.facebook.buck.rules.CachingBuildEngine$4.apply(CachingBuildEngine.java:382)
	at com.facebook.buck.rules.CachingBuildEngine$4.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.util.HumanReadableException: No known output for: //:jgit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$Builder.getAppendableRuleKey(InputBasedRuleKeyBuilderFactory.java:117)
	at com.facebook.buck.rules.RuleKeyBuilder.setAppendableRuleKey(RuleKeyBuilder.java:162)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:168)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:181)
	at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:31)
	at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory.newInstance(ReflectiveRuleKeyBuilderFactory.java:78)
	at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory$1.load(ReflectiveRuleKeyBuilderFactory.java:49)
	at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory$1.load(ReflectiveRuleKeyBuilderFactory.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 12 more
Caused by: com.facebook.buck.util.HumanReadableException: No known output for: //:jgit
	at com.facebook.buck.rules.SourcePathResolver.getPathPrivateImpl(SourcePathResolver.java:163)
	at com.facebook.buck.rules.SourcePathResolver.getAbsolutePath(SourcePathResolver.java:88)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$Builder.setSourcePath(InputBasedRuleKeyBuilderFactory.java:133)
	at com.facebook.buck.rules.RuleKeyBuilder.setSingleValue(RuleKeyBuilder.java:330)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:229)
	at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:202)
	at com.facebook.buck.rules.args.MacroArg.appendToRuleKey(MacroArg.java:81)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$1.load(InputBasedRuleKeyBuilderFactory.java:72)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$1.load(InputBasedRuleKeyBuilderFactory.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 28 more

[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.2s [100%] (2/20 JOBS, 0 UPDATED, 0.0% CACHE MISS)
```

**Comment by davido** [comment]
My fault.

The reason for the failure was, that the library in the foreign cell only had exported dependencies:

```
java_library(
  name = 'jgit',
  exported_deps = ['//org.eclipse.jgit:jgit'],
  visibility = ['PUBLIC'],
)
```

Changing it to:

```
prebuilt_jar(
  name = 'jgit2',
  binary_jar = '//org.eclipse.jgit:jgit',
  visibility = ['PUBLIC'],
)
```

fixed it.
