### ISSUE TITLE
iOS: Failure linking static ObjC framework from remote zip file

### ISSUE THREAD

**Issue by dflems** [facebook/buck#660]
_Reproducible build:_ https://github.com/dflems/buck-repro

Run `buck fetch //ios:BuckDemoApp && buck build //ios:BuckDemoApp` and notice the failures documented below. Running `buck project //ios:BuckDemoApp` will generate a project that Xcode has no problem building, but building with buck fails.

---

I created a simple [BUCK file](https://github.com/dflems/buck-repro/blob/3542ef17a2a36c20e244405d015059287bf463bb/fw/BUCK) that downloads a remote zip file and another genrule that unzips it and extracts a static ObjC framework. When trying to link the framework by adding it to the `frameworks` parameter of the demo app [here](https://github.com/dflems/buck-repro/blob/3542ef17a2a36c20e244405d015059287bf463bb/ios/BUCK#L21), `buck build` fails with this exception:

```
BUILD FAILED: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory.build(ReflectiveRuleKeyBuilderFactory.java:91)
    at com.facebook.buck.rules.CachingBuildEngine$4.apply(CachingBuildEngine.java:382)
    at com.facebook.buck.rules.CachingBuildEngine$4.apply(CachingBuildEngine.java:311)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
    at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$Builder.getAppendableRuleKey(InputBasedRuleKeyBuilderFactory.java:117)
    at com.facebook.buck.rules.RuleKeyBuilder.setAppendableRuleKey(RuleKeyBuilder.java:160)
    at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:168)
    at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:181)
    at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:31)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory.newInstance(ReflectiveRuleKeyBuilderFactory.java:78)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory$1.load(ReflectiveRuleKeyBuilderFactory.java:49)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory$1.load(ReflectiveRuleKeyBuilderFactory.java:46)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    ... 12 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$Builder.getAppendableRuleKey(InputBasedRuleKeyBuilderFactory.java:117)
    at com.facebook.buck.rules.RuleKeyBuilder.setAppendableRuleKey(RuleKeyBuilder.java:160)
    at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:168)
    at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:202)
    at com.facebook.buck.cxx.PreprocessorDelegate.appendToRuleKey(PreprocessorDelegate.java:128)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$1.load(InputBasedRuleKeyBuilderFactory.java:72)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$1.load(InputBasedRuleKeyBuilderFactory.java:67)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    ... 28 more
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$Builder.setSourcePath(InputBasedRuleKeyBuilderFactory.java:136)
    at com.facebook.buck.rules.RuleKeyBuilder.setSingleValue(RuleKeyBuilder.java:330)
    at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:229)
    at com.facebook.buck.rules.RuleKeyBuilder.setReflectively(RuleKeyBuilder.java:181)
    at com.facebook.buck.rules.coercer.AbstractFrameworkPath.appendToRuleKey(AbstractFrameworkPath.java:154)
    at com.facebook.buck.rules.coercer.FrameworkPath.appendToRuleKey(FrameworkPath.java:24)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$1.load(InputBasedRuleKeyBuilderFactory.java:72)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$1.load(InputBasedRuleKeyBuilderFactory.java:67)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    ... 43 more
Caused by: java.nio.file.NoSuchFileException: /Users/dflems/Desktop/repro/buck-out/gen/fw/Lookback/Lookback.framework
    at com.facebook.buck.util.cache.StackedFileHashCache.get(StackedFileHashCache.java:73)
    at com.facebook.buck.rules.RuleKeyBuilder.setPath(RuleKeyBuilder.java:245)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$Builder.setSourcePath(InputBasedRuleKeyBuilderFactory.java:132)
    ... 54 more

```

Any subsequent attempts then generate this exception:

```
BUILD FAILED: java.lang.IllegalStateException
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory.build(ReflectiveRuleKeyBuilderFactory.java:91)
    at com.facebook.buck.rules.CachingBuildEngine$4.apply(CachingBuildEngine.java:382)
    at com.facebook.buck.rules.CachingBuildEngine$4.apply(CachingBuildEngine.java:311)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
    at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
    at com.facebook.buck.rules.keys.InputBasedRuleKeyBuilderFactory$2.build(InputBasedRuleKeyBuilderFactory.java:95)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory$1.load(ReflectiveRuleKeyBuilderFactory.java:49)
    at com.facebook.buck.rules.keys.ReflectiveRuleKeyBuilderFactory$1.load(ReflectiveRuleKeyBuilderFactory.java:46)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    ... 12 more
```

**Comment by Coneko** [comment]
Oh yes, `frameworks` and `libraries` can only refer to system frameworks and libraries, not prebuilt ones.

We need to add support for frameworks to [prebuilt_cxx_library](https://buckbuild.com/rule/prebuilt_cxx_library.html).

**Comment by dflems** [comment]
@Coneko: Thanks. Perhaps it would make more sense to make prebuilt frameworks a first-class citizen? Though they're not particularly favorable, they're probably around to stay. Third-party SDKs frequently ship these as the *only* integration option.

Maybe something like this:

```python
apple_prebuilt_framework(
  name = 'MyFramework',
  path = 'path/to/MyFramework.framework', # or output of another genrule, etc.
  frameworks = ['$SDKROOT/System/Library/Frameworks/Foundation.framework'],
  exported_linker_flags = [],
  exported_preprocessor_flags = [],
  exported_deps = [':AnotherFramework'],
  force_static = False,
  link_style = 'static', # might need dynamic for OSX? not sure
  visibility = ['PUBLIC'],
)
```

IMO, it makes sense to make this syntactically closer to `apple_library` than to `prebuilt_cxx_library`. Frameworks are an Apple construct and may implicitly require other system frameworks, etc.

**Comment by adamhowardprice** [comment]
Any update on this?

**Comment by Coneko** [comment]
Here's a workaround you can use.

Assuming the prebuilt framework is a static framework called `Framework`:

```python
# like export_file, but xcode project generator can actually use this
genrule(
  name = 'SDKBinary',
  srcs = ['Framework.framework/Versions/A/Framework'],
  out = 'libFramework.a',
  bash = 'cp $SRCS $OUT',
)

ios_resource(
  name = 'FrameworkResources',
  dirs = ['Framework.framework/FrameworkResources.bundle'],
  files = [],
  variants = [],
)

ios_library(
  name = 'FrameworkSDK',
  srcs = ['src/dummy.c'],
  supported_platforms_regex = '^(iphoneos|iphonesimulator).*',

  # instructs buck based builds to conditionally link the library.
  # in xcode, $(location ...) is not resolved, so this is a no-op
  exported_linker_flags = [
    '$(location :SDKBinary)',
  ],

  # In xcode these build settings take effect
  # Instruct xcode to conditionally link the static library into this library.
  # for buck based builds, this option is ignored and this library is effectively empty.
  configs = fbobjc_configs(
    FBOBJC_STATIC_LIBRARY,
    extra_target_config={
      'OTHER_LIBTOOLFLAGS[sdk=iphone*]': '$(inherited) $(REPO_ROOT)/FrameworkSDK/Framework.framework/Versions/A/Framework',
    }
  ),

  deps = [
    ':SDKBinary',
    ':FrameworkResources',
  ],
  exported_headers = subdir_glob(
    [
      ('Framework.framework/Versions/A/Headers', '*.h'),
    ],
    prefix='Framework'
  ),
  visibility = [
    'PUBLIC',
  ],
)
```
