### ISSUE TITLE
ParsePipeline incorrectly shares raw nodes between cells

### ISSUE THREAD

**Issue by davido** [facebook/buck#717]
After upgrade of Gerrit Code Review to 9f45799db1cd25b02dadc7cc982f2264c1c13153 `buck test` is broken:

```
[2016-04-19 14:00:48.916][error][command:f86ac0d6-e7fe-473f-a86d-650b26c06570][tid:15][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: Raw data claims to come from [lib/jgit/org.eclipse.jgit], but we tried rooting it at [org.eclipse.jgit].
    at com.facebook.buck.parser.ParsePipeline.parseBuildTargetFromRawRule(ParsePipeline.java:556)
    at com.facebook.buck.parser.DaemonicParserState.createTargetNode(DaemonicParserState.java:395)
    at com.facebook.buck.parser.PerBuildState$3.createTargetNode(PerBuildState.java:134)
    at com.facebook.buck.parser.ParsePipeline$10.apply(ParsePipeline.java:460)
    at com.facebook.buck.parser.ParsePipeline$10.apply(ParsePipeline.java:1)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
    at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
    at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$3.call(WeightedListeningExecutorService.java:102)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
    at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
    at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

All is fine, when `buck test` is used on parent change: 6e1a5f500b54f839d7a63865d28de727944c33c5. Note, that Gerrit Code Review is using JGit cell, that (per default) points to sub-directory lib/jgit:

```
  $ tail -3 .buckconfig 
  [repositories]
  jgit = lib/jgit
```

To reproduce, pull Gerrit: [1] and run `buck test`.

[1] https://gerrit.googlesource.com/gerrit

**Comment by k21** [comment]
Looks like the new check in 9f45799db1cd25b02dadc7cc982f2264c1c13153 revealed an existing issue. `buck test` is equivalent to `buck test //...`, so it recursively finds all test targets, including targets under `lib/jgit`. This way you should get a graph that contains both `//lib/jgit:something` and `@jgit//:something`. However the parser cache uses only the absolute path of the BUCK file as the key, so it only parses that file once, although they should be treated as two different files.

As a workaround, you can add `lib/jgit` to `project.ignore` in `.buckconfig`, which will stop Buck from trying to parse `//lib/jgit:something` and only use the `@jgit//:something` targets if other targets depend on them.

**Comment by davido** [comment]
Thanks. Suggested workaround fixed it.

**Comment by Dominator008** [comment]
`buck audit` doesn't seem to ignore the added `lib/jgit` entry.

**Comment by k21** [comment]
@Dominator008 the `buck audit` problems seem to be caused by a different issue, however I am unable to reproduce them on Buck's master branch (673c14330b16b9e86ea425ad3d369dc28f8ae83a) and Gerrit revision 8a867d6414b55a3a6edb6f0b12725f4477301618. Can you please check if getting the latest Buck version fixes the problem? If not, please let me know which Gerrit commit you are using.

**Comment by Dominator008** [comment]
@k21 Hmmm. I can't reproduce it either. I guess `buck audit` is fine then. We removed the JGit cell for now so some state of the project might have changed on my machine. Commands like:
```sh
buck build //lib/jgit/org.eclipse.jgit:jgit__download_bin
```
still throw an exception, but that's part of the reported issue.

**Comment by davido** [comment]
@k21 This is probably gerrit issue. To reproduce, revert https://github.com/gerrit-review/gerrit/commit/08ea694499c79f7ea07d7e704cffcc4649cbc708 on most recent gerrit master and issue:

```
  $ tools/eclips/project.py
```

What we are doing is issuing `buck audit` and then call specific rules that end with src. For cell based rule we replace jgit cell with its own path, "lib/jgit" in this case, so that from:

```
"@jgit//org.eclipse.jgit.archive:jgit-archive" -> "//org.eclipse.jgit.archive:jgit-archive__download_src"
```

we are calling:

```
  buck build "//lib/jgit/org.eclipse.jgit.archive:jgit-archive"
```

this is failing with: [1]. Shouldn't we be able to use '+' prefix instead?

```
  buck build +jgit//org.eclipse.jgit.archive:jgit-archive
  BUILD FAILED: Build target path cannot be absolute or contain . or .. (found //+jgit//org.eclipse.jgit.archive:jgit-archive)
```

* [1] http://paste.openstack.org/show/495190/

**Comment by Dominator008** [comment]
@davido I'd expect a clear error message instead of an exception.

**Comment by davido** [comment]
@Dominator008 good point. OTOH we are doing something wrong that we don't supposed to do: calling cell based target by rellocating it to the wrong root.

We did it in older Buck versions because this was the only workaround to call a cell-based target from CLI. With most recent Buck master, this workaround doesn't work any more, see the exception. That why we are stuck with cross-cell stuf: it's always needed to invoce a cross-based target from CLI.

**Comment by k21** [comment]
@davido I think Buck should handle building the target both locally and as a cross-cell target, so I do consider this a bug. Only using one of the options in all invocations and dependencies fixes this, but it's just a workaround.

We decided to completely drop the cross-cell prefix in the latest Buck revision (the `+` would introduce ambiguities in `buck query` syntax). The motivation is to make it possible to run for example `buck build jgit//org.eclipse.jgit.archive:jgit-archive__download_src` and have it build the cross-cell target, unfortunately this functionality is not implemented yet.

Right now the only way to build a target from another cell is to `cd` into that repository and build the target there. If that is not feasible for your build, then hopefully we can either get this problem fixed or get the cross-cell building from CLI implemented soon.

**Comment by davido** [comment]
@k21 Thanks for clarifying. Just to check my understanding: the references to the cross cell based targets should be harmonized:

```
  java_library(
    name = 'cache-h2',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
      '//gerrit-common:server',
      '//gerrit-extension-api:api',
      '//gerrit-server:server',
      '//lib:guava',
      '//lib:h2',
      '//lib/guice:guice',
      '//lib/log:api',
      '@jgit//org.eclipse.jgit:jgit',
    ],
    visibility = ['PUBLIC'],
  )
```

The references inside the BUCK file and on the CLI would be both the same and in the form `jgit//org.eclipse.jgit:jgit`:

```
  [...]
      '//lib/log:api',
      'jgit//org.eclipse.jgit:jgit',
    ],
    visibility = ['PUBLIC'],
  )
```

and:

```
  $ buck build jgit//org.eclipse.jgit:jgit
```

right?

**Comment by k21** [comment]
Yeah, that's the goal.

**Comment by davido** [comment]
👍
