### ISSUE TITLE
Windows build failure: Illegal char <:> at index 27: ; Common temp file patterns:

### ISSUE THREAD

**Issue by Coneko** [facebook/buck#718]
Bisected it down to 10942e9e65ce4905bbc7a276e4a18d1d40a2807d .

PS C:\Users\coneko\buck> .\bin\buck.ps1 build buck
Buck does not appear to have been built -- building Buck!
All done, continuing with build.
Not using buckd because watchman isn't installed.
[2016-04-18 17:56:53.659][error][command:76ef54e7-742e-4783-9b4f-95eb59e5fc97][tid:01][com.facebook.buck.cli.Main] Uncau
ght exception at top level
java.nio.file.InvalidPathException: Illegal char <:> at index 27: ; Common temp file patterns:
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at com.facebook.buck.io.ProjectFilesystem$PathOrGlobMatcher.<init>(ProjectFilesystem.java:1202)
        at com.facebook.buck.io.ProjectFilesystem$6.apply(ProjectFilesystem.java:286)
        at com.facebook.buck.io.ProjectFilesystem$6.apply(ProjectFilesystem.java:1)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
        at com.google.common.collect.FluentIterable.toList(FluentIterable.java:484)
        at com.facebook.buck.io.ProjectFilesystem.extractIgnorePaths(ProjectFilesystem.java:291)
        at com.facebook.buck.io.ProjectFilesystem.<init>(ProjectFilesystem.java:172)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:654)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1412)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1497)
        at com.facebook.buck.cli.Main.main(Main.java:1515)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)

PS C:\Users\coneko\buck> git bisect bad
Bisecting: 20 revisions left to test after this (roughly 4 steps)
[2a172df08196f2d682c5d67ede8889735269ef55] Buck compiler error event generation test
PS C:\Users\coneko\buck> ant clean
Buildfile: C:\Users\coneko\buck\build.xml

clean:
   [delete] Deleting directory C:\Users\coneko\buck\build

BUILD SUCCESSFUL
Total time: 2 seconds
PS C:\Users\coneko\buck> .\bin\buck.ps1 build buck
Buck does not appear to have been built -- building Buck!
All done, continuing with build.
Not using buckd because watchman isn't installed.
[2016-04-18 17:58:43.937][error][command:a6031fe1-859b-48a4-81c3-666b5770b950][tid:01][com.facebook.buck.cli.Main] Uncau
ght exception at top level
java.nio.file.InvalidPathException: Illegal char <:> at index 27: ; Common temp file patterns:
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at com.facebook.buck.io.ProjectFilesystem$PathOrGlobMatcher.<init>(ProjectFilesystem.java:1202)
        at com.facebook.buck.io.ProjectFilesystem$6.apply(ProjectFilesystem.java:286)
        at com.facebook.buck.io.ProjectFilesystem$6.apply(ProjectFilesystem.java:1)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
        at com.google.common.collect.FluentIterable.toList(FluentIterable.java:484)
        at com.facebook.buck.io.ProjectFilesystem.extractIgnorePaths(ProjectFilesystem.java:291)
        at com.facebook.buck.io.ProjectFilesystem.<init>(ProjectFilesystem.java:172)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:654)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1405)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1490)
        at com.facebook.buck.cli.Main.main(Main.java:1508)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)

**Comment by sdwilsh** [comment]
*shakes fist at @inglorion*

**Comment by sdwilsh** [comment]
I actually think @inglorion is blameless here.  I was building on Windows last week just fine.  I did my own bisect and it points to @jkeljo's 39ba1d65521d304c6de51fc0365dcb9a3eb4af7d

**Comment by jkeljo** [comment]
Yeah, this is me. I'm on it.

**Comment by jkeljo** [comment]
Fixed with e463578c5b9f417ff1d7845ae817dc64c89664f5

**Comment by jkeljo** [comment]
@Coneko I don't seem to have permissions to close issues. Would you, please?
