### ISSUE TITLE
autodeps - failed to extract Java symbols

### ISSUE THREAD

**Issue by mread** [facebook/buck#740]
Hi, I'm getting the following exceptions from time to time when running `buck autodeps`. Once the exception has happened then the only solution is to `rm -rf buck-out`.

I've not found reliable steps to reproduce it yet, will add more detail when I find it.

Has anyone got any theories on what could be happening?

```
2016-05-10 11:24:14.923][error][command:89908068-cc1a-4744-a2e7-ccacb729cfb0][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: Failed to extract Java symbols for //universe/prepayment-check-service:main
	at com.facebook.buck.jvm.java.autodeps.JavaDepsFinder.getJavaFileFeatures(JavaDepsFinder.java:387)
	at com.facebook.buck.jvm.java.autodeps.JavaDepsFinder.access$1(JavaDepsFinder.java:348)
	at com.facebook.buck.jvm.java.autodeps.JavaDepsFinder$2.visit(JavaDepsFinder.java:223)
	at com.facebook.buck.jvm.java.autodeps.JavaDepsFinder$2.visit(JavaDepsFinder.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:62)
	at com.facebook.buck.jvm.java.autodeps.JavaDepsFinder.findDepsForBuildFiles(JavaDepsFinder.java:232)
	at com.facebook.buck.cli.AutodepsCommand.runWithoutHelp(AutodepsCommand.java:160)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:168)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:90)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1036)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1494)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1579)
	at com.facebook.buck.cli.Main.main(Main.java:1597)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
Caused by: java.io.IOException: Error initializing //universe/prepayment-check-service:main#java_symbols from disk.
	at com.facebook.buck.rules.CachingBuildEngine$7.apply(CachingBuildEngine.java:704)
	at com.facebook.buck.rules.CachingBuildEngine$7.apply(CachingBuildEngine.java:1)
	at com.facebook.buck.rules.CachingBuildEngine$17.apply(CachingBuildEngine.java:1498)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:595)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:96)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:1108)
	at com.facebook.buck.rules.CachingBuildEngine.processBuildRule(CachingBuildEngine.java:710)
	at com.facebook.buck.rules.CachingBuildEngine.access$19(CachingBuildEngine.java:554)
	at com.facebook.buck.rules.CachingBuildEngine$9.apply(CachingBuildEngine.java:912)
	at com.facebook.buck.rules.CachingBuildEngine$9.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$3.call(WeightedListeningExecutorService.java:102)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /Users/mattread/dev/buck-build/buck-out/gen/universe/prepayment-check-service/__main#java_symbols__.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at com.facebook.buck.io.ProjectFilesystem.readLines(ProjectFilesystem.java:870)
	at com.facebook.buck.rules.DefaultOnDiskBuildInfo.getOutputFileContentsByLine(DefaultOnDiskBuildInfo.java:109)
	at com.facebook.buck.jvm.java.autodeps.JavaSymbolsRule.initializeFromDisk(JavaSymbolsRule.java:92)
	at com.facebook.buck.jvm.java.autodeps.JavaSymbolsRule.initializeFromDisk(JavaSymbolsRule.java:1)
	at com.facebook.buck.rules.BuildOutputInitializer.initializeFromDisk(BuildOutputInitializer.java:46)
	at com.facebook.buck.rules.CachingBuildEngine.doInitializeFromDisk(CachingBuildEngine.java:1219)
	at com.facebook.buck.rules.CachingBuildEngine.access$17(CachingBuildEngine.java:1214)
	at com.facebook.buck.rules.CachingBuildEngine$7.apply(CachingBuildEngine.java:701)
	... 28 more
```

**Comment by bolinfest** [comment]
If you can reliably repro and are using buckd (the daemon), can you try killing buck (via 'buck kill') first rather than deleting buck-out and let me know whether that fixes things?

**Comment by mread** [comment]
I can't (yet) reliably reproduce but I'm not running buckd.

**Comment by mread** [comment]
Eventually reproduced this by running two versions of buck against the same project. Apologies, hope I didn't waste too much of anyone's time. Closing.
