### ISSUE TITLE
The following resources were not found: RDotTxtEntry

### ISSUE THREAD

**Issue by vinz243** [facebook/buck#757]
Hi all, I'm trying to use AppCompat and Support:

```
$ buck build app
The following resources were not found when processing /home/vinz243/snappy/res/snappy: 
RDotTxtEntry{idType=int, type=string, name=appbar_scrolling_view_behavior, idValue=0x00000000}

java.lang.RuntimeException
java.lang.RuntimeException
	at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:177)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at  ...
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //res:res failed with exit code 1:
generate_resource_ids
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.4s [100%] (13/20 JOBS, 0 UPDATED, 0.0% CACHE MISS)
```
## Directory tree
```
snappy
├── apps
│   ├── DEFS
│   └── snappy
│       ├── AndroidManifest.xml
│       └── BUCK
├── DEFS
├── java
│   ├── BUCK
│   └── com
│       └── whitedrop
│           └── snappy
│               └── MainActivity.java
├── keystores
│   └── ....
├── libs
│   ├── appcompat-v7-21.0.3.aar
│   ├── appcompat-v7-23.4.0.aar
│   ├── appcompat-v7-23.4.0-sources.jar
│   ├── BUCK
│   ├── design-23.4.0.aar
│   └── design-23.4.0-sources.jar
├── LICENSE
├── README.md
└── res
    ├── BUCK
    └── snappy
        ├── layout
        │   ├── activity_main.xml
        │   └── content_main.xml
        ├── menu
        │   └── activity_main.xml
        └── values
            ├── colors.xml
            ├── dimens.xml
            ├── strings.xml
            └── styles.xml
```

### `libs/BUCK`

```py
android_prebuilt_aar(
  name = 'appcompat-v7',
  aar = 'appcompat-v7-23.4.0.aar',
  visibility = ['PUBLIC']
)
android_prebuilt_aar(
  name = 'design',
  aar = 'design-23.4.0.aar',
  visibility = ['PUBLIC']
)
```
### `res/BUCK`
```py
android_resource(
  name = 'res',
  res = 'snappy',
  package = 'com.whitedrop.snappy',
  visibility = [
    'PUBLIC',
    '//libs:appcompat-v7',
    '//libs:design'
  ]
)
```

Whole source: https://github.com/vinz243/snappy

Thanks in advance

**Comment by vinz243** [comment]
^^ just found that I was putting deps into visibility
