### ISSUE TITLE
Pex is not python 3 compatible

### ISSUE THREAD

**Issue by barancev** [facebook/buck#774]
c:\Devel\selenium>python C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395
af8181d0b90e568f\buck.pex release
Traceback (most recent call last):
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex.bootstrap_pex\pex.py", line 320, in execute
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex.bootstrap_pex\pex.py", line 253, in _wrap_coverage
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex.bootstrap_pex\pex.py", line 285, in _wrap_profiling
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex.bootstrap_pex\pex.py", line 363, in _execute
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex.bootstrap_pex\pex.py", line 421, in execute_entry
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex.bootstrap_pex\pex.py", line 426, in execute_module
  File "C:\Python34\lib\runpy.py", line 185, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexei.crazyfun\buck\d8638250de510497af84a395af8181d0b90e568f\
buck.pex\programs\buck.py", line 9, in <module>
ImportError: No module named 'buck_tool'

**Comment by v-jizhang** [comment]
Buck is Python 3 compatible now.
