### ISSUE TITLE
NameError: name 'GERRIT_PLUGIN_API' is not defined

### ISSUE THREAD

**Issue by antnguyen** [facebook/buck#783]
I'm trying to build gerrit stable-2.10 and got this error:

`Traceback (most recent call last):
  File "/home/anngu2/gerrit/buck-out/tmp/buck_run.3hBOcP3Hf9/buck1735607475540885324.py", line 1145, in <module>
    main()
  File "/home/anngu2/gerrit/buck-out/tmp/buck_run.3hBOcP3Hf9/buck1735607475540885324.py", line 558, in main
    buildFileProcessor.process(build_file)
  File "/home/anngu2/gerrit/buck-out/tmp/buck_run.3hBOcP3Hf9/buck1735607475540885324.py", line 464, in process
    build_env['BUILD_FILE_SYMBOL_TABLE'])
  File "/home/anngu2/gerrit/plugins/cookbook-plugin/BUCK", line 25, in <module>
    deps = GERRIT_PLUGIN_API + GERRIT_TESTS + [
NameError: name 'GERRIT_PLUGIN_API' is not defined
BUILD FAILED: Parser did not exit cleanly (exit code: 1)
call to buck audit failed: Command '['buck', 'audit', 'classpath', '//gerrit-war:log4j-config', '//gerrit-war:init', '//lib:postgresql', '//lib/log:impl_log4j', '//gerrit-war:version']' returned non-zero exit status 1
BUILD FAILED: //:gerrit failed with exit code 1:
genrule`

I have no clue how to fix this. Please help. Thanks.

**Comment by Coneko** [comment]
You should ask in the gerrit project, sorry.
