### ISSUE TITLE
dSYM file move conflict breaks builds

### ISSUE THREAD

**Issue by rmaz** [facebook/buck#794]
@Coneko Looks like commit 0516ac4fcdb0efec566b2e8e0c1bb9db8ccdc8f7 causes intermittent build failures for us due to a file move permissions issue:

```
00:02:07.382 error moving buck-out/gen/apps/myproj/MyProjBinary#apple-dsym,iphonesimulator-x86_64,no-include-frameworks.dSYM/Contents/Resources/DWARF/MyProjBinary#iphonesimulator-x86_64,no-include-frameworks -> buck-out/gen/apps/myproj/MyProjBinary#apple-dsym,iphonesimulator-x86_64,no-include-frameworks.dSYM/Contents/Resources/DWARF/MyProjBinary
00:02:07.382 java.nio.file.FileAlreadyExistsException: /Users/mobileci/jenkins/workspace/build-master-ios/buck-out/gen/apps/myproj/MyProjBinary#apple-dsym,iphonesimulator-x86_64,no-include-frameworks.dSYM/Contents/Resources/DWARF/MyProjBinary
00:02:07.382 java.nio.file.FileAlreadyExistsException: /Users/mobileci/jenkins/workspace/build-master-ios/buck-out/gen/apps/myproj/MyProjBinary#apple-dsym,iphonesimulator-x86_64,no-include-frameworks.dSYM/Contents/Resources/DWARF/MyProjBinary
00:02:07.382 	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:429)
00:02:07.382 	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
00:02:07.382 	at java.nio.file.Files.move(Files.java:1395)
00:02:07.382 	at com.facebook.buck.io.ProjectFilesystem.move(ProjectFilesystem.java:931)
00:02:07.382 	at com.facebook.buck.step.fs.MoveStep.execute(MoveStep.java:49)
00:02:07.382 	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
00:02:07.382 	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1236)
00:02:07.382 	at com.facebook.buck.rules.CachingBuildEngine.access$4(CachingBuildEngine.java:1219)
00:02:07.382 	at com.facebook.buck.rules.CachingBuildEngine$4$1.call(CachingBuildEngine.java:319)
00:02:07.382 	at com.facebook.buck.rules.CachingBuildEngine$4$1.call(CachingBuildEngine.java:1)
00:02:07.382 	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
00:02:07.382 	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
00:02:07.382 	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
00:02:07.382 	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
00:02:07.382 	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
00:02:07.382 	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
00:02:07.382 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:02:07.382 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:02:07.382 	at java.lang.Thread.run(Thread.java:745)
00:02:07.382 
00:02:07.467 BUILD FAILED: //apps/myproj:MyProjBinary#apple-dsym,iphonesimulator-x86_64,no-include-frameworks failed with exit code 1:
```

It would be simple to fix by changing the permissions of the `MoveStep` to be `REPLACE_EXISTING`, but I don't know if this is logically valid or not, is it a bug that the dSYM already exists in this location and is it cool to write over?

**Comment by Coneko** [comment]
Found the issue, working on a fix now, thanks for pointing it out.
