### ISSUE TITLE
com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#814]
When trying to build an exopackage variant of a binary, this error occurs. The non exopackage version builds fine

the `android_binary` rule looks like

```
android_binary(
    name = 'bin_exo',
    manifest = ':manifest_exo',
    keystore = '//.okbuck/keystore/app-apk:key_store_exo.keystore',
    exopackage_modes = ['secondary_dex'],
    use_split_dex = True,
    use_linear_alloc_split_dex = True,
    linear_alloc_hard_limit = 167772160,
    primary_dex_patterns = [
        '^com/facebook/buck/android/support/exopackage/',
        '^com/example/app/AppShell^',
        '^android/support/v7/app/AppCompatActivity^',
        '^android/support/v4/app/FragmentActivity^',
    ],
    manifest_entries = {
        'placeholders': {
            'applicationId': 'com.example.app.exo',
        },
    },
    deps = [
        ':src_exo',
        ':res_exo_ed72d21a643fcb598330f892147f5f0b',
        ':res_exo_efa389e76b0e0c05f8ce0fc1de3efacf',
        ':app_lib_exo',
    ],
    visibility = [
        'PUBLIC',
    ],
)
```

**Comment by kageiit** [comment]
The same issue occurs with `use_linear_alloc_split_dex` set to true and false

**Comment by kageiit** [comment]
This is how the debug variant looks like and is able to build successfully

```
android_binary(
	name = 'bin_debug',
	manifest = ':manifest_debug',
	keystore = '//.okbuck/keystore/app-apk:key_store_debug.keystore',
	use_split_dex = True,
	linear_alloc_hard_limit = 16777216,
	manifest_entries = {
		'placeholders': {
			'applicationId': 'com.example.app.development',
		},
	},
	deps = [
		':src_debug',
		':res_debug_ed72d21a643fcb598330f892147f5f0b',
	],
	visibility = [
		'PUBLIC',
	],
)
```

**Comment by kageiit** [comment]
Here is the full stack trace

```
There was an error in smart dexing step.
com.facebook.buck.step.StepFailedException: Failed on step dx_&&_write_file with an exception:
field ID not in [0, 0xffff]: 65536
com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$5.updateIndex(DexMerger.java:482)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:302)
	at com.android.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:490)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:173)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:195)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:488)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:268)
	at com.android.dx.command.dexer.Main.run(Main.java:238)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:206)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:186)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:43)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:43)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:124)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:1)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.facebook.buck.step.StepFailedException: Failed on step dx_&&_write_file with an exception:
field ID not in [0, 0xffff]: 65536
com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$5.updateIndex(DexMerger.java:482)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:302)
	at com.android.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:490)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:173)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:195)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:488)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:268)
	at com.android.dx.command.dexer.Main.run(Main.java:238)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:206)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:186)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:43)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:43)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:124)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:1)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


	at com.facebook.buck.step.StepFailedException.createForFailingStepWithException(StepFailedException.java:85)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:65)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:124)
	at com.facebook.buck.step.DefaultStepRunner$2$1.call(DefaultStepRunner.java:1)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //app-apk:bin_exo#dex_merge failed with exit code 1:
smart_dex
[-] PROCESSING BUCK FILES...FINISHED 0.2s 🐇
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.6s [100%] (381/383 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS) Details: http://localhost:61950/trace/e0c90467-d4ab-4d86-863a-781a43cfafa0
```
