### ISSUE TITLE
brew install --HEAD buck NDK issue

### ISSUE THREAD

**Issue by mlostekk** [facebook/buck#841]
When i try to install buck with `brew install --HEAD buck` i am getting a build error.

Thats the content the build log.

```
2016-08-10 16:19:27 +0200

./bin/buck
build
buck

Not using buckd because watchman isn't installed.
[2016-08-10 16:19:35.269][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: /Users/mlostek/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:577)
	at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:626)
	at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:378)
	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:137)
	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:101)
	at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:336)
	at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:232)
	at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:43)
	at com.facebook.buck.rules.Cell.<init>(Cell.java:115)
	at com.facebook.buck.rules.Cell.createCell(Cell.java:159)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:821)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:609)
	at com.facebook.buck.cli.Main.main(Main.java:1650)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)


HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 850db4ebf473738ffba8424065d62954d3c95dd1
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6756fa5bfe3ed5881831398ae98cf6190cdd317
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 0
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66, 1.6.0_65-b14-468
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CFLAGS: -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include/darwin
CXXFLAGS: -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include/darwin
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.11
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.11
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin:/usr/local/Library/Homebrew/shims/super:/usr/local/opt/ant/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

The thing is, i do not have the folder `Users/mlostek/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8` 

i am just having `Users/mlostek/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9`

Any ideas how to fix this build issue?

**Comment by k21** [comment]
Since Buck does not need the NDK to build itself, unsetting `ANDROID_NDK` before installing Buck should fix this. After that, you can override the compiler version by putting this in the `.buckconfig` file in your project:
```
[ndk]
  gcc_version = 4.9
```

**Comment by aiked** [comment]
Can you tell me if you are using Android NDK r12b? This might be related to something else.

**Comment by mlostekk** [comment]
my NDK version is `12.1.2977051` Is this `b`? I dont know. Where can i find out that human friendly version string?

**Comment by k21** [comment]
@mlostekk, did unsetting the `ANDROID_NDK` environment variable before installing Buck help?

I am going to merge this into #844 which seems to be hitting the same error.

**Comment by mlostekk** [comment]
Yep, unsetting NDK variable fixed buck usage.
