### ISSUE TITLE
buck --help broken on fresh project

### ISSUE THREAD

**Issue by dcolascione** [facebook/buck#844]
$ buck --help
[2016-08-15 11:25:06.389][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: /home/dancol/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
    at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
    at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:577)
    at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:626)
    at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:378)
    at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:137)
    at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:101)
    at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:337)
    at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:233)
    at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:43)
    at com.facebook.buck.rules.Cell.<init>(Cell.java:115)
    at com.facebook.buck.rules.Cell.createCell(Cell.java:159)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:840)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:628)
    at com.facebook.buck.cli.Main.main(Main.java:1672)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)

**Comment by Coneko** [comment]
It can't find `/home/dancol/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc`, might be because the newer NDKs don't have 4.8 if I remember right, configure Buck to use 4.9 or whatever your NDK has:

```
[ndk]
gcc_version = 4.9
```

See https://buckbuild.com/concept/buckconfig.html#ndk.gcc_version .

**Comment by sdwilsh** [comment]
We should probably bump the default version if newer NDKs do not contain it.

**Comment by LegNeato** [comment]
Just hit this compiling Buck itself. Should we add:

```ini
[ndk]
      gcc_version = 4.9
```

To buck's config? That will that prevent people with only much older NDKs from building, but I think it is more likely people will have a NDK with 4.9 than one without?
