### ISSUE TITLE
"Assuming foo.src.zip is a JAR and renaming to foo.src.jar" suggestion should be "... and renaming to foo-sources.jar"

### ISSUE THREAD

**Issue by davido** [facebook/buck#855]
After upgrading to 6a19cf921c107ea0f1751e4f84c639e5050e2da7 we've got this warning:

```
Assuming edit.src.zip is a JAR and renaming to edit.src.jar in //gerrit-patch-jgit:edit_src. Change the extension of the binary_jar to '.jar' to remove this warning.
```

on this rule:

```
genrule(
  name = 'jgit_edit_src',
  cmd = 'unzip -qd $TMP $(location //lib/jgit/org.eclipse.jgit:jgit_src) ' +
    'org/eclipse/jgit/diff/Edit.java;' +
    'cd $TMP;' +
    'zip -Dq $OUT org/eclipse/jgit/diff/Edit.java',
  out = 'edit.src.zip',
)
```

After renaming the output in the above rule  to `edit.src.jar`, the above warning is disappeared and `buck build gerrit` still works.

However, after that renaming, `buck test` is failing with this error:

```
BUILD FAILED: //gerrit-patch-jgit:Edit failed on step javac_jar with an exception:
no source files
java.lang.IllegalStateException: no source files
	at com.sun.tools.javac.main.Main.error(Main.java:186)
	at com.sun.tools.javac.main.Main.compile(Main.java:428)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:247)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:155)
	at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:154)
	at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:137)
	at com.facebook.buck.jvm.java.JavacDirectToJarStep.execute(JavacDirectToJarStep.java:113)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1254)
	at com.facebook.buck.rules.CachingBuildEngine.access$4(CachingBuildEngine.java:1235)
	at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:306)
	at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:1)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

To reproduce, clone Gerrit Code Review from here: [1].

* [1] https://gerrit.googlesource.com/gerrit

**Comment by Coneko** [comment]
cc @shs96c

**Comment by davido** [comment]
OK, I looked into it and found the root cause: Jsr199Javac.java:391 reads:

```
if (pathString.endsWith(".java")) {
        // For an ordinary .java file, create a corresponding JavaFileObject.
        Iterable<? extends JavaFileObject> javaFileObjects = fileManager.getJavaFileObjects(
            absolutifier.apply(path).toFile());
        compilationUnits.add(Iterables.getOnlyElement(javaFileObjects));
      } else if (pathString.endsWith(SRC_ZIP) || pathString.endsWith(SRC_JAR)) {
```

where the definitions of the constants are:

```
  String SRC_ZIP = ".src.zip";
  String SRC_JAR = "-sources.jar";
```

so after following the suggestion form the warning:

```
Assuming edit.src.zip is a JAR and renaming to edit.src.jar [...]
```

and renaming `edit.src.zip` to `edit.src.jar` the rule is broken. The correct suggestion should be:

```
Assuming edit.src.zip is a JAR and renaming to edit-sources.jar [...]
```

Moreover, looking at the current documentation, i see that this new warning/suggestion isn't reflected there as well:

```
srcs: (defaults to []) The set of .java files to compile for this rule.
If any of the files in this list end in .src.zip, then the entries in the
ZIP file that end in .java will be included as ordinary inputs to 
compilation.
```

[1] https://buckbuild.com/rule/java_library.html

**Comment by davido** [comment]
Unrelated to this issue, but it worth noting, that Bazel requires another suffix: `.srcjar` in `java_library` rule:

```
Source files of type .srcjar are unpacked and compiled.
(This is useful if you need to generate a set of .java files with a genrule.) 
```

It would be nice if Buck could also support it, so that identical rules can be used in both tool chains.

[1] http://bazel.io/docs/be/java.html#java_library

**Comment by Coneko** [comment]
Oh I see what is going on: you have a genrule creating a source jar and use it both as sources and as binary in a prebuilt_jar.

Let's see what we can do.

**Comment by Coneko** [comment]
cc @marcinkosiba, @shs96c

**Comment by davido** [comment]
It was fixed by renaming the input file.
