### ISSUE TITLE
Duplicate file for apk errors during buck build

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#872]
Seeing this error when trying to build an instrumentation apk with buck

```
BUILD FAILED: //app:instrumentation_prodDebug_apk failed on step apk_builder with an exception:
Found duplicate file for APK: LICENSE.txt
Origin 1: /Users/kage/src/OkBuck/buck-out/gen/.okbuck/cache/org.hamcrest.hamcrest-core-1.3.jar.jar
Origin 2: /Users/kage/src/OkBuck/buck-out/gen/.okbuck/cache/org.hamcrest.hamcrest-integration-1.3.jar.jar
com.facebook.buck.util.HumanReadableException: Found duplicate file for APK: LICENSE.txt
Origin 1: /Users/kage/src/OkBuck/buck-out/gen/.okbuck/cache/org.hamcrest.hamcrest-core-1.3.jar.jar
Origin 2: /Users/kage/src/OkBuck/buck-out/gen/.okbuck/cache/org.hamcrest.hamcrest-integration-1.3.jar.jar
        at com.facebook.buck.android.ApkBuilderStep.execute(ApkBuilderStep.java:166)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1223)
        at com.facebook.buck.rules.CachingBuildEngine.access$4(CachingBuildEngine.java:1204)
        at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:304)
        at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:1)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

in gradle, there is a `packagingOptions` configuration to exclude such files
http://stackoverflow.com/a/20675331/1151226

Is there something like that in buck? I could not find it documented anywhere.

**Comment by aiked** [comment]
Hello @kageiit,

Maybe this can help you: https://buckbuild.com/rule/java_library.html, search for remove_classes. It could also be used to remove other types of files since it accepts a pattern. [This test](https://github.com/facebook/buck/commit/1b8fdae8bea03d36ef2f3cf369aba21aec410a7c) is a good example how you could use it. Tell me if that was helpful.

**Comment by kageiit** [comment]
@aiked The issue is coming from a prebuilt jar. I don't see a similar option in `prebuilt_jar`

**Comment by aiked** [comment]
Sorry for the late response, I have not forgotten of this issue. @marcinkosiba do you think we should implement this?

Until then @kageiit you can create a genrule that open the jar, removes the file and zips it again. It's a messy hack but it should do for now.

**Comment by kageiit** [comment]
@aiked that's what we ended up doing, but it would be great to have an option in buck android binary rule for this so things can be excluded before they are packaged, similar to gradle.
