### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by GunNan** [facebook/buck#875]
Hi, I have meat a problem when use buck.

I set the `all-aars` in buck like this:

```
import re
aar_deps = []
for aarfile in glob(['libs/**/*.aar']):
  name = 'aars__' + re.sub(r'^.*/([^/]+)\.aar$', r'\1', aarfile)
  aar_deps.append(':' + name)

  android_prebuilt_aar(
    name = name,
    aar = aarfile,
  )

android_library(
  name = 'all-aars',
  exported_deps = aar_deps,
)

android_resource(
  name = 'res',
  res = 'res',
  assets = 'assets',
  manifest = 'AndroidManifest.xml',
  deps = [
    ':all-aars',
  ],
)

android_binary(
  # ...
)
  # ...

```

There is already contained 'appcompat-v7-24.0.0.aar' in the `libs` folder, and I have a success 'buck build' result. However, when I run my project, it crashed with log like this:

```
FATAL EXCEPTION:
 main java.lang.RuntimeException: 
Unable to start activity ComponentInfo{MainTabActivity}: 
android.content.res.Resources$NotFoundException: 
File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
at android.app.ActivityThread.access$900(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5457)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: 
File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
at android.content.res.Resources.loadDrawable(Resources.java:2111)
at android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:461)
at android.content.res.Resources.getDrawable(Resources.java:702)
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
at com.tencent.karaoke.base.ui.BaseHostActivity.onCreate(BaseHostActivity.java:72)
at com.tencent.karaoke.base.ui.KtvBaseActivity.onCreate(KtvBaseActivity.java:37)
at com.tencent.karaoke.base.ui.KtvFragmentActivity.onCreate(KtvFragmentActivity.java:20)
at com.tencent.karaoke.module.main.ui.MainTabActivity.onCreate(MainTabActivity.java:391)
at android.app.Activity.performCreate(Activity.java:5234)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388) 
at android.app.ActivityThread.access$900(ActivityThread.java:148) 
```

Thanks!

**Comment by aiked** [comment]
You can read this post: #808.
exported_deps in this is broken and do not work for aar, they only work for jars and classpath

**Comment by GunNan** [comment]
hi, I still have problems, and I have put it on the #808. Thanks!
