### ISSUE TITLE
trouble writing output: Too many field references: 104601; max is 65536.

### ISSUE THREAD

**Issue by oboolean** [facebook/buck#926]
## BUILD FAILED: //main:bin_developDebug#dex_uber_r_dot_java failed with exit code 2:

[2016-10-08 21:07:03.873][warn ][command:c0f1cd32-4fd8-47d4-8353-4364ddd4916f][tid:40][com.facebook.buck.event.listener.LoggingBuildListener] 
trouble writing output: Too many field references: 104601; max is 65536.
......

[2016-10-08 21:07:11.030][debug][command:c0f1cd32-4fd8-47d4-8353-4364ddd4916f][tid:18][com.facebook.buck.command.Build] Got an exception during the build.
java.util.concurrent.ExecutionException: com.facebook.buck.step.StepFailedException: //main:bin_developDebug#dex_uber_r_dot_java failed with exit code 2:
dx
    at com.facebook.buck.command.Build.executeBuild(Build.java:312)
    at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:354)
    at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:690)
    at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:642)
    at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:387)
    at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:332)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:198)
    at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:92)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1182)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:641)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1817)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: com.facebook.buck.step.StepFailedException: //main:bin_developDebug#dex_uber_r_dot_java failed with exit code 2:
dx
    at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:62)
    at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:71)
    at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1276)
    at com.facebook.buck.rules.CachingBuildEngine.access$3(CachingBuildEngine.java:1257)
    at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:325)
    at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:1)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:80)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
    at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
    at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by oboolean** [comment]
used the newest buck

buck --version
buck version 099a899b203f6f24fc3264f3e31b415a4b385f50

**Comment by felipecsl** [comment]
This problem is back when using latest master (as of commit aa786c45010d7c70c8680c1dd14d02d451789094)

**Comment by felipecsl** [comment]
Never mind, red herring!

**Comment by ChaitanyaPramod** [comment]
Had the same error. I noticed that `dx` isn't called with `--multi-dex` flag even when `use_split_dex = True`.
PS: gradle build for the same project succeeded

**Comment by mafunes** [comment]
I have same error, anyone knows how to fix it?

**Comment by kageiit** [comment]
Try setting

`trim_resource_ids = True` in your binary rule

**Comment by ChaitanyaPramod** [comment]
That was the first thing we tried when we hit the issue and didn't help.
Tried again today and there's no problem, I must have misconfigured earlier. Thanks @kageiit

**Comment by mafunes** [comment]
`trim_resource_ids = True` work for me :) Thanks @kageiit
