### ISSUE TITLE
Regression in temp directory resolution since 0f034b92e01e2f3585bd6589f394ecfc59632f35

### ISSUE THREAD

**Issue by dpursehouse** [facebook/buck#946]
In the JGit project, when upgrading buck from e64a2e2ada022f81e42be750b774024469551398 to 7b7817c48f30687781040b2b82ac9218d5c4eaa4 we start to get test failures like:

```
FAIL     836ms  0 Passed   0 Skipped   1 Failed   org.eclipse.jgit.http.test.SetAdditionalHeadersTest
FAILURE org.eclipse.jgit.http.test.SetAdditionalHeadersTest testSetHeaders: http://127.0.0.1:53723/git/tmp_2148522726113900848.git: http://127.0.0.1:53723/git/tmp_2148522726113900848.git/info/refs?service=git-upload-pack not found
org.eclipse.jgit.errors.NoRemoteRepositoryException: http://127.0.0.1:53723/git/tmp_2148522726113900848.git: http://127.0.0.1:53723/git/tmp_2148522726113900848.git/info/refs?service=git-upload-pack not found
       	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:479)
       	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:290)
       	at org.eclipse.jgit.http.test.SetAdditionalHeadersTest.testSetHeaders(SetAdditionalHeadersTest.java:118)
```

I've bisected it to 0f034b92e01e2f3585bd6589f394ecfc59632f35

It seems to be happening on Mac OS but not on Suse.  Possible hint in this comment in the failing test source code:

```
// The tmp directory is symlinked on OS X
```

**Comment by Coneko** [comment]
I'm not quite sure what is going on in the test, but as noted in the commit, you can pass

```
vm_args = '-Djava.io.tmpdir=/whatever',
```

to the `java_test` to change the temporary directory, maybe something other than `/tmp` will work? Or maybe it needs to be in `buck-out`?

**Comment by dpursehouse** [comment]
Thanks. Adding `vm_args` fixed it.
