### ISSUE TITLE
Could not initialize class com.facebook.buck.util.ProcessHelper

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#950]
Seeing this error on ci intermittently when building with buck

```
[2016-10-15 09:44:48.878][error][command:null][tid:293][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.buck.util.ProcessHelper
    at com.facebook.buck.util.perf.ProcessTracker.registerProcess(ProcessTracker.java:74)
    at com.facebook.buck.util.perf.ProcessTracker$$Lambda$79/559890980.call(Unknown Source)
    at com.facebook.buck.util.ProcessRegistry.registerProcess(ProcessRegistry.java:46)
    at com.facebook.buck.util.ProcessExecutor.launchProcess(ProcessExecutor.java:188)
    at com.facebook.buck.json.ProjectBuildFileParser.init(ProjectBuildFileParser.java:206)
    at com.facebook.buck.json.ProjectBuildFileParser.initIfNeeded(ProjectBuildFileParser.java:182)
    at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesInternal(ProjectBuildFileParser.java:343)
    at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesAndMetaRules(ProjectBuildFileParser.java:332)
    at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:118)
    at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:1)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
    at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
    at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:105)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$97/808517814.call(Unknown Source)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
    at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$98/1970869041.apply(Unknown Source)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
    at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
    at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
    at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Failed to execute: infer/bin/../lib/python/infer.py --buck -j 4 --out 
```

Happens with/without daemon enabled

**Comment by Coneko** [comment]
Buck running from source or from pex?

**Comment by kageiit** [comment]
Source
