### ISSUE TITLE
Error running buck test

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#951]
```
[2016-10-15 12:08:00.002][error][command:null][tid:144][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NoSuchMethodError: com.facebook.buck.test.TestRunningOptions$Builder.setTestResultCacheMode(Lcom/facebook/buck/test/AbstractTestRunningOptions$TestResultCacheMode;)Lcom/facebook/buck/test/TestRunningOptions$Builder;
    at com.facebook.buck.cli.TestCommand.getTestRunningOptions(TestCommand.java:272)
    at com.facebook.buck.cli.TestCommand.runTestsInternal(TestCommand.java:323)
    at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:564)
    at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:198)
    at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:92)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1187)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:640)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1854)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

This happens intermittently on latest buck master

**Comment by Coneko** [comment]
Buck running from source or from pex?

**Comment by kageiit** [comment]
Git clone buck
Build with an run

I'm not sure what pex is

**Comment by kageiit** [comment]
This is buck running from source @Coneko

**Comment by styurin** [comment]
Do you still have this problem? Have you tried `ant clean`?

**Comment by kageiit** [comment]
Have not tried this in a while. Nowadays I just run tests from intellij. Closing this for now. will reopen if needed
