### ISSUE TITLE
Buck fails to expand $location macros with "Argument List too long"

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#999]
When the build target inside the location macro has many dependencies, buck always fails to expand the macro before it can run the genrule.

Consider

```
genrule(
        name = 'lint_release',
        srcs = [
                '//.okbuck/lintw:config_lint_lint.xml',
        ],
        out = 'lint_release_out',
        bash = 'mkdir -p $OUT ; ' \
        'export LINT_DEPS="$(location //.okbuck/cache/lintDeps:okbuck_lint_deps)" ; ' \
        'export LINT_DEPS="$LINT_DEPS:$(location //tooling/lint:bin_main)" ; ' \
        'export ANDROID_LINT_JARS="/project/.okbuck/cache/com.jakewharton.timber.timber-4.1.2-lint.jar" ; ' \
        'export ANDROID_LINT_JARS="$ANDROID_LINT_JARS:$(location //tooling/lint:src_main)" ; ' \
        'export OUTPUT_DIR=$OUT ; ' \
        'export MODULE_JAR=$(location :src_release) ; ' \
        '$(location //.okbuck/lintw:lintw_app_release)',
)
```

In the above genrule, `:src_release` is a `java_library`, `//.okbuck/cache/lintDeps:okbuck_lint_deps` and  `//tooling/lint:bin_main` are `java_binaries` with several hundred/thousand dependencies.

This is causing "Argument List too long" on Linux where the `ARG_MAX` is set to `2097152`. If we hardcode the location of the output jars that the macros expands to, the genrule runs correctly without any issues.

```
BUILD FAILED: //project/app:lint_release failed on step genrule with an exception:
Cannot run program "/bin/bash" (in directory "/project/buck-out/gen/project/app/lint_release__srcs"): error=7, Argument list too long
java.io.IOException: Cannot run program "/bin/bash" (in directory "/project/buck-out/gen/project/app/lint_release__srcs"): error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.facebook.buck.util.BgProcessKiller.startProcess(BgProcessKiller.java:98)
	at com.facebook.buck.util.ProcessExecutor.launchProcess(ProcessExecutor.java:187)
	at com.facebook.buck.util.ProcessExecutor.launchAndExecute(ProcessExecutor.java:152)
	at com.facebook.buck.shell.ShellStep.launchAndInteractWithProcess(ShellStep.java:160)
	at com.facebook.buck.shell.ShellStep.execute(ShellStep.java:106)
	at com.facebook.buck.shell.AbstractGenruleStep.execute(AbstractGenruleStep.java:81)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:62)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1237)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$10(CachingBuildEngine.java:320)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 17 more
```

**Comment by kageiit** [comment]
cc @yiding @sdwilsh

**Comment by kageiit** [comment]
I took some macros with a lot of dependencies out and put in several hundred macros with no dependencies and the genrule ran fine. I was also able to make it run fine by adding several hundred lines with no location macros to the genrule. Very perplexing

**Comment by yiding** [comment]
Looks like `Genrule` constructs an environment variable `DEPS` that contains the output paths of all transitive dependencies. 

`AbstractGenruleStep` allows this `DEPS` env var to be set based on a substring check for the string `DEPS` (ostensibly this is a substring check so that it can be maximally permissive in matching env accessing constructs, e.g. `$DEPS` `%DEPS%`). The script triggering this issue happens to have `LINT_DEPS`, which would match, at which point this huge environment variable gets shoved into the exec call, which fails with E2BIG. 

Since this feature isn't documented anywhere I'll try and delete it in hopes that it's unused. A true macro (that is expanded when generating the script, rather than an environment variable) can implement this behavior if it's needed in the future.

**Comment by kageiit** [comment]
Seems like this was fixed. Thanks a lot @yiding
